### ISSUE TITLE
How do you update to beta?

### ISSUE THREAD

**Issue by majorsl** [snowie2000/mactype#1002]
I had only installed it with the installer before.  I downloaded the beta .zip and can't identify a way to update.

So, I figured I could just replace the contents of MacType in the program files with the new versions, reboot, and be on my way.  I opened Task Manager and found the processes and quit them (it does not appear the MacTray has an option to Exit).

Files are still in use.

What is the process here to update?  I didn't see anything in the wiki about it.

**Comment by snowie2000** [comment]
You should stop the old mactype from loading first. 

Open the wizard, select "manual" as the loading mode and apply. Reboot your system and it should be ok to overwrite files.

**Comment by snowie2000** [comment]
As of the release of a new installer, there is no need to manually update to a beta version.
