### ISSUE TITLE
你的 MacType 版本与此应用程序不兼容。请更新到版本 2023.5.31 或更高版本

### ISSUE THREAD

**Issue by chinazzl** [snowie2000/mactype#1003]
![image](https://github.com/user-attachments/assets/1e042c2d-c6c9-4ea5-89d8-772a9f888332)

**Comment by jonm58** [comment]
https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31

**Comment by chinazzl** [comment]
> https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31
