### ISSUE TITLE
win10的 DW渲染能关或者者修复吗

### ISSUE THREAD

**Issue by bestv5** [snowie2000/mactype#1004]
我发现我的win10 DirectWrite功能好像坏了，鸿蒙、opposans等黑体字体锯齿严重(见下图鼠标右侧的“慧”字，好多字都这个样子了)，微软雅黑、宋体还凑合。
有人知道怎么修复吗

![image](https://github.com/user-attachments/assets/1789cf75-617c-47ae-8b34-0b90da48e36f)

**Comment by ssssssbbb** [comment]
一不是DW，二要端正坐姿

**Comment by bestv5** [comment]
> 一不是DW，二要端正坐姿

图片拍照拍歪了；另外我也不知道是不是dw坏了，反正，只有微软雅黑看起来正常点，其他字体都不行了。
你看第一行的“慧”字清楚吗

**Comment by ssssssbbb** [comment]
这个地方不使用DW，这个尺寸的这个字就这样，正常坐姿视距不应该看到这样
