### ISSUE TITLE
Mactype突然不能使用，开机一看全是拒绝访问

### ISSUE THREAD

**Issue by passye** [snowie2000/mactype#1008]
今天上午突然出现的情况，不知道是什么原因导致的。
感觉任何程序都变成了拒绝访问，我换了不同的Mactype启动方式都是这样
![PixPin_2024-08-13_10-13-45](https://github.com/user-attachments/assets/2f7885ea-96f3-4bfe-b92f-84e1addb2428)
![PixPin_2024-08-13_10-13-55](https://github.com/user-attachments/assets/ba1164e6-487f-4469-bcbe-7c0a07f6f0b2)
![PixPin_2024-08-13_10-14-09](https://github.com/user-attachments/assets/69886581-a0c0-4e32-ad4c-5326e56ca164)

![PixPin_2024-08-13_10-16-59](https://github.com/user-attachments/assets/9167480f-9546-4703-a8d0-eaf5db52973f)
版本信息如图

**Comment by snowie2000** [comment]
感觉好像是被杀毒软件拦住了，无法访问任何进程信息

**Comment by artorias-zj** [comment]
我这边的几台安装了火绒的也都有此问题，换回到mactype-2021rc的版本暂时可以正常开机渲染使用，火绒论坛那边看起来有出现同样问题的已经提交过问题报告了。
[https://bbs.huorong.cn/thread-143713-1-1.html](url)

**Comment by passye** [comment]
> 我这边的几台安装了火绒的也都有此问题，换回到mactype-2021rc的版本暂时可以正常开机渲染使用，火绒论坛那边看起来有出现同样问题的已经提交过问题报告了。 [https://bbs.huorong.cn/thread-143713-1-1.html](url)

厚礼蟹，我还真是装了火绒

**Comment by snowie2000** [comment]
火绒问题合并至 #1020

**Comment by Vstory** [comment]
大部分都可以正常工作。
![20240916_233109](https://github.com/user-attachments/assets/1a395ed0-540b-41d2-93b3-b856c993fa7e)
