### ISSUE TITLE
能否给一个'只对某一个软件生效'的功能

### ISSUE THREAD

**Issue by tanghululalala** [snowie2000/mactype#1009]
使用myeclipse/eclipse做开发的程序猿，用到了mactype来渲染字体，用了很多年。但现在win11上越来越多软件无法兼容于mactype了，会出现闪退、无法打开的情况，只能一个个排除进程。但只要新安装的软件出现此问题就需要排除，如此往复。
现在迫切需要一个功能，类似于进程白名单，就是在这个白名单内的进程才生效，其他不在此白名单内的就统一不生效

系统是win11专业版最新版本23H2
mactype版本也是最新的2023.1

**Comment by tanghululalala** [comment]
或者当前已有其他功能 能实现此效果, 烦请告知

**Comment by snowie2000** [comment]
https://github.com/snowie2000/mactype/wiki/UseInclude

**Comment by tanghululalala** [comment]
感谢

> https://github.com/snowie2000/mactype/wiki/UseInclude
