### ISSUE TITLE
最新版用搜狗五笔输入法输入(自定义快捷短语)带圈数字(从21到50)识别为空的方框,只能在配置ini排除要输入的exe程序

### ISSUE THREAD

**Issue by WrathGluttony** [snowie2000/mactype#1010]
①Mactype最新版(Version 2023.5.31, still preview)最新版用搜狗五笔输入法输入(自定义快捷短语)带圈数字(从21到50)识别为空的方框,只能在配置ini排除要输入的exe程序。
②在notepad.exe、EmEditor.exe、Evernote.exe、msedge.exe(估计其它程序也一样),只试验了上述4个程序,用搜狗五笔输入法输入(自定义快捷短语)带圈数字(㉑㉒㉓㉔㉕㉖㉗㉘㉙㉚㉛㉜㉝㉞㉟㊱㊲㊳㊴㊵㊶㊷㊸㊹㊺㊻㊼㊽㊾㊿)识别为空的方框。
③但是带圈数字①至⑳是正常的(①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⓪⑱⑲⑳)。
④之前一直用的Mactype旧版(MacType 2021.1-RC1),没有上述变成空的方框的问题
⑤昨天更新到Mactype最新版(Version 2023.5.31, still preview),今天想输入㉑至㊿的带圈数字,出现在搜狗五笔输入法和上述在notepad.exe、EmEditor.exe、Evernote.exe、msedge.exe(估计其它程序也一样)程序中带圈数字㉑至㊿变成空的方框的问题
⑥暂时只能在配置ini文件中排除上述4个exe文件
⑦麻烦大佬适配一下,看看哪里出问题了
⑧为什么旧版Mactype是正常的?
⑨为什么❶❷❸❹❺❻❼❽❾❿⓫⓬⓭⓮⓯⓰⓱⓲⓳⓴⓿和①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⓪⑱⑲⑳是正常的?㉑㉒㉓㉔㉕㉖㉗㉘㉙㉚㉛㉜㉝㉞㉟㊱㊲㊳㊴㊵㊶㊷㊸㊹㊺㊻㊼㊽㊾㊿变成空的方框了呢?
⑩下方这张图片是搜狗五笔输入法-自定义短语文件中㉑至㊿变成空方框了
![搜狗五笔输入法空方框](https://github.com/user-attachments/assets/88165098-49bd-4995-992e-8c07a4d9060e)
⑪下方这张图片是搜狗五笔输入法输入自定义短语"zsys"调出候选框后,候选框中㉑至㊿变成空方框了
![Snipaste_2024-08-31_07-32-43](https://github.com/user-attachments/assets/d50a9702-1985-4f4a-8111-34f2dca6369b)
⑫下方这张图片是搜狗五笔输入法输入自定义短语"zsys"调出候选框后,候选框中㉑至㊿变成空方框了,与上条⑪条相同
![Snipaste_2024-08-31_07-33-09](https://github.com/user-attachments/assets/ee0950b0-995f-41de-a491-3e2aae299129)

**Comment by snowie2000** [comment]
带圈的数字如果选择上屏会正常在对应的软件中显示吗？
我在你发出的issue中可以正常看到带圈的数字，复制到notepad后也依然正常显示没有发现什么问题

**Comment by WrathGluttony** [comment]
> 带圈的数字如果选择上屏会正常在对应的软件中显示吗？ 我在你发出的issue中可以正常看到带圈的数字，复制到notepad后也依然正常显示没有发现什么问题

谢谢大神回复
①带圈的数字1-20是正常的,21-50这个范围内的数字全部是空方框
②在Edge浏览器、Evernote用搜狗五笔输入法输入数字时,21-50是正常的带圈数字
③在Emeditor、notepad中,用搜狗五笔输入法输入21-50时,是空方框
④在Sublime中,21-50显示正常,是带圈的数字
⑤我换成MacType 2021.1-RC1,21-50带圈数字是正常的,用Mactype最新版(Version 2023.5.31, still preview)就会出现上述问题
麻烦大神看看是哪里出问题了,谢谢

**Comment by snowie2000** [comment]
刚刚发布了新的版本，试一下

**Comment by WrathGluttony** [comment]
①已经试用了一会儿刚发布的最新版,暂时只发现只要切换到1个配置,就会导致出现空方框
②这个配置路径是:C:\Program Files\MacType\ini\IoF\HotShift\HotShift→XHei…\Intel.ini

**Comment by snowie2000** [comment]
把配置文件中的字体替换全部删掉

**Comment by WrathGluttony** [comment]
谢谢大神指点
①我按照您的意思,注释掉字体替换字段,如下:
`;[FontSubstitutes]`
其它代码都没改,就是把字体替换字段前面加了"分号",把字段属性注释掉了,现在带圈数字显示正常,没有空方框了
②请问这样就可以了?谢谢

**Comment by snowie2000** [comment]
是的，这样就可以了

**Comment by WrathGluttony** [comment]
谢谢大神不吝赐教,Bow!

**Comment by WrathGluttony** [comment]
作者您好,发现1个解决方法,但是并不完美
①就是搜狗五笔输入法-设置-外观-更换字体-中文,这个选项不要选择XHei-Intel字体,换成其它字体后,搜狗五笔打字时,21-50的带圈数字就不会是空方框,但是搜狗五笔,自定义短语phrases.ini文件里21-50仍然是空方框,但是不影响使用
②不需要把字体替换注释掉,只是搜狗五笔的自定义短语phrases.ini里21-50会显示成空方框,但不影响使用

**Comment by snowie2000** [comment]
应该是xhei-intel这个字体中缺少了对应的圈圈数字导致的，这是字体的问题，没有办法解决

**Comment by WrathGluttony** [comment]
> 应该是xhei-intel这个字体中缺少了对应的圈圈数字导致的，这是字体的问题，没有办法解决

但是之前的版本没有这个问题,之前的版本是MacType 2021.1-RC1,但是之前的版本已经被覆盖掉了,我就不试验了,总之谢谢大神的帮助
