### ISSUE TITLE
请问开启了 mactype 后，系统的 cleartype 还会生效吗？

### ISSUE THREAD

**Issue by Giresharu** [snowie2000/mactype#1013]
需不需要关闭它？
会有效果冲突，还是可以互相配合？或者说干脆 cleartype 会被无视？

**Comment by snowie2000** [comment]
会继续在没有mactype的地方生效。mactype有效的地方你无法感觉到cleartype的效果。

cleartype必须保持开启（即便你根本不需要它）cleartype是保证mactype正常工作的必要组件，虽然mactype本身并不需要cleartype，但Windows在关闭cleartype时，渲染行为会发生变化，会导致部分API的调用变的不一样，从而无法被mactype正常渲染
