### ISSUE TITLE
最新的2023.1版本无法对资源管理器等进程启用

### ISSUE THREAD

**Issue by andykeppel** [snowie2000/mactype#1014]
最新的2023.1版本无法对资源管理器等进程启用，旧版本的安装包形式可以正常启用。

![image](https://github.com/user-attachments/assets/ee40c0c5-3559-429d-abc9-d538f3eb483a)

进程中没有出现explorer.exe，而且chrome等显示拒绝访问。

**Comment by snowie2000** [comment]
缺少了64位相关的文件，重新覆盖一遍

**Comment by andykeppel** [comment]
> 缺少了64位相关的文件，重新覆盖一遍

请问是将2023版本压缩包内的文件全部复制到原来2021版本的安装路径下吗？

**Comment by snowie2000** [comment]
是的

**Comment by andykeppel** [comment]
> 是的

经尝试，还是无法正确启用。

![image](https://github.com/user-attachments/assets/cdbd66a2-c33c-404e-bd3b-e4b85355c83c)

**Comment by snowie2000** [comment]
查看任务管理器中是否有mt64agnt.exe这个进程。另外目前已知火绒似乎会导致mactype无法正常工作

**Comment by andykeppel** [comment]
> 查看任务管理器中是否有mt64agnt.exe这个进程。另外目前已知火绒似乎会导致mactype无法正常工作

还真的是火绒，目前看下来火绒6.0会有这个问题，我退回5.0之后就好了
