### ISSUE TITLE
Steam crashes on first launch after a reboot, despite processes being in UnloadDll

### ISSUE THREAD

**Issue by calmoon** [snowie2000/mactype#1015]
Installed MacType version is Preview 2023.5.31.

On my computer, having MacType enabled causes the application Steam to crash on its first launch after the computer is rebooted. Specifically, steamwebhelper.exe crashes. After restarting Steam, it launches correctly for the rest of the computer session, even if it's exited and launched again, but the issue repeats itself after rebooting the computer. 

This happens both in Service Mode and Standard Tray Mode. Compatibility Tray Mode or disabling MacType by setting it to Manual Mode both stop the issue. 

In an attempt to fix this while keeping MacType enabled for other programs and still able to exclude individual programs, I have added all processes related to Steam to the UnloadDll list:
- steam.exe
- steamwebhelper.exe
- steam_monitor.exe
- steamerrorreporter.exe
- steamerrorreporter64.exe
- steamservice.exe
- steamxboxutil.exe
- steamxboxutil64.exe
- GameOverlayUI.exe
- WriteMiniDump.exe
- drivers.exe
- fossilize-replay.exe
- fossilize-replay64.exe
- gldriverquery.exe
- gldriverquery64.exe
- secure_desktop_capture.exe
- streaming_client.exe
- vulkandriverquery.exe
- vulkandriverquery64.exe
- x64launcher.exe
- x86launcher.exe

Despite this, the crash still happens.

Apologies if this is not enough information. I'd be happy to provide more if required.

**Comment by snowie2000** [comment]
This is a known bug that the mactype loader can cause crash in certain situations. I have had it fixed and was testing it for a while. 

Stay tuned for a new release soon.

**Comment by calmoon** [comment]
Alright, great to hear. Will keep an eye out. Thank you!

**Comment by sammilucia** [comment]
@snowie2000 fixed in nightly? (if so please close)

**Comment by snowie2000** [comment]
Should be fixed in the latest release. Give it a try.

**Comment by calmoon** [comment]
> Should be fixed in the latest release. Give it a try.

I know the issue is already closed, but for closure, just confirmed it's indeed fixed in v2024.8.15. 

Thank you all for your hard work on MacType.

**Comment by sammilucia** [comment]
brilliant ty! 😊
