### ISSUE TITLE
MacLoader still tries to load Easyhook dlls

### ISSUE THREAD

**Issue by iKirby** [snowie2000/mactype#1018]
Version: 2024.8.15

The changelog says that Easyhook dlls are not needed, but when launching apps using MacLoader, the following error is displayed.

```
---------------------------
MacLoader64.exe - System Error
---------------------------
The code execution cannot proceed because EasyHK64.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by snowie2000** [comment]
Oh, I forgot to recompile the loaders...

The mactype itself doesn't require easyhook anymore, but not the loaders. MacType can work without them unless you load it manually.

**Comment by snowie2000** [comment]
Here are two new loaders with no dependencies.

They will be included in the next installer.

[loaders.zip](https://github.com/user-attachments/files/17001529/loaders.zip)

**Comment by iKirby** [comment]
Thanks for the update on this! I can confirm they work well without Easyhook dlls.

**Comment by snowie2000** [comment]
The new loaders work differently now.

Now they are based on detours' method of dll injection and applications that does not allow third-party dlls to be load will simply deny to start.

The loaders are still capable of loading either 32 or 64bit with any of them, but the way it is accomplished is simple: the loader will try to lanuch the matching loader for the executable.
