### ISSUE TITLE
2024.1  缺了兩个功能

### ISSUE THREAD

**Issue by wai148GitHub** [snowie2000/mactype#1021]
![2024-09-12 14 47 35](https://github.com/user-attachments/assets/9486d115-5f58-4f67-8967-925695cc49f4)
![2024-09-12 14 47 24](https://github.com/user-attachments/assets/d86050bf-fd50-462e-89fe-dc06358a2573)

**Comment by jonm58** [comment]
什么系统?
![图片](https://github.com/user-attachments/assets/434c8e92-7a09-4f47-b205-7475f627eba1)
![图片](https://github.com/user-attachments/assets/e0b06e19-8ccb-47bc-9e4e-487c4a000e04)

**Comment by snowie2000** [comment]
安装时的languages文件夹丢失会导致这个问题，请重新安装一下

**Comment by wai148GitHub** [comment]
> 安裝時的語言資料夾遺失會導致這個問題，請重新安裝一下

重新安裝后、问题解決了  謝謝
