### ISSUE TITLE
替换字体相关问题：SimSun、FontLink、Win11

### ISSUE THREAD

**Issue by oahnaLiew** [snowie2000/mactype#1025]
### 一、【SimSun】好像是特殊的

1. **替换 SimSun 会导致部分软件的图标变成方框。**
 
专门新建了一个配置文件来测试，只替换 SimSun，就会出现方框。
给替换的第三方字体复制了 SimSun 的 FontLink，还是方框。
把 SimSun 替换为系统自带的微软雅黑，也还是方框。
 
![1](https://github.com/user-attachments/assets/5c22ca38-ec80-456b-bd01-1f0c6934b7d2)
 
2. 如果不替换 SimSun，有些程序就无法实现替换第三方字体。

- 要么就停留在宋体，比如微信的内置浏览器；
- 要么就保持原字体，比如 Win11 的任务管理器。
 
 

### 二、能不能解释一下替换字体的原理或流程
我用「网易云音乐」进行测试：
1. 只替换微软雅黑，界面变成宋体。
![2-1](https://github.com/user-attachments/assets/498d31b1-2782-4349-86e4-efaa6d4fa834)
 
2. 再替换宋体，界面会出现一些「异体字」，应该是 fallback 到了日韩字体。
![2-2](https://github.com/user-attachments/assets/7b8d2567-f823-4997-bbab-73824645404b)
 
4. 再替换 Arial 和 MS Gothic（少一个都不行），成功替换为第三方字体。
![2-3](https://github.com/user-attachments/assets/a8c3d30e-1a7c-4d4a-8f52-27ca68b7e8e4)

另外，对于微信的内置浏览器，似乎会卡在第二步，
就是再替换宋体的话，就会变成方框和乱码了。
 
**所以 MacType 替换字体具体是什么原理和流程？**
**GDI 和 DirectWrite 的替换字体是否有区别？**
 
### 三、FontLink 具体该怎么用？到底有没有用？
我之所以会折腾这么多，是因为重装了Win11（23H2），又装了最新版MacType，
发现有个新版的配置文件，参考里面的配置折腾了一通，又想起要配置 FontLink。
在这个过程中，似乎通过 FontLink 解决了方框的问题。
但是又改了几次配置文件和 FontLink，就再也找不回解决问题的那个版本了。
也许之前只是我的错觉。。。

### 四、Win11 和 其他工具

- Win11（服务/注册表加载）可以替换任务栏的日期时间的字体，
   但是无法替换 开始菜单、通知控制中心，以及窗口的标题栏。
- 我还用了 noMeiryoUI 工具来替换系统字体，是否会与 MacType 有冲突？

**Comment by snowie2000** [comment]
GDI和DW的替换工作原理是完全不同的。

两者都是通过拦截字体创建的过程，在程序尝试创建A字体时修改为创建B字体，但区别在于GDI的API比较成熟，文档也比较清晰，同时GDI创建字体的入口比较单一，虽然有多个API，但最终都会调用相同的CreateFontIndirectExW进行字体创建，因此拦截比较容易且完善。

同时GDI替换会拦截多个字体相关的API返回虚假字体信息，使程序相信它们创建出来的B字体其实是A字体，部分程序对创建的字体是有判断的。

DW文档较差同时存在大量创建字体的入口，并且由于DW全部都是通过接口调用，拦截相对困难，并且创建字体的入口实在太多了，新版系统甚至还会新增入口，因此DW的字体替换可能会不完整，部分会无法拦截到。

另外DW的字体接口结构复杂，无法像GDI那样完善的欺骗应用程序，因此部分程序可以发现字体被替换，触发fallback行为，例如变成宋体……

> 我还用了 noMeiryoUI 工具来替换系统字体，是否会与 MacType 有冲突？

我没有使用过noMeiryoUI，因此不能确定是否兼容。

FontLink相当复杂，由于字体替换的复杂性因此建议同时为源字体和替换后的字体同时创建FontLink，否则可能会在部分情况下无效。另外FontLink好像需要重启才能生效。

SimSun确实是特殊的，每个语言的Windows都有一个内部默认字体，SimSun就是简中版本的默认字体，这个字体会自动出现在所有fontlink的末尾（即便注册表中没有）。

> Win11（服务/注册表加载）可以替换任务栏的日期时间的字体，
但是无法替换 开始菜单、通知控制中心，以及窗口的标题栏。

Windows中除了创建字体外，还有一个东西叫做stocked object，这个东西是Windows启动后自动存在的，无需创建即可使用，也无需释放。Windows的几个进程中大量使用了stocked object，如果程序先于MacType获得了字体，则无法被替换成功。

**Comment by oahnaLiew** [comment]
> 由于字体替换的复杂性因此建议同时为源字体和替换后的字体同时创建FontLink

也就是说原字体和替换字体的 FontLink 要保持一致？
 
另外，FontLink 中能不能包含已经被替换的字体？
 
比如我在 MacType 的配置文件中，已经把 微软雅黑 替换掉了，
在给其他字体配置 FontLink 的时候，还能不能包含 微软雅黑？

**Comment by snowie2000** [comment]
原则上不可以，因为mactype无法区别字体来源是直接创建还是通过fontlink创建，因为会一视同仁的替换

**Comment by oahnaLiew** [comment]
把 字体A 替换为 字体B，
而 字体A 存在于 字体C 的 FontLink 中，
那么是否需要在 字体C 的 FontLink 中，把 A 改为 B ？

**Comment by ssssssbbb** [comment]
noMeiryoUI没有冲突不冲突一说，它也不是替换，纯粹就是自Win95就存在的指定X处使用X字体功能，被微软砍掉了界面而已，这软件是它的代替品

**Comment by snowie2000** [comment]
> 把 字体A 替换为 字体B， 而 字体A 存在于 字体C 的 FontLink 中， 那么是否需要在 字体C 的 FontLink 中，把 A 改为 B ？

不需要，在fontlink中的字体一样会被替换掉

> noMeiryoUI没有冲突不冲突一说，它也不是替换，纯粹就是自Win95就存在的指定X处使用X字体功能，被微软砍掉了界面而已，这软件是它的代替品

原来是那个功能啊，那我就明白了。我还在想呢，新版本为什么找不到这个功能了，原来真被砍了……

**Comment by digiant** [comment]
建议直接硬替换雅黑和宋体，pcbeta上有大佬碧海潮生做的鸿蒙替换字体效果很好。

**Comment by oahnaLiew** [comment]
### 折腾了半天 FontLink，发现根本没用

**首先，对于我原先提到的第一点，**
**图标变方框的问题还是没解决。**
 
**其次，对于一些特殊字符的显示，**
**FontLink 简直毫无作用。**

--------------------------------
 
替换字体部分配置如下：
（太长了，简写一下，“系列”包括 Bold、Light 等各个字重）
```
[General]
...
FontLoader=0
FontLink=2
FontSubstitutes=1
...

[FontSubstitutes]
微软雅黑（系列）=AritaHeiti
宋体=AritaHeiti
黑体=AritaHeiti
Arial（系列）=AritaHeiti
MS Gothic（系列）=AritaHeiti
Segoe UI（系列）=AritaHeiti
```
 
FontLink 如下：
（已修改上述所有原字体的 FontLink，并为 AritaHeiti 创建）
（注意其中的 Tahoma 和 Segoe UI Historic）
```
TAHOMA.TTF,Tahoma
MICROSS.TTF,Microsoft Sans Serif,108,122
MICROSS.TTF,Microsoft Sans Serif
MSJH.TTC,Microsoft Jhenghei UI,128,96
MSJH.TTC,Microsoft Jhenghei UI
MEIRYO.TTC,Meiryo UI,128,96
MEIRYO.TTC,Meiryo UI
MINGLIU.TTC,PMingLiU
MSMINCHO.TTC,MS PMincho
MALGUN.TTF,Malgun Gothic,128,96
MALGUN.TTF,Malgun Gothic
GULIM.TTC,Gulim
BATANG.TTC,Batang
YUGOTHM.TTC,Yu Gothic UI,128,96
YUGOTHM.TTC,Yu Gothic UI
SEGEOICONS.TTF,Segoe Fluent Icons
SEGMDL2.TTF,Segoe MDL2 Assets
SEGUISYM.TTF,Segoe UI Symbol
SEGUIHIS.TTF,Segoe UI Historic
```


**以阿拉伯语 اللغة العربية 和 特殊符号 𓈈 为例：**
阿拉伯语，会以 Tahoma 来显示；
特殊符号，会以 Segoe UI Historic 来显示。

我用的浏览器是 CentBrowser，并禁用 DirectWrite ：

如果不在 font-family 中写上 Segoe UI Historic，
那么 特殊符号 𓈈 就是无法显示。

而无论样式中是否包含 Tahoma，
阿拉伯语 اللغة العربية 都能正常显示。
 
在微信里，
就是 阿拉伯语 不能正常显示（因为替换了 Segoe UI）。
 
### 问题是，FontLink 对上述情况，毫无影响！
无论 FontLink 中是否包含 Tahoma 和 Segoe UI Historic，
原本能显示的就是能显示，不能的就是不能。

--------------------------------
 
> 建议直接硬替换雅黑和宋体，pcbeta上有大佬碧海潮生做的鸿蒙替换字体效果很好。
 
所以我还是去试一下硬替换吧😂

**Comment by snowie2000** [comment]
微信使用的是directwrite，fontlink对dw的效果不明

dw使用是独立的体系，它的fontlink是否和gdi互通目前没有任何文档说明

**Comment by oahnaLiew** [comment]
> 微信使用的是directwrite，fontlink对dw的效果不明
> 
> dw使用是独立的体系，它的fontlink是否和gdi互通目前没有任何文档说明

问题是现在 FontLink 对 GDI 也不起作用啊。
 
[Font linking and GDI](https://learn.microsoft.com/en-us/globalization/fonts-layout/fonts#font-linking-and-gdi)

> Font linking is a mechanism enabled within GDI and takes priority over font fallback.

感觉这文档就是瞎说，我怎么改 FontLink 都不起作用的。
 
算了，放弃折腾 FontLink 了。

**Comment by snowie2000** [comment]
测试fontlink你要用记事本之类的，浏览器有自己独立的字体引擎，有些也是比较怪的

**Comment by oahnaLiew** [comment]
> 测试fontlink你要用记事本之类的，浏览器有自己独立的字体引擎，有些也是比较怪的

win11 的记事本不也是 DW 了吗

**Comment by jonm58** [comment]
> win11 的记事本不也是 DW 了吗

![图片](https://github.com/user-attachments/assets/b2a53d7c-4535-4dfa-8904-65eb054cff49)
是GDI……

**Comment by oahnaLiew** [comment]
放弃折腾 FontLink，去弄硬替换了，效果还不错。
这个 issue 就关掉吧。
 
给有需要的人留个参考链接：
https://github.com/Frost-ZX/windows-font-replace

**Comment by snowie2000** [comment]
经过一些简单的小测试，Chrome核心似乎不会使用标准的fontlink，你设了也没用。具体Chrome的逻辑我也不清楚

**Comment by realwyz** [comment]
> > win11 的记事本不也是 DW 了吗
> 
> ![图片](https://github.com/user-attachments/assets/b2a53d7c-4535-4dfa-8904-65eb054cff49) 是GDI……

请问图片里的查看工具是什么？
