### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by arkaeins** [snowie2000/mactype#1034]
![001](https://github.com/user-attachments/assets/e418fb9d-7243-4983-aa0e-64ed84fa22b5)

I don't see any characters in the language selection box and it only runs in Chinese.
How can I change it to Korean?

**Comment by snowie2000** [comment]
Install it again. The languages files are missing.

**Comment by arkaeins** [comment]
> Install it again. The languages files are missing.

I've deleted, rebooted, and reinstalled, and it's the same thing.
The version is 2024.9.14.

**Comment by snowie2000** [comment]
Look at your installation folder. There should be a language folder with several language files. If the folder is missing or there isn't any files in that you may need to turn off your antivirus software and try again.

**Comment by arkaeins** [comment]
![001](https://github.com/user-attachments/assets/4c506897-a428-4190-9b4f-c23e1a9f252d)

I don't use any antivirus programs other than Windows Defender, and I don't have any language folders.

**Comment by arkaeins** [comment]
Is there any way to download just the language files?

**Comment by snowie2000** [comment]
Some new languages can be downloaded https://github.com/snowie2000/mactype/issues/742, but Korean is a builtin language which has no external download available.

I've packaged all languages files so you can download directly and extract them to your installation folder
[languages.zip](https://github.com/user-attachments/files/17445224/languages.zip)

**Comment by arkaeins** [comment]
I really want to thank you for your help.
