### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by Anvil5465** [snowie2000/mactype#1035]
The installer seems to require admin privileges, but some of the github issues mention a portable version. Does a portable version still exist? If so, where can I find it?

**Comment by snowie2000** [comment]
Portable version is gone for several reasons, like
- mactype must be installed under the system's program files which requires admin priviledges
- old version of mactype must be stopped and uninstalled before installing a new version which also requires admin priviledges

And there are many cases that people don't know how to correctly set up the mactype without an installer. 

Anyway, whether it's an installer or a zip archive, you will eventually need admin priviledges for it to work. For now, only old preview versions have zip archives only for release simplicity and preview versions are designed for proficient users only.
