### ISSUE TITLE
ForceChangeFont在指定程序下貌似无效

### ISSUE THREAD

**Issue by Mrhyuan** [snowie2000/mactype#1037]
[General@Everything.exe]
ForceChangeFont=HarmonyOS Sans SC

使用如上设置 貌似并没有替换字体 但是使用下面的设置是可以正确替换的 用的最新版本的Mactype和 Win11 23H2
[FontSubstitutes@Tahoma]
Tahoma=HarmonyOS Sans SC
[General@Everything.exe]
Alternative=Tahoma

**Comment by snowie2000** [comment]
ForceChangeFont 已被废弃不再支持

**Comment by Mrhyuan** [comment]
奥好的 谢谢！那请问还有其他办法来实现类似效果吗 还是说我只能自己去确认程序用的字体来一一替换。

**Comment by snowie2000** [comment]
是的，只能一个个替换。
因为替换全部会替换很多你自己都不知道的字体，导致很多无法预测的bug，之前已经被提交了各种奇葩报告了，所以该功能没什么存在的价值。

另外该选项原本就有一个备注，仅用于快捷查看替换字体的效果，不可用于长期使用，但被大量滥用。

**Comment by Mrhyuan** [comment]
明白了 万分感谢！
