### ISSUE TITLE
mactype所有进程都无法访问

### ISSUE THREAD

**Issue by Shuwen-Liu** [snowie2000/mactype#1038]
类似于图中显示的。我使用的是机构的电脑，装了cisco secure client，我怀疑和这个有关？

![image](https://github.com/user-attachments/assets/75c67e09-6aa5-46ae-bd88-2f941be5d958)

**Comment by snowie2000** [comment]
火绒会拦截mactype，其他软件目前不清楚，但是被拦截并不奇怪，你需要找到对应的设置然后信任。
