### ISSUE TITLE
Unattended install

### ISSUE THREAD

**Issue by ppw0** [snowie2000/mactype#1041]
Hello,

I'm interested to know if MacType's latest installer has an option to do an automated, unattended install with all of the default options selected.

**Comment by snowie2000** [comment]
The installer is built with inno setup which has a switch of /SLIENT. 

It is not tested so I am not sure of it.

**Comment by ppw0** [comment]
OK, I've tested it with "/silent" and it seems to have installed normally, so I'm closing this issue. (Wish I could set it to load in the system tray at boot by default, though.)

Thanks!

**Comment by snowie2000** [comment]
You don't need the macwiz to set mactype as autostart.

To startup as a regular user, simply add key-value pair under `HKLM\SOFTWARE\Microsoft\windows\CurrentVersion\Run` should be enough.

To startup as admin is a little complicated. You have to create a task in the task scheduler and set it to run with admin prilividge.

**Comment by ppw0** [comment]
I assume you mean the MacType_SC task? I could probably just export the task from an existing installation and just import it if I need it on a new installation, no?

**Comment by snowie2000** [comment]
Yes, If you want mactype to run as a tray elevated, you have to create a task unless the UAC is completely turned off.

You can also create a service for mactype to make it run in service mode. mactray.exe will aware its running context and start as a service automatically.
