### ISSUE TITLE
Win10 设置等界面、标题栏上完全不生效

### ISSUE THREAD

**Issue by juragao** [snowie2000/mactype#1042]
已经按DirectWrite section编辑了ini：

DirectWrite=1
[DirectWrite]
RenderingMode=5
GammaValue=2
Contrast=1.2
ClearTypeLevel=1.0

加载模式为注册表，其他加载方式好像还是不够稳定，会自己失效

软件版本2024.9.14，系统版本Win10 pro 22H2 19045.5131最新版，显示比例100%
配置：9700X，4070ti super

**Comment by snowie2000** [comment]
由于目前微软没有公布也没有人搞清楚uwp程序的启动模式，所以除了注册表外，其他所有方式对uwp程序的加载都是不可靠的。暂时没有解决方案。

**Comment by juragao** [comment]
感谢雪大，我重启了一下，uwp可以渲染了，标题栏还是不生效（现在还需要#768的hotfix吗…

**Comment by snowie2000** [comment]
不需要。你需要从所有文件中把dwm.exe去掉。很多地方都默认把他unload了

**Comment by juragao** [comment]
果然！从Mactype.ini里去掉dwm.exe，杀掉进程就好了

**Comment by weavers1f** [comment]
> 果然！从Mactype.ini里去掉dwm.exe，杀掉进程就好了

请问是要从哪里来去掉？在[UnloadDll]下面添加dwm.exe吗？

**Comment by juragao** [comment]
> > 果然！从Mactype.ini里去掉dwm.exe，杀掉进程就好了
> 
> 请问是要从哪里来去掉？在[UnloadDll]下面添加dwm.exe吗？

正相反，是说不要unload它，如果你的Mactype.ini或者配置文件里有把它unload，需要删掉

**Comment by weavers1f** [comment]
> > > 果然！从Mactype.ini里去掉dwm.exe，杀掉进程就好了
> > 
> > 
> > 请问是要从哪里来去掉？在[UnloadDll]下面添加dwm.exe吗？
> 
> 正相反，是说不要unload它，如果你的Mactype.ini或者配置文件里有把它unload，需要删掉

哦哦，好的，谢谢，我看了下我的配置中本来就unload中没这项
