### ISSUE TITLE
2024.9.14 崩溃到无法使用

### ISSUE THREAD

**Issue by doio** [snowie2000/mactype#1044]
打开 MacWiz 设置 `Run as a service` 点击下一步就会报错，之前可以成功一次，但是时不时会让 IDM 崩溃退出
使用 MacTray 直接运行，但是选择 Disable 的时候也会崩溃，刚才试了一下又不会了，真的好奇怪

Run as a Service 百分百崩溃 QAQ

![2024-11-25_11-58-11](https://github.com/user-attachments/assets/ec33c995-e235-48bd-be89-5d9437a21178)
![2024-11-25_11-58-22](https://github.com/user-attachments/assets/c93c3034-87d5-4595-9a38-7b56e16be613)

[bugreport.txt](https://github.com/user-attachments/files/17896931/bugreport.txt)

**Comment by snowie2000** [comment]
好的，我一会儿看一下具体报错的位置

**Comment by snowie2000** [comment]
我找到了出错的位置，那是一段十分古老的代码，有十年以上的历史，所以出错的可能性微乎其微……

请把你的 **所有**配置 都传上来我试一下，因为下一步是生成配置缩略图，我相信是你的配置文件夹中存在一个有问题的配置文件，触发了这个bug。

或者你可以重新安装mactype，不要使用你自己创建的配置文件，使用内置的配置，应该不会有问题。

PS：mactype必须安装在c:\program files下(假设c为你的系统盘)，他不可以被安装在任何其他地方。

**Comment by doio** [comment]
啊？那恐怖的问题出来了，
我是新系统，刚安装不久，昨天第一次全新安装了 MacType，使用默认安装位置，并且用的是默认的配置文件，使用了 `ini\XMac\XMac.LCD.HotShift@XHei(iOS^MacOS).ini` 这个配置；
之前自己的配置文件也是根据这个文件修改的，对比发现仅仅修改了 `GammaValue=1.4` 为 1.1 （自己的配置改回 1.4 也是会崩溃），注释了 `Shadow=1,1,60,FFFFFF,30,000000`

看到`[Individual]`下面的字体，
我猜想可能是因为我为了英文系统语言下面，在 Telegram 上显示中文（因为不删就会默认日文字符优先），在注册表软删除了日文、韩文、繁中、字体有关？
Ref. https://zhuanlan.zhihu.com/p/502139239

😲😲

**Comment by snowie2000** [comment]
那是不可能的。我可以看到你安装的位置在C:\User\Milo\Mactype，这不可能是默认的安装位置。

**Comment by doio** [comment]
> 那是不可能的。我可以看到你安装的位置在C:\User\Milo\Mactype，这不可能是默认的安装位置。

因为默认安装位置也会这样所以索性直接变成 portable 了 Orz

**Comment by snowie2000** [comment]
mactype不支持portable。

配置文件用default试试。不要使用字体替换。

那个错误是发现在渲染的过程中，出现了缓存无效的情况。但用到的代码存在了很久很久了……

**Comment by doio** [comment]
刚才又安装了一次到默认位置，安装成功勾选了打开 MacType，直接出现错误了... >_<
![2024-11-25_14-13-50](https://github.com/user-attachments/assets/a219b1ce-250e-411e-9a1d-421f15061122)

[bugreport.txt](https://github.com/user-attachments/files/17898129/bugreport.txt)



第二次可以打开，然后 Run as a service 又出现了

![2](https://github.com/user-attachments/assets/3eafc020-ebb1-4438-8e5d-56337dc77ca6)

**Comment by snowie2000** [comment]
这个错误非常经典了，你是不是languages文件夹没了……

**Comment by doio** [comment]
有的鸭 
![2024-11-25_14-22-42](https://github.com/user-attachments/assets/199c17c4-ecd7-4286-9434-28e1ed89f48a)

顺带一提，系统是 Windows 11 Pro 24H2 (26100.2454)

**Comment by snowie2000** [comment]
该错误出现在mactray的翻译组件中，意味着翻译组件找不到对应的信息，这个错误报告从未出现在任何人的issue中。
`Property CustomHint does not exist` 更是奇葩中的战斗机，因为根本不可能出现这个错误的。该错误出现在TypInfo这个Delphi系统文件中，CustomHint是任何组件都必定存在的属性。我无法解释为什么会出现这个错误。

**Comment by snowie2000** [comment]
你的这个系统存在非常不正常的现象，我怀疑你的内存有问题。

**Comment by doio** [comment]
> 你的这个系统存在非常不正常的现象，我怀疑你的内存有问题。

啊这，那我也无法解释了，前阵子确实蓝屏了一次后来就没有了，但是貌似系统后来也没出现什么问题了，我不愿相信内存有问题，暂且归咎于 24H2 是一坨翔吧 🤷‍♂️🤦‍♂️🤦‍♂️

**Comment by snowie2000** [comment]
建议你使用系统的内存检查工具检查一下。内存问题是很难感知出来的。

你报告的错误不是可以用正常思路可以解释的。如果说mactype.core中的错误可能是我的判断逻辑存在漏洞，那mactray中报出的错误就根本无法解释了。

为了安全考虑，macwiz虽然会加载mactype，但会禁用渲染，以防一不小心设置了奇怪的参数导致整个界面都看不见了，所以mactype中的错误很难影响到macwiz本身。你报错的错误就是在不可能出现错误的地方出错了，并且具有随机性，这很像内存问题导致的。

**Comment by doio** [comment]
> 建议你使用系统的内存检查工具检查一下。内存问题是很难感知出来的。

（就在这时出现了两个不同的错误，仅此记录）
![20241125143305](https://github.com/user-attachments/assets/bce9f019-e864-406e-8351-4262755a11b2)
![3](https://github.com/user-attachments/assets/10e5253c-e995-4a5e-9b40-5a4fe0950015)

（天，塌，了）(这就去检查内存）

**Comment by snowie2000** [comment]
你还是检测下内存吧。。。这些错误要不就是内存，要不就是病毒

**Comment by snowie2000** [comment]
你可以试试把mactype那些dll全删了，再启动看看会不会接着报错……

**Comment by doio** [comment]
> 你还是检测下内存吧。。。这些错误要不就是内存，要不就是病毒

好消息：进度条双双到 100% 然后电脑重启了，无错误
坏消息：重启完到输入密码界面蓝屏了 💀💀

我尝试用用旧版本好了，因为另一台电脑也是 24H2 用服务模式没问题的说...

**Comment by snowie2000** [comment]
………………………………

你应该进系统看报告，我记得好像要回到系统才能看到报告的样子。。。

另外也有用户层的内存检测工具，不过也是很慢的就是了……

你这个输入密码都会蓝屏的系统说没有问题，我是真不相信

**Comment by doio** [comment]
> ………………………………
> 
> 你应该进系统看报告，我记得好像要回到系统才能看到报告的样子。。。
> 
> 另外也有用户层的内存检测工具，不过也是很慢的就是了……
> 
> 你这个输入密码都会蓝屏的系统说没有问题，我是真不相信

甚至因为那次蓝屏在 Events Viewer 还找不到 `MemoryDiagnostics-Results` 的日志...... 

我先去哭一会，谢谢大大的精神存在支持

**Comment by snowie2000** [comment]
Windows那个内存测试在测试过程中就会显示内存是否正常。

不过你可以试试memtest86，那个比Windows的更专业，肯定不会蓝屏~

**Comment by ssssssbbb** [comment]
> 啊？那恐怖的问题出来了， 我是新系统，刚安装不久，昨天第一次全新安装了 MacType，使用默认安装位置，并且用的是默认的配置文件，使用了 `ini\XMac\XMac.LCD.HotShift@XHei(iOS^MacOS).ini` 这个配置； 之前自己的配置文件也是根据这个文件修改的，对比发现仅仅修改了 `GammaValue=1.4` 为 1.1 （自己的配置改回 1.4 也是会崩溃），注释了 `Shadow=1,1,60,FFFFFF,30,000000`
> 
> 看到`[Individual]`下面的字体， 我猜想可能是因为我为了英文系统语言下面，在 Telegram 上显示中文（因为不删就会默认日文字符优先），在注册表软删除了日文、韩文、繁中、字体有关？ Ref. https://zhuanlan.zhihu.com/p/502139239
> 
> 😲😲

温馨提示，这软件没有默认配置，所谓的默认就是随便抓来一个，XMAC那些更是没有章法。自带的里面像mufunyo这种规范工整的可以确保没有错误，其他的你实在要用就拿Mactuner另存一份。

**Comment by ssssssbbb** [comment]
内存问题，有显卡的开Furmark，显卡温度到顶之后并行测试Ycruncher10分钟侧重内存的项目，可以最快速度暴露内存或内存控制器的问题。

**Comment by snowie2000** [comment]
像他这样时不时会蓝屏的不是内存问题也很可能是别的硬件问题。

**Comment by doio** [comment]
（我是来 update 一下的）
应该是 14900K 更新了微代码的锅，追求新 BIOS 一路更新微代码到 0x12B 退回了 BIOS 到 Intel 发神经前就好了... 一切都好了... 应该是如此 

为了更稳定回到了 Windows 11 23H2，果然这破 Windows 字体渲染还是要配合 MacType 来食用...

**Comment by snowie2000** [comment]
传说中缩缸王14代吗？
还好我在用AMD。YES

**Comment by doio** [comment]
> 传说中缩缸王14代吗？ 还好我在用AMD。YES

￣へ￣ 昨晚刚回退，暂时没事，希望只能是这个问题了，否则我反手一个扔进垃圾桶（  
AMD 进入购物车完成 ☑
