### ISSUE TITLE
need help with uninstalling mactype (Windows 11 23H2)

### ISSUE THREAD

**Issue by Plasimticis** [snowie2000/mactype#1050]
i know this may not be seen but,
Recently i uninstalled mactype (i previously installed mactype as a tray i think) because it didn't look good on my resolution, but when i did that, i forgot to click 'Restart Now' and clicked 'Restart Later' but even after i restarted, the fonts were still there, i checked the mactype installation folder and deleted everything inside there, but the dll files: 'Mactype.dll, Mactype.Core.dll' were still there, and said it was being used, so i used powertoys file locksmith, and found out that it was being used by dllhost.exe, so i tried to use a unlocker, but the unlocker ends the dllhost.exe process, which results in a bsod, i have not yet found a way to get rid of the font.

also it isn't happening in just paint.NET, even my taskbar and explorer is using mactype font and some other applications too.

here are some images to show mactype is still running (app shown: paint.net)
![mactype being used](https://github.com/user-attachments/assets/1b458772-285c-4521-98bb-bfe5c9cd5f2f)
![mactype being used](https://github.com/user-attachments/assets/4dab7d6c-90e7-447b-b01d-a2e4dff2f58f)

**Comment by snowie2000** [comment]
Download process explorer, and use it to check DLLs loaded by explorer.exe. In the DLL panel, you should see if there are any remaining mactype files that are being loaded unintentionally.

**Comment by Plasimticis** [comment]
okay i will check

**Comment by Plasimticis** [comment]
i have checked, i dont see any mactype files, but the font rendering is still there
![image](https://github.com/user-attachments/assets/d3ea6c84-fa70-413a-98d9-10d6f26bbc58)
as you can see, the edges are different from normal windows (cleartype)

**Comment by snowie2000** [comment]
If no mactype files are loaded, then mactype does nothing to your system.

It does not have the ability to change any files in your system nor can it modify any registry values permanently.

**Comment by Plasimticis** [comment]
so how can i fix the font still looking like mactype

**Comment by snowie2000** [comment]
you may launch the cleartype tuner by typing cttune in the run dialog to reset cleartype params.

**Comment by Plasimticis** [comment]
didn't change anything

**Comment by snowie2000** [comment]
Then I have no idea what has changed in your system.

**Comment by Plasimticis** [comment]
i think ill just reinstall mactype and then disable it from there, ill tell you if it works

**Comment by Plasimticis** [comment]
Yeah it didn't work, i'll leave it for now, thanks for helping.
