### ISSUE TITLE
VirtualBox-4.3.14-95030-Win 版本不兼容mactype

### ISSUE THREAD

**Issue by GoogleCodeExporter** [snowie2000/mactype#117]
```
VirtualBox-4.3.14-95030-Win 不兼容mactype
运行vbox 就会报错。。


```

Original issue reported on code.google.com by `xua...@gmail.com` on 25 Jul 2014 at 1:17

**Comment by pingplug** [comment]
现在还是不兼容，建议将virtualbox.exe加入排除列表

**Comment by snowie2000** [comment]
vbox有复杂的注入检测机制，由于调试非常麻烦，所以目前无法解决。下个版本直接排除掉算了。
