### ISSUE TITLE
Chrome (44.0.2403.157) rendering PARTIALLY!

### ISSUE THREAD

**Issue by ttcg52** [snowie2000/mactype#132]
Even with --disable-directwrite-for-ui it still does not render some individual characters, and also some characters it does not show at all. What might be wrong here? If you want more details please ask me, thanks!

**Comment by snowie2000** [comment]
Ya, I know these is a issue in Chrome related to multithreads, and I have build a new version which fixed this bug. It is now being tested, if you wanna join this test, just leave a message here to let me know

**Comment by ttcg52** [comment]
Oh, I would most definitely like to test it! What should I do to test it?

**Comment by snowie2000** [comment]
just send me a email to mactype.feedback@gmail.com

**Comment by ttcg52** [comment]
Thank you so much! I just tried it (replaced the dll files), and it seems like it fixed all problems I was having previously! I will report again later whether it continues being consistent.

**Comment by snowie2000** [comment]
No, even not possible to do that.

**Comment by rtpm** [comment]
Any release date on new version?
Ps. will the source be published?

Thanks!

**Comment by ttcg52** [comment]
Okay, so unfortunately I had to come back with bad news, the dev dll's are working great for the most part, but recently I am having some issues with rendering on Chrome (same version), URL bar mostly, here's a screenshot worth 1000 words: 
![mactype partial rendering chrome url bar](https://cloud.githubusercontent.com/assets/9367373/9672914/235eeb00-529f-11e5-8880-5fd24cb6444b.png) And I am running Chrome with this command line to force disabling DirectWrite for UI, cause without it the UI does't render at all (only the website area). Any idea or workaround?

**Comment by ttcg52** [comment]
Okay, so unfortunately I had to come back with bad news, the dev dll's are
working great for the most part, but recently I am having some issues with
rendering on Chrome (version 45.0.2454.85 m, newer), URL bar mostly, here's
a screenshot worth 1000 words:

[image: mactype partial rendering chrome url bar]
<https://cloud.githubusercontent.com/assets/9367373/9672914/235eeb00-529f-11e5-8880-5fd24cb6444b.png>

And I am running Chrome with this command line to force disabling
DirectWrite for UI, cause without it the UI does't render at all (only the
website area). Any idea or workaround? Thanks!

**Comment by snowie2000** [comment]
I'm sorry that I don't such a recent version of chrome (I use some modified version of it, which dose not catch up with chrome in time). I didn't encounter the url bar bug in my browser and I DO know that chrome need a command-line to disable directwrite for UI and flag switch for web content.
But unfortunately I didn't figure out a way to support subpixel rendering for directwrite (only grey scale rendering is possible). Until I find the way or MS provide some good GDI inter-operator APIs, you have to use this trick to make mactype work with chrome.
