### ISSUE TITLE
How to uninstall MacType and revert changes?

### ISSUE THREAD

**Issue by Deorro** [snowie2000/mactype#133]
Hi.

If you uninstall changes again as they were before or have some other configuration to remove deleted?

Bye.

**Comment by snowie2000** [comment]
Hi.
I'm sorry that I cannot quite understand you. So let me guess, you want to get Mactype completed uninstalled and worried that if there was any files or configurations remain in the system.

If my guess is right, here is what you should do to completely wipe mactype out~
1. launch macwiz.exe and select "Manual" mode.
2. if your previous mode is not manual mode, reboot your computer
3. launch uninstall to remove mactype

That's all. Your system is now return to its stock status.

**Comment by Deorro** [comment]
Thanks, but what is macwiz?

**Comment by snowie2000** [comment]
MacWiz, aka MacType Wizard is a executable file in mactype installation folder named macwiz.exe

**Comment by Deorro** [comment]
It was slow to respond, in the end only uninstalled it and it seems that the settings and changes are eliminated

**Comment by alecpermison** [comment]
Doesn't work. The uninstaller only has an install option available.

**Comment by nate456789** [comment]
Same here

**Comment by GarageMan** [comment]
Installing MacType adds an uninstall option to the Windows Start menu. 

This uninstall option is in Chinese - but has an Recycle Bin icon!

Click this to uninstall MacType. 

Once you uninstall the app you have to restart your PC

**Comment by sammilucia** [comment]
Hi @GarageMan, if you install the latest MacType beta5 it shouldn't have icons in Chinese https://github.com/snowie2000/mactype/releases/tag/2018.1-beta5

**Comment by PushkaCom** [comment]
When I select uninstall in Windows 10 Settings, it asks to install the program, or repair / add-remove features, but there is no uninstall option, no recycling bin, and I can't unselect the root-item in the repair list - there is no way to uninstall... I'm on a company computer, I didn't install this app - I tried to install the latest version - and it installed as a 2nd app, not an upgrade, and when I uninstalled it, this un-uninstallable version was still there...

 
![image](https://user-images.githubusercontent.com/985223/228144795-99089ce5-b250-4330-889e-4366be8c3bbf.png)

![image](https://user-images.githubusercontent.com/985223/228144866-6da1e0f0-0d95-47f4-a5dc-c2a950b2984c.png)

 
![image](https://user-images.githubusercontent.com/985223/228144920-4e91068a-4b9c-4b67-ba2f-db82754ddf38.png)

**Comment by snowie2000** [comment]
The installation has been moved from advanced installer to inno setup, so you can't uninstall using the old uninstaller.
