### ISSUE TITLE
无法正常渲染某些特定网页

### ISSUE THREAD

**Issue by neunundneunzig** [snowie2000/mactype#134]
比如这个：http://www.iciba.com/%E6%B5%8B%E8%AF%95

![qq 20150921031748](https://cloud.githubusercontent.com/assets/3582067/9982434/5b6e3690-600f-11e5-80d2-15f0905797d4.png)

**Comment by snowie2000** [comment]
It's undoubtedly working in your screenshot.

**Comment by neunundneunzig** [comment]
look at those characters below and those in the sidebar
I am sure it's not rendered properly
