### ISSUE TITLE
Mactype Mirror

### ISSUE THREAD

**Issue by sms200207** [snowie2000/mactype#136]
Site is dead. But someone Gave us mirror.
https://eddon.systems/Download/MacTypeInstaller_2013_1231_0.exe

**Comment by JohnDDuncanIII** [comment]
Also, the source is still unavailable for download

**Comment by dp12** [comment]
ced64k from [Reddit](https://www.reddit.com/r/techsupport/comments/3bl8lh/need_mactype_install_files_for_windows/) also kindly provided a link: 
[MacTypeInstaller_2013_1231_0.exe](https://mega.nz/#!9og0WIhY!Pg020i0KOZ5iILfURTM_RNuYQ8Im9hddCm1tYsEBbZU)
