### ISSUE TITLE
All 64-bit programs crash with BEX64 error

### ISSUE THREAD

**Issue by jimbo1qaz** [snowie2000/mactype#137]
After a few minutes (variable) of using MacType, all newly opened 64-bit programs crash with BEX64.

**Comment by jimbo1qaz** [comment]
Workaround: Right click -> Set -> uncheck "Allow to manage 64-bit proce...".

**Comment by dannymichel** [comment]
Is this project dead?

**Comment by noe132** [comment]
@dannymichel 
there is a recently update of this program
page: http://tieba.baidu.com/p/4357577608

you can download the update patch at : http://pan.baidu.com/s/1dEoK39B
clicking the button "下载(786KB)" at top right

u need former version install and decompress that file and replace them

maybe you can download the former version installer here:
https://github.com/Klaudit/mactype/releases/download/2013-12-31/MacTypeInstaller_2013_1231_0.exe

i think the author dont have time to maintain this project
and this patch works fine with my win10 64

**Comment by dannymichel** [comment]
I can't seem to translate this page http://pan.baidu.com/s/1dEoK39B

**Comment by jimbo1qaz** [comment]
I wasn't expecting this to pop up in my inbox... I thought MacType was dead! (Well I haven't been using it for a while, due to this issue, some fonts rendering too short (not tall enough), and me using Linux.)

So what commit fixed the issue? Are you releasing, or should I compile myself?
