### ISSUE TITLE
MacTypes causes bugs in some non-GUI programs

### ISSUE THREAD

**Issue by tanmatra** [snowie2000/mactype#139]
Seems MacType can has some bad influence on some console programs (al least 64-bit). See discussions in Git for Windows issues list: https://github.com/git-for-windows/git/issues/704 and https://github.com/git-for-windows/git/issues/710. Probably it creates hooks what do something wrong with Unicode functions.

**Comment by kurisubrooks** [comment]
```WARNING! The MacType's hooks are detected at 0x0000000180000000
         C:\Program Files (x86)\MacType\MacType64.dll
         Please add ConEmuC.exe and ConEmuC64.exe
         to the exclusion list to avoid crashes!
         http://conemu.github.io/en/Installation.html#mactype``` I get this in CMDER :disappointed:

**Comment by Revod** [comment]
I have the same problem, I tried add the .exe to exclude but still getting the Warning message

**Comment by Explorare** [comment]
Same problem on ConEmu.

**Comment by kurumigi** [comment]
Git for Windows is using MSYS2. In my humble opinion, this problem is some relation to #192?

**Comment by Explorare** [comment]
@kurumigi Yep. I think it's the same issue. Thanks.

**Comment by easonyuen** [comment]
@Explorare Hello! I have the same problem then I added `ConEmuC.exe` and `ConEmuC64.exe` to exclude list. But they didn't work even worse than before. Did you solve the problem ?

**Comment by Explorare** [comment]
@easonyuen I excluded `cmd.exe`, `ConEmu64.exe`, `ConEmuC64.exe` and no more error message after. Hope this could help you.

**Comment by easonyuen** [comment]
@Explorare Thanks~let me try

**Comment by amosbird** [comment]
Any updates on this one?

**Comment by sammilucia** [comment]
Hi @amosbird, I'm closing this as it was an issue with an old version of MacType. Please let us know if you're still experiencing this issue with the latest MacType 😊. Thank you
