### ISSUE TITLE
MacType is now opensource. 

### ISSUE THREAD

**Issue by snowie2000** [snowie2000/mactype#141]
If you find any file missing, please reply here. (please search for dependencies on internet, I won't upload them)

Sorry for my lack of time to maintenance mactype.

**Comment by synthtech** [comment]
I have a few questions, if you don't mind:
- What is the code licensed under?
- Does the project only build the MacType dlls?

**Comment by snowie2000** [comment]
- Apache Licence 2.0
- Yes, only the core mactype.dll. For mactype loader, tuner and wizard, I don't think these are anything difficult to replicate. You can surely make your own loader and make it way better than mine. Or just continue to use my loader as long as the hook interface is compatible.

**Comment by synthtech** [comment]
>GPLv3

Including it as a license file might be a good idea.

>Yes, only the core mactype.dll.

Ah, thanks for clarifying. I haven't been able to successfully build it yet, so I wasn't sure.

**Comment by christopherccg** [comment]
Great

**Comment by Pyre909** [comment]
Are there any plans for creating an executable that will install mactype or will we need to create our own?

Thanks!

**Comment by webclerk** [comment]
Thank you.....

**Comment by dogancelik** [comment]
Thank you!

**Comment by snowie2000** [comment]
Not yet.
I'm learning javascript these days :laughing:

**Comment by tanmatra** [comment]
@dogancelik What version is mentioned in that email?

**Comment by dogancelik** [comment]
@tanmatra `MacType_dev_20160216`, you can find if you google, you need to replace the DLL with the old one in MacType folder.

**Comment by Artoria2e5** [comment]
> @synthtech: Including it as a license file might be a good idea.

In addition to LICENSE file inclusion, a (boring but necessary) GPL header is quite important for GPL projects.
