### ISSUE TITLE
Windows 10 anniversary issue

### ISSUE THREAD

**Issue by mnnc** [snowie2000/mactype#144]
After upgrading to w10 anniversary edition - on standalone and compatible mode - the desktop won't stop refreshing every 5-10 seconds until you exit mactype. Also, if you try to open any other program, one of these refreshes will close it. If you want to stop the same behaviour after the next restart, you'll have to uninstall mactype or revert to the previous version of windows 10.

**Comment by Revod** [comment]
Is Weird, I have Windows 10 AU Installed on my computer and mactype work perfect, I uninstalled mactype and install again with Registry Mode and done. See
![2016-08-06_14-38-51](https://cloud.githubusercontent.com/assets/10109689/17458582/9e7db98a-5be3-11e6-807f-d4bd5f3e250e.png)
![2016-08-06_14-39-10](https://cloud.githubusercontent.com/assets/10109689/17458583/9e7eb538-5be3-11e6-9e41-a6225ffb53d5.png)

**Comment by Wolfarelli** [comment]
I have the same problem as mmnc. Tried reinstalling it and setting it in the different modes, but they didn't work, made explorer crash, and the service mode gave me bsod after every boot, had to enter into safe mode and uninstall it.

**Comment by gomifromparis** [comment]
I had the same issue, it can be solved my updating the EasyHK dlls
http://micachi.blog.jp/archives/2016_05_06_Windows+10+Build+14295%E4%BB%A5%E9%99%8D%E7%94%A8%E3%81%AEMacType%E4%BF%AE%E6%AD%A3%E3%83%91%E3%83%83%E3%83%81.html

**Comment by snowie2000** [comment]
update easyhook may solve the issue in some computer, but in some other computers, it will cause mactype x64 stop completely. And the mactype x64 agent will start and stop constantly as you opening the mactray.exe.

I am now working on it and have fixed all the problems I knew. New release come soon.

**Comment by JonnyRedHed** [comment]
And for win7x64 as well :)   

Thanks for doing an update.

**Comment by Wolfarelli** [comment]
Thank you snowie!

**Comment by sifmarcy** [comment]
Where can i download the latest version?
Thanks

**Comment by oxysoft** [comment]
Could we get an eta on that new release?

**Comment by snowie2000** [comment]
@oxysoft There is too many things I need to update, the mactray, the 64bit agent, the installer, all of which take my spare times away.
Probably next week. I'm working on it.

**Comment by oxysoft** [comment]
np, take the time that you need

**Comment by aridzephyr** [comment]
@snowie2000 this is the one piece of software that I need to make windows tolerable for everyday usage, thank you so much for updating it! Can't wait!

**Comment by rudolphos** [comment]
Which is the best way to enable MacType ? registry or service ? 

I have win 10 AU and it doesn't work with registry.
