### ISSUE TITLE
Directwrite font substitute

### ISSUE THREAD

**Issue by river1** [snowie2000/mactype#145]
![1](https://cloud.githubusercontent.com/assets/2911604/17835405/b5d5d156-679d-11e6-9a43-87f976f74cbd.PNG)
![2](https://cloud.githubusercontent.com/assets/2911604/17835409/b9f74c92-679d-11e6-94bc-547944bab8bc.PNG)
Only one rule is active to substitute for SimSun, but the icon is also replaced.

**Comment by snowie2000** [comment]
Which app are you using?

**Comment by river1** [comment]
Nvidia Geforce Experiance 3.0.3.127
