### ISSUE TITLE
Direct Write not working with latest release.

### ISSUE THREAD

**Issue by wasd--** [snowie2000/mactype#147]
Hi,

Till today I was using the 2013 release with silight-jp patch and was working everything(Including Firefox and Chrome). I saw this release deleted everything, installed the new one. Windows is working but Firefox and Chrome don't.

I added the **DirectWrite=1** line to mactype.ini file and the same.

Windows 10 14.393.82.

**Comment by snowie2000** [comment]
You should add this configure to specific profile you actually use, not mactype.ini. It won't work that way.

**Comment by wasd--** [comment]
Ok, working now thanks :)
