### ISSUE TITLE
breaks start menu in win10 anniv update

### ISSUE THREAD

**Issue by ericblade** [snowie2000/mactype#149]
Not sure how to help, but I installed into registry on Win10 AU, rebooted, and after noting that I don't particularly care for the software, I attempted to uninstall, and discovered that my Start menu was completely inoperable.  Rebooting again did not fix.  Pressing the Start key or button on screen resulted in nothing at all obvious happening.

Re-running the installer from my downloads directory, telling it to uninstall, then rebooting again, fixed.

**Comment by snowie2000** [comment]
I am not sure what happened, try to use a profile other than default.ini or comment directwrite=1 in your profile and see if works.

**Comment by sammilucia** [comment]
Closing this as it's with an obsolete version of MacType. Please let us know if this occurs with the latest version.
