### ISSUE TITLE
Error Using Chrome 52 on Windows 10

### ISSUE THREAD

**Issue by fung** [snowie2000/mactype#150]
Hi @snowie2000, 

Thanks for the great effort. MacType brings me a lot more joy using Windows.

After upgraded to latest version, everything seems to be better than old MacType + patch.

The only issue I got so far is Chrome (version 52.0.2743.116) not working at all. In Event Viewer, I got following errors.

Error 1:
> Faulting application name: chrome.exe, version: 52.0.2743.116, time stamp: 0x57a128a8
> Faulting module name: GDI32.dll, version: 10.0.10586.420, time stamp: 0x57491f19
> Exception code: 0xc0000005
> Fault offset: 0x000a1082
> Faulting process id: 0x1fb8
> Faulting application start time: 0x01d20329bb519f6a
> Faulting application path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> Faulting module path: C:\WINDOWS\SYSTEM32\GDI32.dll
> Report Id: a7aec9a5-0c4e-4cca-ab29-f91cfc07bc60

Error 2:
> Faulting application name: chrome.exe, version: 52.0.2743.116, time stamp: 0x57a128a8
> Faulting module name: ntdll.dll, version: 10.0.10586.306, time stamp: 0x571afb7f
> Exception code: 0xc0000005
> Fault offset: 0x0003dc0e
> Faulting process id: 0x1fb8
> Faulting application start time: 0x01d20329bb519f6a
> Faulting application path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
> Report Id: f06eb8b4-47f2-4eb4-828d-b047b959b827

I am using Windows 10 Enterprise v1511 Build 10586.545.

**Comment by drxt** [comment]
Can confirm Chrome is completely broken in the new MacType release, and all browsers that are based on Blink (such as Vivaldi and Opera) are affected as well. When I attempt to start the browser I receive Chrome notifications telling me that my browser extensions have crashed.

**Comment by Revod** [comment]
Is weird, for me work fine, I'm using Cent Browser and dont have problem

**Comment by Bai-Jie** [comment]
I encountered Error 2 when exclude chrome.exe by adding it in *[UnloadDll]* section of Default profile file.

But If I exclude chrome.exe by adding it in ***[ExcludeModule]*** section, chrome will work.

Environment:
 Chrome 53, Windows 8.1 and MacType 1.2016.901.0

**Comment by myshzzx** [comment]
chrome v52 uses DirectWrite,  and this can't be disabled. stay in v51 and wait for update.

**Comment by Revod** [comment]
or use Cent Browser, the kernel is v52 and have DirectWrite support

**Comment by snowie2000** [comment]
Check out the test files I uploaded in forum:
http://bbs.themex.net/showthread.php?t=16904792

**Comment by maaldheefee** [comment]
Can you please upload them elsewhere?

**Comment by snowie2000** [comment]
Alright, you can get them from official site:
http://mactype.net/station/version1.rar
http://mactype.net/station/version2.rar
http://mactype.net/station/version3.rar

**Comment by Bai-Jie** [comment]
All three versions not work here.

Environment:
Windows 8.1
MacType 1.2016.901.0
Chrome 53.0.2785.89 m **(64-bit)**

Issue:
Can start up Chrome, but all tabs and plugins crashed.

My Workaround：
don't render Chrome by adding chrome.exe to **[ExcludeModule]** section

**Comment by wasd--** [comment]
I'am the only one without problems with Chrome? x64 both system and Chrome

**Comment by Bai-Jie** [comment]
After some trial, I found that this error may be related to **HookChildProcesses** config.

I encountered this error only if HookChildProcesses is 1.

**Comment by snowie2000** [comment]
Of course, if this param sets to 0, mactype won't work for chrome at all.

**Comment by Bai-Jie** [comment]
oh, I see
