### ISSUE TITLE
Incorrect rendering of equations in Mathematica with latest release

### ISSUE THREAD

**Issue by kvdvs** [snowie2000/mactype#151]
With the latest MacType release (2016.0830.0), equations in Mathematica are rendered incorrectly. The spacing around some symbols becomes much larger and stretches the equation.

![Screen Cap](http://i.imgur.com/92zdPl2.jpg)

I think this has something to do with the DirectWrite tweak. When using MacType 2013.1231 + silight-jp's Patch, the same problem happens. But you can avoid this by adding Mathematica.exe to the exclude list in UserParams.ini.

Now with MacType 2016.0830, equations are rendered incorrectly even if I set DirectWrite=0. I can add Mathematica.exe to the overall exclusion list, but I want to have the benefit of MacType in Mathematica without it messing up the equations...

@snowie2000 It would be super if you could look into this :-) Thanks!

**Comment by snowie2000** [comment]
try the new version with clipboxfix=0 param

**Comment by maaldheefee** [comment]
What exactly is the clipbox fix? I keep seeing it a lot. Would you consider updating the wiki a bit?

**Comment by snowie2000** [comment]
https://github.com/snowie2000/mactype/wiki/ClipBoxFix

**Comment by kvdvs** [comment]
Thanks for the reply.

I added [Experimental@Mathematica.exe] clipboxfix=0 to the profile I'm using with the latest release (0901). Still, the same problem with unnecessary spacing in the equations :-(

**Comment by maaldheefee** [comment]
@snowie2000 Thanks a lot!

**Comment by snowie2000** [comment]
@kvdvs 
Looks like I made a mistake on if logic. I'll fix it later.

**Comment by kvdvs** [comment]
Noticed a few more rendering issues with Mathematica
![Imgur](http://i.imgur.com/xZDnPdx.jpg)
- The digit grouping symbol is not rendered correctly.
- Strangely, the border lines are rendered much thicker now. I'm guessing they are not characters and should not be rendered by MacType?

**Comment by kvdvs** [comment]
Problem solved in release 0902.1.

Thanks! Great work!
