### ISSUE TITLE
Letters 'g','p','y' etc. cut off at the bottom at certain sizes across the board.

### ISSUE THREAD

**Issue by mjuzikfrik** [snowie2000/mactype#152]
Hi,

Could you please fix this somehow? It occurs at certain sizes and all over the place.

![cut out g](https://cloud.githubusercontent.com/assets/16630872/18174922/adada2d0-706f-11e6-950f-c1b775a19052.png)

**Comment by Revod** [comment]
I have the same problem

**Comment by snowie2000** [comment]
Not possible.
That's because windows clipped text with a predefined height.

**Comment by mjuzikfrik** [comment]
That's a real pity. :( Anyway, thank you very much this piece of software!
