### ISSUE TITLE
With the latest version, booting time became too long

### ISSUE THREAD

**Issue by sym233** [snowie2000/mactype#153]
From initial interface (with Thinkpad logo) to choose you operation system interface, it took minutes of time to load, like this picture:
![u 2553113422 2111761418 fm 21 gp 0](https://cloud.githubusercontent.com/assets/10321547/18176092/c0d1a564-70a6-11e6-8ade-a4602bb368d9.jpg)

Normally, it only takes about 2 seconds with SSD.

The problem occurs with versions both 2016.0830 and 2016.0901, but 2013.1231 is ok.

OS: win10 professional 1151 10586.545, simplified Chinese

**Comment by snowie2000** [comment]
try new release.
