### ISSUE TITLE
Another version of this product is already installed

### ISSUE THREAD

**Issue by 13-beta2** [snowie2000/mactype#154]
Unable to update using provided installer. 

> Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel.

Please consider an option for release .7z with just binaries.

**Comment by snowie2000** [comment]
no portable version will be provided, it will cause too mucb trouble.

ive uploaded a new installer to solve this problem.
