### ISSUE TITLE
v1.2016.910.0造成Chrome无限崩溃

### ISSUE THREAD

**Issue by TianLi-520** [snowie2000/mactype#155]
更新v1.2016.910.0后重启电脑，Chrome就完全不能用了，所有页面都是崩溃，包括设置页面

**Comment by TianLi-520** [comment]
更新最新的v1.2016.902.1也一样

**Comment by snowie2000** [comment]
无法重现，任何系统任意版本chrome均无问题，故不能修复。

**Comment by TianLi-520** [comment]
那可能就是办公室电脑的环境问题了，有一大堆开发运行软件，刚刚确认家里的电脑的确没有复现

**Comment by icepole-jon** [comment]
@TianLi-520 查看是否使用了热替换的配置文件，尝试排除字体替换，忽略渲染。

**Comment by snowie2000** [comment]
晚上放几个测试补丁出来，请关注论坛

**Comment by TianLi-520** [comment]
@icepole-jon 替换字体只有XP用过，从Windows7到10一直都是默认配置

**Comment by Icemic** [comment]
出现类似问题，但不是崩溃，表现为chrome所有页面无法显示，包括起始空白页和输入url按回车

关闭dw支持后，重启chrome恢复正常

**Comment by snowie2000** [comment]
http://bbs.themex.net/showthread.php?t=16904792
请进行站内的测试，谢谢。

**Comment by SharerMax** [comment]
Win10 x64 1511 简体中文专业版
Google Chrome	53.0.2785.89 (正式版本) m （64 位）
MacType 配置 default

开启后无限崩溃

**Comment by snowie2000** [comment]
issued closed due to new release.
