### ISSUE TITLE
The right half of the Unicode Emoji is lack.

### ISSUE THREAD

**Issue by asuto224** [snowie2000/mactype#156]
The right half of the Unicode Emoji is lacking.
Especially the Eyes Unicode Emoji "👀" is often used in 2ch.
Note that the screenshots is a 2ch browser "Jane Xeno".

![2016-09-02 22](https://cloud.githubusercontent.com/assets/21349846/18206617/7106ad4c-7162-11e6-899e-ccab0767730c.png)
![2016-09-02 23](https://cloud.githubusercontent.com/assets/21349846/18206618/7109287e-7162-11e6-9513-f55679b6fc1e.png)

**Comment by snowie2000** [comment]
Hi, I'm quite sorry that after I trying this browser, I really have no idea how to use it. :cry: 
Does it have an English localized version?

**Comment by asuto224** [comment]
I’m sorry I’m late reply.
English version of Jane Xeno is nothing.
I indicates how to reproduce the bug instead.

Download and unzip the "Xeno150312" from the following website.
http://janexeno.client.jp/
Run Jane2ch.exe, and then select "はい" (Yes) in the dialog box that appears.
Select the "公式BBSMENU" (Official BBS Menu) in "ボード一覧" (Boards Menu List) and press the "OK".
Select the "PC等" (PC, etc.) in "板一覧" (Boards List), open the "Windows", and please open the appropriate thread. (You can select the other boards, so this is an example.)
Please press the yellow pencil icon (open writing form) in the toolbar of the thread view.
Please copy and paste the "👀" in writing form.
Please press the "プレビュー" (Preview) tab. You should look the right half of the "👀" is lacking.
(Incidentally, separately requires local proxy in order to browse the 2ch in the current Jane Xeno.)

According to the Jane Xeno developer, probably there is a bug with the hook of GetTextExtentPoint32W function.
Unicode character has been changed to single-byte question mark at the internal of the MacType.
As a result, all Unicode characters have been notified to the Jane Xeno as a character width of the single-byte question mark.
Note that this bug has been resolved in the MacType Unofficial Patch.

**Comment by snowie2000** [comment]
This is weird in my system that I'm not able to paste this unicode emoji to the jane. It always displayed as a big white square with black frame like this "口". But I was able paste it in the chrome...
Maybe I have to set my system locale to Japan to use the emoji. I'll try it later.

**Comment by snowie2000** [comment]
Bug confirmed.
To reproduce to bug, you have to set system locale to JP. In other locale, it is fine. That's why I didn't notice it before.
I'm working on it.

**Comment by snowie2000** [comment]
Fixed.
Try preview version at http://www.mactype.net/station/MacType_CTP_161026.rar

**Comment by sammilucia** [comment]
Closed as resolved in the latest version of MacType. Please let us know if you still experience this bug 😊
