### ISSUE TITLE
单独程序配置字体替换

### ISSUE THREAD

**Issue by icepole-jon** [snowie2000/mactype#159]
没有找到配置文件相关的文档，搜索了一下2011的时候说过新版会有这方面的支持。。
请问要怎么实现啊。。

**Comment by snowie2000** [comment]
这是早就有的功能了。
[FontSubstitutes@应用程序名称.exe]
以下的配置仅对此应用有效。

**Comment by icepole-jon** [comment]
thanks @snowie2000
