### ISSUE TITLE
 "Wininit event id: 11" is recorded .

### ISSUE THREAD

**Issue by mstyle3244** [snowie2000/mactype#160]
When you restart the computer in the registry mode , in the event viewer "wininit event id: 11" it is recorded .

**Comment by snowie2000** [comment]
This is absolutely normal.
see here: http://answers.microsoft.com/en-us/windows/forum/windows_7-windows_install/event-id-11-source-microsoft-windows-wininit/cf21d920-4a10-4b67-a850-c59b5f20d658?auth=1

It means there is a init dll being loaded, which is what exactly MacType did in registry mode.
