### ISSUE TITLE
 There is a space problem between the characters .

### ISSUE THREAD

**Issue by mstyle3244** [snowie2000/mactype#162]
![screenshot-m-style mydns jp 2016-09-04 18-38-02](https://cloud.githubusercontent.com/assets/7287737/18230253/61ddd506-72d0-11e6-9ce4-7eabbd612c94.png)

There is a space problem between the characters .

・Windows 10 TH2
・Mac Type 2016_0904_0(Registry Mode + Default.ini)
・Chrome 51.0.2704.106
・font: Helvetica Neue

This problem was resolved by changing the size of the character .

**Comment by snowie2000** [comment]
This won't and can't be fixed.
This is due to that Windows GDI does not support subpixel positioning and it always calculates letter positions base on hinting. Since you disable hinting in MacType, you will get text shapes different from ClearType.

**Comment by sakimarquis** [comment]
> This won't and can't be fixed. This is due to that Windows GDI does not support subpixel positioning and it always calculates letter positions base on hinting. Since you disable hinting in MacType, you will get text shapes different from ClearType.

Hi, when I turn on the hinting (I tried standard hint and auto hint in Mactype), this problem still exists in centbrowser (directwrite is disabled). 
![image](https://user-images.githubusercontent.com/18731818/152471212-40123297-bc05-4bb6-bc1c-86b2f5325a19.png)
![image](https://user-images.githubusercontent.com/18731818/152471230-5526caa0-a139-4d7c-b779-d3d85a85ebff.png)
![image](https://user-images.githubusercontent.com/18731818/152471241-c2760944-cc37-4907-b219-d091debe06e3.png)


・Windows 10: 19044.1503
・MacType 2021.1-RC1 (Service Mode + XHe.iMicrosoft.ini with standard hint)
・CentBrowser, Chromium 86.0.4240.198
・font: XHei Microsoft

**Comment by snowie2000** [comment]
Chromium (w or w/o directwrite) uses its own layout engine to arrange characters. Hinting has no effect to it.
