### ISSUE TITLE
升级错误

### ISSUE THREAD

**Issue by bruceCzK** [snowie2000/mactype#163]
使用程序自带的 Updater 升级时会遇到安装错误，失败后程序被卸载，重新安装后升级成功。
用的是注册表加载模式，Default 配置文件，未修改
另外升级后原有配置文件会被覆盖，望修复

![qq 20160904230906](https://cloud.githubusercontent.com/assets/8399711/18231790/d088fb38-72f4-11e6-9bd6-453a7d94b471.jpg)

**Comment by snowie2000** [comment]
正常现象，以后不会了，以前安装程序的问题没法改了

**Comment by bruceCzK** [comment]
好的。希望以后配置文件不要再覆盖掉了，会存一些忽略的程序什么的。先关了
