### ISSUE TITLE
Not working with Firefox 52

### ISSUE THREAD

**Issue by nanake** [snowie2000/mactype#165]
MacType 1.2016.904.0
Windows 10 v1067 build14393.105
Firefox Nightly 51.0a1 build 20160904030201

Mactype no longer work with Firefox 51 due to enabling skia content on Windows by default. 
see. https://bugzilla.mozilla.org/show_bug.cgi?id=1007702

**Workaround**: remove _skia_ form _gfx.content.azure.backends_ in about:config

**Comment by snowie2000** [comment]
enable directwrite tweak will do the trick. but dw is as bad as you can imagine.

**Comment by nanake** [comment]
enabling dw tweak doesn't change anything. :(

**Comment by snowie2000** [comment]
Then just disable skia. Nightly version won't be tested.

**Comment by snowie2000** [comment]
I've tried the nightly 51a, and I can tell you that it is definitely working.
The reason you think it doesn't work is that the DirectWrite is really really bad in Windows7, and there is no any other params that can change the way it renders. It just hints all fonts....
Disable it as long as you still can.

**Comment by kud** [comment]
I've got the same problem here even if I disable direct2d as previously.

**Comment by kud** [comment]
+1 with the workaround. Thanks.

**Comment by zhengbli** [comment]
For firefox I recommend this addon:
https://addons.mozilla.org/en-US/firefox/addon/anti-aliasing-tuner/?src=api
Has been working great for me.

**Comment by kud** [comment]
Interesting as alternative option but when you've got already MacType, what's the point? Does it allow you to use direct2d + skia?

**Comment by zhengbli** [comment]
Things is mactype for DW is not working very well for me (Windows 10 insiders build English version, 1920x1080 14'' screen), fonts are rendered fuzzy under DW. Yeah this addon gets tons of options as well, that's my temp workaround.

**Comment by kud** [comment]
Oh yeah I see what you mean. Thanks for the tips. :)

**Comment by nanake** [comment]
> I've tried the nightly 51a, and I can tell you that it is definitely working.

That's strange. With skia, I see _no difference_ between mactype enable/disable.

Testing with http://nanake.bitbucket.org/tests/tategakitest.html

### skia enabled, mactype enabled
![skia mactype](https://cloud.githubusercontent.com/assets/467392/18382541/9ce64474-76ab-11e6-9fe9-634bd2649944.png)

------------

### skia enabled, mactype disabled
![skia-mactype](https://cloud.githubusercontent.com/assets/467392/18382570/bc69ab24-76ab-11e6-9016-642bc4ca4094.png)

------------

### skia disabled, mactype disabled
![skiadisable-mactype](https://cloud.githubusercontent.com/assets/467392/18383086/07f9268a-76ae-11e6-81eb-eafc60a573ab.png)

------------

### skia disables, mactype enabled
![skiadisable mactype](https://cloud.githubusercontent.com/assets/467392/18383105/1fa5c428-76ae-11e6-902f-f7f53a7a03b0.png)

**Comment by nanake** [comment]
Re-title since skia was backed out in Firefox 51. 
This has planned to enable in 52.

**Comment by kud** [comment]
I don't understand, I remove skia in about:config, but everytime I reboot firefox, it gets back, normal?

**Comment by nanake** [comment]
Go to about:addons > experimentals and remove the extension _SKIA content for Windows_.

this addon prevent users to disable skia.

**Comment by kud** [comment]
Lovely, thanks @nanake !

**Comment by absay** [comment]
Here we go again with FF52 and skia being reset upon browser reboot. No Experiments panel in my FF version.

Any workarounds/solutions to this?

**Comment by Fironet** [comment]
Firefox 54.0a2 (2017-04-18) no longer is compatible with the workaround of changing the `gfx.content.azure.backends` value. Tried also changing the `gfx.canvas.azure.backends` value to remove `skia` but that too didn't work.

Can't seen any Experiments area of the addons either as mentioned above.

**Comment by yfdyh000** [comment]
@Fironet If you enabled the Hardware Acceleration in Options>Advanced, it will try to enable direct2d, unless you set the `gfx.direct2d.disabled` to true.

**Comment by colinc-w** [comment]
I tried all of this to no avail. What ultimately worked was changing the Japanese font under Options > Content > Fonts & Colors > Advanced > Japanese, then I changed sans-serif to Meiryo. I re-enabled hardware acceleration reverted SKIA values. Still works!

**Comment by colorworm** [comment]
Hi,

On Pale Moon 27.4.0 (a Firefox fork), setting the pref layers.prefer-d3d9 to true from the default of false also works. You can even set gfx.direct2d.disabled back to false and still have fonts rendered by MacType. :-)

**Comment by cricrazy** [comment]
I am using Firefox 57. I can confirm that I disable 'Hardware Acceleration' and then removed 'skia' from the `gfx.canvas` and `gfx.content`. It fixes the MacType. It looks great again.

**Comment by sammilucia** [comment]
closed because workaround is available.
