### ISSUE TITLE
Ask whether to keep config file when uninstalling

### ISSUE THREAD

**Issue by mxalbert1996** [snowie2000/mactype#166]
It seems that the installer would first uninstall old version when updating, and it deleted my `MacType.ini` without comfirming which I do not have a backup of.

**Comment by snowie2000** [comment]
Sorry for that. I'll try to fix this problem in the next release.
But please beware that when you upgrade to the next release, DO BACKUP your profile, because this bug is related to uninstaller that can't be fixed in new installer.

**Comment by mxalbert1996** [comment]
Got it. Thanks for replying!
