### ISSUE TITLE
Setup wizard and decimal mark

### ISSUE THREAD

**Issue by justdanpo** [snowie2000/mactype#168]
MacType setup wizard uses system defined decimal mark when saves ini. MacType Tray uses a fixed character ('.') as a decimal mark. So in (for example) Russian Windows fractional values from ini are truncated when readed:

    GammaValue=1,2

is treated as 1.0

Setup wizard and MacType Tray should be consistent and they both should use the same character - system defined or fixed character. But as there are many already created presets I'd prefer fixed character ('.') for compatibility.

**Comment by snowie2000** [comment]
Confirm.
Will be fixed in the next release.
Thank you!
