### ISSUE TITLE
Check for errors with PVS-Studio

### ISSUE THREAD

**Issue by texnikru** [snowie2000/mactype#170]
MacType is awesome tool.
I'm using it about 4 years.
Just would to recommend to test sources with http://www.viva64.com/en/pvs-studio/ for best results. Hope it helps for best results.

**Comment by snowie2000** [comment]
Thank you for your suggestions It looks cool! I'll give it a try later.

**Comment by snowie2000** [comment]
I've tried it. It is great. It found at least 4 errors I've never noticed.
Thank you so much!

**Comment by texnikru** [comment]
Will wait for next update ;)
