### ISSUE TITLE
Window titlebars not affected

### ISSUE THREAD

**Issue by Jeremiidesu** [snowie2000/mactype#171]
Window title bars (except for explorer.exe's titlebars and other custom ones) aren't affected by mactype.

Windows 10 version 1607 (14393.105) 64bits

Also affected windows 7 sp1 x64 with aero. 

(My guess is dwm.exe handles this when Aero's enabled, and hooking into dwm.exe is denied, preventing mactype from rendering the corresponding text)

**Comment by everedit** [comment]
+1

**Comment by kraml** [comment]
Just remove dwm.exe from the [UnloadDll] section of your mactype configuration (.ini) file.

**Comment by snowie2000** [comment]
dwm.exe in Win10 is running in high privilege that cannot be intercepted by MacType.
In Win7, dwm.exe uses a special way to draw titles in Aero glass that hasn't been fully investigated.

**Comment by kraml** [comment]
But my Win10 title bars are properly rendered by MacType. I'm using registry loading mode.

**Comment by snowie2000** [comment]
That's because registry loading mode cares nothing about privilege.

**Comment by Jeremiidesu** [comment]
Wait, i'm using registry registry loading iirc, i'll try with the latest MacType. i think i'm using 2016.902.1

**Comment by mirazmac** [comment]
Facing the same problem with Windows 8 x64. No title bar, including explorer.exe is affected by MacType.

**Comment by sammilucia** [comment]
Can anyone confirm whether this is working in the latest Win10 and the latest beta https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2 ?

I'm having no problems with Win8.1 x64

**Comment by sammilucia** [comment]
Closing as unresponded.

**Comment by joulev** [comment]
Not working for me:

![image](https://user-images.githubusercontent.com/44609036/78205601-bf4c0b80-74c6-11ea-97ed-2df9f56eb246.png)

The title bar does not have the same font as the stuff below.

Windows 10 version 2004 build 19035  
MacType loaded in Registry mode.

**Comment by Popslip** [comment]
Still not working in Windows 11 23H2

**Comment by snowie2000** [comment]
dwm.exe is unloaded by default, you need to remove it from mactype.ini and your profile manually.

Even after removing the dwm.exe and successfully hooking into it, it is still not guaranteed to work as DWM.exe painting is quite special and may be interpreted as mono for unknown reasons.
