### ISSUE TITLE
Cannot install any of 2016 builds on Windows 7 x64.

### ISSUE THREAD

**Issue by xfishbonex** [snowie2000/mactype#172]
2013.1231.0 build installed and works fine with your patched dlls but I cannot update it or just install the 2016 build due to the error:
安装程序在安装此程序包时遇到了错误。可能表明此程序包有错。错误代码是 2755。

**Comment by snowie2000** [comment]
Installer is 100% good.
In the name of science!

**Comment by xfishbonex** [comment]
I didn't mean it's something about the installer but I thought the cause of the issue might be interesting for you. 
So I've collected an install log [install.zip](https://github.com/snowie2000/mactype/files/461075/install.zip). Unfortunately I don't see any particular reason for the issue but hope it can help to clarify it.
Thanks and regards.

**Comment by snowie2000** [comment]
> MSI (s) (E4:CC) [10:42:27:600]: SOFTWARE RESTRICTION POLICY: Verifying transform --> 'C:\Users\Andrey_Bormotov\AppData\Local\Temp\MacType\install\8E66446\1033' against software restriction policy
MSI (s) (E4:CC) [10:42:27:600]: Note: 1: 2262 2: DigitalSignature 3: -2147287038 
MSI (s) (E4:CC) [10:42:27:600]: SOFTWARE RESTRICTION POLICY: C:\Users\Andrey_Bormotov\AppData\Local\Temp\MacType\install\8E66446\1033 is not digitally signed
MSI (s) (E4:CC) [10:42:27:602]: SOFTWARE RESTRICTION POLICY: C:\Users\Andrey_Bormotov\AppData\Local\Temp\MacType\install\8E66446\1033 is not permitted to run at the 'unrestricted' authorization level.
MSI (s) (E4:CC) [10:42:27:603]: The installation of C:\Users\Andrey_Bormotov\AppData\Local\Temp\MacType\install\8E66446\1033 is not permitted by software restriction policy. The Windows Installer only allows installation of unrestricted items. The authorization level returned by software restriction policy was 0x0 (status return 0x0).
One or more customizations are not permitted by software restriction policy.

Looks like you have some software restriction policies set on your system.

**Comment by xfishbonex** [comment]
Thanks a lot! I'll try to resolve it somehow then.

> MacType\install\8E66446\1033 is not digitally signed
So if I still can install the 2013 build it means it was signed? Can we expect that the 2016 build will be signed too?

**Comment by snowie2000** [comment]
I never signed any installer, nor will I do in the future, 'cause the certificate for software signing is not free :laughing: 
I don't know what's your software restriction is, maybe a white list?
