### ISSUE TITLE
Font looks rough under some cases

### ISSUE THREAD

**Issue by Yoctillion** [snowie2000/mactype#174]
For example, if using the default configuration, it looks not so good when searching in Cortana.
![search in cortana](https://cloud.githubusercontent.com/assets/11324635/18344467/67f43cf8-75f2-11e6-8e0e-bc1fd9b3c9b2.png)

**Comment by snowie2000** [comment]
This is the directwrite.

**Comment by Yoctillion** [comment]
Does mactype support DirectWrite now?

**Comment by snowie2000** [comment]
Yes, but it is now no more than a tweak.
A tweak means, it is still the directwrite that does the rendering, and as you can see, it's bad, and bad, and bad.

**Comment by zhengbli** [comment]
Sorry if I missed that part, but are there plans / hope to improve the direct-write case in the future?

**Comment by casef** [comment]
This is NOT how DirectWrite normally looks, though. It's not the greatest font renderer there is, but it's not THIS bad. That's MacType doing something to it, as it doesn't happen if you're not using MacType. Seems like it has something to do with gamma, so maybe try tweaking the new DW gamma setting.

**Comment by Yoctillion** [comment]
I have repleaced system fonts before. It may affect DirectWrite working.

**Comment by zhengbli** [comment]
I actually see the same thing (clean system), that's why I asked.
I know that this is what vanilla DirectWrite looks like. I was just curious about the hope that MacType can render DW as well as it did for GDI.

**Comment by snowie2000** [comment]
> This is NOT how DirectWrite normally looks, though. It's not the greatest font renderer there is, but it's not THIS bad. That's MacType doing something to it, as it doesn't happen if you're not using MacType. Seems like it has something to do with gamma, so maybe try tweaking the new DW gamma setting.

Of course it's not the original way DW renders, because MacType altered some of its params, but it is still the directwrite who does the actual rendering. Maybe there is something to do with gamma, but you are just making selection between bad and worse.

**Comment by mjuzikfrik** [comment]
I've set DW gamma to 1.8 and it looks quite okay. At 2.2 it looks really fine for me, but then notification sidebar and start menu look like they are not affected somehow. Dunno why.

**Comment by casef** [comment]
snowie2000: Well the way you put it ("it's Directwrite and as you can see it's bad") sounds as if it's DirectWrite's fault and that it's just normal for it to look THIS bad, which isn't really fair, since it's in fact MacType that makes it look this bad by altering its parameters. I guess nobody using MacType likes DW, but let's not make it look worse than it actually is. Any font renderer (or in fact any tool) can give you bad results if you feed it altered data.

So the best course of action would IMO be to use some kind of default/recommended values to not make DW look this bad, so people would be aware of the issue.

**Comment by zhengbli** [comment]
By default mactype does not render DirectWrite at all, so you have to add `DirectWrite=1` to opt-in. Therefore I think people who do that know what they are doing.

**Comment by YellowOnion** [comment]
@zhengbli I haven't touched that setting and DirectWrite looks extremely bad.

**Comment by sammilucia** [comment]
@Yoctillion @zhengbli @YellowOnion is this still an issue for you?

**Comment by sammilucia** [comment]
Closing as unresponded.

To wrap this issue up - set DirectWrite=0 in your ini file to stop MacType touching DW fonts. You can also set DirectWrite=0 and install MacType-Patch to attempt to tune DW further.

MacType doesn't modify DW font rendering if DW=0.
