### ISSUE TITLE
How does Manual Mode work?

### ISSUE THREAD

**Issue by fabrizio11** [snowie2000/mactype#175]
Hello,

I'm sorry if I write here but I didn't find any support area so I write this as an issue, even if probably it's not.

I'm trying to understand how **manual mode** works. The wizard says "MacType will not runt automatically, you could manually load MacType into programs simply by drag them to **MacType GUI**".

I can't really understand which GUI the wizard is talking about! I tried in all the possible GUIs: the wizard's, the profile settings... even if both are not logical to use for me and of course it didn't work.

**Comment by snowie2000** [comment]
It's the macloader.exe which you should drag your programs to.
But I've found a mistake that I forgot to attach a MacType loader for x64 system. That macloader.exe doesn't work for x64 processes.
Something is wrong with github that I can't attach this file in reply. I'll fix it later.
