### ISSUE TITLE
Disable MacType when running from battery?

### ISSUE THREAD

**Issue by TheAquir** [snowie2000/mactype#176]
Firstly thanks for this amazing piece of software!

I have a feature request : It would be nice to Disable MacType automatically when the PC is running on Battery. It's using some processor time almost constantly (which is fine) but maybe you could save some battery with this feature...

Cheers!

**Comment by snowie2000** [comment]
Sorry, this can't be done.
MacType  has no separate thread checking system conditions. It is only triggered by GDI calls from original program. If we check power condition on every call, it will consume more battery.
It is also not possible to do this with MacTray. It is always dangerous to disable MacType during operation, 'cause it may conflict with many anti-cheat or anti-malware softwares.

**Comment by TheAquir** [comment]
Hi, thanks for the explanation!

Have a nice day then
