### ISSUE TITLE
win10 周年版性能问题

### ISSUE THREAD

**Issue by myshzzx** [snowie2000/mactype#178]
无论加载方式, cpu占用过高了, 虽是间歇性的, 但两个进程时不时会占满一个核. 我是4核8线程, 12.5就算占满了.
![image](https://cloud.githubusercontent.com/assets/2025090/18410697/4f01b694-779b-11e6-9732-6f9e1d740c2c.png)

**Comment by snowie2000** [comment]
您用的是最新版？我这边虚拟机win10已经慢的跟渣渣一样了，从未出现过100%情况。

**Comment by snowie2000** [comment]
另外无论加载方式，您注册表加载也有两个进程时不时占满一个核？

**Comment by myshzzx** [comment]
是新版的

**Comment by myshzzx** [comment]
我试了托盘加载和服务加载

**Comment by snowie2000** [comment]
很抱歉这个问题没有任何其他人反馈，多半是您的系统存在冲突。

**Comment by myshzzx** [comment]
会是啥冲突

**Comment by snowie2000** [comment]
谁也不知道，只能猜。

**Comment by myshzzx** [comment]
很规律地5秒满一下
![image](https://cloud.githubusercontent.com/assets/2025090/18410742/f792648e-779b-11e6-84f7-afac462c78d4.png)

**Comment by snowie2000** [comment]
因为mactray间隔5秒会扫描系统进程，并进行判断是否需要对没有启用的进程加载，所以你看到有5秒的脉冲也正常。
但是一般来说这种扫描占用的cpu很少。我现在的电脑双核4线程也只占用2%而已。

**Comment by snowie2000** [comment]
如果您对这个间隔特别看不舒服的话，您可以降低这个间隔，在mactray托盘图标-右键-重新加载间隔，设置一个更高的数值就可以了。
您也可以使用注册表模式，那就完全没有扫描了。

**Comment by myshzzx** [comment]
果然没有了, 是电脑热得烫手才检查了一下. 谢谢.
