### ISSUE TITLE
'Microsoft Visual C++ Runtime Library' keeps popping up when starting Adobe Reader DC

### ISSUE THREAD

**Issue by sahmb0edy** [snowie2000/mactype#179]
A few seconds after launching Adobe Acrobat Reader DC in Windows 8.1 x64 with MacType version 2016_0904_0 enabled, a 'Microsoft Visual C++ Runtime Library' message box keeps appearing, saying "Runtime Error! This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information." This error message pops up immediately again after closing it, for about two to five times. Launching from a PDF file tends to make the error pop up more often than it does when launching the program directly.

![mactype adobe reader error](https://cloud.githubusercontent.com/assets/22114513/18415982/d975e054-7848-11e6-8d70-ebb4f4a4c363.png)

(This also occurs with Chrome. This problem also existed in the 2016_0830_0 version, but with the error message titled 'WerFault.exe - Application Error', saying "The application was unable to start correctly (0xc0000142). Click OK to close the application.")

**Comment by snowie2000** [comment]
cannot reproduce in win7.

**Comment by sahmb0edy** [comment]
I think it only happens in Windows 8.1. I also tested this with Windows 10 but the error didn't happen there.

**Comment by sammilucia** [comment]
@sahmb0edy is this issue still occurring for you?

**Comment by sahmb0edy** [comment]
The issue doesn't occur anymore as of the v1.2017.628.0 version and hasn't appeared in the latest v1.2018.09.17-beta2 release.

**Comment by snowie2000** [comment]
Thank you for your feedback.
