### ISSUE TITLE
DW mode does not support subpixel antialiasing

### ISSUE THREAD

**Issue by tcbbd** [snowie2000/mactype#180]
> ;-1:Disable 0:Normal 1:Light 2:LCD(RGB) 3:LCD(GBR) 4:Light-LCD(RGB) 5:Light-LCD(GBR)
> AntiAliasMode=4

With this setting, I get grayscale antialiasing instead (at least I think so) in Chrome 53

**Comment by snowie2000** [comment]
Chrome does its rasterizer by itself.

**Comment by tcbbd** [comment]
Closed for misreport. Finally figured out that it's not grayscale antialiasing but the stupid hinting which makes the font blurring. But it's still impossible to turn off hinting in Chrome.
