### ISSUE TITLE
Troubles with Roboto font rendering (Win 8.1 x64)

### ISSUE THREAD

**Issue by Twilightssuperb** [snowie2000/mactype#181]
This is how Roboto must be displayed. MacType isn't run, DirectWrite and #lcd-text-aa are enabled, browser is based on Chromium 48:
![screencapture-nplus1-ru-1473682066210](https://cloud.githubusercontent.com/assets/7080928/18435499/5034ec9a-78fc-11e6-9350-c851e7b9946a.png)
And how I see the same main page of [nplus1.ru](url) after Mactype 2013.1231 has been launched, DirectWrite and #lcd-text-aa flag have been disabled, #enable-zero-cory has been turned on, #num-raster-threads has been set at 1:
![n 1_ directwrite off chromium 48 mactype 2013 with patch](https://cloud.githubusercontent.com/assets/7080928/18435545/99c17928-78fc-11e6-81a3-fd460455324d.png)
Roboto is too bold. It's a bit ugly. Sorry for screenshot from russian site, nevertheless it doesn't matter.

**Comment by maaldheefee** [comment]
Somehow it renders with the semibold or medium varient. I had this issue a too (in Firefox). If you inspect the page and check the fonts it shows that the semibold version is selected. even though the CSS specifies the normal weight of the font.

I also had the issue with "Garamond Premere Pro". It used to work with font name written as "Garamond Premr Pro" which is the "styling group name", but after installing MacType it only works when I write the "full name": "Garamond Premier Pro"

Maybe @snowie2000 will share his insight with us.

**Comment by snowie2000** [comment]
I have looked at it, and it seems totally fine in my chrome:
![nplus1](https://cloud.githubusercontent.com/assets/11767189/18613987/da388a68-7db7-11e6-8292-4c757d7c7284.png)

As you can see in the screenshot, the Regular version of roboto is selected.
