### ISSUE TITLE
Can't start with registry mode but OK with Windows service mode or tray mode

### ISSUE THREAD

**Issue by kfstorm** [snowie2000/mactype#182]
I have two machines. Both are Windows 10 Enterprise 14393.105. One is Chinese language and the other is English. I'm using MacType 1.2016.904.0. However, registry mode only works on my Chinese machine. When I choose registry mode on my English machine, nothing happens. After I switched to other modes, it worked.

Does MacType has any log? How can I know the detail of this failure?

**Comment by snowie2000** [comment]
MacType doesn't have any log, nor can it output any logs during system boot up.

**Comment by rudolphos** [comment]
I have the same problem, only service mode works. I think it would be better if it worked through registry - less memory and slowdown on startup..

**Comment by matthewadamsdk** [comment]
@kfstorm & @rudolphos - please see this post:

https://github.com/snowie2000/mactype/issues/194#issuecomment-250270274

It appears that disabling Secure Boot in Bios solves the problem and makes it possible to use mactype in registry mode again. :-)

**Comment by sammilucia** [comment]
Registry injection is blocked by SecureBoot. Please see the notes on Secure Boot on the latest beta https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2 (the workaround is to disable secureboot, which enables registry mode again - which I don't recommend)

Closing as this is not an issue with MacType.
