### ISSUE TITLE
Chinese text overlaps in Notepad++ and shows ? in Notepad2

### ISSUE THREAD

**Issue by kfstorm** [snowie2000/mactype#183]
I'm using MacType 1.2016.904.0. I use exactly the same config for two Windows 10 machines. One is Chinese and the other is English. Everything works fine on Chinese machine. But the Chinese text on English machine is strange in Notepad++ and Notepad2.

![image](https://cloud.githubusercontent.com/assets/3626358/18445578/d24435e8-7950-11e6-97b6-161694499f39.png)

![image](https://cloud.githubusercontent.com/assets/3626358/18445542/a4b0ea68-7950-11e6-98e3-b7271fb7a5ec.png)

Attached my config file.
[MyMacTypeConfig.ini.txt](https://github.com/snowie2000/mactype/files/467908/MyMacTypeConfig.ini.txt)

**Comment by Garfield550** [comment]
Hi kfstorm, 
My Windows 10 doesn't have your problem.
Notepad ++ Screenshot: 
![Notepad ++ Screenshot](https://cloud.githubusercontent.com/assets/3471836/21857076/2df4bfee-d85f-11e6-9065-c39ee4b71ac2.PNG)
My Windows 10 version: 
![About Windows 10](https://cloud.githubusercontent.com/assets/3471836/21857129/60f2fac8-d85f-11e6-8800-9038c4b1a18c.PNG)
Here are some of my recommendations, u can give it a try: 
1. U can try to change your Region -- Language for non-Unicode programs settings on your Windows's Control Panel.
2. U can try to install Chinese(PRC) Language pack on your Settings application.
3. U can try to use a custom font in your MacType config, like mine: 
```Text
[FontSubstitutes]
;【字体替代】
;系统在调用“=”前面的字体时会忽视“=”前面的字体，而去直接调用“=”后面的字体
Fixedsys=Inziu Roboto SC
SimSun=Inziu Roboto SC
@SimSun=@Inziu Roboto SC
NSimSun=Inziu Roboto SC
@NSimSun=@Inziu Roboto SC

[FontSubstitutes@Office]
;【字体替代 for Office】
Fixedsys=Inziu Roboto SC
SimSun=Inziu Roboto SC
@SimSun=@Inziu Roboto SC
NSimSun=Inziu Roboto SC
@NSimSun=@Inziu Roboto SC
```

**Comment by sammilucia** [comment]
Closing issue as @Garfield550 's answer is correct. Also note that some software just doesn't support unicode.

@kfstorm please let me know if the above fix didn't work for you.
