### ISSUE TITLE
无法渲染所有dw的系统界面

### ISSUE THREAD

**Issue by YH0426** [snowie2000/mactype#185]
例如UAC界面以及登陆界面的DW文字没办法渲染，之前silight的补丁是可以实现全部渲染的
附上截图
![2016-09-13](https://cloud.githubusercontent.com/assets/18507944/18475957/ea1d04d8-79fa-11e6-9424-a5e4ca799701.png)
![qq 20160913214359](https://cloud.githubusercontent.com/assets/18507944/18476066/3830fe0e-79fb-11e6-8098-8ebc04d2e9dc.png)

**Comment by snowie2000** [comment]
必须注册表模式才行 之前的补丁不支持别的模式，只能注册表，当然可以

**Comment by YH0426** [comment]
我使用的就是注册表模式。。。

**Comment by snowie2000** [comment]
这个主要是由于，新版本的软件会检测一个进程是否是交互进程，uac进程不属于交互进程，所以会被自动排除掉，而老版本的软件不会做这个事情。 你可以注释掉hook.cpp里面的判断函数后再试试
