### ISSUE TITLE
翻新 FreeType2——新功能和安全性

### ISSUE THREAD

**Issue by Artoria2e5** [snowie2000/mactype#186]
FreeType 这事儿我看[一直都有人在提](https://github.com/snowie2000/mactype/issues?utf8=%E2%9C%93&q=freetype)，结果很多 Google Code 过来的事情好像没结束就给 close 了……

稍微安利一下新版本那么……

* 2.7: “更像 DirectWrite”的 TrueType Hinting "[v40](https://www.freetype.org/freetype2/docs/subpixel-hinting.html)" 解释器，支持次像素（有开关可调）
  * 之前原版 FreeType 的 v35 解释器基本上是 XP 的水平——整像素对齐
  * 从 Infinality 合并进来的 v38 基本上是 [MS ClearType 的方式](https://www.microsoft.com/typography/cleartype/truetypecleartype.aspx)
  * FreeType 的人觉得 v38 太慢了（MS 那套很折腾，可配置参数也太多），发现敲掉水平对齐长得也差不多，出来了 v40
* 2.6.2: 对于液晶次像素渲染滤镜参数的[调整](https://www.freetype.org/freetype2/docs/text-rendering-general.html)
  * 新滤镜在色彩上是均衡的，截图缩小不会五颜六色
  * 新滤镜达到完美色彩表现需要正确 Gamma 颜色混合处理
  * 正确 Gamma 会让小字变淡，所以有个笔画加粗功能
* 2.5:  Adobe CFF（“OpenType 轮廓”）字体渲染器 #89 
  * 之后的 2.5.x 版本修复了 Adobe 家渲染器的安全漏洞（Orz）
* 2.5: 彩色 Emoji 渲染（Google）
  * [![Noto Color Emoji](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Emoji_u1f424.svg/128px-Emoji_u1f424.svg.png)](https://commons.wikimedia.org/wiki/File:Emoji_u1f424.svg)
* 2.4.x: 各种 Type 1 安全漏洞，不过也不关 Windows 用户事……

关于 Infinality 的 FT 补丁：目前这些东西主要的意义不是额外功能（适合进 FreeType 的都进去了），而是可配置性（各种环境变量和把老东西重新捞出来加开关）。

MacType 需要能够提供配置的地方（[Property](https://www.freetype.org/freetype2/docs/reference/ft2-module_management.html#FT_Property_Get)）：

* https://www.freetype.org/freetype2/docs/reference/ft2-auto_hinter.html#darkening-parameters(autofit)
* https://www.freetype.org/freetype2/docs/reference/ft2-cff_driver.html#darkening-parameters(cff)
* https://www.freetype.org/freetype2/docs/reference/ft2-auto_hinter.html#default-script
* https://www.freetype.org/freetype2/docs/reference/ft2-auto_hinter.html#fallback-script
* https://www.freetype.org/freetype2/docs/reference/ft2-auto_hinter.html#glyph-to-script-map
* https://www.freetype.org/freetype2/docs/reference/ft2-cff_driver.html#hinting-engine(cff)
* https://www.freetype.org/freetype2/docs/reference/ft2-auto_hinter.html#increase-x-height
* https://www.freetype.org/freetype2/docs/reference/ft2-tt_driver.html#interpreter-version
* https://www.freetype.org/freetype2/docs/reference/ft2-auto_hinter.html#no-stem-darkening(autofit)
* https://www.freetype.org/freetype2/docs/reference/ft2-cff_driver.html#no-stem-darkening(cff)
* https://www.freetype.org/freetype2/docs/reference/ft2-auto_hinter.html#warping

对于彩色 emoji 需要做出的调整：

* 如果用到 `FT_Load_Glyph` 的话 `| FT_LOAD_COLOR` 一下。没用到的话就算了没戏了。（

**Comment by snowie2000** [comment]
There is a test build of mactype with freetype 2.7 cleartype hinting included.
Get it here: http://mactype.net/station/MacType_CTP.rar

Tested and works in W7 x64. Use at your own risk!!

**Comment by IceMan81** [comment]
@snowie2000 Could you elaborate on how the mactype settings relate to the freetype settings? For example, to use the build above with the new cleartype hinting, what settings should I use in mactype? And should I set to use the new default lcd filter for sub-pixel rendering?
https://www.freetype.org/freetype2/docs/text-rendering-general.html#the-default-lcd-filter-for-subpixel-rendering-has-been-changed

Sorry for commenting on a closed ticket, but this had the most relevant context.

**Comment by IceMan81** [comment]
@snowie200 The freetype 2.7 mactype build works well for me. Could you please clarify my questions above?

**Comment by snowie2000** [comment]
@IceMan81 The hintingMode, AntiAliasMode, Lcd filter is directly applied to the freetype engine. 
ItalicSlant, BolderMode, NormalWeight and BoldWeight will affect how mactype adjust font outlines.

All other settings are not related to freetype.
For all the new features, mactype does not provide any setting to toggle them. They are just by default all enabled. And there maybe some settings to switch between old and new versions if freetype provides such possibilities for example, lcdfilter, if you didn't define LcdFilterWeight in your profile, mactype will use freetype predefined values which is identical with old version.

**Comment by Artoria2e5** [comment]
My suggestion is to implement these properties some time.

**Comment by snowie2000** [comment]
@Artoria2e5 
What property?

**Comment by snowie2000** [comment]
我看了一下也许会提供彩色emoji的支持，但是其他选项不会支持。
MacType的配置从来不是为制造麻烦而生的。

**Comment by Artoria2e5** [comment]
考虑把处理环境变量设置的那块东西挪个地方插进去吧……

**Comment by snowie2000** [comment]
没有明白是什么意思

**Comment by Artoria2e5** [comment]
FT 的 Property 是可以用环境变量设置的，这样要改的地方少一点懂的人自然会……

**Comment by IceMan81** [comment]
@snowie2000 More questions, sorry. 
I was going through the MacType code to understand how hintingmode and antialiasmode are passed to freetype.
From the code it looks like, hintingmode range is 0-2 but in the ini files, its 0-3.
`; 0:NoHinting  [1:Normal]  2:AutoHinting  3:Light+AutoHinting`
What does '3' correspond to in FreeType? And I don't see any setting for 3 in the mactype code either.

**Comment by Artoria2e5** [comment]
@IceMan81 Perhaps it's something like `1 | 2` (`|` denotes bitwise or.)

**Comment by IceMan81** [comment]
@Artoria2e5 @snowie2000 

See ft.cpp, line 1305
https://github.com/snowie2000/mactype/blob/master/ft.cpp

**Comment by IceMan81** [comment]
@snowie2000 Would you comment on my observation above?
