### ISSUE TITLE
Freetype 2.7

### ISSUE THREAD

**Issue by fk2001** [snowie2000/mactype#187]
Is mactype updated to freetype 2.7?

**Comment by snowie2000** [comment]
The most recent release of MacType is compile against freetype 2.6.5 while you are free to compile with any version of FreeType. MacType and FreeType are not deeply coupled.

If you want a compiled version for testing purpose, get it from http://mactype.net/station/MacType_CTP.rar

**Comment by IceMan81** [comment]
@snowie2000 It would be great if mactype is officially upgraded to FT 2.7. Looks really good with it.
