### ISSUE TITLE
Unclear situation with DirectWrite

### ISSUE THREAD

**Issue by Jigsaff** [snowie2000/mactype#189]
Hi there!

I just installed the latest MacType version (1.2016.904.0), registry mode, default profile with DirectWrite=1 flag. Clean Chrome installation (53.0.2785.116 m (64-bit)) running with --disable-directwrite-for-ui. UI looks just great, smooth as I need. But there is no effect on any website. What I'm doing wrong?

P.S. After deleting chrome://flags/#disable-direct-write in 52 version I had to use 51 and all was ok. Can I have the same effect with this new version?

**Comment by nanake** [comment]
> But there is no effect on any website

DirectWrite (for content) cannot be disabled in Chrome 52+

**Comment by Jigsaff** [comment]
> DirectWrite (for content) cannot be disabled in Chrome 52+

Now I have only 2 options?
1. Use 51 version.
2. Get used to these crappy fonts.

**Comment by nanake** [comment]
or

3. Use firefox. :)

**Comment by Jigsaff** [comment]
FIrefox is my secondary brouser since Netscape times :)

**Comment by 8pr** [comment]
you can use mactype 2014 with patch 1.13 provided here: http://silight.hatenablog.jp/entry/MacTypePatch

**Comment by Jigsaff** [comment]
> you can use mactype 2013_1231_0 with patch 1.13

Just tested. The same shit. :(

**Comment by Revod** [comment]
@8pr  @Jigsaff Why you dont use Cent Browser? is based on chrome with more options and in the latest version (52) is using the DirectWrite option in chrome:flags  http://www.centbrowser.com/history.html

**Comment by caesarnovaldy** [comment]
use older mactype  + patch that @8pr said.
it worked well although the font looks thinner than in windows interface
