### ISSUE TITLE
mactype64.dll导致火狐崩溃

### ISSUE THREAD

**Issue by yoyocheung** [snowie2000/mactype#191]
经常性点击火狐工具栏上的ublock origin按钮就崩溃，
常用火狐51开发者版x64，其他版本也一样，很早就有的Bug
系统Win10 LTSB企业版x64
崩溃代码页面
https://crash-stats.mozilla.com/report/index/6412514f-e8f2-4d22-8468-53c482160924#details

**Comment by snowie2000** [comment]
从哪个版本的mactype开始出现的？

**Comment by yoyocheung** [comment]
2013.1231，应该是这个就开始的吧，最新的MacType 1.2016.904.0 released还是会崩，重现方法：确认ublock的requests blocked已经展开，打开元素较复杂的页面，点击ublock图标，崩溃几率不定，也有可能受到火狐e10s（多进程）影响。

**Comment by snowie2000** [comment]
试试使用这个文件覆盖：
http://mactype.net/station/MacType_CTP_firefox.rar

**Comment by yoyocheung** [comment]
好的，但这个要时间测试，崩溃几率太随机，过几天给您结果，辛苦了~

**Comment by snowie2000** [comment]
从bug报告上看这确实是老bug，应该是从很早以前就有了，但是最近的更新对firefox的纵向排列做了处理，可能更严重的引起了问题。尝试了一种解决方案，不过不确定是否会引起其他问题

**Comment by yoyocheung** [comment]
初步测试：没覆盖之前猛点ublock图标几十次之后崩溃，覆盖之后鼠标点烂也没崩，火狐版本第三方49.0.1官方51和52，最快明天给您最终测试结果。

**Comment by yoyocheung** [comment]
还是崩了，这次是点右上角三道杠（菜单）

**Comment by yoyocheung** [comment]
https://crash-stats.mozilla.com/report/index/1f7bbad2-8134-45a3-8457-afabb2160926

**Comment by yoyocheung** [comment]
再次测试：已覆盖补丁，有扩展和无扩展都一样，点击（猛点，点烂为止）有弹出式菜单的按钮较容易崩溃，测试得这样才能触发，日常是点击一下时不时可能就崩

**Comment by yoyocheung** [comment]
触发机制太奇葩了，这里是测试步骤：
http://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-aurora/firefox-51.0a2.en-US.win64.zip
火狐51，运行，地址栏输入about:config?filter=gfx.direct2d.disabled改为true，重启火狐，之后使用按键精灵或者手动猛点菜单或者书签图标。日常使用都是点击一下就崩溃，很随机

**Comment by snowie2000** [comment]
我明天再看看是什么情况

**Comment by snowie2000** [comment]
尝试这个版本，应该修复了。
http://mactype.net/station/MacType_CTP_160927.rar

一个存在很久的非常傻的错误导致的。

**Comment by yoyocheung** [comment]
测试完毕，按键精灵频率1毫秒点击，三个版本火狐均测试5分钟，没有崩溃，没有崩溃，没有崩溃！可以确定是修复了，真的非常感谢，请问之后会整合到release吗，还是说要单独下载？

**Comment by snowie2000** [comment]
发布的时间肯定会使用最新版本的代码，当然是修复了问题的，在发布新版本前你还得下载补丁来覆盖。
最新编译出来的测试版本可以在 http://mactype.net/station/ 找到，一般出现一些重要修复的时候我会上传一个文件。
