### ISSUE TITLE
MacType/64 DLLs not signed

### ISSUE THREAD

**Issue by shadeMe** [snowie2000/mactype#193]
Since the MacType loader DLLs are not signed, the AppInitDLL on Windows 10 AU refuses to load them. Code-signing them ought to fix the issue.

Edit: Hmm, disabling the requirement in the registry doesn't seem to have any issue. Investigating further reveals that the AppInitDLL mechanism is [disabled when secure boot](https://msdn.microsoft.com/en-us/library/windows/desktop/dn280412(v=vs.85).aspx) is enabled.

**Comment by snowie2000** [comment]
Code-signing is cool and useful, and also expensive.
