### ISSUE TITLE
Chrome support

### ISSUE THREAD

**Issue by f3yisayo** [snowie2000/mactype#197]
Now that mactype supports directwrite, is it just me or Chrome doesn't render properly as before?

Before Chrome ditched Directwrite, I used to have mactype render Chrome properly.

**Comment by DiglidiDudeNG** [comment]
AFAIK, Chrome uses it's own method of rendering text, which is dependent on the running platform.

**Comment by casef** [comment]
Chrome didn't ditch DirectWrite, quite the opposite actually - they recently removed the flag to disable it.

And for some reason, the Blink rendering engine also seems to apply some kind of custom font sharpening on Windows, making them look thinner than they should be. I believe it did that even when you disabled DW (when it still could be done), it just is a lot more noticeable with DirectWrite.

**Comment by pointcache** [comment]
So what to do? I want mactype on chrome its the only thing i care about atm.

**Comment by snowie2000** [comment]
Not possible currently, maybe possible in the future, but I don't think it will be as good as it was even if directwrite got supported, because Chrome doesn't use directwrite in a standard way.

**Comment by f3yisayo** [comment]
I've had to stick with Cent Browser, it's basically Chrome without DirectWrite and it renders nicely with mactype.

**Comment by snowie2000** [comment]
me too, and its webkit core is very up-to-date.

**Comment by lyubomyr-shaydariv** [comment]
@f3yisayo 
Hi, how did you manage to make MacType work in Cent Browser? I'm not sure I have configured the MacType-compatibility options in chrome://flags properly. Any help would be greatly appreciated.

**Comment by f3yisayo** [comment]
@lyubomyr-shaydariv  
1. In `chrome://flags` disable directwrite
2. In Cent Browser ` Settings > Other Settings` ,  enable startup command line and add this
 `--disable--directwrite-for-ui`

**Comment by lyubomyr-shaydariv** [comment]
@f3yisayo Thanks! Hm, I tried the same earlier, and the older version of MacType seemed to be the issue (I can't really remember but I had a 2015 version). Some fonts are now rendered slightly different in Cent (and I would say a little better) than the running original Chrome. However they almost look the same to me. Comparing to Firefox, Firefox+MacType renders the fonts way better.

Chrome:

![1-chrome](https://cloud.githubusercontent.com/assets/1956806/19329364/fb65ba94-90e0-11e6-809a-af0c93bca658.png)

Cent:

![2-cent](https://cloud.githubusercontent.com/assets/1956806/19329366/fb698c64-90e0-11e6-9410-4e863aedeaee.png)

Firefox:

![3-firefox](https://cloud.githubusercontent.com/assets/1956806/19329365/fb6667e6-90e0-11e6-87e0-1d4f70cd6726.png)

**Comment by f3yisayo** [comment]
@lyubomyr-shaydariv My own Cent:

![fireshot capture 4 - chrome support issue 197_ - https___github com_snowie2000_mactype_issues_197](https://cloud.githubusercontent.com/assets/9140532/19329670/ef2553a2-90d1-11e6-9073-10a77fbdd472.png)

**Comment by lyubomyr-shaydariv** [comment]
@f3yisayo you're really lucky. :) Thank you for the help anyway. I'm going to dig it deeper.

**Comment by Kesantielu** [comment]
Chrome 51, the last version with `--disable-directwrite` flag support 
![snap05379](https://cloud.githubusercontent.com/assets/7416833/22236067/66e680b2-e22d-11e6-9329-2b7d5ffa65ad.png)

**Comment by f3yisayo** [comment]
@Kesantielu I've stopped using Chrome since DirectWrite had to be forced on us, so I've switched to Cent Browser now! :smile:
