### ISSUE TITLE
windows重新启动之后需打开一次mactype用户向导才能够正常渲染chrome

### ISSUE THREAD

**Issue by hflser2014** [snowie2000/mactype#198]
windows重新启动之后需打开一次mactype用户向导才能够正常渲染chrome，其余软件及界面一切正常（我是通过在快捷方式里加上「--disable-directwrite-for-ui」来保证chrome渲染正常）

**Comment by Bronts** [comment]
新版的chrome已经不太好渲染了，在快捷方式加入启动参数 --no-sandbox

**Comment by Bronts** [comment]
但是会提示有安全风险

**Comment by skinnyshy** [comment]
直接用cent浏览器，可以设置directwrite

**Comment by sammilucia** [comment]
Duplicate #441 , closing
