### ISSUE TITLE
当运行较长时间后，MacTypeTray 托盘图标右键不响应，且停止自动渲染新进程

### ISSUE THREAD

**Issue by RadarNyan** [snowie2000/mactype#199]
Windows 7 SP1 64-bit ( 英文版 ) 使用独立托盘加载 ( 管理员权限 ) 较长时间是指开数小时甚至数天才会出现，没有找到稳定复现的方法 ( 有时候是休眠唤醒后出现，有时候休眠唤醒后依然能正常工作 ) 

虽然右键无法呼出菜单，但依然可以双击打开窗口，手动「刷新」列表后对未渲染进程执行「启用」可以渲染，但窗口中始终显示「启用中」，再次「刷新」后显示「已启用」。手动杀掉 MacTray.exe 进程并重新以管理员权限启动可以继续使用，一定时间后问题可能再次出现。

无法确定是哪个版本开始出现的，但可以肯定的是今年二月份的版本就存在这个问题。

**Comment by snowie2000** [comment]
今年2月份的版本和几年前的版本中tray和64位辅助进程是完全一样的，根本就没更新过。
此问题不会被修正，因为重现难度实在太高。
