### ISSUE TITLE
Invalid image size + EOutOfResources

### ISSUE THREAD

**Issue by firewater2** [snowie2000/mactype#200]
The last version of MacType that works for me is 'MacType 2013 1231.0', the new ones on this site output the following series of error:

```
MacTray:
Invalid Image Size
```

After clicking okay, the standard troubleshooter window of 'MacType' has stopped working' appears. When I close it I get:

```
MacTray:
Exception EOutOfResources in module MacTray.exe at 000386D0. The windows does not have scroll bars.

```
I run Windows 8 and a custom theme, but since previous versions work, I don't think it should have to do with that.

**Comment by snowie2000** [comment]
It is highly possible that your theme misses some resources as there is no other user reporting about this issue with standard Windows installation.

**Comment by firewater2** [comment]
The 'Invalid image size' error has been reported before. Google displays shows two cases, one is a vague answer in Japanese ('it has been fixed'), and the other is a guy talking about how the error exists because he taskbar is not of a certain size. My theme is not anything wild, although some parts are removed (not scrollbars, though), but it has never clashed with any program before. MacType sort of works, but fiddling around MacTray makes it crash. Hopefully it may be fixed in the future, but I guess I'll stay with the old version for now (whihch works fine, I updated for the sake of being up to date).

**Comment by snowie2000** [comment]
I don't think windows has open support for any third party themes. You must have done some hack to enable it.

**Comment by firewater2** [comment]
Yeah, sure. All themes require you to install some sort of enabler. I use http://uxstyle.com/ which actually runs as a process and doesn't modify anything, I think.

It would be good if someone else with using theme has the latest MacTray working commented, I think the communities of modding Windows overlap a lot with this.

**Comment by snowie2000** [comment]
I haven't played windows themes for a long time since W7. Can you give me a link to your theme?

**Comment by firewater2** [comment]
I could, but it only works on Windows 8 (not 8.1, nor 10). 

I feel like it has something to do with the theme, but then I change it and the problem persists. Then I think I'm also running LiteStep, but I close the process and it persists. Same for another program called TrueTransparency (changes the borders of windows), so I'm trying to think of hacks that I've made on the computer, and I'm very organized at that, so I know that the only things I've done is adding these .reg files which I could share if you want:

Enable Smallest Padded Borders.reg
Disable ''Open File - Security Warning''.reg
Disable Navigation Pane.reg
Disable Status Bar in File Explorer.reg
Disable Shadow Under Images.reg
Disable UAC.reg
Disable Tooltips.reg

Beside this, the theme disables some stuff of explorer (I don't recall what part specifically, but the result is a window that is just the icons + scrollbar).

**Comment by snowie2000** [comment]
Well, it is a bit complex for me. What's worse is that I only have W7 and W10 to test, not W8.

**Comment by firewater2** [comment]
So it's the theme. I just tried a way to properly change the theme (removing the 'cache' from the last theme) and it loads fine. I do not know what to change for it to work, though. I do have the scrollbars, so I don't know what part is about.
