### ISSUE TITLE
4K Display

### ISSUE THREAD

**Issue by achalgupta889** [snowie2000/mactype#201]
Hi How can i apply the mac type to 4k display. I tired several times, but nothing seems to change. Please assist.

**Comment by Jeremiidesu** [comment]
"seems" keyword here. It may be changing, but my guess is the display's so sharp that you can't see a change. you could provide screenshots with and without mactype for us to tell you if it actually changes

**Comment by achalgupta889** [comment]
You are right that i can not see any change.  But then the real uniqueness of the Mac type software ( i have used this for last 4 years), is the Roundness of the font which actually you get on Mac but nowhere on Windows......Please let me know if there is solution to make it like Mac at this high resolution......Thanks again for all your reply.

**Comment by Jeremiidesu** [comment]
Well, it also depends on which "MacType style" (these .ini files) you use I guess. I have no 4K display so i can't tell you from my own experience.

"the roundness of the font you actually get on a Mac" You look like you already saw how a Mac looks on a 4K display. If you did, please provide a screenshot so I (or other people) can help you finding/creating a profile that looks like what you're looking for.

**Comment by readytechgo** [comment]
I have a 4K display. It works for me in everything but Chrome, because Chrome now uses it's own set of rendering for fonts as of a few updates ago. It greatly improves the look of fonts especially with the 'LCD' preset.

**Comment by ilikecola** [comment]
Mactype is working well with my 4K Display but chrome as well.

**Comment by achalgupta889** [comment]
Can you please share the profile which you have applied

**Comment by readytechgo** [comment]
@ ilikecola How did you get MacType working on Chrome?

**Comment by srimajji** [comment]
4K display and mactype works for me. However i am on the same boat as other as far as chrome is concerend. Anyway, in the mean time i am using this extension [Font Rendering Enchancer](https://chrome.google.com/webstore/detail/font-rendering-enhancer/hmbmmdjlcdediglgfcdkhinjdelkiock).

**Comment by achalgupta889** [comment]
Thanks guys...it does work....I first started as service and then i can see the effect of it on fonts.....however computer screen does hang up 1-2 times.......Anyways for windows users this is one of the best software to be used in my opinion.
