### ISSUE TITLE
"Set" window text and Online Update error

### ISSUE THREAD

**Issue by Endilus** [snowie2000/mactype#202]
Hi,

I noticed that the "Set" window text is cut out using the following:
Windows 8.1 
Resolution: 1680 x 1050
MacType version:    1.2016.904.0
MacTray version:    1.0.5.2013
MacTuner version:   1.0.2.301
![2016-10-12 14_35_25-set](https://cloud.githubusercontent.com/assets/18008933/19310239/6fcfd048-9089-11e6-97b7-50716a5ce39f.png)

Also, the Online Update fails when checking for new versions:
![2016-10-12 14_37_23-new issue snowie2000_mactype](https://cloud.githubusercontent.com/assets/18008933/19310240/6fd0a00e-9089-11e6-9015-60f399896943.png)

**Comment by snowie2000** [comment]
Try accessing mactype.net via your browser. If you can't, there is something wrong with your network.
This setting window is designed for Chinese UI, thus it may have some truncation on other languages.

**Comment by sammilucia** [comment]
Obsolete version, closing
