### ISSUE TITLE
Doesn't work as a service with programs in administrator mode.

### ISSUE THREAD

**Issue by 11igors11** [snowie2000/mactype#204]
Windows 10
Version 1607 (OS Build 14393.321)
MacType 1.2016.904.0

**Comment by snowie2000** [comment]
Too few information provided.

**Comment by nocturnalbeast** [comment]
I've been having the same issue too.
I'm on Windows 10 Anniversary Update edition.
To be specific, I've changed my shell from windows explorer to blackbox and I'm running mactype in standalone mode(normal mode, not the compatible mode) and when I try to launch an explorer window when mactype is on, it doesn't load. After I disable mactype though, it works fine.
help?

**Comment by sammilucia** [comment]
@11igors11 are you still having this issue?

**Comment by sammilucia** [comment]
Closing as abandoned. Please let us know if you still have this problem with beta2 https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2

**Comment by 11igors11** [comment]
don't use mactype now

**Comment by sammilucia** [comment]
no problems thanks @11igors11 we'll still keep an eye out for this in case it was a bug
