### ISSUE TITLE
注册表加载模式造成火绒4.0测试版系统任务栏图标变灰，防护中心无法开启。 

### ISSUE THREAD

**Issue by streamgo** [snowie2000/mactype#205]
当将其设置为注册表加载模式（服务加载模式未测试）时，造成火绒4.0测试版防护中心全部关闭，无法开启。

最新版MacType版本号：MacType 1.2016.904.0 released

可能涉及到的DLL文件：根目录下 MacType.dll MacType64.dll（64位系统）。

请排查。同时已经向火绒官方反馈。

**Comment by streamgo** [comment]
经进一步测试：当选择以注册表模式加载时，火绒的usysdiag.exe进程直接秒退。选其他模式时，usysdiag.exe进程都正常，不会退出。

**Comment by snowie2000** [comment]
不会与杀毒软件做兼容。难度过高。
