### ISSUE TITLE
ttf fonts converted from otf are aliased (i.e. no anti-aliasing)

### ISSUE THREAD

**Issue by tcbbd** [snowie2000/mactype#206]
为了不让DW对思源黑体进行hinting，我将思源黑体的otf转成ttf并加入了gasp hack（只有truetype outline允许gasp table），在DW下效果提升了，但在GDI环境下Mactype似乎无法渲染修改后的字体了，表现为字体完全没有反锯齿，根本没法看
我的反锯齿选项为2，hinting选项关闭
复现:转换使用FontCreator 9.1或10，gasp表通过FontCreator添加或用网上流传的使用的ttx脚本添加，都会产生此问题

**Comment by snowie2000** [comment]
请您找个地方上传下字体我好测试

**Comment by tcbbd** [comment]
https://drive.google.com/open?id=0B7DwIsv0TQv0MlNodUZvcTZvLTg
https://drive.google.com/open?id=0B7DwIsv0TQv0WlhBRWlkOTJzblE

**Comment by snowie2000** [comment]
测试过确实无法渲染，原因是freetype无法载入您修改过的字体，错误为 无效的表。可能您修改的方式有些问题导致表不能被ft识别了。
