### ISSUE TITLE
Per Process settings?

### ISSUE THREAD

**Issue by IceMan81** [snowie2000/mactype#207]
Is there a way to control settings for specific processes. For example, I would like to use a different gamma and contrast settings for Intellij but not for any of the other processes. 

Is there a way to do this?

**Comment by snowie2000** [comment]
use grammar:
[general@exename.exe]
xxxxxx
[fontsubtitutes@exename.exe]
xxxxx
All sections and all the values can be configed this way.

**Comment by IceMan81** [comment]
@snowie2000 This works. Thanks. To confirm gamma behavior, higher gamma values lighten glyphs?

**Comment by snowie2000** [comment]
Yes.
You can try most values via MacTunner app.

**Comment by IceMan81** [comment]
@snowie2000 I find that increasing gamma darkens glyphs. Fonts look fatter at higher gamma. Whats the best way to sharpen a font, adjust contrast?

**Comment by snowie2000** [comment]
I think tweak the lcd filter will do the job.
