### ISSUE TITLE
无法编译，似乎缺少依赖

### ISSUE THREAD

**Issue by krrr** [snowie2000/mactype#208]
发现没有iniparser那个玩意：`cannot open source file "IniParser/ParseIni.h"`
还有很多疑似mfc的错误，我的环境是vs2015 community：`syntax error: missing ';' before identifier 'GetProcAddress'    MacType c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\include\atltransactionmanager.h   448`

编译指南里写要装Windows sdk，但是装vs时已经有了一个8.1版的
这个程序也不像要用到mfc的样子……
还有很多字符编码问题，每开一个文件就报警……

**Comment by snowie2000** [comment]
@krrr
iniparser请从我的repo下载。
报错问题请您自己检查设置。
Windows sdk必须安装且必须是最新版，否则Directwrite部分无法通过编译（除非你愿意自己去除dw部分代码）
字符编码问题是因为代码中残留了大量来自gdi++的注释，这些注释是日文编码，而我的注释是GBK的。

**Comment by krrr** [comment]
@snowie2000 啊原来是在这，编译指南里没写啊，我试试加进去
另外我装的是vs2015 community update3，官网上确实有说包含最新sdk，我再确认一下……

**Comment by krrr** [comment]
@snowie2000 确实是我没装。另外我的代码页不是cp936，有些“/*”会因为编码问题被合并到上一行的注释，然后一堆语法错误

可以改成utf-8 with BOM吗？directwrite.cpp用的就是那个。我已经批量转换好了，可以开个PR

**Comment by snowie2000** [comment]
@krrr 应该是可以改为utf8的，因为我这边没有什么问题也就没去改，估计英文系统也是没问题的，但是别的文字估计就不好说了。

**Comment by krrr** [comment]
@snowie2000 请问下delayload的问题……为什么要自己加载一遍easyhk的dll呢。看逻辑是dll不在PATH里的时候也能加载成功，但是官网上的版本如果CWD里没有那个dll就会在DllMain开始执行前就失败了（即使mactype.dll和easyhk32.dll在同一目录）。我自己编译的不知道改了什么设置不会这样了，不在同一目录也能工作，然而找不到就会直接segfault
还有delayhlp.cpp这个文件，为什么不用SDK自带的helper function呢

另外我想做的其实是mactype嵌入到我的小程序里，并且希望放到子目录里……

**Comment by snowie2000** [comment]
@krrr delayhlp好像是很早以前由于什么原因放进来的，确实没有存在的意义，感谢提醒，我会把他删掉。
至于为什么要手动加载一次dll，你试试win10 metro~~~

**Comment by krrr** [comment]
@snowie2000 突然又出问题了，调用LoadLibraryW64的时候会死。wow64ext这个库也是从你的repo下载的，那个版本对吗？官方版的没问题，就我自己编译的出错

怎么坑这么多，简直是预先埋好的陷阱（开个玩笑

**Comment by snowie2000** [comment]
你有试过我编译的ctp版本吗？
http://mactype.net/station/ 找时间最近的。

**Comment by krrr** [comment]
试了试，一样会崩，还是死在开64位子进程的时候

**Comment by snowie2000** [comment]
官网的版本是没有使用这个库的，这是使用的新方法来注入。
LdrLoadDll是很麻烦的函数，有个参数是内部参数，外部调用只能填0，不过一般系统中都能正常工作。
不知道为什么你的系统中不行。如果存在崩溃的问题的话，这个版本就不能发布了，而且不知道猴年马月能修复……

**Comment by snowie2000** [comment]
你可以写一个小demo来专门测试下这个LoadLibraryW64吗？我这边不会出错所以测试不出什么问题来。

**Comment by krrr** [comment]
我有试过，会发生一些神奇的现象。运行不崩溃，但是直接运行总是输出0，而开调试器的话会出两个控制台窗口，一个输出非0数字一个没内容。

我的系统版本是windows 10 1511，你的呢？

```c++
	DWORD64 hKernel32Dll = 0;
	InitWow64ext();
	hKernel32Dll = LoadLibraryW64(L"kernel32.dll");
	cout << hKernel32Dll << endl;
```

**Comment by snowie2000** [comment]
不可以加载kernel32.dll，只能加载kernelbase.dll的，除非你是vista。
在win7以后，kernel32.dll 64位不能和32位同时加载。wow64ext原作者有说明。

**Comment by krrr** [comment]
然而换成kernelbase.dll之后还是一样
![Imgur](http://i.imgur.com/hMeIx50.jpg)

**Comment by snowie2000** [comment]
不要编译console程序试试，来个win32的

**Comment by krrr** [comment]
win32的也不崩溃，dll的句柄也顺利获取了。注入的代码我看不懂，好像成功了吧，但是64位子进程没有mactype的效果。有些程序会崩有些不崩……

可能是我系统问题吧，你就当这个是个例好了

**Comment by snowie2000** [comment]
@krrr 具体崩溃是什么样的情况呢？是从32位启动64位时，32位程序崩溃还是64位程序崩溃？崩溃的程序是不是完全看不到任何界面就直接报错退出了？
从64位启动64位是不是存在问题？

另外方便的话，请帮忙做这个测试：
1. 启动MacType的情况下，从资源管理器启动一个32位程序，然后从这个32位程序启动一个64位程序，是否会出现崩溃问题。
2. 完全关闭MacType，重启，确保MacType没有启动。将32位程序拖到macloader.exe上启动他，然后从这个32位程序启动64位程序，是否崩溃。
谢谢。

**Comment by krrr** [comment]
我的系统64位，上面指的崩溃都是被注入了mactype.dll的32位进程开64位子进程（HookChildProcesses=1）有时会崩溃。崩溃时就直接退出了，连程序停止响应的提示都没有。挂调试器上去发现调用栈的顶端是X64Call的那堆汇编，是Access Violation

1.一样崩。如果关掉HookChildProcesses就不会了，但是mactype的效果过一会儿才出现
2.崩

**Comment by snowie2000** [comment]
32位程序崩溃还是64位程序崩溃？
在第二种情况中，LoadLibraryW64这个函数是根本就不会被调用的。
`GetEnvironmentVariable(L"MACTYPE_X64ADDR", NULL, 0);
			if (GetLastError() == ERROR_ENVVAR_NOT_FOUND) {
				// kernel32.dll not loaded
				DWORD64 hKernel32Dll = 0;
				if (IsWindows7OrGreater())
					hKernel32Dll = LoadLibraryW64(L"kernelbase.dll");
				else
					hKernel32Dll = LoadLibraryW64(L"kernel32.dll");

				if (hKernel32Dll) {
					DWORD64 pfnLdrAddr = GetProcAddress64(hKernel32Dll, "LoadLibraryExW");
					if (pfnLdrAddr) {
						dwLoaderOffset = (DWORD)(pfnLdrAddr - hKernel32Dll);
					}
				}
			}`

通过x64-x86-x64这种启动方式链中，一个特殊的环境变量会被创建出来，由于这个环境变量的存在，x86程序不需要重新计算LoadLibraryW的位置，所以LoadLibraryW64并不需要被调用。

**Comment by krrr** [comment]
是32位程序崩溃。x64运行x64没问题。

看逻辑是这样的，但是确实没有这个环境变量。MacType64.dll是官方版的，我懒的编译64位就没动过

**Comment by snowie2000** [comment]
@krrr 必须要同时使用CTP版本里面的64位和32位，否则是不会出现那个环境变量的。

**Comment by snowie2000** [comment]
@krrr 我上传了一个新的版本，你测试一下。
http://www.mactype.net/station/MacType_CTP_161116.rar

**Comment by krrr** [comment]
我刚刚测试了161026那个，环境变量有了，x64-x86-x64的崩溃现象消失了

这个问题看样子是少数中的少数吧，只有用macloader+特定系统的人才能遇到，忽略好了？

**Comment by snowie2000** [comment]
试一下161116那个，测试方法同上面的2，从macloader干净启动32位，然后启动64位。

**Comment by krrr** [comment]
竟然好了，这是怎么做到的，果然还是我的编译方式有问题？

**Comment by snowie2000** [comment]
> 既然这个LoadLibrary会死，干脆被注入进程也用LdrLoadDll好了？

如你所言，我换成了这种方式。源代码已经更新。

**Comment by krrr** [comment]
@snowie2000 我花了一晚把该死的win10从1511升级到1607，然后原来那个LoadLibraryW64的方式也正常工作了……你会不会有种被骗的感觉

**Comment by snowie2000** [comment]
@krrr 你在测试那个LoadLibraryW64的时候最好要重启一下，不然64位MacType创建的辅助环境变量会一直有效，以至于LoadLibraryW64根本不会运行

**Comment by krrr** [comment]
我当然有考虑那个，确定没有环境变量

**Comment by snowie2000** [comment]
也许Win10的1511中kernelbase.dll做了什么特别的动作导致64位和32位一起加载时会有概率出现冲突吧。
不管怎么说我已经放弃原来的做法了，LdrLoadDll目前看来是更稳妥的方案。
