### ISSUE TITLE
Programs specified in Mactype.ini are not excluded

### ISSUE THREAD

**Issue by mxalbert1996** [snowie2000/mactype#209]
For example, in `Mactype.ini`:

```
[ExcludeSub]
chrome.exe

[UnloadDll]
studio64.exe
```

But actually they are not excluded.
This problem didn't exist in version 0904, and at least exists in version 0928 and 1026.

P.S. Tested with Registry mode on Windows 10 x86 and x64.

**Comment by Explorare** [comment]
Define it in `./ini/Default.ini` please.

**Comment by mxalbert1996** [comment]
@Explorare That's the config file of the `Default` profile. If you are not using that profile, it doesn't work.

**Comment by Explorare** [comment]
@mxalbert1996 So add these exclude rules to the profile your are using. All the exclude added from GUI will be added to the current profile at the same time, not 'Mactype.ini'.

**Comment by mxalbert1996** [comment]
@Explorare Of cource I know that works. But what I need is global control. And considering this (in official config files)
![2016-10-31 2](https://cloud.githubusercontent.com/assets/9391933/19842995/b6569e48-9f61-11e6-9713-a2c9f6b0127f.png)
and the fact that it worked in the older versions, I think it's a bug.

**Comment by Explorare** [comment]
@mxalbert1996 Umm. Seems so. ( ´_ゝ`)

**Comment by snowie2000** [comment]
@mxalbert1996 
Yes, it worked in old version, and I removed it during the ini performance improvement. I thought it was not used very often and you can easily move these sections to your profile.
If you guys think it's very important or handy, I may get it back later.

**Comment by mxalbert1996** [comment]
@snowie2000 Understood. If removing it can bring performance improvement, I think it's OK.
