### ISSUE TITLE
关于白名单的问题（About white list）

### ISSUE THREAD

**Issue by wangxiya** [snowie2000/mactype#212]
部分应用启动时没有窗口，比如listary，它是一个资源管理器的一个插件，主要负责弹出右键！默认mactype无法对其渲染，除非我到详细设置中，强行选择该进程，并启动渲染，方可有效。可否设计白名单，针对此进程确保可以渲染？！谢谢！

**Comment by snowie2000** [comment]
不存在能保证渲染的白名单。
listary这个软件我也有在使用，并没有出现不能渲染的情况。您可以检查下是否被排除了，您的mactray是不是有管理员权限，mactype.ini中的RedrawDelay是不是等于0。
