### ISSUE TITLE
Mactype "Opt" profiles do not work in explorer in Win 10

### ISSUE THREAD

**Issue by tedbell** [snowie2000/mactype#213]
Mactype does render the fonts in windows explorer in windows 10 but when I select an "Opt" profile (the ones with the shadows) it does not render the shadows.

**Comment by snowie2000** [comment]
Can you upload a screenshot?

**Comment by tedbell** [comment]
Looks like the application of the mactype is a bit dodgy. Right now I have it working in explorer but it's not working in Firefox (with hw acceleration off) as it usually does. It seems to apply when it wants to whatever it wants.

**Comment by snowie2000** [comment]
set false to direct2d in about:config page for firefox is enough to enable mactype.
