### ISSUE TITLE
DirectWrite:1

### ISSUE THREAD

**Issue by kaanguner** [snowie2000/mactype#215]
What does this do? Is it for chrome? I cant make this to work on Chrome. Is there any way to override Chromes font rendering?

**Comment by drxt** [comment]
It works on Chrome, but you should've typed in DirectWrite = 1, not DirectWrite:1.

**Comment by snowie2000** [comment]
And it works best in Windows 10, cause DirectWrite is better implemented in Windows 10.

**Comment by kaanguner** [comment]
So guys do I need the patch? What are the other patches for?

**Comment by BandageWorm** [comment]
I tried it and it does work on Edge, which is fantastic. But it seems that the Office DW is still not overrided?

**Comment by rudolphos** [comment]
@snowie2000 I have 

```
; DirectWrite 支持；DirectWrite support
DirectWrite=1
```

But fonts on Chrome still look ugly

![chrome_2016-12-20_17-12-12](https://cloud.githubusercontent.com/assets/4366810/21355650/829e5d1e-c6d7-11e6-8163-ddc39d099ace.png)
