### ISSUE TITLE
chrome55崩溃

### ISSUE THREAD

**Issue by enuma0** [snowie2000/mactype#217]
![default](https://cloud.githubusercontent.com/assets/3970620/21292068/a95728b0-c532-11e6-9cb9-d57a6f251645.png)
系统win8.1 X64 mactype0904  chrome 55.0.2883.87 m (64-bit)
尝试过使用MacTypePatch_1.19 依然会崩溃

**Comment by zzh1991** [comment]
chrome 56 也是崩溃，chrome 无法使用

**Comment by snowie2000** [comment]
请试一下最新的CTP版本。请不要使用补丁，使用补丁导致的一切问题均不处理。
