### ISSUE TITLE
installer not working with /quiet

### ISSUE THREAD

**Issue by chantisnake** [snowie2000/mactype#218]
I just need the silent argument for this package to create a chocolatey package for this app,

According to `/?` this package should work with all the msi install parameter:
```
<MSI 选项> 运行 MSI 软件包时的 msiexec.exe 选项
```

It just not working with `/quiet`, any ideas?

**Comment by snowie2000** [comment]
Here is all the command line information you need:
http://www.advancedinstaller.com/user-guide/exe-setup-file.html
