### ISSUE TITLE
No build since september?

### ISSUE THREAD

**Issue by kiravi** [snowie2000/mactype#219]
Do you have a release schedule?  I see no windows builds since September 2016.

**Comment by snowie2000** [comment]
Not recent. I'm working on separating mactype into several parts and improve its stability and compatibility.
I'll update code once I finished.

**Comment by rudolphos** [comment]
Is there anyone who can compile the current code ?
It's too much work to download all dependencies & tools. Maybe there is somebody who has all the necessary tools and can compile it ?

**Comment by IceMan81** [comment]
@rudolphos There are some recent builds here, the archives just contain the 64 and 32 bit dlls.
http://mactype.net/station/

**Comment by snowie2000** [comment]
I've uploaded a new CTP version with some new techs. You may want to have a try.

**Comment by IceMan81** [comment]
@snowie2000 Will do;thanks for the upload. Is there anything that requires us to tweak existing settings we use?

**Comment by snowie2000** [comment]
No change is required

**Comment by rudolphos** [comment]
@snowie2000 

> with some new techs


Then should I remove that Japanese patch, before I replace the new CTP dlls ?
Because now Chrome fonts look a little bit weird (in extension pages)

**Comment by snowie2000** [comment]
If you put mactype patch files under system folder, it will be invalid in
this release.
