### ISSUE TITLE
Conflicts on Windows 10 build 15002, 15007, 15014, 15019, 15025, 15031, 15042, 15046, 15048

### ISSUE THREAD

**Issue by Kesantielu** [snowie2000/mactype#221]
> Faulting application name: mmc.exe, version: 10.0.15002.1001
> Faulting module name:: MacType64.dll, version: 1.2016.904.0
> Exception code: 0xc0000005

> Faulting application name: cleanmgr.exe, version: 10.0.15002.1001
> Faulting module name:: MacType64.dll, version: 1.2016.904.0
> Exception code: 0xc0000005

**Comment by Kesantielu** [comment]
Not only with system apps.

> Faulting application name: vmware.exe, version: 12.5.2.13578
> Faulting module name:: MacType.dll, version: 1.2016.904.0
> Exception code: 0xc000041d

**Comment by snowie2000** [comment]
I'm sorry about it, but Windows 10, especially Windows 10 Insider version has very low priority in development. It is unlikely to be investigated and fixed recently.

**Comment by Garfield550** [comment]
Windows 10 build 15019 

![windows 15019](https://cloud.githubusercontent.com/assets/3471836/22396998/7f553b12-e5a1-11e6-831a-7a69f88a8683.PNG)

**Comment by Kesantielu** [comment]
Mactype is totally incompatible with build 15042. 15042 is rtm-candidate build, it means Mactype may be incompatible with next release, Redstone 2.

**Comment by imebeh** [comment]
maybe since 15025, till 15042, shift + delete crashes explorer.exe

**Comment by chenrylee** [comment]
Maybe a new version should be appended.
This tool cannot work with in Windows 10 build 15046, totally.
I ran it in service mode.

**Comment by ivansf** [comment]
Also experiences the same issues.
Shift+delete causes Explorer to crash.

Running Build 15048.rs2_release.170228-1522

**Comment by snowie2000** [comment]
Try new CTP build.

**Comment by imebeh** [comment]
CTP 170307 seems work for me.
Win10 build 15048

**Comment by Kesantielu** [comment]
Great! CTP works.

**Comment by ShintakuNobuhiro** [comment]
It is operating correctly. There is no problem anymore.(I used Google Translate.)

**Comment by ivansf** [comment]
Sorry, but where is this CTP build? How do I access them?

**Comment by adelduprat** [comment]
@ivansf You can get it [here](http://mactype.net/station/).

**Comment by Kesantielu** [comment]
Win10 build 15055, CTP works

**Comment by ShintakuNobuhiro** [comment]
Build 15060, CTP works.

**Comment by ShintakuNobuhiro** [comment]
Build 15061, CTP works.

**Comment by snowie2000** [comment]
Thank you for your report!

**Comment by ShintakuNobuhiro** [comment]
Build 15063 too, CTP works.

**Comment by wasd--** [comment]
Even with CTP fix there are things that were working before(Anniversary Update) and don't now.

The right click, properties windows it's not working here, Java apps like JDownloader neither.

**Comment by KTsarlz** [comment]
How do you install CTP builds? @snowie2000

**Comment by wasd--** [comment]
@KTsarlz download the CTP dll's from the link posted before and replace them in your installation directory.

**Comment by L96Github** [comment]
CTP build from [http://mactype.net/station/](url) solved windows installer crashes for me. Windows 10 build 15063.
