### ISSUE TITLE
可否加入白名单功能

### ISSUE THREAD

**Issue by Arrow-Li** [snowie2000/mactype#222]
现在是排除特定程序，可不可以增加白名单功能，只渲染指定的程序

**Comment by snowie2000** [comment]
[General]
UseInclude=1

[Include]
xxx.exe

**Comment by Arrow-Li** [comment]
试了一下应该是
[IncludeModule]
snowie2000 <notifications@github.com>于2017年1月13日 周五14:09写道：

**Comment by snowie2000** [comment]
Thanks for correction.
