### ISSUE TITLE
Cause Edge Crash

### ISSUE THREAD

**Issue by Arrow-Li** [snowie2000/mactype#223]
开启MacType会导致Edge崩溃，Edge打开2-3s就会退出
(并没有渲染Edge，对Edge是禁用状态)

**Comment by Arrow-Li** [comment]
所有UWP应用都会闪退

**Comment by snowie2000** [comment]
insider 版本均不开发不测试，很抱歉。

Arrow-Li <notifications@github.com>于2017年1月17日 周二18:38写道：

**Comment by Arrow-Li** [comment]
周年更新正式版
![default](https://cloud.githubusercontent.com/assets/17962902/22019870/44b5c346-dcf0-11e6-8bb7-1e2af02d9129.PNG)

**Comment by snowie2000** [comment]
这个版本测试并未发现这种问题，请注意干净安装不要使用任何补丁，如使用补丁请按照补丁说明使用。

Arrow-Li <notifications@github.com>于2017年1月17日 周二20:05写道：

**Comment by Arrow-Li** [comment]
没有打任何补丁，测试default配置没有问题
似乎是include模式的问题

正在用的配置文件
[General]
Name=Game
HintingMode=3
AntiAliasMode=2
NormalWeight=15
BoldWeight=0
ItalicSlant=0
EnableKerning=0
GammaMode=0
LcdFilter=1
BolderMode=0
TextTuning=0
TextTuningR=0
TextTuningG=0
TextTuningB=0
GammaValue=0.8
Contrast=1.5
RenderWeight=1.5
Fontlink=1
HookChildProcesses=1
FontLoader=0
FontSubstitutes=1
Shadow=1,1,7,0x0,0,0x0
MaxBitmap=0
CacheMaxFaces=256
CacheMaxSizes=12554432
CacheMaxBytes=12108864
UseInclude=1
[exclude]
[FontSubstitutes]
Microsoft YaHei UI=方正剑体简体
Microsoft YaHei UI Light=方正剑体简体
微软雅黑=方正剑体简体
微软雅黑 Light=方正剑体简体
新宋体=方正剑体简体
宋体=方正剑体简体
黑体=方正剑体简体
等线 Light=方正剑体简体
等线=方正剑体简体
Yu Gothic UI=方正剑体简体
Yu Gothic=方正剑体简体
SimSun-ExtB=方正剑体简体
[Individual]
[excludeSub]
[IncludeModule]
Grim Dawn.exe
[UnloadDll]
explorer.exe

snowie2000 <notifications@github.com>于2017年1月17日周二 下午8:16写道：

**Comment by snowie2000** [comment]
include这个模式很少有人用，所以我其实从来没测试过………
我找时间试下
Arrow-Li <notifications@github.com>于2017年1月17日 周二23:23写道：

**Comment by Arrow-Li** [comment]
主要有的游戏字库不好做，只能外挂程序改字体了
但是不想动其他的地方字体

**Comment by snowie2000** [comment]
之前有听说在windows10下面，有的时候排除一个进程，会出现崩溃的问题，我这边有一个新的版本正在测试，我可以去试一下include模式会不会出现问题
Arrow-Li <notifications@github.com>于2017年1月17日 周二23:26写道：

**Comment by snowie2000** [comment]
经过测试新的开发版本并不会导致崩溃问题，如果您需要的话我可以上传到文档服务器

**Comment by Arrow-Li** [comment]
没事您慢慢测试就好，我也不怎么用uwp应用

snowie2000 <notifications@github.com>于2017年1月18日周三 下午2:07写道：

**Comment by snowie2000** [comment]
新CTP版本已上传。

**Comment by Arrow-Li** [comment]
Thanks
snowie2000 <notifications@github.com>于2017年2月5日 周日15:42写道：
