### ISSUE TITLE
Not compatible with World of Warships

### ISSUE THREAD

**Issue by Explorare** [snowie2000/mactype#226]
System: Windows 8.1 Enterprise
MacType Version: 1.2016.904.0 
MacType Mode:  standalone tray mode (with admin)
Issue
The process can't be ended if the `WoWSLauncher.exe ` execute with MacType enabled, with a error message `Access is denied`. This issue caused WoWS launcher unable to execute again. Only reboot fixes it. 

![image_2017-02-02_ 001](https://cloud.githubusercontent.com/assets/5090766/22549016/34d7e7e2-e984-11e6-856b-5bf17940dc83.png)
![image_2017-02-02_ 002](https://cloud.githubusercontent.com/assets/5090766/22549015/34a9819a-e984-11e6-88bf-31f95f18ebd0.png)

**Comment by Mahayu** [comment]
(Sorry for my poor English)
World of Warships has a function that can detect dll injecting and prevent it.
For online games, it is highly recommended to put it into the excluding list.

**Comment by Mahayu** [comment]
(Sorry for my poor English)
World of Warships has a function that can detect dll injecting and prevent it.
For online games, it is highly recommended to put it into the excluding list.

**Comment by Explorare** [comment]
@Mahayu 
I've already added `WargamingGameUpdater.exe` and `WoWSLauncher.exe` to the `[UnloadDLL]` section but didn't work. The issue only affects WoWS launcher, not the game itself. But I need the launcher to check for update. So I have to reboot every time I need to update the client. Not a big problem but still annoying. 

I can understand CHS and CHT, btw.

**Comment by snowie2000** [comment]
Try my newly uploaded CTP version which introduces a new child hook model.

**Comment by Explorare** [comment]
This issue has been solved with the patch CTP 0205. Thanks.

**Comment by Explorare** [comment]
It seems that the new patch brought in a new issue, which Direct Write content can't be rendered anymore (I used MacType Patch 1.19 before). Any further plan for supporting or hacking Direct Write? My laptop don't support Windows 10.

**Comment by adeldpt** [comment]
@Explorare Add `DirectWrite=1` to the .ini file of your current profile (usually `C:\Program Files\MacType\ini\Default.ini`).

**Comment by Explorare** [comment]
@adeldpt Thanks. Problem solved. : )

**Comment by snowie2000** [comment]
@Explorare 
You have to put MacType-patch files in the same folder of MacType. All files in system folder will no longer be loaded.

**Comment by Explorare** [comment]
The ReadMe in MacType_Patch_1.19 mentioned that the `EasyHook64.dll` should also be copied to `\System32`. So this no longer have any meanings?

**Comment by snowie2000** [comment]
Yeah, it is true in public version, but not in CTP version. I changed hook method alot.

**Comment by Explorare** [comment]
Okey. I've removed EasyHook from system folder. But it looks odd in OneNote 2013 like this
![image](https://cloud.githubusercontent.com/assets/5090766/22726175/f0c70ae6-ee0c-11e6-8d50-45f4cd079b11.png)

Compared with OneNote Online on Cent Browser with DirectWrite OFF
![image](https://cloud.githubusercontent.com/assets/5090766/22726260/8396c5b4-ee0d-11e6-89ac-394210f20d18.png)

**Comment by snowie2000** [comment]
DirectWrite tweak is not as good as freetype provided by MacType, especially on Windows other than Windows 10

**Comment by Explorare** [comment]
So the only way could I fix this is upgrade to Windows 10?

**Comment by snowie2000** [comment]
Yes and you must upgrade to Creator update to get the new directwrite engine.

**Comment by Explorare** [comment]
Umm. I'll have a try.

**Comment by snowie2000** [comment]
Be prepared. Windows 10 is also known as Bug 10.

**Comment by Explorare** [comment]
Yep. May the Force be with me.

**Comment by Explorare** [comment]
Updated to Windows 10 14393.447 successfully. All functions works well include fingerprint reader. But It still looks awful for CJK characters.

![image](https://cloud.githubusercontent.com/assets/5090766/22770326/9a59147e-eeca-11e6-9f16-ba7faaf5f54a.png)

![image](https://cloud.githubusercontent.com/assets/5090766/22770328/a31fc878-eeca-11e6-8df6-adce1726839b.png)
