### ISSUE TITLE
Programs like Foobar2000 or Firefox only in Admin mode

### ISSUE THREAD

**Issue by rissol** [snowie2000/mactype#227]
Hi,

After i install Mactype latest version, programs like Foobar2000, Firefox or Chrome (the ones i checked until now) only run in Administrator mode, if i disable or unload Mactype everything back to normal.

I tried several types of Mactype instalation and none solve this.

Thank you.

**Comment by snowie2000** [comment]
Please provide your system configuration information.

**Comment by rissol** [comment]
Hi,

Im using windows 7 x64, my hardware is asus z97 mb i5 cpu 16g ram and gtx770.

Im goint to try one of the new versions of mactype, is just to copy the dll files to the installation dir and reboot? 

Thks

**Comment by snowie2000** [comment]
Yes. just overwrite and reboot.

**Comment by rissol** [comment]
Still the same, not even with newer files, i can run the apps only in admin mode.
Thanks

**Comment by jjjjjiiii** [comment]
Are you using Avast?

**Comment by jjjjjiiii** [comment]
I had the same problem, but after disable avast, the problem was solved.

**Comment by rissol** [comment]
Hi,

No i have AGV Free, but i have Mactype folder in exceptions, dunno if even in exceptions the AVG interfere with it or not.

Thanks

**Comment by rissol** [comment]
Hi,

Well its seems is AVG Free, i disabled it for 10 minutes and i can run apps without the need to do it in Admin mode, i have Mactype Folder in exceptions but that doesnt help as it seems.

What can i do ?

Thanks

**Comment by IgnacioMD** [comment]
Rissol, you can open profile and set HookChildProcesses=0.

Mactype was working fine for me in Windows 7 32 bits, but when i Installed Windows 7 64 bits, i had the same problem.

Setting HookChildProcesses=0 worked for me, this way is avoided the conflict with Avast and perhaps with AVG too.

Is explained here, this link can be accessed through the "Wiki" tab of this same web page
https://github.com/snowie2000/mactype/wiki/HookChildProcesses

**Comment by sammilucia** [comment]
- This is a known issue, it's very difficult to work around anti-virus software because their methods are always ever-evolving.
- Added to known issues in Readme (thanks @IgnacioMD 😊)
