### ISSUE TITLE
Problem with font rendering in Adobe Indesign

### ISSUE THREAD

**Issue by carelfransen** [snowie2000/mactype#228]
I have a problem with the font rendering within Adobe Indesign. While MacType works perfectly with most software, including the interface of Adobe Indesign, I cannot seem it to work with the actual type within my designs.

Attached are two images showing part of the design of a page, and part of the Indesign interface, one with MacType turned on, the other turned off. You can see MacType does work on the interface, but not on the design itself.

MacType turned off:
![mactype-off](https://cloud.githubusercontent.com/assets/25610961/22691177/75acc482-ed39-11e6-83bc-c3cda3c9775e.JPG)

MacType turned on:
![mactype-on](https://cloud.githubusercontent.com/assets/25610961/22691178/75aeaed2-ed39-11e6-973f-f2f817fa683b.JPG)

**Comment by casef** [comment]
I believe Adobe uses their own font rendering engine in their products, so this is probably to be expected.

**Comment by snowie2000** [comment]
Most adobe softwares have their own builtin font engine.
