### ISSUE TITLE
如何实现将某一程序的字体全部热替换为一种字体，而不影响其他程序

### ISSUE THREAD

**Issue by gttwork** [snowie2000/mactype#233]
我有一个常见的读书软件，字体其丑无比，还无法更改字体，各种书籍使用的字体各不相同，只能通过热替换来更改。试过很多方法，只有 “ForceChangeFont=” 有用。但其他软件会出现各种问题。曾试过“[FontSubstitutes@.exe]” 也没有用。希望知道如何设置可实现仅将这个软件的字体进行 “ForceChangeFont=” 。

**Comment by snowie2000** [comment]
[General@exe_full_name]
ForceChangeFont=New_Font_Name

**Comment by IceMan81** [comment]
When doing font replacements, can font names have spaces in them?

What does ForceChangeFont do?

**Comment by snowie2000** [comment]
As far as INI format allows, you can use any letter in this field.

ForceChangeFont is quite simple and straightforward. It simply creates designated font for all font creation requests, and cheats system that you've created the actual font it requested.

**Comment by gttwork** [comment]
It works! Thank you so much! Thank you for all your hard work.
![5621](https://cloud.githubusercontent.com/assets/16264455/23050917/38443c64-f500-11e6-89e1-aa13aa732840.png)
