### ISSUE TITLE
Cannot install: "an error occurred while extracting"

### ISSUE THREAD

**Issue by unalignedcoder** [snowie2000/mactype#235]
Re-downloaded a dozen times, from different browsers, checked temp folder permissions, run as administrator, always get the same error: "an error occurred while extracting".
As I close this message window, another one appears for a second with a "details" button there's no time to click.
The "MacType" folder appears during the few seconds in the Temp folder before the installation fails, containing two files, "1033.dll" and "decoder.dll" in the "install" folder.
I'm on windows 7 x64.

**Comment by unalignedcoder** [comment]
After a lot of obtuse double-clicking the installer finally ran past the error. However it soon encountered another series of errors, relating to not being able to find files in the ini folder and MacTray.exe. Whatever. What's wrong with this installer? I tried different releases and they all behave like this. I suggest releasing all files already extracted and ready to install, it would probably work out better.

**Comment by unalignedcoder** [comment]
After a lot of obtuse double-clicking the installer finally ran past the error. However it soon encountered another series of errors, relating to not being able to find files in the ini folder and MacTray.exe. Whatever. What's wrong with this installer? I tried different releases and they all behave like this. I suggest releasing all files already extracted and ready to install, it would probably work out better.

**Comment by snowie2000** [comment]
There is obviously something wrong with your system.
Anyway, you can use mactypeinstaller.exe /extract "you target folder" to extract all files from the installer.

**Comment by unalignedcoder** [comment]
Thanks! You were probably right, I ran system restore and finally managed to install correctly. The program looks great, but I'm not too happy with the font rendering, especially with Tahoma's "i" and "l" when next to each other, as in the word "file". But this is for another thread I guess.
