### ISSUE TITLE
4K显示器下CPU占用率过高 / High CPU usage with 4K 

### ISSUE THREAD

**Issue by AbraxasVi** [snowie2000/mactype#237]
不管是采用服务加载还是托盘加载，不管DirectWrite是否打开，都会产生CPU占用率过高的问题，主要是MacTray.exe和mt64agnt.exe两个进程，加起来会一直占满一个单核心，CPU是4590，占用率基本上维持在25%左右。

DPI也调过，从一开始的200%到100%每一档都试过，结果都一样。同样另一台1080p的电脑不会出现这种情况。
![snipaste20170223_192837](https://cloud.githubusercontent.com/assets/17812669/23257340/4fe9ae50-f9fe-11e6-9c51-08418874ce0c.png)

No matter Mactype is loaded by the service or the taskbar, or the DirectWrite value is set to 0 or 1 in the ini file, the CPU usage is always so high, i'm using a i5-4590, the CPU usage combined by the "MacTray.exe and mt64agnt.exe" can always be about 25%. 

DPI is 100%, but 125% or 150% is always the same.

**Comment by snowie2000** [comment]
这两个进程理论上并没有做和分辨率有关的事情。应该是和系统有关，可能是和系统中的某些程序存在冲突。
如果实在介意，请换成注册表模式。

**Comment by AbraxasVi** [comment]
对了，如果采用注册表加载的话，重启系统后MacType并不会加载，不知是否和采用UEFI+Fast Boot有关系，Secure Boot已开启。之前我也以为是冲突，也重装过系统。
现在暂时采用的解决方案是开机后直接关闭MacType服务，已加载的程序并不会失去渲染，但同时新开启的程序不会渲染。
感谢回复！

**Comment by snowie2000** [comment]
Secureboot下任何注册表加载项不会生效，这是微软的设定。
UEFI没有影响。

**Comment by sammilucia** [comment]
Hi @AbraxasVi, are you still having this problem?

**Comment by sammilucia** [comment]
Closing as abandoned. Please let us know if you still have this problem with beta2 https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2

**Comment by AbraxasVi** [comment]
@sammilucia Thanks for calling. It seems the problem had been solved with beta2, with 10.0.17134.345
and also when i open the user guide, it wont stuck now. 
beta2 is working very well, may i ask why the cpu usage is so strange before?

**Comment by sammilucia** [comment]
@AbraxasVi that's great news!
before, running in Tray Mode before, MacType used to check for new processes very often (by default) ... I believe snowie changed this in the beta to check less often 😊

**Comment by snowie2000** [comment]
> @AbraxasVi that's great news!
> before, running in Tray Mode before, MacType used to check for new processes very often (by default) ... I believe snowie changed this in the beta to check less often

I changed the way mactray.exe/mt64agnt.exe looking for new processes.
The tray app used to scan through the whole process list and check each process for new created processes (every 5sec by default). That's the peak you saw in the CPU graphic.
Now it utilizes the WMI to capture new processes. It never scans the process list anymore.
