### ISSUE TITLE
MacType not working for Google Chrome 56.0.2924.87 64 bit version

### ISSUE THREAD

**Issue by Shirofune** [snowie2000/mactype#238]
Hello. I've downloaded MacType and installed it. No issues so far. Pretty much everywhere in Windows 10 works flawlessly and in some programs like for example, Notepad is very noticeable.

However, I can't seem to notice any difference at all in Google Chrome.  Checking the processes MacType is currently running on, Google Chrome constantly resets from Running to Disabled, then goes back to Running again.

I don't know if this is a personal issue or an issue with MacType, but I would be glad if anyone could give me some insight.

Thank you and thanks for the awesome work of MacType (still remind the difference when you could disable DirectWrite in Chrome, that was night and day)

**Comment by snowie2000** [comment]
You can turn on DirectWrite support by setting DirectWrite=1 in profile. But it won't make huge difference. DirectWrite support is very preliminary currently.

**Comment by rudolphos** [comment]
@Shirofune You need to use MacType patch (.dll) to notice some improvements in Chrome.
Also you need to install mactype as a service for it to better work, otherwise not all programs will use MacType.

**Comment by Shirofune** [comment]
@rudolphos Would you be so kind to link me to the patch you're talking about, please?
But anyway, as you guys are saying, is it worth going through all of that. I mean, there're versions of Chrome, like Cent Browser, in which you can disable DirectWrite. Is it worth using the patch over switching?

**Comment by rudolphos** [comment]
@Shirofune  http://silight.hatenablog.jp/entry/MacTypePatch
