### ISSUE TITLE
MACTYPE20160904版本渲染导致异常

### ISSUE THREAD

**Issue by duying0425** [snowie2000/mactype#240]
你好,
我使用0904的版本,安装了XHei系列字体,WINDOWS 10 Insider Preview Enterprise VOL(15002~15042)版本存在问题
发生错误的场景为任意文件查看属性的安全/兼容性两个选项卡时出现COM Surrogate停止工作的问题
尝试更换为英语界面仍存在此问题
在此请教如何解决,谢谢
![image](https://cloud.githubusercontent.com/assets/4560911/23576842/1c398762-00eb-11e7-936e-c68dc527de68.png)

再次补充一下:使用注册表模式,托盘(独立/统一)模式均有此问题

**Comment by duying0425** [comment]
在此补充系统错误相关信息
![image](https://cloud.githubusercontent.com/assets/4560911/23576869/80c7fa7e-00eb-11e7-92a9-a2d81ba68b56.png)

**Comment by snowie2000** [comment]
目前mactype所有版本均与win10 insider preview 15000以后的版本不兼容。

**Comment by MoeGakuen** [comment]
我也遇到了，一开始以为是系统更新过程中出了问题，后来无奈重装了系统发现不会崩溃，装了 MacType 就会。。
现在只能先把资源管理器进程过滤。

**Comment by snowie2000** [comment]
Please use CTP version instead, ref: #221
