### ISSUE TITLE
官网无法下载

### ISSUE THREAD

**Issue by kid1412621** [snowie2000/mactype#242]
official site cannot download

**Comment by Mahayu** [comment]
……是怎么样的无法下载呢？请描述具体情况。
Further details are needed.

**Comment by kid1412621** [comment]
不论挂不挂代理，不论用浏览器还是迅雷，就是不动，卡在0%，或者百分之几

**Comment by snowie2000** [comment]
你需要换个更科学的梯子。

**Comment by kid1412621** [comment]
谢谢，已解决
