### ISSUE TITLE
Mactype does not change the Windows Explorer font Aliasing

### ISSUE THREAD

**Issue by cricrazy** [snowie2000/mactype#243]
Mactype does not change the windows explorer's fonts aliasing. When I looked into to the `Processes loading status`, the `explorer.exe` is shown as access denied. 

![2017-03-08 09-11-20_greenshot image editor](https://cloud.githubusercontent.com/assets/4622816/23709490/3ce2b4ba-03df-11e7-8986-03b3295b65fb.png)

I am using `Load with MacTray` mode with `Run ad Administrator` checked. 

Please help. It is bothering me so much.

**Comment by Mahayu** [comment]
Maybe you can try the Registry Mode?

**Comment by cricrazy** [comment]
I tried the registry mode and it still does not work. It always show `access denied` for Explorer process.

**Comment by Twilightssuperb** [comment]
What about to start Mactype with normal account, not with admin? 🤔 At Win 8.1 it helped me to solve the same trouble — my main account is normal (with limited rights), not admin.

**Comment by skinnyshy** [comment]
Did you disable `secure boot` ?

**Comment by sammilucia** [comment]
Hi @cricrazy did you ever get this sorted?

**Comment by sammilucia** [comment]
Closing as abandoned. Please let us know if you still have this problem with beta2 https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2
