### ISSUE TITLE
Feature Request:  only render specified process

### ISSUE THREAD

**Issue by daxiaoming** [snowie2000/mactype#244]
1. Mactype is an excellent work, thank you snowie2000.   
2. Despite your most honorable effort, mactype often runs into compatibility issues, with programs or windows. I think if you implement a option to enable mactype to render only specified process(es), most of the issues can be avoided in such mode. Me, for example, is using mactype to render  eclipse and got myself an excellent IDE with exceptional outstanding fonts. But the [UnloadDll] option is very troublesome to achieve this. And mt64agent.exe consume a lot of CPU, even for programs in UnloadDll section.

**Comment by snowie2000** [comment]
[IncludeModule]
Notepad.exe

[General]
UseInclude=1

**Comment by daxiaoming** [comment]
Yes I tried the new CTP version of  20170307, but didn't see big improvement.
These two options you gave work like a charm!  
Thank you very much!
