### ISSUE TITLE
Directwrite hook is not affecting UWP apps (except Settings)

### ISSUE THREAD

**Issue by trha** [snowie2000/mactype#245]
Tested with many UWP apps: start menu, action center, edge, calculator, ... All are not affected, except Settings. Win32 apps using DW like Firefox, Chrome, IE, Visual Studio are still working fine. 
MacType Patch works with UWP apps though.

My configuration: Windows 10 build 14393.693 (Anniversary update), MacType 1.2016.904.0 (latest stable release) with registry hook

## Without MacType Patch
![untitled](https://cloud.githubusercontent.com/assets/9519031/23886282/bc73e2b0-08b4-11e7-84e1-d13f69b90058.png)
Raw image: https://1drv.ms/i/s!Ahjx3c1h9ljcjpBxjFYN8_amuLKUtg

## With MacType Patch
![untitled2](https://cloud.githubusercontent.com/assets/9519031/23886269/99f81544-08b4-11e7-8079-859238ce20bf.png)
Raw image: https://1drv.ms/i/s!Ahjx3c1h9ljcjpBwtsZUKufzNv_cTg

**Comment by snowie2000** [comment]
You have to install MacType to your program files folder (C:\Program Files in most cases) to get mactype directwrite support work in Windows 10. Windows Metro environment will refuse to load any dlls located other than Program files and system32 unless they have driver level signature.

**Comment by snowie2000** [comment]
Obviously this behavior is not documented, and may be changed anytime in the future.
But settings app is an exception. It has way higher privileges than any other Metro Apps.

**Comment by trha** [comment]
Thanks for your suggestion. My MacType is already in Program Files. I moved the DLLs to System32/SysWOW64 and everything now works perfectly. I hope this won't get worse in future Windows updates.

**Comment by githubhao0705** [comment]
@trha HI，Can you tell the method?，please~
-I can not speak English, i use google translation.
