### ISSUE TITLE
MacType 20160904 在Windows 10 Insider Preview 15058版本下，查看IE菜单中的Internet选项及兼容性视图设置，导致IE崩溃

### ISSUE THREAD

**Issue by zcgkiller** [snowie2000/mactype#247]
MacType 20160904版本默认安装，默认设置，采用服务模式加载。在查看IE兼容性试图设置及Internet选项时，IE崩溃。
停止MacType Service后，查看兼容性视图设置及Internet选项没有问题

**Comment by snowie2000** [comment]
请使用CTP版本。公开版不支持所有最新的insider preview
