### ISSUE TITLE
新的CTP版本中排除列表失效

### ISSUE THREAD

**Issue by wegood9** [snowie2000/mactype#248]
配置文件相同，UnloadDll列表在2016_0904下正常，在CTP_170307下测试失效，无法启动UnloadDll列表中的程序。
操作系统：Windows 10 build 15058 slow ring 采用注册表加载
还有一个在我的电脑上出现的小问题，部分应用程序（例如chrome、cfosspeed）无法直接在资源管理器中使用mactype渲染并启动，但可以通过一个已停用mactype的程序启动并渲染。此问题在我当前电脑上从Windows 8到Windows 10一直存在，请问是不是个别现象？

**Comment by dbsn** [comment]
搭车问一下，啥时候出新版啊？
mactype太好用了，完全离不开啊。

**Comment by mxalbert1996** [comment]
#209
