### ISSUE TITLE
Contrast functionality

### ISSUE THREAD

**Issue by IceMan81** [snowie2000/mactype#249]
@snowie2000  What does the contrast setting do? Not clear what I should expect when I modify contrast.

**Comment by snowie2000** [comment]
Try MacTuner to visually adjust contrast, and you will have a better understanding about it.

**Comment by IceMan81** [comment]
@snowie2000 How's Contrast different from TextTuning? I couldn't figure out the difference in MacTuner. Also I see that for LCD, you need to use the TextTuningR/G/B settings.
