### ISSUE TITLE
Not working with Pinegrow

### ISSUE THREAD

**Issue by ModDM** [snowie2000/mactype#250]
Mactype works on my Windows 10 computer, but it seems to totally ignore web edit program Pinegrow, even when I set Pinegrow on 'running' in Mactype and Mactype successfully shows it's running on Pinegrow. All my applications are showing better rendered fonts using Mactype, except Pinegrow. Pinegrow is installed in program files x86. Does Mactype supports both programs installed in program files and program files x86? Any idea why this program is not enhanced by Mactype?

Pinegrow program:
https://pinegrow.com/

**Comment by sammilucia** [comment]
Hi @ModDM. Sorry we missed your issue.

Yes MacType supports both x86 and x64 programs.

Thank you for reporting this issue, can you please confirm whether the latest version fo MacType is working in Pinegrow http://www.mactype.net/station/Release/MacTypeInstaller_2017_0628_0.exe
or you can try the newer .dll files here http://www.mactype.net/station/MacType_CTP_171017.rar.

Please also note the **Important notice!** in the readme here: https://github.com/snowie2000/mactype

**Comment by sammilucia** [comment]
Closed as unresponded.
