### ISSUE TITLE
Support `palt` when using a OpenType font as a system font.

### ISSUE THREAD

**Issue by Explorare** [snowie2000/mactype#251]
OpenType 字体支持 `palt` 特性，详见 [Syntax for OpenType features in CSS](https://helpx.adobe.com/typekit/using/open-type-syntax.html)，可以实现更紧凑的排版而不影响可读性，开启后字形为可变宽度，也就是比例字体。今天试了下思源黑体和思源宋体的显示效果，在开启 `palt` 后效果意外的好，如果作为系统字体时能支持此特性并提供一个参数控制就好了。效果对比见此
[开启了 palt 的思源黑体、思源宋体的显示效果](https://bgm.tv/group/topic/342533)

**Comment by snowie2000** [comment]
This cannot be support as mactype always obey the Windows GDI layout which looks like has no future plan to support palt.
If GDI does, mactype does too.
