### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by goncalossilva** [snowie2000/mactype#252]
Hello!

Since updating to the latest Windows 10 (Creator's Update) last night I was having random problems such as not being able to empty the recycle bin or running disk cleanup. Looking at the Event Viewer, there were some problems with MacType's dlls. Uninstalling MacType fixed all Windows' issues, though fonts look pretty terrible now.

I see master has advanced quite a bit since the latest official release. Is a new one in the horizon?

Thanks and keep up the good work!

**Comment by richsleo** [comment]
Yes.I have the same problem.

**Comment by RetroRevo** [comment]
was having the same issues, uninstalling resolved them. hopefully we can get an update

**Comment by MoeGakuen** [comment]
Try new CTP build.  #221

**Comment by RetroRevo** [comment]
That fixed it, thank you

**Comment by vrships** [comment]
Try the new CTP build. It would fix most issues (like empty the recycle bin). However none of the new build gives you the option to fine tune Directwrite (which is present in Userparams.ini in the mactype folder). One workaround is to download the old hookdll files 1.19 from  http://silight.hatenablog.jp/entry/MacTypePatch
and you get to adjust gamma, contrast, etc.. for DW, that would make the fonts look fabulous.
But these DLLs are not so compatible for 1706. I got random memory read errors, but no big issue like explorer crashing.

**Comment by goncalossilva** [comment]
I can confirm the new CTP build works in the Creator's Update without crashing like before.

@vrships I've seen DirectWrite associated with browsers, but would this fix the complete lack of anti-aliasing in Windows Settings and other UWP apps?
