### ISSUE TITLE
Windows10创意者正式版本问题

### ISSUE THREAD

**Issue by richsleo** [snowie2000/mactype#253]
开发者您好，更新到Windows 10正式版本后会出现回收站无法清理，点击回收站清理的时候会卡住，使用新的补丁也没有用，希望您能复现该问题并发布个新补丁让软件能适配新系统，感谢您的付出！

**Comment by richsleo** [comment]
Windows10创意者正式版本号是15063(1703)

**Comment by DearTanker** [comment]
不止这个问题，我的直接桌面的文字不显示，所有软件的文字都不显示了。任务管理器中的文件不显示。也是今晚刚升级的。Mactype用的是服务模式。

现在卸载了以后一切正常。

**Comment by snowie2000** [comment]
请尝试ctp版本

**Comment by jxcangel** [comment]
是的，刚刚升级了创意者版本，不管是服务模式还是注册表模式，甚至基本模式都会出现无法删除文件，无法清空回收站，甚至不显示任何文字的问题，估计还是什么地方有问题了

**Comment by jingouwangzi** [comment]
替换最新ctp之后，word2016无法渲染

**Comment by DearTanker** [comment]
@snowie2000 ctp版本的链接是？

**Comment by snowie2000** [comment]
#221

**Comment by richsleo** [comment]
@snowie2000 替换了CTP版本后还是会出现这个问题！

**Comment by snowie2000** [comment]
@richsleo 我早上把我的测试系统升级到了10563（1703）版本，CTP版本并没有出现任何你提出的所有问题。除非你覆盖的方式不对。

**Comment by MoeGakuen** [comment]
@richsleo 你操作有问题吧。15063没任何问题

**Comment by jxcangel** [comment]
@richsleo 呃，我这里替换了，没任何问题啊，最新发布的创意者更新

**Comment by Explorare** [comment]
没有遇到此问题。

**Comment by myGod0rz** [comment]
1703版 覆盖0307CTP后，未发现任何报错，但
1、属性对话框无渲染；
2、Android studio 断头，
目前遇到以上两个问题

**Comment by snowie2000** [comment]
属性对话框无渲染的问题我好像解决过，忘了是否解决掉了。
请打开ClipBoxFix=1选项，因正式版默认为1，测试版默认为0导致。

**Comment by myGod0rz** [comment]
@snowie2000 你好，我安装了官网下载的最新版mactype，使用了default.ini & \MacType\ini\IoF\XCross\Clear.&.Sharp.ini，其中default.ini默认是开启了ClipBoxFix=1，未见有效，Clear.&.Sharp.ini手动添加了ClipBoxFix=1，也未见效。

**Comment by richsleo** [comment]
@snowie2000 我这里使用服务模式加载没问题，使用注册表加载有问题！属性对话框我这里也是没有渲染，情况和楼上说的是一样的。default.ini的配置也是1，但是没有效果！
