### ISSUE TITLE
关于 Office 2016 在 Windows 10 1703 更新后的渲染效果

### ISSUE THREAD

**Issue by Explorare** [snowie2000/mactype#255]
System Version: Windows 10 15063.13
Mactype Version: CTP 170307_W10 (Without DW patch)
Display: 15.6inch, 1920*1080, 100%
`DirectWrite=1;` by default.

Outlook 2016 中的正文显示效果依旧烂的不行，Onenote 2016 同样，如图：

**Outlook 2016**
`FontSubstitutes=0;`
![Outlook 2016 00](https://cloud.githubusercontent.com/assets/5090766/24791830/43295b8a-1bae-11e7-9c9e-c5281546f4e2.png)

`FontSubstitutes=2;`
`Microsoft Yahei UI = Source Han Sans SC;`
`Microsoft Yahei = Source Han Sans SC;`
![Outlook 2016 01](https://cloud.githubusercontent.com/assets/5090766/24795308/83c16504-1bbb-11e7-8c41-b101ce6215b7.png)

`FontSubstitutes=2;`
`Microsoft Yahei UI = Source Han Serif SC;`
`Microsoft Yahei = Source Han Serif SC;`
![Outlook 2016 02](https://cloud.githubusercontent.com/assets/5090766/24795474/0ca8576a-1bbc-11e7-8760-c6eb29896094.png)

**File Explorer**
`FontSubstitutes=0;`
![File Explorer 00](https://cloud.githubusercontent.com/assets/5090766/24795173/f6f07854-1bba-11e7-8ab8-a68ff64bf1e4.png)

`FontSubstitutes=2;`
`Microsoft Yahei UI = Source Han Sans SC;`
![File Explorer 01](https://cloud.githubusercontent.com/assets/5090766/24795059/9c0500ea-1bba-11e7-82a3-8a2cd7e215c5.png)

`FontSubstitutes=2;`
`Microsoft Yahei UI = Source Han Serif SC;`
![File Explorer 02](https://cloud.githubusercontent.com/assets/5090766/24795235/3c00b562-1bbb-11e7-912d-9db3f6035aa4.png)

与 File Explorer 或 Outlook 2016 的 UI 相比，Outlook 2016 的正文部分明显是没能渲染到，字体替换也不起作用，那么怎么做才能让 Outlook 2016 和 Onenote 2016 的正文字体显示比较舒服呢？

P.S. 如果要替换 Windows 字体，请注意替换的是 `Microsoft Yahei UI` 而不是 `Microsoft Yahei`，系统 UI 字体用了前者。所以如果不想影响正文的雅黑，就避免在文档中使用 `Microsoft Yahei UI`，并将其替换为想要的字体。

P.P.S. 如果 MacType 能尽快支持 proportional 字体特性就好了，Source Han Sans 和 Source Han Serif 都支持。
[Need for a new CJK release branch with proportional kana as default · Issue #143 · adobe-fonts/source-han-sans](https://github.com/adobe-fonts/source-han-sans/issues/143)

---
刚才发现一些邮件的内容确实可以被替换，比如 SONY 发来的 HTML 邮件广告
![image_2017-04-07_ 009](https://cloud.githubusercontent.com/assets/5090766/24796172/85e2de28-1bbe-11e7-9d41-8c3850e77c66.png)
![image_2017-04-07_ 008](https://cloud.githubusercontent.com/assets/5090766/24796173/85e4af14-1bbe-11e7-8273-860a291ff338.png)
正文的字体可以被正确替换并渲染，所以是什么问题导致一些邮件的文字不能被替换、渲染呢？

**Comment by ershiwo** [comment]
打开 DirectWrite 渲染看看。

**Comment by Explorare** [comment]
@ershiwo 第四行写了，默认开着。

**Comment by ershiwo** [comment]
正文字体有可能是等线吧，你替换掉它试试。

**Comment by Explorare** [comment]
@ershiwo 添加了 `DengXian = Source Han Sans SC` 规则
![image](https://cloud.githubusercontent.com/assets/5090766/24805978/ef285422-1be5-11e7-9b12-e6a6b9b0dc50.png)
似乎没效果。

**Comment by Explorare** [comment]
`ForceChangeFont=Source Han Sans SC`
![image](https://cloud.githubusercontent.com/assets/5090766/24806721/5ae36bbe-1be8-11e7-84ec-05842648efad.png)
邮件正文 200%，能看出确实是等线，这微妙的喇叭口。Outlook 2016 似乎是在用 Word 引擎来渲染内容，而不是 IE。所以说 MacType 不能干涉 Word 渲染引擎么？

**Comment by vrships** [comment]
你这个显然是已经开启了DW渲染的结果啊。没有渲染的话雅黑哪里来这么浓的抗锯齿。CTP版的Easyhook以及官网0904版的Easyhook，不支持DW的参数调整，就是只有开启DW和关闭两种选项。

我是去日本人的网站 http://silight.hatenablog.jp/entry/MacTypePatch 下的最新的DLL并替换，这样Mactype文件夹下就有可以Userparams.ini 这个文件可以提供大量DW参数的调整。

微软默认的DW参数，比如Gamma等等，是绝对有问题的，所有小字号下的渲染毛刺很重，粗细不均匀，总是很糟。可以参考Mactype你的自定义文件里GDI字体的渲染参数进行调整。比如Gamma在1.4-1.8是合理值。 Gamma过低，白纸黑字的字会很重，毛刺也会很夸张。Gamma过高的话字体会比较平滑，但是太细太轻。

这个不是字体的锅，无论等线还是雅黑还是Hans source，参数不对效果都会很糟糕，只不过有的字体会更糟而已。

**Comment by Explorare** [comment]
@vrships 请问这个 patch 中的 UserParams.ini 是放在 .\MacType\ 下还是 .\MacType\ini\ 下？

**Comment by vrships** [comment]
放在/macType 下。
去下载最新的1.21Patch吧，完美解决所有问题。 Ini文件修改后，UWP App有一定几率即使生效，开始菜单什么的需要重启才能看到变化

Sent from Mail for Windows 10

**Comment by Explorare** [comment]
ini 文件修改是什么意思？我已经打了 1.21 补丁，重启后发现 Outlook 2016 的正文渲染效果确实变好了不少，如图
![image](https://cloud.githubusercontent.com/assets/5090766/24940634/e132b08a-1f76-11e7-86fb-3a141e932ba1.png)
现在我想知道如何让字体稍微黑一点。谢谢。

**Comment by vrships** [comment]
Params.ini 修改参数后的结果，有一部分界面要重启才能看出变化。嗯这就对了。Mactype对DW差不能做到的极致就是这样了。DW本身抗锯齿倍数太低，比GDI+Mactype的效果还是差不少的。

Sent from Mail for Windows 10

**Comment by Explorare** [comment]
@vrships 那么现在 MacType 的配置是完全只由 UserParasm.ini 决定的咯？比如字体替换、进程排除之类的。

**Comment by vrships** [comment]
不不不。 Userparams只决定几个有限的DW渲染参数。剩下的所有选项还由原先的ini文件控制。

Sent from Mail for Windows 10

**Comment by Explorare** [comment]
@vrships 明白了，谢谢。如果我希望在 15.6吋 1920*1080 100% 缩放的屏幕上实现比较好的显示效果，ForceNoHinting 选 0 还是 1 呢？其他参数有建议值么？

**Comment by vrships** [comment]
Params文件我只改过Gamma和Contrast。现在除了Gamma外，剩下的参数我都是默认了。

Sent from Mail for Windows 10
