### ISSUE TITLE
Windows 10 Creator Update not fully compatible, messes up with some dll's

### ISSUE THREAD

**Issue by KTsarlz** [snowie2000/mactype#257]
So I'm trying now the creators update, I've reinstalled this many times with a lot of variations to know which causes the issue. One crash would occur in going in tabs in windows explorer, com surrogate has stopped working etc. Uninstalling the mactype did the fix.

**Comment by snowie2000** [comment]
#221 Please.

**Comment by KTsarlz** [comment]
@snowie2000 I have read that already except for the part to try another version, will reinstall and update. Thanks!
