### ISSUE TITLE
在win10 红石2兼容性问题

### ISSUE THREAD

**Issue by xinkunZ** [snowie2000/mactype#258]
1. 在红石2上，右键应用的快捷方式，选择兼容性的时候就报错com surrogate停止工作，关闭mactype后就正常，可认为是mactype兼容性问题
2. 在红石2上选择使用服务加载，然后整个windows桌面会崩溃，画面太美不敢重试。。求解决

**Comment by EMLVIRUS** [comment]
TCP覆盖?

**Comment by xinkunZ** [comment]
妈蛋  好像打了那个日本的patch补丁就可以了。。

**Comment by pingplug** [comment]
我遇到资源管理器弹通知时界面卡死的问题（怀疑是内存泄漏，但是所有界面都卡住了什么都看不到，系统日志里也没有什么有价值的信息），打了日本的非官方补丁之后也好了。。。
