### ISSUE TITLE
Windows 1073, install font file COM Surrogate

### ISSUE THREAD

**Issue by charlzyx** [snowie2000/mactype#259]
while i uninstall or stop mactype it will be ok.
I have use the hack by #255 but no use.
And I don't know how to get detail error info.

**Comment by icepole-jon** [comment]
@charlzyx 
![tim20170413210149](https://cloud.githubusercontent.com/assets/3428205/25005921/6ecf86c2-208d-11e7-84db-a58e0d913172.jpg)
You can exclude it and do not replace the font
