### ISSUE TITLE
Windows 1607, crash when not use "Mactray" to load.

### ISSUE THREAD

**Issue by hyrious** [snowie2000/mactype#260]
Hello,

Both "Registry" and "Service" mode will crash when cleaning RecycleBin / openning MacWiz, etc.
I'm not sure if it could be reproduced on another PC.
Yet using "Mactray" mode will be ok, except for not rendering some win32 apps' title.

[My pofile](https://github.com/hyrious/Mactype.Profile.Mac/blob/master/hyrious.ini).

Thanks.

**Comment by ktdd** [comment]
Download CTP version http://mactype.net/station/
