### ISSUE TITLE
Please add VirtualBox to the default exclude list in the next stable release.

### ISSUE THREAD

**Issue by Explorare** [snowie2000/mactype#262]
VirtualBox would fail to initialize a virtual machine due to MacType. Please add the following processes to the dafault `[UnloadDll]` in the next stable release. 

```
vbox-img.exe
VBoxBalloonCtrl.exe
VBoxDTrace.exe
VBoxExtPackHelperApp.exe
VBoxHeadless.exe
VBoxManage.exe
VBoxNetDHCP.exe
VBoxNetNAT.exe
VBoxSDL.exe
VBoxSVC.exe
VBoxTestOGL.exe
VBoxWebSrv.exe
VirtualBox.exe
WoWSLauncher.exe
WorldOfWarships.exe
```

And what's the difference between `UnloadDll` and `ExcludeSub`?

**Comment by snowie2000** [comment]
I will. Thanks.

VBoxSvc.exe and VirtualBox.exe are enough to make VirtualBox work.

**Comment by ErmanSayin** [comment]
VirtualBox is still not excluded by default on release 1.2017.614.0

**Comment by snowie2000** [comment]
Thank you for reminding me the thing, I will add it in the coming patch version.
