### ISSUE TITLE
Windows 10 Creators Update: unable to login

### ISSUE THREAD

**Issue by adolfintel** [snowie2000/mactype#263]
After enabling the MacType service, I cannot log in anymore (I think winlogon.exe crashes after a few seconds).
Booting to safe mode and deleting the MacType service makes it work again, but MacType cannot be uninstalled directly from safe mode

**Comment by hyrious** [comment]
Try
~~~ ini
[ExcludeSub]

**Comment by musereboot** [comment]
I'm also having some issues like I cannot open security tab when I want to check the properties of a file or a folder, a window will popout "COM Surrogate has stopped working" and also "Inaccessible powershell in system32" something like that while installing updates in Adobe Creative Cloud

**Comment by adolfintel** [comment]
@hyrious that fixes the crashing but...

![2017-04-15 17_07_52-](https://cloud.githubusercontent.com/assets/16307689/25064642/b6760bd2-21fe-11e7-9ca5-cdc9417ee8fb.png)
