### ISSUE TITLE
Multiple issues with Windows 10 Build 15063.138

### ISSUE THREAD

**Issue by l19980623** [snowie2000/mactype#264]
I am having issues here and there with latest CU Build 138. One of them being #256 and it still exist with latest MacType. Also I cannot open some Windows utilities such as ``msconfig`` and ``winver``. After uninstalling MacType everything went back to normal. Thanks!

**Comment by ahmadabdel-halim** [comment]
Same here. It broke my system after I updated windows 10.

**Comment by yatahaze** [comment]
Same here. If I download anything sort of installer, whatever program I open it from (Chrome, Firefox, Windows Explorer, etc.) will crash with the following error log:

`
Faulting application name: explorer.exe, version: 10.0.15063.0, time stamp: 0xa25b6083
Faulting module name: MacType64.dll, version: 1.2016.904.0, time stamp: 0x57cbac4e
Exception code: 0xc0000005
Fault offset: 0x0000000000007bbd
Faulting process id: 0x8c8
Faulting application start time: 0x01d2b670b0d357d0
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\Program Files\MacType\MacType64.dll
Report Id: 339d3c58-dc4e-49d6-bade-d0bb2b7e1c0a
Faulting package full name: 
Faulting package-relative application ID: 
`

**Comment by nucklearproject** [comment]
Deleted files (shift+del) crash the explorer and close it. When I disable Mactype, all work fine...
windows 10 Creators update. 15063.138
MacType version:	1.2016.904.0
MacTray version:	1.0.5.2013
MacTuner version:	1.0.2.301

**Comment by l19980623** [comment]
For time being the unofficial patch mentioned in @nucklearproject post is the best way to go. Don't have any issue yet.

**Comment by Jeremiidesu** [comment]
I'm using the CTP builds and they work great, no problem so far. Some programs don't have their font rendering changed (like right click -> properties, but that's com surrogate and hooking it makes the system go boom)
