### ISSUE TITLE
COM Surrogate Error on Windows 10 Creative Update

### ISSUE THREAD

**Issue by readytechgo** [snowie2000/mactype#265]
Many programs won't open using MacType on the Windows 10 Creative Update and give an error. an example of the issue can be replicated by clicking on the 'Compatibility' tab of any program and getting a COM surrogate error.

**Comment by duying0425** [comment]
Try CTP #221

**Comment by readytechgo** [comment]
I actually got it working. I installed the 'Creative Update' patch that has been referenced around here. Everything works perfectly now.
