### ISSUE TITLE
Mactype + patch = doesn't work

### ISSUE THREAD

**Issue by rudolphos** [snowie2000/mactype#266]
I installed latest Mactype (2016 September) with latest 1.23 Mactype patch which is released for Creators Update.

silight.hatenablog.jp/entry/MacTypePatch

I did everything that was written in readme file, but this is the result

![image](https://cloud.githubusercontent.com/assets/4366810/25075334/06991f1a-231b-11e7-9891-63cfdbd834d3.png)

![image](https://cloud.githubusercontent.com/assets/4366810/25075335/0901aea2-231b-11e7-8a3d-8397d449d1ea.png)

![image](https://cloud.githubusercontent.com/assets/4366810/25075355/78726d6c-231b-11e7-81d8-3328ccb463ec.png)

Chrome is also crashing and some other programs.

**Comment by Jeremiidesu** [comment]
I have the same issue, except I successfully uninstalled MacType through the Settings app, and for some reasosn directwrite hooks (i think that's it, because chrome and metro apps were smoothed) were still working fine. I'll try rebooting my pc to see what happens

**Comment by Jeremiidesu** [comment]
using the CTP builds in #221 work well for me. you should try them

**Comment by rudolphos** [comment]
@Jeremiidesu  I installed CTP build, almost everything works except Chrome.

**Comment by Jeremiidesu** [comment]
Chrome works fine for me. Make sure you have `DirectWrite=1` in the [General] section of your profile's ini file.

**Comment by chr0max** [comment]
I also have the com surrogate error with 1.23

**Comment by Craftplacer** [comment]
MY WHOLE DESKTOP TEXT IS HIDDEN.
IT WAS LITERALLY UNUSEABLE

**Comment by rudolphos** [comment]
I finally had a time to make a comparison


1. is **MacType before Creators Update** with 2016 September 4. version.
http://i.imgur.com/HD28a3K.png

2. is with **CTP** March 3, 2017 version
http://i.imgur.com/H2TNGca.png


The difference is clearly visible, 1. has font smoothed, 2nd one just has ClearType it seems.

**Comment by snowie2000** [comment]
If you are using edge as your browser, it is not supported any more.

**Comment by rudolphos** [comment]
@snowie2000 
Wow.. That was fast response.

I'm using Chrome Dev..

![image](https://cloud.githubusercontent.com/assets/4366810/26636692/320b62b0-4626-11e7-8ef8-a79890a5f16b.png)

**Comment by snowie2000** [comment]
What does your profile look like?

**Comment by rudolphos** [comment]
@snowie2000 It's the default one

![image](https://cloud.githubusercontent.com/assets/4366810/26637795/1ed95410-4629-11e7-9463-bb33b7e6cc61.png)

This is after installing MacType Patch which is updated now to support CTP build

![image](https://cloud.githubusercontent.com/assets/4366810/26637841/3f3cbd6e-4629-11e7-92aa-79ac33cfa696.png)

So I guess my problem is fixed now, this can be closed.

**Comment by snowie2000** [comment]
Alright, the mactype-patch author has just updated to compatible with CTP version. If your are using his patch together with CTP, you should get it up to date.

**Comment by IceMan81** [comment]
@snowie2000 Any idea if the patch works with Java applications like Intellij. The patch instruction says I need to set ClipBoxFix=0. Without the patch I'm currently using ClipBoxFix=1 in the Experimental section

**Comment by snowie2000** [comment]
@IceMan81 There is a known bug about pre-app basis profile recognition and also there is another known bug about profile parsing that the last line of the profile will be omitted.
Thus, to make ClipBoxFix work, you have to set the option in the expertimental section and put it in place other than the last line.

**Comment by IceMan81** [comment]
@snowie2000 You had already explained the bug in the per-app profile parsing. 
I was asking about ClipBoxFix if using mactype-patch? For mactype-patch, it says ClipBoxFix should be set to 0. So, I was wondering if mactype-patch fixes clipping issue in Intellij even when ClipBoxFix=0.

**Comment by snowie2000** [comment]
@IceMan81 Yes, the patch fixes the clipbox "bug" by default and there is no way to turn it off.
The fix will cause some program to flicker or laggy, that's why I turn it off by default in CTP version.

**Comment by IceMan81** [comment]
@snowie2000 Do you happen to know what the `ForceNoHinting` option in the patch ini file means? Sorry, I don't have a way to raise questions to the patch author. Thought you might know the answer. `ForceNoHinting` seems to be one of the differences between the Win 7 and Win8+ versions of the ini file.

**Comment by snowie2000** [comment]
Sure.
Force no hinting will turn font hinting off by turning off grid fit mode of directwrite. 
But as you can see, there is no such setting in win7's directwrite 'cause Microsoft has never updated directwrite for win 7. 
Therefore, this setting does nothing in win7

**Comment by snowie2000** [comment]
If you wanna turn off hinting in win7, the only way is set rendering mode to 6. And this is only valid for direct2d. As for directwrite, there is no way to turn off hinting in win 7

**Comment by IceMan81** [comment]
Wow, that's fast! I don't want to turn off hinting mode but good to know what those options mean. Thanks for quick responses!

**Comment by rudolphos** [comment]
@IceMan81 I think it's working with java apps
Here's a screenshot of jdownloader
![image](https://user-images.githubusercontent.com/4366810/27089140-39dfc0da-5062-11e7-81c9-af66aa243be7.png)

**Comment by gengyu89** [comment]
I am sorry to hear that! This is the most unfortunate case ever.

**Comment by snowie2000** [comment]
@gengyu89 What do you mean by "This is the most unfortunate case ever."?
