### ISSUE TITLE
win10创意者更新中容易导致jetbrain家的产品崩溃

### ISSUE THREAD

**Issue by immadolf** [snowie2000/mactype#267]
你好，我将windows升到创意者更新版本后发现在intellij idea中输入中文(非编辑框)会导致idea崩溃。
idea版本2017.1.1
mactype版本MacTypeInstaller_2016_0904_0.exe
![""](http://ww4.sinaimg.cn/large/a15b4afegy1feqyfk1z50j21hc0swtba)

**Comment by l19980623** [comment]
很多人已经确认这个问题了
我在另一个issue里面收到这个*非官方*的补丁，我这几天用下来没问题，你可以试试

http://silight.hatenablog.jp/entry/2017/04/08/213849

作者（非官方）在后来又发布了新版的补丁（[v1.23](http://silight.hatenablog.jp/entry/2017/04/14/214544)），但是我不能确定最新版是否稳定

**Comment by immadolf** [comment]
谢谢 我试试
