### ISSUE TITLE
Firefox stopped working with the new release.

### ISSUE THREAD

**Issue by wasd--** [snowie2000/mactype#269]
Hey,

Since Firefox 53 that was released today bookmarks bar and the rest of the UI is not rendered by mactype, looks as default. Previous release was working fine.

Regards

**Comment by cacophobe** [comment]
Disabling DirectWrite through `gfx.direct2d.disabled=true` on Windows 10 isn't working anymore, possibly because of the new [Quantum Compositor](https://blog.mozilla.org/blog/2017/04/19/first-big-bytes-project-quantum/) being introduced with this version.

**Comment by Enchiridion** [comment]
Looks like Firefox enabled the skia graphics library by default.
Disable it by removing skia from `gfx.canvas.azure.backends` and `gfx.content.azure.backends` under about:config.

**Comment by nanake** [comment]
> Looks like Firefox enabled the skia graphics library by default.
Disable it by removing skia from gfx.canvas.azure.backends and gfx.content.azure.backends under about:config.

It's #165 and maybe not related to this issue because reporter says this affect _UI_ (NOT _content_?) since 53 (_`previous release was working fine`_).

Firefox use _skia_ rather than _cairo_ since 52.

**Comment by wasd--** [comment]
Affects UI and content and as @nanake said skia was enabled on previous release.

**Comment by wasd--** [comment]
I can confirm that after disabling skia like @Enchiridion said Firefox is working fine with mactype again.

**Comment by Fironet** [comment]
I experienced this in v54.0a2 (2017-04-18) of the Developer version and the workaround of removing the `skia` value no longer works as neither the UI nor content is affected by MacType. Posted in the #165 issue though I'm not sure which issue I should be commenting in.

**Comment by wasd--** [comment]
With the lat mactype update Firefox is supposed to work with skia enabled or we have to disable it anyways?

For me at least it's not working with skia enabled.

**Comment by snowie2000** [comment]
@wasd-- it works with skia enabled.
if you suffered from any rendering problem, try using default profile for your profile may miss some needed settings.

**Comment by wasd--** [comment]
@snowie2000 I uninstalled completely mactype, installed again using Default profile and the same. As long as I activate Skia I can see how Bookmarks fonts are not rendered and if I deleted the Skia option I see Firefox rendered good.

Skia disabled: http://i.imgur.com/WOaI6FH.png

Skia Enabled: http://i.imgur.com/dzMhKLX.png

**Comment by snowie2000** [comment]
DirectWrite can never be the same as GDI no matter what params you used.
You should compare it with skia without mactype

**Comment by wasd--** [comment]
@snowie2000 without mactype both options(Skia enabled and disabled) look exactly the same.

**Comment by snowie2000** [comment]
Looks like you enabled hinting.
DirectWrite with hinting looks very similar with Microsoft ClearType.

**Comment by wasd--** [comment]
@snowie2000 With skia enabled looks like the only the bookmarks bar are not rendered, the web looks fine weird

**Comment by snowie2000** [comment]
Snapshot preferred. :framed_picture:

**Comment by wasd--** [comment]
@snowie2000 sure!

Skia Enabled: http://i.imgur.com/YeFVMtc.png

Skia Disabled: http://i.imgur.com/ymDFINp.png

**Comment by snowie2000** [comment]
Please upload a snapshot with skia enabled and mactype disabled.
Please restart firefox after disabling mactype to fully reset DirectWrite parameters.

**Comment by wasd--** [comment]
Firefox Skia enabled(Default) and mactype disabled, restarted Firefox(I did in the last post as well)

http://i.imgur.com/6D0J9rR.png

**Comment by snowie2000** [comment]
Please check the text of the web navibar in the last two screenshot, they are surely different.

**Comment by wasd--** [comment]
What do you mean

**Comment by snowie2000** [comment]
![ymdfinp](https://user-images.githubusercontent.com/11767189/27695240-e8f1538e-5d20-11e7-8bf5-e14d5cfd6bdf.png)
Please check the marked parts,
 the top part : skia: on mactype: on
 the bottom part: skia: on mactype: off.

It's easy to see their difference.

**Comment by snowie2000** [comment]
You should understand that although DirectWrite can be now interpreted, it is still DirectWrite who does the actual render while GDI is fully replaced with FreeType. Their outputs can never be the same.

**Comment by snowie2000** [comment]
As I said, you enabled hinting.
With hinting enabled (in DirectWrite, only cleartype style hinting can be applied, no freetype auto hinting available), tweaked DirectWrite (i.e. dw with mactype) is very similar with normal DirectWrite. Also, mactype is unable to embolden any font in DirectWrite mode which is one of most important feature to make serif font look better.

**Comment by wasd--** [comment]
@snowie2000 I have the default profile(HintingMode=1)

**Comment by snowie2000** [comment]
Did you do a gasp hack to Microsoft yahei?


@snowie2000 <https://github.com/snowie2000> I have the default

**Comment by snowie2000** [comment]
This is the solution now and in the near future.
If you're not satisfied, stay with skia disabled and hope it will last for long.

**Comment by colorworm** [comment]
Also, this might be of interest: https://github.com/snowie2000/mactype/issues/165
