### ISSUE TITLE
MacType Problems in Microsoft Edge on Windows Creators Update

### ISSUE THREAD

**Issue by gmncls** [snowie2000/mactype#273]
Seems like font rendering is fine everywhere after upgrading to Windows Creators Update _except_ on Microsoft Edge. The font on the tabs, address bar, and settings are OK but the text on the main website looks terrible.

![picture1](https://cloud.githubusercontent.com/assets/28075595/25463447/e88b7296-2b28-11e7-8185-cecfa9270401.png)

**Comment by trha** [comment]
This is a security enhancement in CU: only Microsoft signed DLLs are allowed in Edge content processes. We need a new method of injection to workaround this.

**Comment by snowie2000** [comment]
Microsoft added signature check so that mactype cannot be loaded.
I tried a lot method to remove to protection, but once the protection removed, the edge will crash immediately. So, right now, there is no known way to support new edge.

**Comment by gmncls** [comment]
Thanks for the clarification. Sad that there's no workaround... yet. But will keep waiting. Thanks again.
