### ISSUE TITLE
Mactype conflict with explorer.exe after updating Windows 10 to creative update

### ISSUE THREAD

**Issue by wzx1996** [snowie2000/mactype#275]
Before updating, Mactype works fine with explorer.exe, but after updating, explorer.exe would behave strangely when Mactype is enabled for it: attempting to delete a file, or view "safety" tab in the file properties dialogue would crash explorer.exe, and non-admin-privilege program would simply not launch if it's not launched with admin privilege.

My only solution currently is to disable Mactype for explorer.exe, but if this issue can be resolved it would be better.

**Comment by Mahayu** [comment]
You may try the CTP Version.

http://mactype.net/station/

**Comment by drxt** [comment]
Would you mind detailing the steps to take to install Mactype on Creators Update? I tried installing the CTP DLLs on the base 1609 build and explorer.exe was still fucked up no matter what I did. I wonder what do people do to make it work.

**Comment by wzx1996** [comment]
@drxt Since for now MacType work on my computer fine enough I didn't try installing the CTP version. I think you only need to use MacType in standard tray mode and then manually disable "explorer.exe" in MacType's setting and it would work fine.

**Comment by ndlinn** [comment]
@wzx1996: Thanks for sharing. I wondered if you wouldn’t mind briefly outlining the steps you used in order to bypass this issue.

@Mahayu: Are there any instructions available for using CTP for the uninitated?

Thanks in advance!

**Comment by wzx1996** [comment]
@ndlinn Launch MacType in standard tray mode, then left click on the tray icon. A window should pop up. Find "explorer.exe" (You might have to open an Explorer window), right click and select "ignore this process" (or something similar, my software language is set to be Chinese so I don't know the exact text in English).

That should do it. If you do it correctly the effect should stay even after you reboot your computer.

**Comment by ndlinn** [comment]
Thanks much, @wzx1996 —I’m using MacType version 1.2016.904.0 on Windows 10 and can't seem to find the popup window you mention by left clicking on the tray icon (in fact, nothing happens on left click for me, only right-click, which shows the menu). Is it possible we're using different versions of this utility? Thanks again for your help.

**Comment by wzx1996** [comment]
@ndlinn Maybe you have to double click the icon. If you right click it, there's a "detail information" option being shown in bold, and that's the option to go.

I don't really think the version difference matters. I've used MacType years ago, and when I start using it again recently (due to the poor appearance of built-in antialiasing on Surface Pro 4), it feels exactly the same as how it made me felt years ago.

**Comment by ndlinn** [comment]
Thanks again, everyone—I was finally able to get MacType working properly again by installing the [CTP version](http://mactype.net/station/MacType_CTP_170307_W10.rar) on top of the latest version of MacType in my copy of Windows 10 Home Edition.

Since I couldn’t locate any instructions for installing the CTP version, I went ahead and threw together a rough guide here:

https://medium.com/@ndlinn/how-to-make-your-windows-pc-look-more-like-an-expensive-mac-with-apple-quality-fonts-for-free-888acccf712a

Let me know if I missed anything. Thanks in advance.

**Comment by takfate** [comment]
what is CTP version?
