### ISSUE TITLE
Can't empty recycle bin when using mactype on Windows10 (version1703)

### ISSUE THREAD

**Issue by CHN-STUDENT** [snowie2000/mactype#277]
There is a issues when i used mactype on Windows10 (version1703),I can not empty recycle bin because it will crash.The people met same issues here https://github.com/snowie2000/mactype/issues/260.

Thanks.

**Comment by ktdd** [comment]
http://mactype.net/station/ download CTP version

**Comment by CHN-STUDENT** [comment]
@ktdd Thank you,now it works normal.

**Comment by drxt** [comment]
Can @snowie2000 package the CTP version together with launcher and make a proper release to reduce confusion? The current "release" is completely broken and hasn't been updated since September.
