### ISSUE TITLE
Mactype cause newest Windows 10 crash

### ISSUE THREAD

**Issue by zzrcxb** [snowie2000/mactype#278]
After upgrading my Windows 10 Professional to the creator updates, some system functions failed. Such as shift+del can cause Windows Explorer crash if you are using MacType with registry mode. When I made MacType run in service mode, it got worse. No more text could be shown expect in UWP app. Then, I restarted my PC and entered safe mode, uninstalled MacType, every problem was solved. So, some compatibility issues may cause system crash on newest Windows 10.

**Comment by EMLVIRUS** [comment]
[TCP build](http://mactype.net/station/)?

**Comment by zzrcxb** [comment]
I just downloaded it from www.mactype.net

**Comment by rudolphos** [comment]
@zzrcxb that is an old version .exe from September 2016... Since then there have been creators update, etc. So it doesn't work anymore...

**Comment by zzrcxb** [comment]
So is there some newest MacType which is compatible for newest Windows 10? Or should I just download the dlls from [previous link](http://mactype.net/station/) and replace the old ones?

**Comment by EMLVIRUS** [comment]
> So is there some newest MacType which is compatible for newest Windows 10? Or should I just download the dlls from previous link and replace the old ones?

That's right

**Comment by zzrcxb** [comment]
Thanks

**Comment by EPuigdemont** [comment]
I had been dealing with crashes in Destiny 2 for the longest time, and Forza Motorsport 7 would suffer from both stuttery and laggy menus and crashes every now and then, I finally managed to narrow it down to MacType being the culprit, the only solution is to not have MacType running (no need to uninstall for me) and then the games become smooth and stable once again. Very annoying and I don't know exactly what might be at fault.

If it matters, I have a Vega 64 with the latest drivers (throughout all driver versions I've tried, the games were unstable with MacType running).
I found no fix other than stopping the application.

**Comment by snowie2000** [comment]
@EPuigdemont I guess those games used some GDI APIs to get the text outline or something and then do some post effects on it which can be incompatible with MacType.

You'd better exclude them from MacType by adding them to unloaddll list.
