### ISSUE TITLE
Programs not starting with MacType enabled

### ISSUE THREAD

**Issue by Polyterative** [snowie2000/mactype#279]
Hello, wanted to report that on my system a number of app don't start if MacType is enabled.
If I start MacType tray disabled, launch the programm and then enable it everything works ok, but then I have to disable MacType to be able to start the program again.

Programs affected include:
 - Chrome (64 bit)
 - Discord
 - OneDrive
 - Adobe Reader DC
 - Adobe Premiere Pro CC 2017 
 - Ableton Live 9 Suite | Although it works if you exclude "Ableton Index" process
 - Virtualbox machines | they return error on boot
 - Android Studio 2.3.3
 

My machine is Windows 10 | 64 Bit | Anniversary Update 1607

[GIF explaining the problem](http://imgur.com/a/ZuKVZ)

**Comment by CHN-STUDENT** [comment]
I think you need to try to download CTP version [http://mactype.net/station/](http://mactype.net/station/l)

**Comment by maidpretty** [comment]
I confirm the problem. When mactype is started, some programs (including all abovementioned and more) crash/fail on attempt to load.
CTP version MacType_CTP_170307_W10 / patches didn't work.

Windows 10 | x64 | 1607

**Comment by snowie2000** [comment]
Please provide your profile and your installed antivirus conditions.

**Comment by Pyre909** [comment]
With virtualbox place it under unloaddll in your profile. I've had this issue due to windows hardening(security). There are 2 services/applications that run under virtualbox can't remember them off the top of my head.

**Comment by Polyterative** [comment]
I've partially solved the problem by setting certain processes to "ignore this process" but I have to constantly swith between mactype on and off, so still, the problem persists

**Comment by rudolphos** [comment]
This is how Chrome looks with CTP build (March 2017) for me:

![image](https://cloud.githubusercontent.com/assets/4366810/26284788/c39387ea-3e4b-11e7-8801-996dac9cd0e4.png)

**Comment by maidpretty** [comment]
>Please provide your profile and your installed antivirus conditions.
I did a clean install with "default" profile. No antivirus is installed, Windows antivirus disabled.

**Comment by Gino** [comment]
Same problem here. I would like to see a feature that you can basically disable **all** applications and only enable a few apps.

**Comment by drxt** [comment]
Have you guys copied the EasyHK64 (32 if your Windows is 32bits) DLL from the CTP build into the System32 and SysWOW64 folders aside from the Mactype folder? It works for me now that I've copied the DLL into all 3 places.

**Comment by Gino** [comment]
@drxt, just tried this, unfortunately my application is still not opening. I even disabled it in MacType and it still doesn't open, it only works when I disable MacType completely.

**Comment by snowie2000** [comment]
@drxt Unfortunately, copy these easyhook dll to anywhere else besides mactype folder won't make any sense, because from the CTP build on, mactype won't load dll from anywhere else other than its folder.
You can check the source code.

**Comment by wasd--** [comment]
@snowie2000 Idk if someone reported it but MPC-HC crashes(freezes)with latest CTP version when you play a video with subs.

**Comment by jeh-c** [comment]
I am having the same issue. Programs won't start unless I disable MacType. Used dll files from latest CTP build. Everything works fine on my Windows 10 PC, but not on my Windows 7 one.

Running Win 7 64bit + AVG Free; added an exception in Antivirus.

**Comment by IceMan81** [comment]
I'm using the latest CTP on Windows 7 and it works well for the most part.

**Comment by RetroRevo** [comment]
I'm having the same issue as wasd--, using subtitles in MPC freezes and crashes the player.

**Comment by snowie2000** [comment]
For some reason, my virtual win10 (running on vmware 10.0) can't play any video with MPC-HC, so that I can't test it myself.
And in my working system , windows 7, everything is fine.

**Comment by wasd--** [comment]
@snowie2000 there is a way I can help you?

**Comment by wasd--** [comment]
@RetroRevo Yeah, disabling just MPC works for me tho

**Comment by wasd--** [comment]
I can confirm that MPC works now with the latest version released today @snowie2000 ;)

**Comment by wegood9** [comment]
I have the same problem.Try to open profile and set HookChildProcesses=0 #227 
It worked for me.
@snowie2000 My profile is what you posted in themex.net and I do not have any anti-virus software.
