### ISSUE TITLE
mactype 是否提供API 来重启

### ISSUE THREAD

**Issue by hsanyue** [snowie2000/mactype#283]
希望整合mactype 到我的程序中，但不清楚mactype 是否提供api来重启自身

**Comment by Mahayu** [comment]
直接利用 Freetype 岂不美哉？

**Comment by hsanyue** [comment]
我这不是懒么，mactype做得这么完善了。

**Comment by snowie2000** [comment]
没有重启的API，你有两个办法可以来“重启”MacType。
1. FreeLibrary mactype.dll/mactype64.dll 然后loadlibrary，这样可以使mactype重新加载。
2. 使用IControlCenter接口。这个接口提供了很多可以直接控制MacType相关渲染参数的方法，你可以查看源代码settings.cpp/settings.h来了解这个接口。

**Comment by hsanyue** [comment]
感谢
