### ISSUE TITLE
Refresh Issue with Windows 10 after 1703 Update

### ISSUE THREAD

**Issue by dumbcode** [snowie2000/mactype#288]
There is a Strange Issue happening after Windows 10 1703 Update.

1- If MacType is running is Taskbar you can not empty recycle bin, As soon you right click on Recycle bin and choose "Empty Recycle Bin" it will cause Refresh Screen and Taskbar Icons. It does not let you empty recycle bin regardless of how many times you try.

2- To Solve this, Disable Mac Type and then Empty Recycle bin.

I have tested it on 3 different machines and issue is same.

**Comment by Mahayu** [comment]
#275

**Comment by Befeeter** [comment]
Yes, i have same problem, and have another, when you go to isntall some software, and appear the window "security advice" if you have mactype activated, will refresh screen and don't show the installer, and you can't install.

PD: i reffer to this window http://subefotos.com/ver/?abe9605f85d6d307dfc6be31b13f4b5eo.png
Sorry for my english!

**Comment by maqboolkhan** [comment]
@Mahayu and @snowie2000 same happened with me i had to uninstall mactype so can plz guide how can i solve this issue?
