### ISSUE TITLE
Sublime Text MacType

### ISSUE THREAD

**Issue by Gino** [snowie2000/mactype#289]
Hello,

I am currently MacType CTP for Sublime Text but when I close Sublime Text and open it again, the font rendering is default again.
Even when I restart MacType.

I am using the CTP build.

**Comment by lybris** [comment]
You can set `font_options: ["gdi"]` in SublimeText 3. Thus setting it to native windows rendering which then, to my understanding, gets overwritten by MacType.

**Comment by sammilucia** [comment]
From the number of upvotes on @JohnnyGoodNews comment I'm going to assume the workaround works, so closing issue... Please let us know if the problem continues 😊
