### ISSUE TITLE
MacType 1.2017.614.0 - features 

### ISSUE THREAD

**Issue by IceMan81** [snowie2000/mactype#290]
Could you provide some info on:

- Two-stage mactype loader introduced.
- Separate DirectWrite parameter adjustment. 

Also, will the mactype-patch still work with this or are some of the direct write changes in the patch available in this release that the patch is no longer needed.
…

**Comment by snowie2000** [comment]
Here it goes:

- Two-stage loader:
    Instead of fully load mactype font engine directly which has a significant overhead, now the mactype will only load mactype.dll/mactype64.dll into process first, which only contains an INI parser and some simple hooks to determine the right opportunity to load the engine (and the child process hook is now done by this first stage loader). 
    Once the predefined criteria is fulfilled, the mactype.core.dll/mactype64.core.dll will be loaded, and everything will work as before.

- Separate DirectWrite parameter adjustment.
    First, you need to enable DirectWrite support by setting DirectWrite=1 in General section.
    And then comes the new section, DirectWrite. and then... please refer to wiki  [[DirectWrite-section]] for more information.

**Comment by IceMan81** [comment]
Thanks for the detailed info. 
From reading the DirectWrite-section, it looks like the third party [mactype-patch](https://github.com/silight-jp/MacType-Patch) is no longer required.

**Comment by snowie2000** [comment]
Theoretically yes, but silight-jp dips into DirectWrite way deeper than me. I guess he has a better implementation than my version. You can still have a try.
