### ISSUE TITLE
MacType V2017 is not working on Firefox 54.0 32bits.

### ISSUE THREAD

**Issue by takerusb** [snowie2000/mactype#293]
I was working perfectly before update. I tried running FF with administrator privilege, but same result. It also isn't working on Intermapper.

I'm adding some screenshots of V2017 (up) vs V2016 (down)
![2016](https://user-images.githubusercontent.com/29487721/27235712-dddab238-528f-11e7-9a33-f746e5e2f083.png)
![2017](https://user-images.githubusercontent.com/29487721/27235711-ddd5081a-528f-11e7-8979-5ee625d694d3.png)

**Comment by snowie2000** [comment]
Maybe you should post your profile here so that I can try it myself.

**Comment by IgnacioMD** [comment]
Hi, i have Firefox 54.0 32 bits EME FREE and MacType 2017 is working fine,

**Comment by takerusb** [comment]
I'll send the requested profile on monday, since the problem is present y my office PC.
Thanks for the answer! I really love this software.

I apologize for my bad english.

**Comment by takerusb** [comment]
I returned to the V2016 and it's working again. I don't know what may be
the problem.

2017-06-17 21:24 GMT-04:00 IgnacioMD <notifications@github.com>:
