### ISSUE TITLE
MacType V2017 does not work with Chrome

### ISSUE THREAD

**Issue by tcbbd** [snowie2000/mactype#294]
With MacType 20160904 + CTP patch, I can render Chrome without hinting (although unable to change other render settings) .
With MacType 20170614, settings in DirectWrite section cannot affect rendering of Chrome (tried rendermode 0,5,6), so I get ugly hinted fonts.

**Comment by snowie2000** [comment]
If you're using Win7, it's impossible to disable hinting in Chrome.
