### ISSUE TITLE
It seems that the new version of the mactype may lead to system crashes

### ISSUE THREAD

**Issue by cmradix** [snowie2000/mactype#295]
It seems that the new version of the mactype may lead to system crashes。
I do not know what reason he is caused by, but in a crash program, I see the problem is pointing to [MacType64.Core.dll]

**Comment by jnecoj** [comment]
I just crushed in WIN10 newest updated .

disable Mactype(set back to Default.INI) in Safe Mode will solve it :)))

**Comment by cmradix** [comment]
It seems that I involves this fatal problem,It look at it and dwm.exe between a little contradiction
[UnloadDll]
Svchost.exe
Dwm.exe

**Comment by edison0354** [comment]
same

When I start a new APP, the screen hangs up, only mouse can move, after a few seconds, the screen turns black. But seems the system is still running, it's still copying files to my flash disk.
Also solved by disabling mactype in safemode.

not solved by adding the two .exe in my .ini
