### ISSUE TITLE
Can't uninstall MacType

### ISSUE THREAD

**Issue by thevirq** [snowie2000/mactype#296]
I get this window when I try to uninstall MacType

http://i.imgur.com/i7nTHsB.png

**Comment by snowie2000** [comment]
Delete all files and do a clean reinstall.

**Comment by Wideshanks** [comment]
I can't *uninstall* the program.

I choose "uninstall" from Windows Control Panel:

![00](https://user-images.githubusercontent.com/2061925/27295246-372351cc-54ea-11e7-85bd-05ff58becf3a.png)

This screen pops up:

![01](https://user-images.githubusercontent.com/2061925/27294774-c01f7e8a-54e8-11e7-9e9d-1a87fce68541.png)

I agree to the license. I have these options:

![02](https://user-images.githubusercontent.com/2061925/27294777-c292d914-54e8-11e7-84cc-43dbccffe03d.png)

"典型(T)" looks like a normal installation. I try clicking "自定叉(U)" to try to uninstall the program:

![03](https://user-images.githubusercontent.com/2061925/27294778-c4575ab8-54e8-11e7-961f-a77a13b1d0f8.png)

It's modifying the installed components. I want to get rid of all of them, so I try to deselect all components:

![04](https://user-images.githubusercontent.com/2061925/27294780-c5c68b62-54e8-11e7-8b64-bf34b463a789.png)

But it hasn't uninstalled it. It remains in Windows Control Panel.

Does MacType provide an uninstaller?

**Comment by snowie2000** [comment]
I believe it's a compatibility issue with advanced installer since I upgraded it from 13.x to 14.x
