### ISSUE TITLE
(新)宋体、黑体、楷体、仿宋等字体假消失

### ISSUE THREAD

**Issue by hyrious** [snowie2000/mactype#299]
Mactype 1.2017.614.0; win10 rs2; 安装了 “简体中文补充字体”

![image](https://user-images.githubusercontent.com/8097890/27284608-04ed1c78-552c-11e7-8381-2dfe94dab968.png)

![image](https://user-images.githubusercontent.com/8097890/27284542-c307932e-552b-11e7-8f6e-49899ca14d73.png)

此时，任何别的软件（画图、记事本）里都无法使用黑体等字体。

消失的这部分字体还在 C:\Windows\Fonts 里，任意打开并安装一个之后所有的又会出现，应该是字体链接上的问题。

![image](https://user-images.githubusercontent.com/8097890/27284943-60fd7372-552d-11e7-9696-354123247d88.png)

此时这些字体仍然无法使用，但是可以通过手动安装 C:\Windows\Fonts 下的对应文件来恢复。
下图中，本来“黑体”是不存在的，但是手动安装了一下 C:\Windows\Fonts\simhei.ttf 之后就有了。

![image](https://user-images.githubusercontent.com/8097890/27285157-490e36b0-552e-11e7-9edf-c0d738c2e1f3.png)

停用 Mactype 后仍需重新安装字体来恢复。

[个人配置](https://github.com/hyrious/Mactype.Profile.Mac/blob/master/hyrious.ini)
```ini
FontLoader=0
FontLink=2
```

**Comment by hyrious** [comment]
今天好像一切都正常了，奇怪。
总之关 issue 。

**Comment by snowie2000** [comment]
这是一个正常现象，如果你使用热替换替换这些字体的话，就会导致系统看不到这些字体。

hyrious <notifications@github.com>于2017年6月20日 周二09:04写道：

**Comment by hyrious** [comment]
@snowie2000 感谢回复。
我的热替换部分的配置是这样的：
```ini
[FontSubstitutes]
Courier=XHei OSX Mono
Terminal=XHei OSX Mono
MS Sans Serif=XHei OSX
MS Serif=XHei OSX
Microsoft Sans Serif=XHei OSX
SimSun=XHei OSX SimSun
NSimSun=XHei OSX NSimSun
Fixedsys=XHei OSX NSimSun
```
上表中除了 SimSun（宋体）和 NSimSun（新宋体）会在打开 Mactype 时消失在列表里，其他的都能看到，不知道是什么原因。

**Comment by snowie2000** [comment]
热替换会让系统认为宋体就是另外一个字体，他们是等价的，所以在列表中就显示不出来了。
