### ISSUE TITLE
MacType 2017.614.0 not working on Win10's Chrome 59

### ISSUE THREAD

**Issue by ghosrt** [snowie2000/mactype#301]
OS: Windows 10 1703 (15063.413) (Both Home and Pro)
Chrome: 59.0.3071.104 (64-bit)

Upgrade from MacType 1.2016.904.0.
Before upgrade, everything works well.
After upgrade, only Chrome's Frame can be rendered. Screenshot attached.
![image](https://user-images.githubusercontent.com/1570985/27321856-7f150414-55ce-11e7-99cd-8c9435488237.png)

Should I uninstall all previous version and do a clean install ?

**Comment by snowie2000** [comment]
This is a known bug for current version and I'm working on it.
A fix should be available soon.

**Comment by jmbattle0** [comment]
Hmmm...I thought that it was impossible for MacType to affect Chrome after the 'Disable DirectWrite' flag was removed?  Therefore, it was recommended to switch to Cent Browser which reinstated the 'Disable Direct Write' function?

For what it's worth, even with MacType patching Cent Browser, the text is very thin compared to Firefox when browsing the same page. 

Firefox vs Cent Browser:
![mactype_firefoxvscentbrowser](https://user-images.githubusercontent.com/29031955/27415259-09e41260-5741-11e7-8ef6-a92bd4ae7b79.png)

Chrome vs Cent Browser:
![mactype_chromevscentbrowser](https://user-images.githubusercontent.com/29031955/27415275-1ce99a88-5741-11e7-9ac1-8dcd0e195007.png)

**Comment by snowie2000** [comment]
This is how it looks like in IE11 win7 now. I think it is now a little bit more readable.
![qq 20170622105448](https://user-images.githubusercontent.com/11767189/27415384-56576104-5739-11e7-97f4-ac30ef1e3d3f.png)

**Comment by jmbattle0** [comment]
Yes, that's pretty good! I assume this is using the 2017 version of MacType, yes?

I'm still using the 2016 version (due to Symantec blocking the installer, as discussed previously) which doesn't appear to influence IE11 on my Win7 machine.
![mactype_ie11](https://user-images.githubusercontent.com/29031955/27416635-98034aae-5749-11e7-8d06-29dfe860a0d4.png)

**Comment by rudolphos** [comment]
The only option we have is to wait for the new version of unofficial patch

silight.hatenablog.jp/entry/MacTypePatch

**Comment by snowie2000** [comment]
New version will be released no later than tomorrow.

**Comment by jmbattle0** [comment]
Thank you for the update.

I just tried IE11 with the 20170628 portable version, but text rendering appears identical to my screenshot a few days ago.
![mactype_20170628_ie11](https://user-images.githubusercontent.com/29031955/27626086-ad08e0b2-5c21-11e7-9f69-f0bde83ce051.png)

Do I need to change anything in my .ini file to allow MacType to render text in IE11?

**Comment by snowie2000** [comment]
Please add DirectWrite=1 under general section.

**Comment by jmbattle0** [comment]
It appears to already by set.

[Default_TweakedJMB.ini.txt](https://github.com/snowie2000/mactype/files/1107956/Default_TweakedJMB.ini.txt)

**Comment by snowie2000** [comment]
I checked your profile and it is set.
But, enabling this toggle just makes values under DirectWrite section valid, which are the real settings you should care about.
You may want to see https://github.com/snowie2000/mactype/wiki/DirectWrite-section  to have a better understanding of all the possible settings.

**Comment by jmbattle0** [comment]
Ah, I see.

I didn't realise that the additional [DirectWrite] properties were added.
I will copy those into my ini now.

Are there any other additional parameters in the default.ini since the final 2016 release?

By the way, Chrome looks pretty good too now...excellent work!

**Comment by snowie2000** [comment]
I think [MaxBitmap](https://github.com/snowie2000/mactype/wiki/MaxBitmap) and [HintSmallFont](https://github.com/snowie2000/mactype/wiki/HintSmallFont) are the new settings I added, but I don't remember which version I added them.
