### ISSUE TITLE
MacType 2017.614.0 DirectWrite font rendering issue

### ISSUE THREAD

**Issue by JohnKoutsoumpas** [snowie2000/mactype#302]
After installing the new MacType 2017.614.0, there is a bad rendering issue with some applications which are using DirectWrite. Note: I completely uninstall the previous version, rebooted and installed the new) and I used the Default.ini profile without any change (it has DirectWrite=1).

## Notepad++ (GOOD rendering)
![mactype-2017-notepad](https://user-images.githubusercontent.com/26739138/27323013-ba2e43c4-55a8-11e7-88bb-92513a6be57f.PNG)

## Webstorm 2017 (BAD rending)
![mactype-2017-webstorm](https://user-images.githubusercontent.com/26739138/27323014-ba37545a-55a8-11e7-87e6-f827f6f35203.png)

Notice how the letters are missing some of their top pixels, as if they are cut and how the rendering is different from notepad++ above and is ugly. Is this a bug that should get fixed or this is how Mactype does the DirectWrite tweaking? 

Previously I used the MacTypePatch and had great rendering with both DirectWrite apps and Notepad++. 

I am willing to help fix this and I am a developer too, just let me know what you need me to do.

**Comment by snowie2000** [comment]
Just add 
[experimental@webstorm.exe(or your program filename)]
ClipBoxFix=1
to your profile as I disabled this fix by default in the current version.

**Comment by JohnKoutsoumpas** [comment]
It worked great! Thanks :)
