### ISSUE TITLE
About translation 

### ISSUE THREAD

**Issue by kulaLin** [snowie2000/mactype#303]
作者你好。

你的軟體繁體中文是直接簡體轉繁體來的，用語尚未在地化。Really fully localized ?

由衷希望我能協助能夠處理在地化問題。

**Comment by snowie2000** [comment]
Fully localized only means that every string has a corresponding translation, no string is missing. But for accuracy, sorry to say that I have no guarantee.

I appreciate if you can help me translating it into Chinese traditional. :kissing_heart: 
Thanks in advance.

**Comment by kulaLin** [comment]
All right.

How should I do it now ?
