### ISSUE TITLE
MacType安装失败

### ISSUE THREAD

**Issue by weiLanhao** [snowie2000/mactype#304]
到最后一步，点击“安装”后，弹出对话框“是否取消安装”，
选择“是”就真的取消了，选择“否”就会回到选择安装路径的步骤。

之前的0904版本是通过原有的installer卸载的。
使用过“日本补丁”。
发现新版本不能安装后，又清理了注册表，
环境变量中和mactype相关的也清空了，
反复重启多次，还是不行。
然后发现老版本的安装包也不行了，一样的现象。

**Comment by snowie2000** [comment]
您可以尝试下微软出品的installer cleaner看看是不是installer存在注册表异常。

在 2017年6月21日 上午11:09，weiLanhao <notifications@github.com>写道：

**Comment by weiLanhao** [comment]
Windows Install Clean Up 用过了，没找到mactype

在 2017年6月21日 上午11:11，snowie2000 <notifications@github.com>写道：
