### ISSUE TITLE
要是出个portableapps的版本就好了

### ISSUE THREAD

**Issue by nobk** [snowie2000/mactype#306]
和自己惯用的字体以及浏览器等等portableapps一起放在u盘里随身带着，用一些不方便安装程序的临时机子的时候也有顺眼的字体上网了。

**Comment by snowie2000** [comment]
參見 https://github.com/snowie2000/mactype/issues/298#issuecomment-309625069

**Comment by nobk** [comment]
不对吧，怎和安装包数字签名的帖子合并了，portableapps只要遵循他们的程序格式规范就行了，和有没有数字签名没多大关系吧。
https://portableapps.com/development/portableapps.com_format

**Comment by snowie2000** [comment]
直接提供zip文档，即所谓绿色版使用。在仅使用托盘模式的情况下无需读写任何系统文件夹和注册表。
所以本身就没有必要使用任何第三方的绿化工具。
