### ISSUE TITLE
Mactype version 20170614 and 20170628 doesn't work on windows 8.1

### ISSUE THREAD

**Issue by rewindcat** [snowie2000/mactype#308]
I uninstalled the 20160904 version and deleted all files from C:\Program Files\Mactype\. then rebooted and installed the 20170628 version.

Clicking "run" after install completion leads me to an error window.
![notitle](https://user-images.githubusercontent.com/28673087/27627043-f5626392-5c1c-11e7-8266-9cd86fd970f2.png)

The “Mactype用户向导” window does show up sometimes but always stuck at "Generating Prewiew". And it constantly consumes a lot of CPU, which is definitely abnormal.

I uninstalled the 20170628 version, rebooted, and installed 20170614 version, got the same error.

20160904 version, the CTP version are both not compatible with Chrome 52+ on my machine with clean installed windows 8.1.

OS: Windows 8.1 UEFI without secure boot. All important updates from Microsoft are installed. Windows Defender with latest definition is used.

If more information is required, feel free to reply to me.

**Comment by snowie2000** [comment]
Please, do a uninstall and reboot and re-install. It's a bug of the installer.

**Comment by rewindcat** [comment]
Update: I uninstalled, rebooted, re-installed the latest version and granted _Everyone_ and _Users_ group full control privilege over C:\Program Files\Mactype folder according to previous issues.

After that the not-working problem seems solved, but contents in Chromium 61 dev looks to be not rendered by Mactype (though not crashing anymore), Chrome 50 with directwrite disabled is working fine.

_Pardon me for I'm not sure how to reply to a person in the Issue Tracker._

**Comment by snowie2000** [comment]
check this #301

**Comment by rewindcat** [comment]
After some experiments, I've found some clues.

As the latest Mactype release contain DirectWrite=1 and default settings for DirectWrite in default.ini, rendering for Google Chrome is working out-of-the-box and extra configuration may be not necessary, even when I renamed chrome.exe to chrome2.exe.

However similar browsers based on Chromium, like the one I downloaded from [here ](https://chromium.woolyss.com/) doesn't work with Mactype. I don't know why.


![sfhdbc angjobvetzw ob3](https://user-images.githubusercontent.com/28673087/27671192-c2b10b1c-5cc4-11e7-876b-19a3715cb28f.png)

Well this does not seem to be a problem caused by Mactype after all.

**Comment by snowie2000** [comment]
Well, I never tried Chromium browser. Maybe it uses other DirectWrite API to render.
As you may know, directwrite is a disaster. It exposes so many different text APIs to end user without having a unified low-level API, and it iterates itself and create new interface on almost every big windows update.
