### ISSUE TITLE
HintingMode=0 - Freetype v40 truetype interpreter

### ISSUE THREAD

**Issue by IceMan81** [snowie2000/mactype#309]
@snowie2000 Does hintingMode=0 enable usage of the Freetype v40 truetype interpreter?

**Comment by snowie2000** [comment]
It depends on what antialias mode you are using.
If you're using lcd mode, it will prefer to use embedded hinting rather than freetype hinting. 
If you're using light+lcd, it will always use freetype hinting.
Note: freetype hinter behaves differently under lcd and light+lcd.

**Comment by IceMan81** [comment]
I use a combination of HintingMode=0 & AntialiasMode=4 (light+lcd).
I don't understq how that differs from HintingMode=3 & AntialiasMode=4.
In FreeType 2.8, I believe the default is the v40 FreeType interpreter which enables sub-pixel hinting. So, would HintingMode=0 and AntialiasMode=4, enable this v40 interpreter?

**Comment by snowie2000** [comment]
I tried all the combinations and inspected the source. It seems that there is a long lived mistake made by someone that hintingmode actually only has 3 values: 0, 1, 2. (check line 16 of settings.cpp, you'll see hinting_max is 2 instead of 3). which means hingtingmode 3 is equivalent to 2.

I also checked the Antialiasmode and it looks identical with light and lcd now. I have no idea what's going on right now, they are definitely different before. :sob: I haven't changed these code for years and it is likely a freetype modification in the recent versions.

**Comment by IceMan81** [comment]
I had arrived at a similar conclusion here https://github.com/snowie2000/mactype/issues/186#issuecomment-258216217      
😁 
There were lot of changes in freetype since 2.6, with v40 truetype interpreter which enables sub-pixel antialiasing being made the default in 2.8. I think with HintingMode=0, it is using the freetype default interpreter. 

https://www.freetype.org/freetype2/docs/reference/ft2-tt_driver.html

**Comment by IceMan81** [comment]
@snowie2000 Btw, isnt the range for DirectWrite Contrast a value between 0 - 400. In mactype you have suggested a much smaller range. Are you scaling Contrast somewhere in the code?

**Comment by snowie2000** [comment]
I've looked into my freetype compilation option and confirmed that I only compiled autohinter v40 into mactype. Which means you can only use v40 engine to generate hinting for your font.
For contrast in DirectWrite, Microsoft has declared that it can only be a float between 0 and 1, however, mactype allows you to set up to 10.0 for contrast...
The directwrite behaves weird with such a large value, it's not recommended to exceed Microsoft's suggested range.

**Comment by IceMan81** [comment]
@snowie2000 Does that mean the contrast values in DirectWrite and General have different meanings? 
As per MSFT docs, In DirectWrite increasing Contrast means increasing the darkness of text. 
https://msdn.microsoft.com/en-us/library/windows/desktop/dd371290(v=vs.85).aspx

But the contrast in the General section has a different meaning - is my understanding correct?
https://github.com/snowie2000/mactype/wiki/Contrast

**Comment by snowie2000** [comment]
Contrast is mainly the difference between the light part and the dark part.
The description of the DirectWrite contrast provided by Microsoft is actually not correct.
![qq 20170630093210](https://user-images.githubusercontent.com/11767189/27717355-1bfe6cf2-5d77-11e7-9804-ef4711fe6517.png)
Above picture is a text test with contrast=10 on both DW and GDI. You can clearly see although the results are not exactly the same, they behave the same way - make the edge sharper. What's different is that by increasing contrast value, Microsoft emboldens the font while MacType only adjusts the edge.
