### ISSUE TITLE
FontSubstitutes does not work in DirectWrite. (1.2017.614.0)

### ISSUE THREAD

**Issue by wmdmf2003** [snowie2000/mactype#310]
In the latest release FontSubstitutes does not work in DirectWrite mode.
but, work in 2017.614.0 version.

**Comment by snowie2000** [comment]
I'm sorry. I forgot to mention it - it has been removed due to compatibility reason. It may back in the later release, I hope...

**Comment by extratype** [comment]
How about adding FontSubstitutes=1 parameter under DirectWrite section? Users may be able to workaround compatibility issues. For example, Chrome ignores substituted fonts in `font-family` property. A workaround is to substitute them via Stylish chrome extension with `@font-face`.
