### ISSUE TITLE
IntelliJ IDEA 界面文本被裁剪 (1.2017.628.0)

### ISSUE THREAD

**Issue by SilentDepth** [snowie2000/mactype#313]
Windows 10 (1703)
MacType 1.2017.628.0（内置 iOS 方案）
IntelliJ IDEA 2017.2 EAP

![snipaste20170630_230013](https://user-images.githubusercontent.com/7194254/27743569-08aed86c-5def-11e7-8c9f-09717808b077.png)

**Comment by snowie2000** [comment]
请参考wiki中的clipboxfix

SilentDepth <notifications@github.com>于2017年6月30日 周五23:52写道：

**Comment by SilentDepth** [comment]
在 iOS.ini 文件中添加如下配置并重新启用后问题解决：
```
[Experimental@idea64.exe]
clipboxfix=1
```
Problem resolved. Thanks!

**Comment by AnClark** [comment]
**建议置顶，让更多使用 JetBrains IDE 的朋友能看到。**
不过最根本的解决办法还是请开发者从根源上修复。
已知最新的2017/06/28版本有这个问题。

**Comment by snowie2000** [comment]
首先issue无法置顶。
其次这个问题实际上不是无法解决，而是解决方案有瑕疵，所以不能设为默认值。
根本原因是因为java（和部分程序比如picasa）他们显示字体的方式上的特点导致的，他们会精确的按照clipbox来裁切文字，而Windows的clipbox是按照hinting后的字体来生成的，mactype（默认情况下）生成的无hinting文字几乎在所有情况下都会比ClearType的hinting文字要大一点点，也就形成了你所看到的斩头斩脚。

问题在于简单的扩大clipbox的方法对IntelliJ之类的程序虽然是有效的，但是对另一些程序（如emacs）却是有害的，会导致他们在进行行高的计算等情况中出错，出现兼容性问题，所以目前为止，clipboxfix的方案依然是默认关闭项。

**Comment by AnClark** [comment]
多谢解答。期待MacType能更加完善。（对了，既然无法置顶的话，不妨加标签，如果可以的话。）
