### ISSUE TITLE
请教，想用其他ini，必须要按照Default.ini来编辑内容才行？？

### ISSUE THREAD

**Issue by jorismq** [snowie2000/mactype#314]
其他的ini都没有【DirectWrite】语句，我想用的话，是不是要按照新版的Default.ini来重新编写ini文件？？

还有，感谢大神的工作！！！

**Comment by snowie2000** [comment]
请参考这里编写https://github.com/snowie2000/mactype/wiki/DirectWrite-section
当然你也可以直接抄默认的。改成你自己看着舒服的就行了
