### ISSUE TITLE
strange performance issues

### ISSUE THREAD

**Issue by RitzyBusiness** [snowie2000/mactype#315]
On the latest mactype I've been getting performance issues when my PC has been running for a while or i've got a game up.  I noticed when I went into services and regedit, it took a long time for registry values to load.  As if its rendering the font verryyyy slowly.

**Comment by snowie2000** [comment]
Try disabling directwrite support as I only changed that part.

RitzyBusiness <notifications@github.com>于2017年7月1日 周六09:47写道：

**Comment by RitzyBusiness** [comment]
I must of disabled the right thing, have not had trouble for a while already.
