### ISSUE TITLE
Additional settings of about:flags in Chromium v.52 or newer at browsers with always enable DirectWrite

### ISSUE THREAD

**Issue by Twilightssuperb** [snowie2000/mactype#316]
Till Chromium reached v.52 and deleted flag # _disable-directwrite_, I should have disable DirectWrite and # _LCD-text-aa_ flags, set _number of raster threads_ to 1 for complete Mactype performance. But should I also disable # _LCD-text-area_ and set _number of raster threads_ to 1, while I can't turn off DirectWrite at newest browsers? I added DirectWrite=1 in my current Mactype profile. Looks like there is no need to interfere with about:fags now. 🤷‍♂️

**Comment by snowie2000** [comment]
Since MacType can only change some params of DirectWrite, I believe there is no need to touch any setting in chrome://flags.

**Comment by Twilightssuperb** [comment]
🆗, maybe you would add this thought in Wiki [here](https://github.com/snowie2000/mactype/wiki/DirectWrite)? I'm not sure, but some users can be confused...

**Comment by JonnyRedHed** [comment]
Can I ask,  for chrome based browsers, Chrome, Opera, Vivaldi.  What  chrome://flags should be left as default now with latest mactype release, which were previously advised to change.  Its been so long I forgot which ones were changed.

**Comment by snowie2000** [comment]
No additional settings besides DirectWrite disabling is required. Changing "raster threads" to comply with MacType is an outdated hack related to a bug which has been fixed by latest release.
