### ISSUE TITLE
我发现628版除了Default.ini，其他的ini都和以前的版本一样啊！大神啥时候能更新下不？

### ISSUE THREAD

**Issue by jorismq** [snowie2000/mactype#318]

**Comment by snowie2000** [comment]
不会更新的，其他配置都是给你当样例用的，而且并非来自我

jorismq <notifications@github.com>于2017年7月2日 周日17:23写道：

**Comment by jorismq** [comment]
就是说大神只维护Default.ini，其他的ini我按需要抄写就行了是吧

**Comment by snowie2000** [comment]
其他配置其实来自xhei的作者和以前的gdi++，一般我只维护那个默认的.

jorismq <notifications@github.com>于2017年7月2日 周日17:26写道：
