### ISSUE TITLE
Cause explorer.exe crashed on boot

### ISSUE THREAD

**Issue by Mahayu** [snowie2000/mactype#319]
Environment : Win10 14393
              Mactype v1.2017.628.0 , registry mode.

the explorer.exe can't start on these conditions sometimes. When trying boot from taskmgr, it returns with error.

**Comment by snowie2000** [comment]
Don't use registry unless you have to.

**Comment by IceMan81** [comment]
Why do you say that? On win 7, I thought that using registry mode was
better for performance

**Comment by snowie2000** [comment]
Sure, registry mode gives you best performance, but it is a non-selective mode, meaning every possible process will load mactype.
MacType is known to have some compatible issue with antivirus software. Besides, its compatibility with windows bootloader is unknown. MacType runs with assumption that the Win32 GUI system is up while in boot up stage, the criteria may not meet which may cause a crash and what's worse is that there is hardly anyway to debug it.

**Comment by JonnyRedHed** [comment]
@snowie2000 

So for windows 7 what would be your current best option you would choose if installing your latest release. For least hassle day to day usage.

**Comment by snowie2000** [comment]
I always prefer to run in tray mode, but I do believe the service mode is as stable as tray mode.

**Comment by JonnyRedHed** [comment]
I tried the typical install of latest release.  But its not wanting to change to Win7 Opt.  A small pop up window down by the system tray icon says cannot start mactype. And if I try and change to win7opt via right click the mactype icon in system try I get a windows popup application error.

Exception EAccess Violation in modual MacTray.exe at 00000000. Access violation at address 0000000. Write of address 00000000.

**Comment by snowie2000** [comment]
You encountered the installer bug. Please uninstall, reboot and re-install.

**Comment by JonnyRedHed** [comment]
It won't let me uninstall it.  I just get the installer again and this time with no English option so I cannot tell whats going on.

**Comment by snowie2000** [comment]
Use any mode as your wish. It's a known bug for advanced  installer and I don't know how to avoid it...
Sorry for that.

**Comment by JonnyRedHed** [comment]
And I can try `--disable-direct-write --disable-directwrite-for-ui` for Opera/Vivaldi/Chrome.   Brave browser also?
