### ISSUE TITLE
MacType doesn't start on boot

### ISSUE THREAD

**Issue by Gino** [snowie2000/mactype#320]
Hello,

I thought MacType would always start on boot, unfortunately it doesn't anymore after the last update.
I tried to make a shortcut and copy it to the startup folder (CTRL + R and then "shell:start"), but it still doesn't start on boot.

Is there another way to get it started on boot?

Thanks

**Comment by snowie2000** [comment]
I didn't make any big change on mactray.exe. However, there are a few scenarios that mactray won't auto start.
1. If you check "run as administrator" on mactray property and run Windows with UAC enabled, Windows will refuse to autorun such a shortcut.
2. blocked by antivirus software.
