### ISSUE TITLE
最新版628不能渲染UWP应用，比如 设置、应用商店等

### ISSUE THREAD

**Issue by vDeepblue** [snowie2000/mactype#321]
系统为Win10最新版1703，求解决办法

**Comment by snowie2000** [comment]
您必须安装在默认路径或者system32（如果您愿意），否则一律不能渲染。
若已经在默认路径，很抱歉无法解决。这个和系统环境有关，需要您自行排除。

**Comment by vDeepblue** [comment]
好吧，那看来我得自行排除了，不过可能造成不能渲染的原因大概有哪些呢？

**Comment by snowie2000** [comment]
我也不清楚，我本身并不用win10，只是有一个虚拟机用来测试而已。

**Comment by vDeepblue** [comment]
噢噢，好的，多谢！
