### ISSUE TITLE
最新版对于win10的vscode还是不起作用么

### ISSUE THREAD

**Issue by muzichen** [snowie2000/mactype#322]

**Comment by gitlikang** [comment]
旧版本VisualStudioCode可以关闭DirectWrite技术，可以去尝试。

snowie2000说过基于DirectWrite技术的软件，考虑到兼容性问题，暂时移除了字体置换功能。

**Comment by Mahayu** [comment]
VS Code 于 1.14.1 正式版可以通过 `--disable-directwrite-for-ui --disable-directwrite` 指令关闭
DW。

**Comment by Mahayu** [comment]
你是要改变字体还是要改善渲染效果？
如果是想要改变字体的话，使用这个插件：
https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css
或者是在市场内搜索 custom css 插件来自定义 css 以改变字体.

如果想要稍微改善一下渲染效果的话，可以试试利用这些（快捷方式-目标+空格）
`--disable-directwrite-for-ui` `--disable-directwrite`
希望对你有用~

**Comment by thomasklash** [comment]
https://github.com/thomasklash/vscode-mactype-hack

**Comment by sammilucia** [comment]
duplicate of #401, now that vscode / Chromium / Electron only support DirectWrite... this is now a "how to work better in directwrite" question
