### ISSUE TITLE
Unable to uninstall MacType

### ISSUE THREAD

**Issue by Jeremiidesu** [snowie2000/mactype#323]
I've tried to uninstall MacType recently only to find out it only somewhat *reinstalled* the software (MacType 1.17.0628 according to Programs and Features)

Any idea what can be causing this?

**Comment by snowie2000** [comment]
Grab a installer from mactype.net and uninstall with it.

**Comment by catamphetamine** [comment]
Also make sure to exit all MacType-enabled applications before doing that.
E.g. I had Chrome run in "manual" mode through drag-and-drop and it returned an error "MacWiz exited prematurely", then I closed Chrome and it uninstalled without errors.

**Comment by alecpermison** [comment]
Doesn't work. The uninstaller doesn't let you unclick the whole program. Plus instructions are only in Japanese. Bottom line: can't get this off of Windows 10.

**Comment by naomeh** [comment]
What uninstaller? That only downloads the installer.
The installer only offers the option to reinstall the program. There is no option to uninstall it.

I had to forcefully and manually uninstall/delete this in the registry, files, etc. It absolutely refuses to uninstall otherwise.

**Comment by alecpermison** [comment]
Yup you are right. I did the same. I think that makes Mactype a bit suspicious.

**Comment by connor-minton** [comment]
I had the same issue. Resolved by following the steps in the "Uninstall MacType" section here: https://www.addictivetips.com/windows-tips/get-macos-like-smooth-fonts-on-windows-10/

Basically, look for a program under the MacType folder in the start menu with a recycle bin icon.

**Comment by Yoselintp** [comment]
Realizar este procedimiento me funcionó con el programa Revo Uninstaller
Les dejo el link donde explica paso a paso con ejemplos desde su descarga hasta la desintalación completa.
http://www.forospyware.com/t243205.html

También el link de descarga del programa para desinstalar
https://www.infospyware.com/herramientas/revo-uninstaller/

Saludos.

**Comment by PayneLessDesigns** [comment]
Update 2 June 2018; Download the latest INSTALL program (MacTypeInstaller_2017_0628_0.exe was mine) from mactype.net. Run the downloaded install program. It should come up with a window indicating you can: Install, Repair, or, Remove. When I clicked Remove, it did a clean uninstalled.

**Comment by sammilucia** [comment]
Duplicate of #428.
