### ISSUE TITLE
请问 DirectWrite 下的字体渲染效果会改进吗？

### ISSUE THREAD

**Issue by YihangFu** [snowie2000/mactype#324]
非常感谢您的作品。
最新版本的 MacType 加入了对 DirectWrite 的支持，但在我的 PC 上 DW 部分的效果距离正常渲染差距不小，为此正在考虑更换掉 Chrome 浏览器，请问 MacType 会在新的版本中进行调整吗？

**Comment by snowie2000** [comment]
很抱歉暂时不会。由于微软的DW也一直在进步，并且替换DW的难度较大，短时间不会有什么大的改动，只是对微软原生DW进行参数调整。随着Win10的快速迭代，DW应该会越来越好吧。
