### ISSUE TITLE
Cent browser & --disable-directwrite-for-ui

### ISSUE THREAD

**Issue by Jigsaff** [snowie2000/mactype#325]
My Cent Browser (2.6.5.52 (64-bit) (Chromium 58.0.3029.110)) does not react on --disable-directwrite-for-ui since I installed (fresh install) MacType v1.2017.628.0. As well as on #disable-direct-write.

In my Win7 new MacType works perfect except Cent Browser. What's wrong? Default profile is used.

**Comment by adelduprat** [comment]
You'll have to use [MacType Patch](https://silight.hatenablog.jp/entry/MacTypePatch).

**Comment by adelduprat** [comment]
You'll have to use [MacType Patch](http://silight.hatenablog.jp/entry/MacTypePatch).

**Comment by snowie2000** [comment]
@adelduprat What a advertise, there is nothing related.

The DirectWrite of Cent browser can be entirely disable by toggle off #disable-direct-write. Both UI and web content. You don't need that command line. But the reason it's not affected remains unknown to me.

**Comment by adelduprat** [comment]
@snowie2000 Well, that's how I made it work for me. YMMV.

**Comment by sammilucia** [comment]
--disable-directwrite-for-ui is no longer required for CentBrowser latest (3.5.3.50). Closing issue.
