### ISSUE TITLE
当启动Mactype时，使用远程桌面会出现设备声音无法播放的现象

### ISSUE THREAD

**Issue by JiongDream** [snowie2000/mactype#326]
其实这个现象已经出现了很久，到现在的1.2017.628.0貌似都没有修复
在未安装Mactype前，我使用微软的Microsoft Remote Desktop进行远程桌面连接，可以正常播放设备声音。而在我安装并启动后，使用远程连接就会出现无法播放设备声音的问题。在排查后，发现为Windows Shell 公用 DLL 出现问题。
这并不是我使用的Insider版本(Build 16193)问题，在Build 14393下，安装Mactype后我在远程桌面依然无法播放设备声音并出现Windows Shell 公用 DLL 已停止工作的问题。
不知道这个问题有没有被反馈过，望修复。
附截图信息：http://imgur.com/a/udgSc

**Comment by snowie2000** [comment]
当程序崩溃的时候应该会在事件日志中记录一个错误信息，并生成一个minidump，一般来说会存在这个路径下： C:\Users\用户名\AppData\Local\CrashDumps，如果您能上传给我的话，可以让我尽可能的定位问题，谢谢。

**Comment by JiongDream** [comment]
回复作者大大：
我尝试获得错误信息，但是我无法找到此文件夹以及生成的minidump:(
事件查看器中有很多错误报告，但我无法分辨。在事件中一共出现了四个文件，分别为AUDIODG.EXE，vorbis.acm，rundll32.exe，shell32.dll。
待会会尝试一下卸载音频驱动后再重新测试

**Comment by snowie2000** [comment]
具体minidump在哪里我只是按照我自己的电脑找的，我也不是特别清楚。
最好是出错后立刻去看事件日志，应该最近的一次就是。

**Comment by JiongDream** [comment]
上传了一份出现错误后的事件日志，不知道能不能用
https://mega.nz/#!GcAEXDjD!ry_3zQ87ZZNxJjfYO98Ksl2dItiFQ3TWjIkcXzUOi6c
另外尝试卸载音频驱动后再次测试依然是同样的情况。。

**Comment by snowie2000** [comment]
从日志上看问题是出现在system32\vorbis.acm这个文件，我搜索了下，是
 Ogg Vorbis Audio codec for MSACM from HMS 

其他问题无法从日志中看出来了。

**Comment by snowie2000** [comment]
这似乎是一个已知问题：
https://social.technet.microsoft.com/Forums/lync/en-US/9afd47d7-7f4e-4acc-9d88-8497ae94d92c/remote-desktop-crashes-when-vorbisacm-is-present-win-81-x64?forum=winRDc

**Comment by JiongDream** [comment]
好的，谢谢snow大神的解答，之前一直认为是Mactype的问题= =不好意思麻烦您了。
