### ISSUE TITLE
在控制台方，沒有解除安裝的選項

### ISSUE THREAD

**Issue by cool91788** [snowie2000/mactype#328]
無意中發現

win10 1703

直接使用installer可以執行反安裝，

不過如果透過控制台那邊的話，會變成全新安裝嚮導

**Comment by snowie2000** [comment]
安裝程式已知bug，不知道如何解決…………

**Comment by cool91788** [comment]
同串在回報一下...
自訂安裝若勾選「XMAC 系列設定檔」

啟動後會crash，不知道是不是我本身環境的問題？
Access violation at address 004EE484 in moudle 'MacTray.exe'.
Read of address 00000000.

**Comment by snowie2000** [comment]
這個和你選擇了什麼並沒有關係，只是安裝程式的一個bug，你重啟後再安裝就不會有問題了。
