### ISSUE TITLE
Win 10 1703无法使用注册表加载MacType 20170628

### ISSUE THREAD

**Issue by TianLi-520** [snowie2000/mactype#329]
开始的时候用之前的版本，注册表加载可以正常渲染，重启系统后无法渲染，必须重新运行设置向导，先设置托盘加载，再改为注册表加载
更新20170628后，设置注册表加载就直接失效，正常渲染的情况下直接就变成无渲染了

**Comment by snowie2000** [comment]
在开启Secureboot的情况下，注册表加载无效，无论你是重启还是先设置托盘加载都永远无效，这是微软的设定。如果之前能渲染，那纯属bug而已。
macwiz部分代码一字未动。
