### ISSUE TITLE
Profile issue

### ISSUE THREAD

**Issue by Antiever** [snowie2000/mactype#332]
After installing, I have replaced the ini file with a older version and I counted on an identical look 
But something goes wrong...

# New  |  Old
![1](https://user-images.githubusercontent.com/9666515/27917541-f4c1de64-6274-11e7-9b27-ac014f2b53d6.png)

### Desktop icons:
# Old  |  New 
![2](https://user-images.githubusercontent.com/9666515/27917546-f8caafa4-6274-11e7-93aa-a06225945f39.png)
And many more things now looks not the way I like.
It's the first version with which I have so many problems...

### **And one more thing** - where I can get info about right way to add exclusions?

**_There is:_**  
- [Exclude] 
- [ExcludeModule] - _not sure what the difference_
- [System Process] - _isn't it supposed to be = Exclude?_ 
- [UnloadDll] - _what another fallback exclude or what?_
- [ExcludeSub] - _have no idea what is it :)_

**Comment by snowie2000** [comment]
Ok, I'll try to explain some of them:
First, I upgrade freetype to the latest version - 2.8.0. Every version of freetype may change its result a bit, someone may like the change, others may not. Anyway, you ( and I ) have no other choice but accept.

Here is the description of the exclusion options:

[Exclude] - does not exist.

[ExcludeModule] - processes listed here will not be rendered, but mactype.dll/mactype64.dll will still be loaded to make "HookChildProcess" option working. i.e. the child process started from excluded process will still be rendered without any delay.

[System Process] - does not exist

[UnloadDll] - processes listed here will not be rendered nor will it load any mactype files. MacType is completely disabled for those processes. All child processes launched by it will not be rendered until mactray.exe detect them ( you will see  a significant delay of rendering )

[ExcludeSub] - processes listed here will still be affected by MacType, however fontsubsitution will not work on them.

**Comment by Antiever** [comment]
**Thanks for the explanation!**
So the only way to get old look - downgrade back to  2016.0904, right?

> [Exclude] - does not exist
> [System Process] - does not exist

Is it also true for 2016.0904?
And if not, could you give some info about

**Comment by snowie2000** [comment]
There is another way: compile with old freetype by yourself.

It's true for all versions.

**Comment by Antiever** [comment]
Ok I get it. Thx.

**Comment by Antiever** [comment]
I've tried to build latest solution with VS2015 to get old freetype back and looks like it will be not so easy...
Then I decided to forget this idea and just downgrade to 1.2016.904.0 but something strange happened:

```
Bad or empty value (name: "PackageName", value: "") in 
"HKLM\Software\Classes\Installer\Products\5090CFDBC67D9E746A90386953DBE913\SourceList"

MacType 安装程序在安装此程序包时遇到了错误。可能表明此程序包有错。错误代码是 2755 : 1610, T:\Temp\MacType\install\8E66446\mactype.x64.msi

0000   7B 35 45 37 41 37 45 43 39 2D 45 37 35 42 2D 34    {5E7A7EC9-E75B-4
0010   32 42 31 2D 38 41 41 31 2D 44 39 41 32 39 38 45    2B1-8AA1-D9A298E
0020   36 36 34 34 36 7D                                  66446}

```
**All other** installer works fine (even old 2012 and 2013) but 1.2016.904.0 shows this error and quit...

So I have to ask you for a big favor - could you compile 1.2017.628.0 with old freetype (I think I am not the one who would like this) or help me to solve installer issue. 
I really like the work that you did with MacType and I would like to get from this wonderful program best that it can give.
I would be very grateful for your help

**Comment by snowie2000** [comment]
I don't remember the freetype version I was using with 2016.904.0.

**Comment by Antiever** [comment]
I get your point.

Ok, so I was able to install `1.2016.904.0` on my Win10 virtual machine, what about replacing whole `\Program Files\MacType` folder on my Win7 host to folder from guest, I suppose it will do the trick (in fact equal to proper downgrade)?

There is 3 extra files

![bcompare_2017-07-13_06-42-27](https://user-images.githubusercontent.com/9666515/28149577-637622b2-6797-11e7-8afc-d76e506fd97a.png)

I guess they belongs only to newest version and won't affect anything if full replacement deletes them.
What do you think about that "method of install", will it work?

**Comment by snowie2000** [comment]
These two dlls are not used. The exe is useful to load 64bit executables and it useless if you don't need that feature.

**Comment by Antiever** [comment]
> exe is useful to load **64bit executables**

What do you mean? 
I just replaced folder on live system and looks like everything is ok (_I finally get my favorite font render look back!_) and mactype working for x86 **and x64 processes as well**. I hope there will be no surprises after reboot, and if not - job is done.

**Comment by snowie2000** [comment]
The macloader.exe and macloader64.exe are for manually load mactype by drag-drop. All other automatic modes don't rely on them.
