### ISSUE TITLE
使用idea时字体显示被截断了,用potplayer播放mkv电影,加载内嵌字幕出现机器卡顿的现象

### ISSUE THREAD

**Issue by asiaon123** [snowie2000/mactype#333]

**Comment by snowie2000** [comment]
你在使用日本的补丁吗？如果是的话请删除。

**Comment by asiaon123** [comment]
@snowie2000 如果对于多个jetbrains家族的产品呢？ 要分别加上配置吗？

**Comment by snowie2000** [comment]
你要不担心兼容性问题你也可以直接把clipboxfix放在experimental下面，而不使用按应用配置。

**Comment by asiaon123** [comment]
Tks

**Comment by asiaon123** [comment]
UWP打不开的概率很大啊,而且时常崩溃

**Comment by snowie2000** [comment]
请详细给出你的环境，配置，是否安装了patch

**Comment by asiaon123** [comment]
环境:win10 1703最新版, Default 配置, 没有使用patch

**Comment by snowie2000** [comment]
32还是64位系统

**Comment by asiaon123** [comment]
64bit

**Comment by asiaon123** [comment]
![default](https://user-images.githubusercontent.com/5396968/28112156-93d33138-672a-11e7-8500-c4c7b5560953.PNG)
请问chrome中这种字体发虚有什么解决方案吗？

**Comment by neoherus** [comment]
宋体就是这样，你用个字体替换的配置文件替换成黑体类的

**Comment by asiaon123** [comment]
请问下具体怎么操作？怎么替换字体？

**Comment by snowie2000** [comment]
chrome可以直接指定字体，也可以使用css

**Comment by asiaon123** [comment]
好的,我制订了为微软雅黑,但是似乎网站的css采用了默认宋体,所以还是没有效果,是我的设置方式不对吗?

**Comment by asiaon123** [comment]
我刚刚禁用网站默认的css字体,变得好看了,但是并不能每次打开都要去禁用一下,所以请问下有什么更好的解决方案吗?

**Comment by hyrious** [comment]
@asiaon123 [Stylish](https://userstyles.org/) 加一条 `* { font-family: SimSun !important }` （逃

**Comment by asiaon123** [comment]
在我的电脑上 貌似 sans-serif很好一点,但是我并没有采用

**Comment by asiaon123** [comment]
我安装试了一下发现对于字体icon会有side effect

**Comment by snowie2000** [comment]
以上的css貌似是错误的，

**Comment by neoherus** [comment]
安装一个chrome扩展：Stylish，在里面搜索配置：mactype

**Comment by kokutoukiritsugu** [comment]
* { font-family: "微软雅黑" !important }

**Comment by AnClark** [comment]
**IDEA的那一帖建议置顶，让更多使用 JetBrains IDE 的朋友能看到。** 理论上全系列 JB IDE 都会中招。
不过最根本的解决办法还是请开发者从根源上修复。
已知最新的2017/06/28版本 MacType 有这个问题。

**Comment by snowie2000** [comment]
https://github.com/snowie2000/mactype/issues/313#issuecomment-323002611

**Comment by sammilucia** [comment]
Updated release notes to include how to use clipboxfix per #313 https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4
Closing.
