### ISSUE TITLE
Can Mactype support Opentype font?

### ISSUE THREAD

**Issue by likesoap** [snowie2000/mactype#335]
I am new to mactype and I was trying substitute system font with Noto cjk font (OTF font) however I always failed.

I later came to the understanding that TTC fonts would have worked after downloading the XXX LOF family fonts. I wonder if OTF fonts are not supported (At least under 'FontSubstitutes' section)

Thanks.

win 10: 1703: build: 16237.1001
MacType版本:	1.2017.628.0
MacTray版本:	1.0.5.2048
MacTuner版本:	1.0.2.350

**Comment by snowie2000** [comment]
Please upload the font so I can check it.

**Comment by likesoap** [comment]
Thanks a lot in advance for looking into this, here is the URL to the font family.

https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip

For other fonts you might wanna check out "https://www.google.com/get/noto/help/cjk/"

--Likesoap

**Comment by extratype** [comment]
I put quotes around the font name in FontSubstitutes section and it didn't work. It worked when I removed the quotes.
