### ISSUE TITLE
Restart in Registry mode

### ISSUE THREAD

**Issue by Antiever** [snowie2000/mactype#336]
Lets say that we have app crashing with Mactype (which is quite common) and we want to add it to ini file but in registry mode there is no way to (restart mactype) force it to reload the config, right?
The only way I know is:

![untitled](https://user-images.githubusercontent.com/9666515/28121197-ffe2da8e-6722-11e7-828b-e94a095b186a.png)

or I miss something?

**Comment by snowie2000** [comment]
This is simple. Just launch wizard, select a profile other than your in use
profile, click next to apply it and select back to your profile and apply
it.

**Comment by Antiever** [comment]
That solution is little bit faster
Thx

**Comment by snowie2000** [comment]
Also, there is another solution.
Launch wizard, click process manager, hold shift key and you'll the stop
button turns to stop all. Click it to unload mactype from all processes and
load it again by same method.
