### ISSUE TITLE
MacType Can't be disabled 

### ISSUE THREAD

**Issue by manskou** [snowie2000/mactype#339]
Hello,
I've enabled MacType through registry and even with an uninstall I seem unable to disable it!

I'm using the latest version, and I am 100% sure it's still running because Photoshop Crashes on launch (and the fonts are visibly altered).

I really can't understand how this could be possible, as every file in the MacType install dir was deleted (except from the inis)

I also tried to swich the mode from registry to manual but nothing.

Just to note, I'm on Windows 10 Creators Update (possibly a few minor updates after that...)

Edit: *I think* the problem is that I enabled it through registry, I am not sure tho, since all services seem deleted/disabled.

**Comment by Mahayu** [comment]
Check for registry by `regedit.exe` and see if there is any appinit that wasn't deleted.

**Comment by manskou** [comment]
by searching for `appinit` in the registry I came up with nothing related to MacType (most of them were MSOffice telemetry). Do we know what changes does MacType do exactly and where?

**Comment by snowie2000** [comment]
Then your problem is caused by something else.

**Comment by manskou** [comment]
I am stupid, I had the GDIPP service running the whole time.
Sorry for the inconvenience.
