### ISSUE TITLE
今早遇见每次重启蓝屏 卸了以后就没事了

### ISSUE THREAD

**Issue by asiaon123** [snowie2000/mactype#341]
defalut配置,注册表加载, 64位系统, 没用补丁, 而且一直有的一个问题就是对于UWP的新界面,总是会出错,比如设置,右通知栏,点开的话要么闪退,要么空白

**Comment by snowie2000** [comment]
没有足够自信请不要使用注册表模式
请把配置发一下，谢谢

**Comment by asiaon123** [comment]
具体什么配置？
没有修改任何东西，default的配置

**Comment by snowie2000** [comment]
是否替换过字体，另外请关掉注册表模式再看。注册表模式和很多系统级软件可能会冲突，这毫不奇怪。

**Comment by asiaon123** [comment]
没替换过字体，晚上回去试一下注册表模式

**Comment by asiaon123** [comment]
还是不太好使, 对于UWP的,设置都打不开,右边通知中心页不行

**Comment by snowie2000** [comment]
关掉DirectWrite再试试

YaZhou Gu <notifications@github.com>于2017年7月17日 周一20:08写道：

**Comment by sammilucia** [comment]
Closing as this issue is resolved in the latest build. Also please use Service Mode for Windows 10 as per the latest release notes https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2
