### ISSUE TITLE
Please help explain option: 文字边界设置.

### ISSUE THREAD

**Issue by likesoap** [snowie2000/mactype#342]
Dear fellas,

Could someone help explain the options we have under the following section in the default.ini file? I am using v1.2017.628.0 released.

;【文字边界设置】
;数字越大越强调背景（类似文字边界被侵蚀的感觉），强调背景会有中字体锐利的感觉。适当降低对比度，提高TextTuning，可以使文字周围的颜色看起来“淡一点”
;再加上RenderWeight，把这三个设置的微妙平衡调节好的话，能得到不输给Mac的效果
0:12

It seems the format of this tweaks are number:number but I have no idea how much to put in. Any best practice/good known sample are greatly appreciated.

--Likesoap.

**Comment by snowie2000** [comment]
No, it's not a number:number format. I think there is unicode display problem with your notepad.
it is actually a range, from 0 to 12.
Check wiki: https://github.com/snowie2000/mactype/wiki/RenderWeight

**Comment by likesoap** [comment]
Thanks a lot!!!!

**Comment by likesoap** [comment]
indeed, It was the freaking font I used in my notepad ++ ... Sorry for the trouble caused.
