### ISSUE TITLE
你好, 0628版本  Win10 1703 设置等UWP界面闪退

### ISSUE THREAD

**Issue by zh0122** [snowie2000/mactype#344]
系统: win10 1703
mactype: 0628

打开win10的设置等界面时, 有时可以打开, 有时闪退, 试过两台电脑, 4种加载模式都试过, 都是这样, 请教如何修改可以修复? 谢谢!

**Comment by snowie2000** [comment]
关掉DirectWrite支持试试看吧。我没有什么好办法。

**Comment by zh0122** [comment]
可以了, 谢谢
