### ISSUE TITLE
提示environment error, please check your system

### ISSUE THREAD

**Issue by goldmonkey163com** [snowie2000/mactype#346]
提示environment error, please check your system，用以前的版本也这样，win7的64位系统，运行库从2005到2017都打了。。。这是为什么？
![2017-08-01_090952](https://user-images.githubusercontent.com/21063655/28805587-c3517df2-769d-11e7-8908-fe26a1d45b18.png)

**Comment by snowie2000** [comment]
检查您的环境变量，可能存在mactype相关名称的变量了。

**Comment by goldmonkey163com** [comment]
@snowie2000 我把我所有环境变量都打出来了，感觉找不到您说的：

```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\zy>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\zy\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=ZY-THINK
ComSpec=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\zy
LOCALAPPDATA=C:\Users\zy\AppData\Local
LOGONSERVER=\\ZY-THINK
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\zy\OneDrive
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32
\WindowsPowerShell\v1.0\;;e:\Program Files (x86)\Microsoft VS Code\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3a09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\zy\AppData\Local\Temp
TMP=C:\Users\zy\AppData\Local\Temp
USERDOMAIN=ZY-THINK
USERNAME=zy
USERPROFILE=C:\Users\zy
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
_DFX_INSTALL_UNSIGNED_DRIVER=1

C:\Users\zy>
```

**Comment by sammilucia** [comment]
Hi @goldmonkey163com , did you ever manage to resolve this?

**Comment by goldmonkey163com** [comment]
@sammilucia No. I checked environment variable as he said, but I cannot find the reason.

**Comment by sammilucia** [comment]
Okay thanks @goldmonkey163com ... That string ("Environment error, please check your system") is hard-coded into MacWiz.exe's own error handlers...

I'll leave this here for snowie to have a look or @snowie2000 grant me access to MacWiz source and I can debug.

**Comment by snowie2000** [comment]
@sammilucia It's a string hardcoded into the MacTuner instead of the macwiz.
Here is the basic principle:
To use the tuner to tweak/create a profile, the Tuner must be accessible by the MacType, however, for some reason, users may choose to use include-only mode, or they may have mistakenly written the mactunner.exe into the unloaddll/exclude list so that the tuner can no longer get rendered by MacType.

To force mactype to render the tuner, a special environment will be created, and the mactuner will spawn itself as its child process to inherit the environment so that it gets the environment from the very beginning since MacType only checks the environment before the process actually starts to run.
If MacTuner child process failed to detect the environment variable, it responses to you with that error message and there is no way to walk around it.

**Comment by sammilucia** [comment]
Yes sorry meant MacTuner... thanks for the explanation.. I wonder if it's a permissions problem then.

**Comment by goldmonkey163com** [comment]
I wonder if it is useful to send you the records on MacTuner.exe by Process Monitor. If it's convenient, can I have your email address? @sammilucia @snowie2000

**Comment by snowie2000** [comment]
mailto:mactype.feedback@gmail.com
or use the link in my bio profile.

**Comment by sammilucia** [comment]
Resolved by https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4. Please let us know if problems continue. Closing issue.

**Comment by goldmonkey163com** [comment]
The problem continues with the new release. I wonder if there is anything I can provide. @snowie2000 @sammilucia

**Comment by snowie2000** [comment]
Provide your profile and you can use process explorer to check if `mactype.dll` and `mactype.core.dll` has been loaded by mactuner.

**Comment by goldmonkey163com** [comment]
I use the new release by uninstalling the old one first and installing a new one, so there is no specific profile I can provide. As I said in the new email, it seems that mactray.exe has something wrong.

**Comment by snowie2000** [comment]
Okay... I forgot that I had the same design in the tray app.
Try this one.
[MacTray.zip](https://github.com/snowie2000/mactype/files/2501223/MacTray.zip)

**Comment by goldmonkey163com** [comment]
Thank you very much, it is perfect now @snowie2000

**Comment by snowie2000** [comment]
Then what do you mean by "something wrong"

goldmonkey163com <notifications@github.com>于2018年10月22日 周一19:27写道：
