### ISSUE TITLE
v20170628发现没法渲染Steam

### ISSUE THREAD

**Issue by githubhao0705** [snowie2000/mactype#347]
你好，snowie2000，我是今天发现有更新的，在更新前是使用的v20160904，再加上MacType_CTP_170307_W10和MacTypePatch_1.26，装后续这两个主要是为了能够成功渲染windows10的设置界面。

当前的电脑版本是：Windows 10 1703
OS版本：15063.483

我使用的字体一直都是IOF字体集中的“XHei lntel”，无论是更新之前还是更新之后，而配置文件我是使用的安装MT后自带的对应字体的设置文件。最后我会贴出我更新之后的配置文件（其实与默认相比就只是设置了DirectWrite=0）。

更新了v20170628，发现设置界面没法渲染，经过这许久时间，也无所谓了，因为凡事没有完美，于是打开steam打算开始游戏，发现steam竟然都无法渲染了。而GrimDawn（译名：恐怖黎明，一个游戏）也无法成功渲染了。

说是更新，其实我是删除了所有存留文件，再重新安装的v20170628，并没有添加CTP和MTP。

最后请问是否可以顺利渲染呢？还有感谢你所编写的MacType，它帮助了我很多年，字体显示非常棒！祝你一切安康。

; ----------------------------------------------------------------------
; XMac
; (Only for MacType, NOT SUPPORT THE OLD VERSION OF GDI++/HE)
;
; maxchow@qq.com
; QQ Group: 18988755
; ----------------------------------------------------------------------

[Preview]
Font=XHei Intel
Color=$990088
Text=热替换为 XHei Intel
Size=11
Align=Center

[General]
Name=XHei Intel
Icon=IoF\XHei.ico,0

;【自动挂钩子进程】
;[0:Disable]  1:Enable
HookChildProcesses=1

;【字体微调】
;0:Normal 1:NoHinting 2:AutoHinting 3:Light+AutoHinting
HintingMode=1

;【抗锯齿方式】
;-1:Disable 0:Normal 1:Light 2:LCD(RGB) 3:LCD(GBR) 4:Light-LCD(RGB) 5:Light-LCD(GBR)
AntiAliasMode=2

;【常规体调整】
;-32:+32
NormalWeight=16

;【粗体字的调整】
;-16:+16
BoldWeight=2

;【斜体字的倾斜角度微调】
;-16:+16
ItalicSlant=0

;【只有在FontLoader=0（在下面）时此项设置才有效。建议选0，选1会占用大量内存，也没看出有什么好处。】
;0:Disable 1:Enable
UseMapping=0

;【Gamma模式开关】
;-1：关闭；0：使用设置的Gamma值（GammaValue）；1：使用sRGB的Gamma值；2：不明
GammaMode=0

;【Gamma值】
;GammaMode=0的时候此项设置才有效
;Windows的ClearType的Gamma值是1.4
;OSX标准级Gamma值是1.8，电视级Gamma值是2.2
GammaValue=1.4

;【对比度】
;数字越大越锐利，数字越小越发虚
Contrast=1.4

;【字体轮廓】
;数字越大字体就越粗越黑
RenderWeight=1.2

;【文字边界设置】
;数字越大越强调背景（类似文字边界被侵蚀的感觉），强调背景会有中字体锐利的感觉。适当降低对比度，提高TextTuning，可以使文字周围的颜色看起来“淡一点”
;再加上RenderWeight，把这三个设置的微妙平衡调节好的话，能得到不输给Mac的效果
;取值范围：0~12

;当AntiAliasMode=1时，通过TextTuning分量来调节
TextTuning=0
;当AntiAliasMode=2时，通过TextTuningR/G/B三个分量来调节
TextTuningR=2
TextTuningG=2
TextTuningB=2

;【字体加粗模式】
;对NormalWeight和BoldWeight有效
;0：Weight值大时横向加粗，值小时双向加粗，主要是避免Weight值过大时，模式3中在小字号时加粗过度出现斩头的现象；
;1：总是横向加粗；
;2：总是双向加粗，也就是freetype本身的粗体渲染。
;注意：通过加大GammaValue、TextTuning的值，可以减少Weight值过大的造成的效果问题，即可以在BolderMode=2时也可以避免斩头
BolderMode=0

;【字体的载入方法】
;（注意是载入方法，不是渲染方法）
;0：用freetype载入字体
;1：用windows的绘图核心载入字体
;很多freetype的设置需要此项选0才能生效
FontLoader=0

;【字体链接】
;当FontLoader=0时
;0：什么都不做；
;1：使用注册表里的字体链接设置，通过FreeType的字符表进行查找
;2：使用注册表里的字体链接设置，使用Windows的转换函数直接查找
;当FontLoader=1时
;会保持启用的状态，但是所有字体链接的处理会交由WIN32API完成。
FontLink=2

;【字体替代】
;当FontLoader=0时
;0：什么都不做；
;1：安全替换方案（兼容性较好），根据以下FontSubstitutes的配置进行替换；
;2：完全替换方案（效果较全面，如替换后出现乱码，请尝试使用1），根据以下FontSubstitutes的配置进行替换；
;当FontLoader=1时
;会保持启用的状态，但是所有字体替代的处理会交由WIN32API完成
FontSubstitutes=1

;【让freetype处理的最大的字体尺寸，单位是像素，0的话就是全尺寸】
;交付 gdi++ 处理的最大尺寸（单位为像素）
;0-2147483647
MaxHeight=0

;【阴影设置】
;格式：水平偏移,垂直偏移,深色文字的阴影透明度(0-100),深色文字的阴影颜色，浅色文字的阴影透明度(0-100),浅色文字的阴影颜色
;阴影透明度值越低，则越透明
;颜色值格式：BBGGRR
;Shadow=1,1,70,FFFFFF,50,000000

;【液晶显示器的优化配置】
;[0:None]  1:Default  2:Light  16:Legacy
LcdFilter=2

;【微调LcdFilterWeight】
;LcdFilter>0，且AntiAliasMode>-1时，该微调才生效
;这5个值分别代表文字笔划中从左到右的笔划浓度，最小为0，最大为255
;注释掉这个参数则恢复使用
;当LcdFilter=1，默认值为“16,64,112,64,16”
;当LcdFilter=2，默认值为“0,85,86,85,0”
;LcdFilterWeight=16,64,128,64,16

;【字体缓存、内存的设置】
LoadOnDemand=1
CacheMaxFaces=256
CacheMaxSizes=33554432
CacheMaxBytes=67108864
EnableKerning=0

;【强制使用某一个字体】
;无视所有其他字体，全系统的字体都会被这里设置的字体代替
;ForceChangeFont=华文中宋

;【优先使用点阵】
;小于指定字号的文字将优先使用内嵌点阵
MaxBitmap=0

;【强制对小字体使用Hinting】
;对9号以下字体自动施加Hinting，使小字体更清晰
;此参数仅在AntiAliasMode=1、4、5时有效
;0：关闭，1：开启。默认开启
HintSmallFont=0

;【对硬件加速的渲染支持】
;对使用DirectWrite作为硬件加速技术的软件（如IE和firefox的硬件加速）提供渲染支持开关
;0：关闭，1：开启。默认开启
DirectWrite=0

[Individual]
;【单独设置的字体】
;格式＝Hinting, AAMode, NormalWeight, BoldWeight, ItalicSlant, Kerning
宋体=,,28,0,,
新宋体=,,28,0,,
SimSun-ExtB=,,28,0,,
仿宋_GB2312=,,28,0,,
仿宋=,,28,0,,
华文仿宋=,,28,0,,
华文宋体=,,28,0,,
华文中宋=,,28,0,,
Batang=,,28,0,,
MingLiU=,,28,0,,
MingLiU-ExtB=,,28,0,,
PMingLiU=,,28,0,,
PMingLiU-ExtB=,,28,0,,
PMingLiU_HKSCS=,,28,0,,
PMingLiU_HKSCS-ExtB=,,28,0,,
MS Mincho=,,28,0,,
MS PMincho=,,28,0,,
方正等线=,,24,6,,

;[Individual@Unused]
;如希望启用以下字体的单独配置，请把上面的“[Individual@Unused]”一行注释掉
;同时该段困于必须紧跟“[Individual]”段原有内容之后
XHei iOS=,,20,6,,,
XHei iOS Mono=,,20,6,,,
XHei iOS SimSun=,,20,6,,,
XHei iOS NSimSun=,,20,6,,,

XHei iOS7=,,20,6,,,
XHei iOS7 Mono=,,20,6,,,
XHei iOS7 SimSun=,,20,6,,,
XHei iOS7 NSimSun=,,20,6,,,

XHei OSX=,,20,6,,,
XHei OSX Mono=,,20,6,,,
XHei OSX SimSun=,,20,6,,,
XHei OSX NSimSun=,,20,6,,,

XHei Android=,,12,,,,
XHei Android Mono=,,12,,,,
XHei Android SimSun=,,12,,,,
XHei Android NSimSun=,,12,,,,

XHei Ubuntu=,,12,,,,
XHei Ubuntu Mono=,,12,,,,
XHei Ubuntu SimSun=,,12,,,,
XHei Ubuntu NSimSun=,,12,,,,

XHei Traditional=,,24,6,,,
XHei Traditional Mono=,,24,6,,,
XHei Traditional SimSun=,,24,6,,,
XHei Traditional NSimSun=,,24,6,,,

XSung Clear=,,32,8,,,
XSung Clear Mono=,,32,8,,,
XSung Clear SimSun=,,32,8,,,
XSung Clear NSimSun=,,32,8,,,

XSung Sharp=,,32,8,,,
XSung Sharp Mono=,,32,8,,,
XSung Sharp SimSun=,,32,8,,,
XSung Sharp NSimSun=,,32,8,,,

XSung Classical=,,24,6,,,
XSung Classical Mono=,,24,6,,,
XSung Classical SimSun=,,26,6,,,
XSung Classical NSimSun=,,24,6,,,

XCross Clear=,,32,,,,
XCross Clear Mono=,,32,,,,
XCross Clear SimSun=,,32,8,,,
XCross Clear NSimSun=,,32,8,,,

XCross Sharp=,,32,,,,
XCross Sharp Mono=,,32,,,,
XCross Sharp SimSun=,,32,8,,,
XCross Sharp NSimSun=,,32,8,,,

XCross Classical=,,24,,,,
XCross Classical Mono=,,24,,,,
XCross Classical SimSun=,,24,6,,,
XCross Classical NSimSun=,,24,6,,,

XCross Traditional=,,32,6,,,
XCross Traditional Mono=,,32,6,,,
XCross Traditional SimSun=,,32,6,,,
XCross Traditional NSimSun=,,32,6,,,
[Exclude]
;【除外的字体】，会与MacType.ini中的同名配置共同生效

[ExcludeModule]
;【不渲染的程序，但仍会加载DLL】，会与MacType.ini中的同名配置共同生效

[ExcludeSub]
;【排除不替换字体的程序】，会与MacType.ini中的同名配置共同生效
;以下程序不会被进行字体热替换

[UnloadDll]
;【不渲染的程序，同时完全不加载DLL】，会与MacType.ini中的同名配置共同生效

[FontSubstitutes]
;【字体替代】
;系统在调用“=”前面的字体时会忽视“=”前面的字体，而去直接调用“=”后面的字体
XXX=XHei Intel
XXX Bold=XHei Intel Bold
XXX Mono=XHei Intel Mono
XXX Mono Bold=XHei Intel Mono Bold
XXX SimSun=XHei Intel SimSun
XXX NSimSun=XHei Intel NSimSun
Courier=XHei Intel Mono
Terminal=XHei Intel Mono
MS Sans Serif=XHei Intel
MS Serif=XHei Intel
Microsoft Sans Serif=XHei Intel
SimSun=XHei Intel SimSun
NSimSun=XHei Intel NSimSun
Fixedsys=XHei Intel NSimSun

;[FontSubstitutes@ExHotShift]
;【扩展的字体替代】
;如希望启用以下字体替换配置，请把上面的“[FontSubstitutes@ExHotShift]”一行注释掉
;同时该段困于必须紧跟“[FontSubstitutes]”段原有内容之后
Arial=XHei Intel
Arial Black=XHei Intel
Arial Narrow=XHei Intel
Arial Unicode MS=XHei Intel
Microsoft JhengHei=XHei Intel
Microsoft JhengHei UI=XHei Intel
Microsoft YaHei=XHei Intel
Microsoft YaHei UI=XHei Intel
Lucida Sans Unicode=XHei Intel
Segoe UI=XHei Intel
Tahoma=XHei Intel
Calibri=XHei Intel
Verdana=XHei Intel

;[FontSubstitutes@ExAppleFont]
;【对Apple系统的字体替代】
;如希望启用以下字体替代配置，请把上面的“[FontSubstitutes@ExAppleFont]”一行注释掉
;同时该段困于必须紧跟“[FontSubstitutes]”段原有内容之后
Heiti SC=XHei Intel
Heiti TC=XHei Intel
Hiragino Sans GB=XHei Intel
Lucida Grande=XHei Intel
Helvetica=XHei Intel
Helvetica Neue=XHei Intel

;===== 标识为Office的通用配置组 =====
[General@Office]
;【针对Office组的字体替换】
;当FontLoader=0时
;0：什么都不做；
;1：安全替换方案（兼容性较好），根据以下FontSubstitutes的配置进行替换；
;2：完全替换方案（效果较全面，如替换后出现乱码，请尝试使用1），根据以下FontSubstitutes的配置进行替换；
;当FontLoader=1时
;会保持启用的状态，但是所有字体替代的处理会交由WIN32API完成
FontSubstitutes=0
shadow=0,0,0,0,0,0

;===== 标识为Office的热替换配置组 =====
[FontSubstitutes@Office]
;针对Office组的字体替换，当FontSubstitutes>0时生效
XXX=XHei Intel
XXX Bold=XHei Intel Bold
XXX Mono=XHei Intel Mono
XXX Mono Bold=XHei Intel Mono Bold
XXX SimSun=XHei Intel SimSun
XXX NSimSun=XHei Intel NSimSun
Courier=XHei Intel Mono
Terminal=XHei Intel Mono
MS Sans Serif=XHei Intel
MS Serif=XHei Intel
Microsoft Sans Serif=XHei Intel
SimSun=XHei Intel SimSun
NSimSun=XHei Intel NSimSun
Fixedsys=XHei Intel NSimSun

;===== 标识为ExSimSunWithBold的热替换配置组 =====
[FontSubstitutes@ExSimSunWithBold]
;针对ExSimSunWithBold组的字体替换，当FontSubstitutes>0时生效
XXX=XHei Intel
XXX Bold=XHei Intel Bold
XXX Mono=XHei Intel Mono
XXX Mono Bold=XHei Intel Mono Bold
XXX SimSun=XHei Intel
XXX NSimSun=XHei Intel
Courier=XHei Intel Mono
Terminal=XHei Intel Mono
MS Sans Serif=XHei Intel
MS Serif=XHei Intel
Microsoft Sans Serif=XHei Intel
SimSun=XHei Intel
NSimSun=XHei Intel
Fixedsys=XHei Intel

;[FontSubstitutes@ExHotShift]
;【扩展的字体替代】
;如希望启用以下字体替换配置，请把上面的“[FontSubstitutes@ExHotShift]”一行注释掉
;同时该段困于必须紧跟“[FontSubstitutes]”段原有内容之后
Arial=XHei Intel
Arial Black=XHei Intel
Arial Narrow=XHei Intel
Arial Unicode MS=XHei Intel
Microsoft JhengHei=XHei Intel
Microsoft JhengHei UI=XHei Intel
Microsoft YaHei=XHei Intel
Microsoft YaHei UI=XHei Intel
Lucida Sans Unicode=XHei Intel
Segoe UI=XHei Intel
Tahoma=XHei Intel
Calibri=XHei Intel
Verdana=XHei Intel

;[FontSubstitutes@ExAppleFont]
;【对Apple系统的字体替代】
;如希望启用以下字体替代配置，请把上面的“[FontSubstitutes@ExAppleFont]”一行注释掉
;同时该段困于必须紧跟“[FontSubstitutes]”段原有内容之后
Heiti SC=XHei Intel
Heiti TC=XHei Intel
Hiragino Sans GB=XHei Intel
Lucida Grande=XHei Intel
Helvetica=XHei Intel
Helvetica Neue=XHei Intel

;===== 标识为NoShadow的通用配置组 =====
[General@NoShadow]
shadow=0,0,0,0,0,0

;>>>>> 对特定EXE程序的配置，使用指定标识的配置组配置覆盖默认的同名配置 >>>>>
[General@EXCEL.EXE]
Alternative=Office
[General@POWERPNT.EXE]
Alternative=Office
[General@WINWORD.EXE]
Alternative=Office
[General@VISIO.EXE]
Alternative=Office
[General@WINPROJ.EXE]
Alternative=Office
[General@ONENOTE.EXE]
Alternative=Office
[General@et.exe]
Alternative=Office
[General@wps.exe]
Alternative=Office
[General@wpp.exe]
Alternative=Office
[General@webkit2webprocess.exe]
Alternative=Office
[General@chrome.exe]
Alternative=ExSimSunWithBold
[General@iexplore.exe]
Alternative=ExSimSunWithBold
[General@firefox.exe]
Alternative=ExSimSunWithBold
[General@opera.exe]
Alternative=ExSimSunWithBold
[General@qq.exe]
Alternative=ExSimSunWithBold
[General@foxmail.exe]
Alternative=ExSimSunWithBold
[General@tdxw.exe]
Alternative=NoShadow

**Comment by githubhao0705** [comment]
新问题，网页出现空方块。
就好像这个网站：https://read01.com/mAzEM.html
![bandicam 2017-08-01 14-51-18-457](https://user-images.githubusercontent.com/17467692/28811257-f05acaf8-76c8-11e7-8dad-5e78f6948d64.jpg)

**Comment by Mahayu** [comment]
steam 默认是以 DirectWrite 方式渲染的，目前版本的 Mt 并不能成功挂钩，你可以在设置-界面处将其关闭。
另外的话游戏可能有DRM之类的防止DLL挂钩……

**Comment by githubhao0705** [comment]
@Mahayu 但是更新前可以，唉，我试试旧版本吧，总之谢谢你。

**Comment by githubhao0705** [comment]
@Mahayu 我看出你的留言了。的确是可以在设置里关掉，我真蠢。这下连游戏也可以渲染了。至于window设置无法渲染就算了，我也不想多装其他的补丁了。谢谢你啊。
![snipaste_20170801_214044](https://user-images.githubusercontent.com/17467692/28828044-1f02ad88-7702-11e7-8757-1584b46ebe83.png)
