### ISSUE TITLE
Black screen and system log off

### ISSUE THREAD

**Issue by superfalse** [snowie2000/mactype#349]
I installed Windows 10 Prof x64 from scratch yesterday. Also installed MacType (2017_0628_0) which I've been using for a long time (thanks a lot for your effort!) on both Win7 and Win10 PCs.

After restarting I was no longer able to open any other app but Explorer and Firefox - opening anything else (even Task manager or the Run command prompt) would cause the screen to go black, followed by an automatic log off. I had to do a system recovery to get it back working. I tried installing MacType again today and got the same result. Is this a bug or somehow my fault?

**Comment by kriston** [comment]
Same here.  It just doesn't work on Windows 10 Pro x64.

**Comment by RitzyBusiness** [comment]
This only happened when I made my own render settings using the wizard. Are you guys attempting the same? or using the default setting.

I found that using default as a template and changing the values with what the wizard gave works fine.  If that is your problem otherwise I would try setting manual mode.

Also you don't need system restore~ just open safemode with command prompt and you can delete the ini file that is causing you problems or just load safe mode proper and it wont autoload mactype.

**Comment by superfalse** [comment]
I used one of the presets (Mac LCD?) you can choose from after installation. I'm gonna try the default one.

> just open safemode with command prompt
Doesn't work because it closes everything up immediately and leaves you with an empty desktop or black screen. Couldn't get into safe mode via F8 either, Windows 10 seems to be a bit different here.

**Comment by RitzyBusiness** [comment]
Windows 10 uses a recovery partition instead so you have to enter recovery
https://www.tenforums.com/tutorials/2294-boot-advanced-startup-options-windows-10-a.html

If you can make it far enough into windows the fastest way is to Shift Click Resetart before full load.

**Comment by snowie2000** [comment]
Try not start mactype with registry mode and using the default profile to check if it is an issue with your profile as some of the settings are known to have compatible problems (but they are powerful enough to make me decided to keep them).

**Comment by superfalse** [comment]
My own profile caused the same problem but after switching to Tray mode everything seems to work (except Mactype doesn't affect Firefox - couldn't tell if it did in registry mode).

**Comment by kriston** [comment]
Right, I set it to be Tray mode without Administrator and it worked magically well.  I'm going to dig out my old Freetype settings and check out what I can do with this.

Thanks for the information!

**Comment by deggua** [comment]
Same problem, windows logs off whenever I open task manager, open a file, etc

**Comment by admhlt** [comment]
This happened to me as well -- it was pretty worrying to discover that every app I launched would cause Windows to restart completely. Eventually I figured out that it was MacType, was able to launch the tray version, and disable and uninstall the app.

Nice to know that it only happens when you create a config using the wizard, but I can't bring myself to reinstall MacType until I know this isn't a problem anymore.

**Comment by RitzyBusiness** [comment]
It mostly stopped happening already, sometimes you get a windows crash on reboot but it'll go away on second boot.  I used the wizard once more to mess with it and didn't have any problems that time around.

That said merging wizard data with a copy of default should also net you no problems.  Asides from the BSOD the first time you apply it.

**Comment by snowie2000** [comment]
I'm quite curious what your profiles look like, and I have a guess that the reason you don't suffer from BSOD after merging your new profile with the old profile is most probably because of the unload section. It excluded a lot of system processes by default which may have some potential incompatibility issues.

**Comment by MasonicCGI** [comment]
Please, is there anybody who could provide any clear information or solution for this issue?
I am installing Mactype 628_0 in Windows 10 Pro x64 and encountering a black screen immediately after booting the OS. The mouse cursor in not shown on the black screen and there is now way to access any Windows recovery tool. Only solution is to clean reinstall the entire OS.
I am configuring Mactype to run as a service, default mode.
It seems to me that Mactype somehow interferes with Windows 10 system boot and renders the system unusable.
I tried disabling Windows Update entirely but this configuration does not change the behavior of the OS at boot.
Please could someone help on this issue?

**Comment by superfalse** [comment]
I installed it on a new Win10 installation a few weeks ago and it runs fine — tray mode only, though, as before. AFAIK there has not been an update yet.

**Comment by MasonicCGI** [comment]
Thank you for your answer, Superfalse.
I just finished installing it in Manual mode and it seems that the crash at boot is solved for the moment. Will keep everyone updated.

Just one last thing: did you manage to create a working MacType shortcut for application Explorer.exe.
I am able to create working desktop shortcuts for all user installed applications, but not for this.
Maybe you were able to do that?

**Comment by superfalse** [comment]
Never tried manual mode as tray mode has always worked fine for me.

**Comment by MasonicCGI** [comment]
What do you mean with Tray mode?
I see three modes, Registry, Service and Manual.

**Comment by superfalse** [comment]
Load with MacTray: https://mk0intowindows84fvao.kinstacdn.com/wp-content/uploads/2016/09/macType1.png

**Comment by MasonicCGI** [comment]
I see, thank you for the screenshot.
Are you selecting the option "Run as admin"?
And what about the two radio buttons after "Run as admin"?

**Comment by superfalse** [comment]
I chose Run as admin and Standalone loading mode.
If it doesn't work as intended, you can always go back to the wizard and try other options.

**Comment by sammilucia** [comment]
For Windows 10 please check out the **Important notice!!** on the Readme here: https://github.com/snowie2000/mactype. Let us know if you still have problems.

I've created a new issue #431 to track this. Closing.
