### ISSUE TITLE
DWM.exe crash

### ISSUE THREAD

**Issue by RibShark** [snowie2000/mactype#350]
With MacType loaded (running as a Service), performing certain actions, such as opening a new program like Notepad, will crash DWM.exe. Here is the log in Event Viewer:

```<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-08-06T19:35:49.205613400Z" /> 
  <EventRecordID>48960</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Computer</Computer> 
  <Security /> 
  </System>
 <EventData>
  <Data>dwm.exe</Data> 
  <Data>10.0.15063.0</Data> 
  <Data>982d0cc7</Data> 
  <Data>MacType64.Core.dll</Data> 
  <Data>1.2017.628.0</Data> 
  <Data>59532090</Data> 
  <Data>c00000fd</Data> 
  <Data>000000000008b107</Data> 
  <Data>199c</Data> 
  <Data>01d30eeb14d045ba</Data> 
  <Data>C:\WINDOWS\system32\dwm.exe</Data> 
  <Data>C:\Program Files\MacType\MacType64.Core.dll</Data> 
  <Data>65a8c78a-f5e9-4bd5-92ec-fbf17539f6af</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

Obviously adding DWM.exe to [UnloadDLL] fixes this, but then Window Titles are not rendered via MacType.

**Comment by Ichicoro** [comment]
This is because when running as a service MacType doesn't have all permissions it has while it runs in registry mode. You should switch to registry mode if you really want `DWM.exe` to render using MacType

**Comment by snowie2000** [comment]
I checked your report and it does not help much. The exception occurred inside library codes which are used almost everywhere. So there is no way to identify the error point.
