### ISSUE TITLE
Infinality patches

### ISSUE THREAD

**Issue by kriston** [snowie2000/mactype#351]
Forgive me if this is already known by everyone here, but how many of the Infinality patches were included in MacType?  Many of these patches have to do with aligning vertical lines with pixels to avoid blurriness and doing single-direction pixel alignment.  Essentially, it tries to emulate Microsoft ClearType, the aim of which was for screen clarity and not perfect shapes. I see some of these in the code but I am opening this Issue to inquire as to how many of the other Infinality patches are present, and if some aren't, I'd like to help integrating them.

Thank you.

For reference:

Ubuntu package:
https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa

Archived (and gone) Infinality.net:
http://web.archive.org/web/20160113234301/http://www.infinality.net/blog/infinality-freetype-patches/

**Comment by snowie2000** [comment]
Indeed, the infinality patch (the hinter to be exactly) was included in the latest freetype.
Here is a code snippet of ftoption.h from freetype 2.8 

```   /*************************************************************************/
  /*                                                                       */
  /* Define TT_CONFIG_OPTION_SUBPIXEL_HINTING if you want to compile       */
  /* subpixel hinting support into the TrueType driver.  This modifies the */
  /* TrueType hinting mechanism when anything but FT_RENDER_MODE_MONO is   */
  /* requested.                                                            */
  /*                                                                       */
  /* In particular, it modifies the bytecode interpreter to interpret (or  */
  /* not) instructions in a certain way so that all TrueType fonts look    */
  /* like they do in a Windows ClearType (DirectWrite) environment.  See   */
  /* [1] for a technical overview on what this means.  See `ttinterp.h'    */
  /* for more details on the LEAN option.                                  */
  /*                                                                       */
  /* There are three possible values.                                      */
  /*                                                                       */
  /* Value 1:                                                              */
  /*    This value is associated with the `Infinality' moniker,            */
  /*    contributed by an individual nicknamed Infinality with the goal of */
  /*    making TrueType fonts render better than on Windows.  A high       */
  /*    amount of configurability and flexibility, down to rules for       */
  /*    single glyphs in fonts, but also very slow.  Its experimental and  */
  /*    slow nature and the original developer losing interest meant that  */
  /*    this option was never enabled in default builds.                   */
  /*                                                                       */
  /*    The corresponding interpreter version is v38.                      */
  /*                                                                       */
  /* Value 2:                                                              */
  /*    The new default mode for the TrueType driver.  The Infinality code */
  /*    base was stripped to the bare minimum and all configurability      */
  /*    removed in the name of speed and simplicity.  The configurability  */
  /*    was mainly aimed at legacy fonts like Arial, Times New Roman, or   */
  /*    Courier.  Legacy fonts are fonts that modify vertical stems to     */
  /*    achieve clean black-and-white bitmaps.  The new mode focuses on    */
  /*    applying a minimal set of rules to all fonts indiscriminately so   */
  /*    that modern and web fonts render well while legacy fonts render    */
  /*    okay.                                                              */
  /*                                                                       */
  /*    The corresponding interpreter version is v40.                      */
  /*                                                                       */
  /* Value 3:                                                              */
  /*    Compile both, making both v38 and v40 available (the latter is the */
  /*    default).                                                          */
  /*                                                                       */
  /* By undefining these, you get rendering behavior like on Windows       */
  /* without ClearType, i.e., Windows XP without ClearType enabled and     */
  /* Win9x (interpreter version v35).  Or not, depending on how much       */
  /* hinting blood and testing tears the font designer put into a given    */
  /* font.  If you define one or both subpixel hinting options, you can    */
  /* switch between between v35 and the ones you define (using             */
  /* `FT_Property_Set').                                                   */
  /*                                                                       */
  /* This option requires TT_CONFIG_OPTION_BYTECODE_INTERPRETER to be      */
  /* defined.                                                              */
  /*                                                                       */
  /* [1] http://www.microsoft.com/typography/cleartype/truetypecleartype.aspx */
  /*                                                                       */
/* #define TT_CONFIG_OPTION_SUBPIXEL_HINTING  1         */
#define TT_CONFIG_OPTION_SUBPIXEL_HINTING  2
/* #define TT_CONFIG_OPTION_SUBPIXEL_HINTING  ( 1 | 2 ) */
```
MacType was compile with this macro definition so that the hinter mactype is using right now is the ClearType hinter, but to use it, you have to disable LCD light mode (Slight mode in freetype terms actually) and set Hintingmode to use embedded font hinting rather than using freetype autohinter.

**Comment by IceMan81** [comment]
@snowie2000 Are you saying that to use the ClearType hinter in MacType you have to use a combination of HintingMode=0 and AntiAliasMode=2 (since AntiAliasMode=4 is Light LCD) ?
Could you please confirm this ? Thanks.

**Comment by snowie2000** [comment]
Looks true.

**Comment by kriston** [comment]
I take back my earlier comment somewhat.  I was wondering why Infinality went away and I realized that most of the Infinality patches concerned filters that aligned glyphs to pixels in order to avoid what Microsoft called the "pixel explosion" effect.  The author preferred the "slight" method which disables the bytecode hinter and favors the FreeType autohinter instead.

Now that ClearType bytecode hinter has been implemented in FreeType, much of the Infinality pixel-alignment tweaks weren't needed anymore since the new bytecode hinter handles it now.

**Comment by IceMan81** [comment]
@snowie2000 I just tried HintingMode=0 and AntiAliasMode=2. Didn't really work out. 
Tried to upload a screenshot but unable to for some reason.

**Comment by Infinality** [comment]
I've successfully compiled freetype 2.8 with the (unmerged) Infinality patches and will post it once I can get mactype to compile.

**Comment by kriston** [comment]
Thank you for your great work.  Your patches to FreeType make it all very beautiful.
Forgive me for asking, but will have you published your FreeType 2.8 patch set?

Thanks again, Infinality, for your excellent improvements to FreeType rendering.

**Comment by Infinality** [comment]
Thanks.  :)   I've actually been using the arch patches on Fedora for Freetype 2.8 and they seemed to work fine with a little tweaking:
https://aur.archlinux.org/packages/freetype2-infinality-ultimate/

2.8.1 had some changes and I haven't gotten that working yet.  I think I'm about 90% of the way through getting them applied on Mactype but I'm running into some issues with external references that Freetype makes to standard C library functions that MS doesn't seem to support.

Really, I think the rendering with these patches is far superior to the rendering on Windows, if nothing else than because you can customize it to exactly how you want it.  The really good stuff is already in Freetype (and Mactype), but the one thing I miss on Mactype is the stem alignment code in the unmerged patches, which is why I'm trying to get it working.

**Comment by IceMan81** [comment]
@Infinality Looking forward to see Mactype with your patches. Exciting times! 👍

**Comment by snowie2000** [comment]
@IceMan81 
Here is the patch
http://www.mactype.net/station/MacType_CTP_171017.rar

**Comment by kriston** [comment]
Is there a pull request to include these patches in the Mactype source?

**Comment by snowie2000** [comment]
It's a patch to freetype, not to mactype.

**Comment by kriston** [comment]
My mistake.

What settings can we put into the *.ini file to enable the features?

**Comment by IceMan81** [comment]
@kriston You do no need any settings in the*.ini file to enable the Infinality features, you need to use a version of MacType compiled with Infinality patched freetype. 

See the discussion here on some of the environment variables that are useful when using a patched version of Mactype.

**Comment by kriston** [comment]
Thanks, @IceMan81.  I realized after I posted that message that the really good Infinality tweaks are activated by environment variables in Unix.  I didn't realize that it also works with Windows environment variables.  I will take a look at the beautiful Infinality settings I use on Unix and transfer them to my Windows installation.

Thanks!

**Comment by IceMan81** [comment]
@kriston If you don't mind, could you share your the Infinality settings you are using esp. if they look great on Windows as well.

**Comment by sammilucia** [comment]
Closing as old issue (which has kinda been continued in #366)
