### ISSUE TITLE
MacWiz crashes on start, cannot uninstall

### ISSUE THREAD

**Issue by detly** [snowie2000/mactype#352]
I have just installed `2017_0628_0` on a Win10 machine (previously had `2016_0904_0`). When I try to launch MacWiz I get a lot of mouse cursor flickering and the error: 'Access violation at address 004EE483 in module 'MacTray.exe'. Read of address 00000000.' MacWiz continues to run, but the mouse cursor continually jumps and flickers up and down by a few pixels.

So I figure maybe I should completely uninstall it and try again. When I select "uninstall" from the MacType entry in Windows' Add/Remove Programs settings, it just brings up the installer (not in English, which is my default language; note that the installer ran in English when I launched it manually). There's no option to uninstall! I can't even uncheck everything if I use the custom install method.

How do I uninstall MacType?

**Comment by snowie2000** [comment]
Get an installer from mactype.net and do an uninstall from installer.
This is a known bug with new installer which I can't solve.

**Comment by detly** [comment]
Ah right. I didn't think to try the downloaded installer again. Thanks!

**Comment by sammilucia** [comment]
Closed as resolved. Please install as "Typical" mode for now (avoid "Custom") to avoid this problem.
