### ISSUE TITLE
MacType Stopped working on W10

### ISSUE THREAD

**Issue by Rodro150** [snowie2000/mactype#354]
So, basically whenever I try to execute the program I get that, and then  "Aplication Error, Exception ElniFileException in module MacTray.exe at 000B78F1. Unable to write to."﻿

**Comment by snowie2000** [comment]
Run with administrator privilege or use service mode instead.

**Comment by Rodro150** [comment]
Thank you for answering me but the problem still persists!

**Comment by Rodro150** [comment]
Thanks, it works now!
