### ISSUE TITLE
Freetype 'Slight' hinting support

### ISSUE THREAD

**Issue by Nek80** [snowie2000/mactype#356]
Following #351 and #312 I want to ask a question about font rendering/hinting with Freetype and Mactype and if it is possible to make it look as the Freetype rendering in Linux. I took screenshots of yahoo.com website with Firefox both on Linux Freetype and Windows Mactype for comparison.

**Linux** (Freetype 2.8)
Subpixel rendering: **none**
Hinting: **Slight**
![linux-full](https://user-images.githubusercontent.com/5416165/29710988-6c64b19c-899b-11e7-839d-fe225f4381c4.png)

**Windows** (MacType version:	1.2017.628.0)
HintingMode = **2** (AutoHinting)
AntiAliasMode = **1** (Light)
![mactype-full](https://user-images.githubusercontent.com/5416165/29710991-6f41cde6-899b-11e7-8e5c-dabdd0c2471e.png)

Here a better comparison:
Linux (Freetype 2.8)
![linux](https://user-images.githubusercontent.com/5416165/29710890-03c7153a-899b-11e7-90c0-61e46eda2821.png)

Windows (MacType version:	1.2017.628.0)
![mactype](https://user-images.githubusercontent.com/5416165/29710888-039b4b1c-899b-11e7-94b6-153ee8d9e77c.png)

In the Mactype image note the top side of the characters, they are blurred and are shorter in height. On the other hand the Linux characters are taller and their top side is crisp. As a result the Linux text appears more crisp and clear while the Windows Mactype one appears more blurry and ugly.

Is there a way that we can get with Mactype the exact rendering of this Linux freetype rendering?

**Comment by snowie2000** [comment]
You have to disable directwrite for firefox on Windows or you are just comparing freetype with DirectWrite which makes no sense.

**Comment by IceMan81** [comment]
@snowie2000 Do you know the right way to disable DirectWrite in the latest Firefox 57?

**Comment by Infinality** [comment]
Pretty sure you can use this plugin:   https://addons.mozilla.org/en-US/firefox/addon/anti-aliasing-tuner/

**Comment by IceMan81** [comment]
That plugin will not work with the latest Firefox 57. The best way to use Mactype with FF is to disable directwrite and remove skia from the list of azure backends.

**Comment by Nek80** [comment]
Here are some updated font rendering tests and comparisons between Mactype on Windows 10 and Freetype on Linux. I now used the Chromium on Linux and Cent Browser on Windows which I configured it to use GDI. Now they are both using freetype, but still, they have the same issues that I described in the first post.

Configurations:

**Linux (Freetype 2.8)**
Subpixel rendering: none
Hinting: Slight

**Windows (MacType version:	1.2017.628.0)**
HintingMode = 2 (AutoHinting)
AntiAliasMode = 1 (Light)

### First comparison - Wikipedia 
(click on each image to open them in a new tab with full resolution)

**Linux**:
![linux-wikipedia](https://user-images.githubusercontent.com/5416165/31867704-c11d4332-b79c-11e7-977e-8667f0ae68b5.png)

Windows:
![windows-wikipedia](https://user-images.githubusercontent.com/5416165/31867703-c10199de-b79c-11e7-954c-79cd8d0f900e.png)


### Second comparison - Google Fonts
(click on each image to open them in a new tab with full resolution)

Linux
![linux-full](https://user-images.githubusercontent.com/5416165/31867675-7aead550-b79c-11e7-8ac7-e946bddd2086.png)

Windows
![mactype-windows-full](https://user-images.githubusercontent.com/5416165/31867686-9a235564-b79c-11e7-9350-ff109910fb9a.png)

Detailed comparison
![comparison](https://user-images.githubusercontent.com/5416165/31867674-7ad12164-b79c-11e7-99c9-4bb547f16d22.png)

### Third comparison - Open Sans font rendering
(click on each image to open them in a new tab with full resolution)

![comparison-opensans](https://user-images.githubusercontent.com/5416165/31867673-7a8317ee-b79c-11e7-914f-b80d326ab0ab.png)

### Summary

The font rendering is different despite that both browsers are Chromium based and have the same  engine and with Mactype, they both use Freetype rendering with equivalent configuration. Notice how in the windows renderings, the characters are slightly blurred, particularly on their top sides, whereas in the linux renderings the characters are crisper, cleaner and more legible. I strongly prefer the Linux rendering as it is much better for me and I would like to have the same with Mactype/Windows.

@snowie2000 do you perhaps know why these differences happen and how they can be fixed (have the same rendering as linux)?

**Comment by snowie2000** [comment]
It's very interesting.
It is obvious that the screenshots you shown for Windows are clearly not hinted. You can see this from many letters especially the letter "e" and "f". You can clearly see that the horizontal line of "f" is blurred in Windows and clean in Linux which is the result of hinting.

Here are more comparisons:
This is Open sans with my profile comparing with your screenshot in Windows. You can see that your screenshot is very much like the result without hinting especially when I compare two layers with Photoshop by subtracting them.
![compare1](https://user-images.githubusercontent.com/11767189/31871275-a2f2287a-b7e5-11e7-9190-4f3da59385d5.png)
![compare2](https://user-images.githubusercontent.com/11767189/31871278-a55a1852-b7e5-11e7-92d8-3120f2b61519.png)

**Comment by Nek80** [comment]
You are right! My bad, the HintingMode was 1 and not 2 in my profile by a mistake... I'll switch it to 2 and compare it again and let you know if they are correctly rendering now.
