### ISSUE TITLE
Explorer crashes in Control Panel -> Fonts when rendering Courier Regular (VGA res)

### ISSUE THREAD

**Issue by Idearum** [snowie2000/mactype#357]
OS: Windows 10 x64 1703
MacType: MacTray (standalone loading mode)

Trying to browse Control Panel -> Fonts always crashes explorer.exe when it tries to render Courier Regular with MacType enabled. Disabling MacType stops the issue from occuring.

I assume it has something to do with the type of font Courier Regular is: http://i.imgur.com/cPEHNjC.png

According to [this page](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_other/fonts-courier-vs-courier-regular/4263344d-2464-41ec-80a6-70fed00e0826?auth=1) the font is "a 'screen font' that is not scalable."

**Comment by snowie2000** [comment]
Theoretically, mactype can detect this font as a bitmap font and bypass it automatically.

**Comment by sammilucia** [comment]
Could not reproduce.

@Idearum are you still having this issue? If so could you please let us know your MacType load mode and post your INI here? (you can zip it to attach it to this issue)

**Comment by Idearum** [comment]
Sorry, but I haven't been using MacTray in over a year now, and the OS and my system have been frequently reinstalled since then. I somewhat doubt I'll be able to reproduce it now either.

**Comment by sammilucia** [comment]
okay thank you @Idearum , please let us know if we can help any further.
