### ISSUE TITLE
Changing the decimals in settings seems to have no effect

### ISSUE THREAD

**Issue by Skyyblaze** [snowie2000/mactype#358]
I'm new to using MacType since I upgraded to Windows 10 and I love the way it makes my fonts look, playing around with my config file I noticed something odd though.

When changing the values for the following settings:

GammaValue=
Contrast=
RenderWeight=

a decimal value seems to have no effect. For example RenderWeight=1.5, RenderWeight=1.6 or RenderWeight=1.7 looks the same as RenderWeight=1.0. The only change happens when I set RenderWeight=2.0 and then again no matter if I set 2.1, 2.2 etc it looks the same as 2.0 and the next change I see is when I reach 3.0.

Is MacType ignoring the decimals and is this a bug or am I doing something wrong?

I'm using Windows 10 Pro Version 1703 (Build 15063.540) on the Creators Update and my MacType version is 1.17.0628 according to my update.ini, I have no idea where else to check for the MacType version I use but I downloaded the newest installer within the last two weeks.

**Comment by Nek80** [comment]
I had the same problem and found what is causing this. You probably have a regional settings set that uses the comma (,) instead of the dot (.) for decimal separation. The solution is to use decimal values with comma e.g.

RenderWeight=1,7

This is a small bug though and should be fixed.

**Comment by sammilucia** [comment]
Hmm, should regional settings apply to ini parsing?

**Comment by snowie2000** [comment]
> Hmm, should regional settings apply to ini parsing?

@sammilucia It will. The standard `strtod` function will convert string to double based on locale.
http://www.cplusplus.com/reference/cstdlib/strtod/

I have fixed the problem by using a standalone version of strtod in iniparser: https://github.com/snowie2000/IniParser/commit/6bd26818acf80b7912b291e40d63177e4f6ee6d3

**Comment by sammilucia** [comment]
Hi @Skyyblaze @Nek80 ... can you please
1. install the latest beta2 https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2
2. check the decimal in your ini files matches your regional settings ('.' or ',')

let me know if it's now working?

**Comment by sammilucia** [comment]
Resolved by https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4. Please let us know if problems continue. Closing issue.
