### ISSUE TITLE
Can't uninstall v1.2017.628.0

### ISSUE THREAD

**Issue by JustDragon** [snowie2000/mactype#359]
I tried to uninstall v1.2017.628.0 but it couldn't. Any idea?

**Comment by snowie2000** [comment]
Uninstall with installer if the uninstall command doesn't work in control panel.

**Comment by JustDragon** [comment]
Thank you, it works now. I doubt Mactype is causing bootloop for bluestacks2.

**Comment by sammilucia** [comment]
Closing as resolved.
