### ISSUE TITLE
MacType not working with Chrome 60 on Windows 10 or unclear instructions.

### ISSUE THREAD

**Issue by denysonique** [snowie2000/mactype#360]
After installing the latest build 1.2017.628.0 and choosing the default profile which has `DirectWrite=1` and `RenderingMode=6` fonts rendered by Chrome are not improved.

Either MacType is not working or the instructions are not provided/clear enough. It does not work OTB.

**Comment by RitzyBusiness** [comment]
Unless they've changed anything the chrome flag to disable directwrite is gone which means mactype should not work on it.  Most of us that use chrome prefer Cent Browser which runs updated chromium but has the DW flag for mactype compatibility.  (as well as assurances that they will continue to support it as long as possible)

Unless snowie made changes that I am unaware of that make it compatible with the latest chrome.

**Comment by thomasklash** [comment]
Use [CentBrowser](https://www.centbrowser.com/)

**Comment by sammilucia** [comment]
Sorry for the delay. Please see https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2 for how to use MacType with CentBrowser.

Chrome changes the DirectWrite pipeline so (as yet) does not work with MacType.

**Comment by ssolidus** [comment]
> 
> 
> Sorry for the delay. Please see https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2 for how to use MacType with CentBrowser.
> 
> Chrome changes the DirectWrite pipeline so (as yet) does not work with MacType.

It should be noted that this is an upstream change to Chromium, which affects all Chromium-based apps i.e. Electron apps

**Comment by sammilucia** [comment]
Thanks @ssolidus yes I've noted that in the release notes also 😊

**Comment by KenWayTheGod** [comment]
You can forcibly disable DirectWrite in the shortcut to your Chrome, right-click the shortcut to your Chrome and in the "Target:" Box, right after the end of the quotes type, 

--disable-directwrite-for-ui

Like this: https://lithi.io/file/81f8.png

**Comment by sammilucia** [comment]
Hi @KenWayTheGod unfortunately this switch is no longer supported by Chrome and Electron.
