### ISSUE TITLE
MACTYPE crashes explorer.

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [snowie2000/mactype#362]
When I install this and then reboot the second I click on the desktop, explorer crashes and then logs me out. I cannot uninstall from a regular session because I can't click anything. I had to go into safe mode and manually start installer service to get rid of this. ANy solutions?

**Comment by snowie2000** [comment]
Which version and loading mode do you use?

**Comment by dubbadubbadubbacha** [comment]
WOW. Thanks for the light fast reply. I use the latest version and I tried both registry and service mode and they both do the same thing. Aparently it is preventing my NVIDIA driver from loading and it loads the basic MS driver instead. I cannot click the desktop though without it crashing and logging me out every time. My computer is an ASUS ROG g750jw with a GTX765 device.

**Comment by snowie2000** [comment]
Apparently, I don't have any computer with NVIDIA graphic card available to test.
The best and first mode I recommend every user to try is the tray mode.

**Comment by dubbadubbadubbacha** [comment]
ok i'll give that a try and report back

**Comment by dubbadubbadubbacha** [comment]
ok i'll give that a try and report back

**Comment by dubbadubbadubbacha** [comment]
Everything seems ok now.

**Comment by snowie2000** [comment]
Service mode and registry mode has too high privileges which may accidentally inject into system critical processes.

**Comment by sammilucia** [comment]
Closed as resolved.
