### ISSUE TITLE
MacType not working on Office (Word, PowerPoint, and Excel)

### ISSUE THREAD

**Issue by gmncls** [snowie2000/mactype#365]
I reinstalled MacType after receiving the latest build for Fast Ring Insiders (16299.15). All apps rendered fine except for Microsoft Edge and all the Office programs that I use most of the time (Word, PowerPoint, and Excel). Any remedy? Ugly fonts irritate me and take away any motivation to continue working :( Thanks!

![picture1](https://user-images.githubusercontent.com/28075595/31303310-d9388e56-ab3d-11e7-9913-b6d02168881c.png)

**Comment by gmncls** [comment]
Reinstalled again and now, only the fonts in the File Explorer and Opera are looking good. The other apps - Mail, Twitter, Weather, News, Office, Edge - have terrible fonts. Any explanation on this? Thanks.

**Comment by dbkblk** [comment]
I have the same problem on the latest Fall Creators Update (first time I try MacType since a long time). Everything works except Office and Edge.

Mactype 2017.0628
Windows 10 16299.19

**Comment by snowie2000** [comment]
For some unknown reason, word uses grayscale rendering of DirectWrite, which is very bad under normal circumstance, and even worse with gridfit turned off (by mactype or by mactype-patch).
You can clearly see the difference between word-grayscale-rendering and typical sub-pixel rendering:
![screen](https://user-images.githubusercontent.com/11767189/31870678-ce4d258c-b7e1-11e7-9a2d-6c1ecc00c098.png)
And this is what it looks like with MacType:
![after](https://user-images.githubusercontent.com/11767189/31870687-d936f9b4-b7e1-11e7-9fd7-2ee3460c2bc9.png)

**Comment by lukaschan** [comment]
It really works on Office if Hardware acceleration is disabled!!! Thx dbkblk!!

**Comment by gmncls** [comment]
I did disable the hardware acceleration and it's working! Cool! Now I hope there's a way to make it work on Microsoft Edge. Thanks!

**Comment by extratype** [comment]
Turning off and on hardware acceleration enables DirectWrite tweaks. I don't know what's going on.

**Comment by sammilucia** [comment]
Since Office 2013, Office uses its own font rendering engine which is neither ClearType/GDI nor DirectWrite. Goodness knows why!!

Disabling Hardware Acceleration in Office 2013 still doesn't use DirectWrite, so MacType can't touch it. I believe Office 2016 moved to DirectWrite, so MacType can do some tuning of DW settings.

I'll update the Readme known issues.

Closing as wontfix for Office 2013. Please use Office 2010 or 2016! 😜
