### ISSUE TITLE
FT Opt config doesn't work properly in explorer.

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [snowie2000/mactype#367]
I believe I made a post about this a while back but it's still a problem. This is the config that gives the text a shadow effect. It works in most other programs but explorer.exe. Sometimes it works in explorer but most times no shadow appears. When I change configs those are seen in explorer but no shadow appears. The shadow appears in most other programs like firefox. Sometimes rebooting helps but most times does not. Sometimes the shadows show up but then disappear after a while. Any suggestions?

**Comment by snowie2000** [comment]
Did you set an exception for the explorer.exe? i.e. [General@explorer.exe]?

**Comment by dubbadubbadubbacha** [comment]
I forgot to mention I installed the tray version with admin privileges. I don't know what you mean. If you mean exclude the process then no. It says "running". Sometimes it works but most times it does not. Sometimes it works then disappears.

**Comment by sammilucia** [comment]
Hi @dubbadubbadubbacha , can you please confirm if this issue occurs in Service or Registry Mode?

**Comment by dubbadubbadubbacha** [comment]
Both

**Comment by dubbadubbadubbacha** [comment]
It should be on the Mac type site. It's not an issue now as I no longer use windows so this issue can be closed. Thanks

**Comment by sammilucia** [comment]
@dubbadubbadubbacha Ahhhh i understand now ... 

I can't find the profile you mean, so I've created a test profile with an obvious shadow. There were changes in beta4 which allow Service Mode to hook explorer better, from what I can see this is working consistently now.

Though... @snowie2000 the clipbox isn't working for shadows?
![image](https://user-images.githubusercontent.com/3295286/47251936-2b79b180-d483-11e8-9ca5-e74852328947.png)

**Comment by snowie2000** [comment]
No, clipbox is only enlarged for texts, not shadows, so they can be clipped in programs.

**Comment by sammilucia** [comment]
ok. closing issue - resolved in beta4
