### ISSUE TITLE
MacType Installer stuck at "Extracting the main application files ..".

### ISSUE THREAD

**Issue by ssray23** [snowie2000/mactype#370]
Hi,
I had to uninstall MacType for some reason, but when I tried installing it again (i.e. MacTypeInstaller_2017_0628_0.exe), the installer is stuck at "Extracting main application files ..".

When I had installed it for the the first time, the issue did not happen. Its only when I try to install it for the second time, I get this error (i.e. stuck at "Extracting main application files .."). Please see screenshot.

![image](https://user-images.githubusercontent.com/8319449/31853663-3af0eb6a-b684-11e7-84b4-ec3a48f12474.png)

Any clues on how I can resolve this?

**Comment by ssray23** [comment]
Can I get the 'Default Profile' dlls as a zip, which I can just copy to my System32 folder? Will this alternative method work?

**Comment by snowie2000** [comment]
You can get all files as a portable zip files here:
http://www.mactype.net/station/?dir=Portable

**Comment by ssray23** [comment]
Thanks for sharing. I have now been able to apply the Default profile (works best for me) by unzipping the portable zip file.
