### ISSUE TITLE
Slow Shutdown/Startup Times Windows 10

### ISSUE THREAD

**Issue by TeddStriker** [snowie2000/mactype#371]
Hi, I installed Mactype as follows:

- Run downloaded file from the main page.
- Install in manual mode.
- Restart PC.

After this restart bootup was significantly increased, I tried to find an uninstall option, but control panel only opened up the installer. I restarted again thinking the first boot might be the culprit but it continued happening, I'm running Windows 10 on an Asus x540L.

 Installing mactype was the only change I made to the system. After not being able to uninstall MacType via a conventional method, I used a System Restore Point from 8 days ago which was successful, MacType is no longer installed. The issues persist however. On bootup, the ASUS logo screen loads, goes blank then continues loading for about ~10s, after that the login screen also takes much longer to load, when it does, the desktop needs a couple of seconds to display the:

- wifi
- sound
- notification

tray icons, and is largely inoperable during this period, after everything loads the system is relatively fine, with the exception of the Disk, which is running at 100% all the time. This is only a month old laptop so it is largely brand new, it now takes at least 4 times longer to boot. Please help. 

Thanks.

**Comment by snowie2000** [comment]
When you install mactype and run it in manual mode, it actually does nothing.
The so-called manual mode is just a friendly name of disabled. MacType won't affect your system in any aspect except the installer database which is inevitable.

**Comment by TeddStriker** [comment]
I figured, which is why I installed it in manual mode. I did run the app and selected a preset which was applied successfully. Do you have any idea on why it would cause such performance issues and how to resolve them? I found a closed github issue where you outline basically a reinstall via manual mode. Would that do the trick?

**Comment by snowie2000** [comment]
Even if you selected a profile and applied it, it only affects applications running with MacType (manually enabled via drag-drop to macloader.exe/macloader64.exe or any other possible methods).
Plus, you did a system restore which surely reverted all the changes made by mactype installer, and there is no reason it still drags system speed down.

**Comment by sammilucia** [comment]
Closed as I don't believe this is an issue with MacType. However, please be aware:
- There are problems with the Custom install of MacType 2017_628 - please use Typical install instead

**Comment by LaiNguyen** [comment]
happened same to mine machine. Everything significantly slow down after installing MacType from its official website. I'm using window 10. Strongly recommend not to install this app.
