### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ssray23** [snowie2000/mactype#375]
Hi,

Lately, I have noticed that MacType consumes high CPU on my laptop running Win 10 Pro. 

![image](https://user-images.githubusercontent.com/8319449/32377761-9730cd3e-c0a0-11e7-9a52-17e03e9db7ca.png)

The task bar often becomes non-responsive in this situation (i.e. nothing happens on clicking) and I have to wait for couple of minutes before the applications comes back to focus.

I am using the portable build taken from here:
http://www.mactype.net/station/?dir=Portable

Is there anything I can do to reduce CPU usage for MacType?

Thanks,

**Comment by snowie2000** [comment]
Actually, this is a bug of Windows where sometimes it costs significant
amount of time to create snapshot of processes.
In case this happened, you have to switch to registry mode or fully disable
mactray from refreshing process list by setting refresh interval to 0 in
the setting.

**Comment by ssray23** [comment]
Setting refresh interval to zero seem to have helped! 

Thanks,
Suddha

**Comment by sammilucia** [comment]
Closing issue
