### ISSUE TITLE
一个不能完全加载ini效果的bug

### ISSUE THREAD

**Issue by jorismq** [snowie2000/mactype#378]
下载了一个ini，用最新版2017.628加载了以后，很多效果没有，例如字体加粗，阴影什么的。但是，神奇的是，我把ini里面的；开头的注释语句全部删除了以后居然可以了！！！
什么问题？？
win10 1709

**Comment by snowie2000** [comment]
新版本使用了一个新的ini解释器，有更快的解释速度（为了提高mactype的启动速度），但是新的解释器的兼容性显然没有Windows原生的好。可能一些特殊的符号等影响了他，使他不能正常解析你的配置文件。

**Comment by sammilucia** [comment]
@snowie2000 the new parser supports unicode?

**Comment by snowie2000** [comment]
@sammilucia It should be. I tested it using Unicode LE/UTF-8/UTF-8 with BOM/ANSI and they all worked.
However, I'm not sure if all special characters can be parsed correctly. More samples are needed for that.

**Comment by snowie2000** [comment]
@jorismq 如果你能提供一下不能正确解析的ini配置的供我测试的话，应该可以解决掉这个问题。

**Comment by sammilucia** [comment]
Resolved by https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4. Please let us know if problems continue. Closing issue.
