### ISSUE TITLE
Cent Browser support

### ISSUE THREAD

**Issue by hootenannymagic** [snowie2000/mactype#380]
Hi,
My Cent Browser (2.9.4.39) doesn't work with Mactype 1.2017.1017.0 (June 28 '17). I switched to Cent from Chrome because DirectWrite was f***ed up, but I dont know what to do now that Cent doesn't work with it. I've had` --disable--directwrite-for-ui` & `--disable--directwrite` in Cent startup settings and disable the chrome://flag, still doesnt work. 
I have the Default profile in Mactype on.

Dunno if this is a bug or just me struggling with directions...
(other programs work perfectly)

**Comment by nguyenbathanh** [comment]
It is working for me. Just disable direct write flag in `chrome:://flags`.
![image](https://user-images.githubusercontent.com/4046112/33517401-5a924b32-d7b6-11e7-98ca-93b9b2e402cf.png)

**Comment by hootenannymagic** [comment]
@nguyenbathanh Thanks for the reply, are you using the CTP version? I am on Windows 10 still on 1511 and fonts on Cent still isnt working. Can you also tell me your profiles?

**Comment by nguyenbathanh** [comment]
I'm using Mactype  [v1.2017.628.0](https://github.com/snowie2000/mactype/releases/download/v1.2017.628.0/MacTypeInstaller_2017_0628_0.exe) running in Registry Mode and Windows 10 Creators Update (build 1703). Cent browser version 2.8.3.58 (Official Build) (64-bit) (Chromium 60.0.3112.101). All I did is just disable Disable direct write flag in chrome settings.

**Comment by nguyenbathanh** [comment]
This also works with newest version of Cent Browser (Chromium 62).
