### ISSUE TITLE
system unstability

### ISSUE THREAD

**Issue by u2em** [snowie2000/mactype#381]
i made up mactype with the directwrite full injection and registry injection. it looks fine.

but after system reboot, looks like sttutering display
  and forced logout soon as possible within about 1-2 minutes.

logout, so it might unable to any works including launch the task manager to kill some annoying process.

**Comment by garoto** [comment]
Stop using registry injection method?

**Comment by vrships** [comment]
This was the issue for me when I activated Mactype with the Japanese patch on Windows 10 1709 (All previous version are fine). The display driver would fail to load and the screen blacked out and kicked me back to log screen. Basically I uninstalled mactype and reinstalled it without any other patch then it became OK. But I no longer have DW support for UWP apps.

**Comment by snowie2000** [comment]
Stop using registry mode if you encounter any compatibility problem.

**Comment by u2em** [comment]
Currently using mactype as Service mode, resulting no more crashing.

**Comment by azizzaamir** [comment]
Patched version 1.26
Windows 10 1709 creators fall update
Still having issues some apps not working. Tried using both tray and service mode
Please any solution?

**Comment by sammilucia** [comment]
Closed, as service mode is recommended for Windows 10 (see https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2)
