### ISSUE TITLE
serious bug!

### ISSUE THREAD

**Issue by hellotuitu** [snowie2000/mactype#382]
I install mactype today(11.13) with changing  registry and many softwares crashed.After every crash, windows will let me login again.Now, I can't uninstall mactype because mactype will crash too...I really need help.

**Comment by snowie2000** [comment]
This is a well-known bug or defect or glitch if you would like to say that. Some system processes in some specific environment are not compatible with MacType. The best solution so far is to switch mactype to any other modes other than Registry mode.

I'll try to improve the compatibility of the registry mode in the later build.

**Comment by hellotuitu** [comment]
thanks for your reply.the problem is I can't even open mactype itself, so I can't switch mactype to any other mode.is there ant other solutions?I guess I have to reinstall my OS...

**Comment by snowie2000** [comment]
Reboot into safe mode and you can do that there.

**Comment by hellotuitu** [comment]
thanks, I will try that.

**Comment by vrships** [comment]
You only got this problem in 1709, right? Were the previous windows versions good?

**Comment by hellotuitu** [comment]
it was the first time I install mactype，so I don't know whether previous versions were good.

**Comment by xldistance** [comment]
Don't use registry  model，I have this proble too。。。。。。

**Comment by sammilucia** [comment]
This is a known problem with the installer logged in #428 ... Please choose a Typical install and **not** custom install for now.

Closing issue as duplicate.
