### ISSUE TITLE
mt64agnt.exe high cpu usage

### ISSUE THREAD

**Issue by dptr** [snowie2000/mactype#383]
![image](https://user-images.githubusercontent.com/3236685/32978019-5b67cd72-cc74-11e7-9ff4-5032efaa6875.png)
It costs cpu periodically, 13% or above is often.

**Comment by dptr** [comment]
can it be optimised?  what does mt64agnt.exe do when it is consuming CPU ?

**Comment by snowie2000** [comment]
1. It is scanning for new x64 processes. As you can see, Mactray.exe is an x86 process which has no privilege to operate x64 processes, which means an x64 agent/proxy process is required. mt64agnt.exe is the process here.
The resource consumption varies from systems. If you want to disable the scan process, set 0 for refresh interval via MacTray settings menu.

2. Maybe it can be optimized, I just don't know how. So it won't happen in the near future unless someone contributes that piece of code to me.

**Comment by sammilucia** [comment]
MacTray has been optimised in the new beta https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2

Closing issue, but please let us know if this is still a problem 😊
