### ISSUE TITLE
Uninstall Issue

### ISSUE THREAD

**Issue by daniel-fink** [snowie2000/mactype#384]
In trying to uninstall 2016.904.0, I think I'm missing "mactype.x64.msi" file located in 
\AppData\Local\Temp\MacType\install\8E66446\ (Which is empty)

See image:

![capture](https://user-images.githubusercontent.com/32397975/33134658-4c94dcfc-cf6e-11e7-8a34-2467c9272677.JPG)

How do I go about getting the .MSI file, or is there another way to uninstall?

Thanks!

**Comment by snowie2000** [comment]
Rerun the installer, it should give you the uninstall option.

**Comment by daniel-fink** [comment]
Thanks for the prompt reply. I get a
`Error applying transforms. Verify that the specified transform paths are valid`
error on attempting to install from MacTypeInstaller_2016_0904_0.exe

**Comment by daniel-fink** [comment]
Should I try installing from the 0902.1 build?

**Comment by snowie2000** [comment]
It won't work since these two installers are not fully compatible.
Use installer cleanup to clean it and reinstall it from installer (although I don't think you can run the installer...)

**Comment by sammilucia** [comment]
Closing this issue as installer 904 is obsolete.
