### ISSUE TITLE
mactype与sublime3143冲突，导致plugin_host经常出错

### ISSUE THREAD

**Issue by xldistance** [snowie2000/mactype#386]
有人能解决这个BUG吗

**Comment by snowie2000** [comment]
这么模糊的错误信息，恐怕没有人能够帮你。

**Comment by xldistance** [comment]
就是有时plugin_host可以正常启动，有时在process explorer里面显示暂停。导致sublime的插件都无法启动......

**Comment by YunHsiao** [comment]
我也用的是3143，mactype 2017.0628，windows 7 64bit，一直正常使用，可能不是mactype引起的问题.

**Comment by sammilucia** [comment]
@xldistance 你可以安装新的测试版，如果这个问题仍然存在，请告诉我们吗 can you please install the new beta and let us know if this issue still occurs? https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2

(auto-translated)

**Comment by sammilucia** [comment]
Closing as abandoned. Please let us know if you still have this problem with beta2 https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2
