### ISSUE TITLE
Win10 1709 ，2017.628 版本 印象笔记 6.8.7.6387 渲染失败

### ISSUE THREAD

**Issue by pzxiaoyi** [snowie2000/mactype#390]
印象笔记自己更新成现在的最新版，渲染失效了。

**Comment by iambalajis** [comment]
在托盘模式下使用，不使用mactype补丁。有用

**Comment by pzxiaoyi** [comment]
@iambalajis 不使用补丁的话，Chrome又无法渲染。

**Comment by iambalajis** [comment]
修补程序在1709年在镀铬。但是我得到一个werfault.exe错误。一旦我压制WER，没关系。

**Comment by tanhx** [comment]
把不希望或者不能由MacType接管的程序加到配置文件的“[UnloadDll]”段中。

**Comment by sammilucia** [comment]
Evernote Desktop is now working with the new beta4 😊 https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4. Please let us know if you have further problems. Closing issue

![image](https://user-images.githubusercontent.com/3295286/47212721-8a3a1f00-d3e0-11e8-974f-456adb926a8c.png)
