### ISSUE TITLE
Flickering cut-off of top pixels

### ISSUE THREAD

**Issue by UserNaem** [snowie2000/mactype#391]
Windows 7 Service Pack 1
Resolution:	1920 x 1080
MacType version:	1.2017.628.0
MacTray version:	1.0.5.2048
MacTuner version:	1.0.2.350

Certain fonts of certain sizes appear as if their top line has been cut off. Also, in Firefox's developer tools it's possible to make the top line "flicker".
Firefox's about:config settings:
gfx.direct2d.disabled;true
gfx.content.azure.backends;direct2d1.1,cairo
Video: https://a.safe.moe/Wg5gD.webm
Screenshot (cut off):
![mpv-shot0001](https://user-images.githubusercontent.com/21028464/34378448-9d63eab4-eb17-11e7-855e-9a60d5c938a6.png)

**Comment by snowie2000** [comment]
Set clipboxfix to 1 will fix the problem, but don't make it global. It conflicts with some programs.

**Comment by UserNaem** [comment]
Thanks, that fixed it. I wish there was better documentation to how to use this, I had to search the existing configuration files.
