### ISSUE TITLE
server returned when installing

### ISSUE THREAD

**Issue by lutein** [snowie2000/mactype#392]
![image](https://user-images.githubusercontent.com/21138938/34465733-63d8638c-eef6-11e7-99d5-e893e60c7d87.png)

retried many times, how to deal with this error?
Thx.

**Comment by snowie2000** [comment]
This should be something gone wrong with your installer service. I don't
have any known method to solve it, but you can use portable version
instead.

**Comment by sammilucia** [comment]
Hi @lutein , can you please tell us the full version of Windows Server? You can type `WINVER` from the Run prompt to find out easily.

**Comment by sammilucia** [comment]
Closing as the installer is being replaced see #443
