### ISSUE TITLE
Installed 628.0 in registry tray, apps won't launch, no uninstaller

### ISSUE THREAD

**Issue by RWTucker** [snowie2000/mactype#393]
After installing v. 628.0 to Win7-64,  IE and associated software no longer launches (MS Office, Avast, Notepad, etc, etc). Pretty much all .exe files no longer launch. Tried using add/remove but just get error windows in Chinese (sorry, only understand English). Cannot open any Downloaded apps that might help uninstall it...can only download and save them.  Went to C:\program files\ mactype and there is no uninstall file! After much web searching trying many options (tried to reinstall mactype, but cannot do that either. I'm not a coder, just trying to get my pc back without reformatting the drive.

**Comment by sammilucia** [comment]
Hey @RWTucker - sorry I thought responded to this. Please try installing again as a Typical install (not custom). Please re-open this if that doesn't fix the issue.
