### ISSUE TITLE
DLL Signing Virtualbox

### ISSUE THREAD

**Issue by DOFfactory** [snowie2000/mactype#396]
Hi Guys, I discovered and installed MacType just recently. It took me a while to realise that it is MacType which produces an error in Virtualbox. More details here: https://forums.virtualbox.org/viewtopic.php?f=6&t=86326

Just for the record, the users provide a solution by adding the following lines to MacType.ini:
```
[UnloadDll]
VirtualBox.exe
VBoxSvc.exe
```

However, there is an additional recommendation worth noting:

```
You might want to contact the MacType people and mention the importance of signing their DLLs if they intend to behave like malware! At least they have the exclusion option.
```

Would be great to implement this for security reasons?

**Comment by snowie2000** [comment]
@DOFfactory We all know the importance of digital sign and we also know the price of it.

**Comment by sammilucia** [comment]
Won't fix for now. Please donate if you want MacType digitally signed! 😊
