### ISSUE TITLE
strange text on "apply changes" window

### ISSUE THREAD

**Issue by s1nceri7y** [snowie2000/mactype#398]
![screenshot_1](https://user-images.githubusercontent.com/23638148/35296430-09fc4d3a-008d-11e8-8993-deab3b162fb8.png)

how i can see, there is no code of MacType wizard on this repo, but nevertheless:

- there are the same hotkeys on each buttons ("Close" and "Cancel", 'c' key)
- there is strange text before the butttons ("Click OK to apply" when we have "Close" button")

**Comment by snowie2000** [comment]
Thanks. It is a problem with my translation file. I'll fix it.
