### ISSUE TITLE
firefox 58 can't working?

### ISSUE THREAD

**Issue by gs180** [snowie2000/mactype#400]
as title. 57 ota to 58 or delete all 57 setup new version 58. after Manual config, both way can't make 58 working on mactype. what happened? ( go back to 57 work fine) ,(as mactype run as adminstrator).

**Comment by IceMan81** [comment]
@gs180 What is the issue that you see with FF 58? Maybe a screen shot will help.

**Comment by gs180** [comment]
Thanks for reply. as you seeing. after firefox 58. it maytype keep doing running and disabled for firefox.
(before 57 never being like this). what happened?


![image](https://user-images.githubusercontent.com/35795432/35494314-ca20c9a4-04f4-11e8-8c64-1eba9a5808ff.png)

![image](https://user-images.githubusercontent.com/35795432/35494339-f7156ee2-04f4-11e8-93b7-beabe84b5bef.png)

**Comment by Explorare** [comment]
As is discussed in issue #376 , Firefox 52+ has changed from Cairo to Skia for canvas/content rendering. You can disable Skia to make MacType work again on Firefox.
The steps to disable Skia is described in the following post.
[url=https://support.mozilla.org/en-US/questions/1181704]Why does the text (only in firefox) look like i'm using a PC from the 90's? It worked fine before. | Firefox Support Forum | Mozilla Support[/url]

**Comment by gs180** [comment]
as i said. i did all modify ( 57 is work fine). after 58. not.

**Comment by Explorare** [comment]
![image](https://user-images.githubusercontent.com/5090766/35598433-51a254e6-065e-11e8-921a-3d4555b47c49.png)

Firefox Dev 59.0b5 (64-bit)
Windows 10 Enterprise 16299.192
MacType 1.2017.628.0

![image](https://user-images.githubusercontent.com/5090766/35598477-91892832-065e-11e8-8921-720cf65f342d.png)

**Comment by gs180** [comment]
Thanks for reply. i'll try the beta.  still don't know what happened in 58. downgrade to 57 again.
Win 10 home single language.
Mactype 1.2017.628

**Comment by autocar23** [comment]
Found this would help : http://mozilla.com.cn/thread-382070-1-1.html 
I've successfully opened MacType on Firefox 58.
Basically just change the "gfx.content.azure.backends" from "direct2d1.1,skia,cairo" to "direct2d1.1,cairo" and change the "gfx.direct2d.disabled" to true then it works. 

My setup:
Firefox 58.0.2
MacTypeInstaller_2017_0628_0.exe
Windows 10 1709

**Comment by snowie2000** [comment]
Deleting all backends except "cairo" and turn direct2d off should force firebox to run on GDI again.
