### ISSUE TITLE
Fonts lack weight (MacType on Chrome on Windows 7)

### ISSUE THREAD

**Issue by kiwi0fruit** [snowie2000/mactype#402]
When MacType on Chrome (v64) on Windows 7 x64 (default profile, MacType v1.2017.628.0) fonts are rendered by MacType - they actually stop being distorted by ClearType. But they are of another weight than fonts in other programs - seems like MacType font weight settings are not applied. Is it a known bug/feature? What can be done?

**Comment by duprat** [comment]
1. Launch Chrome using the `-disable-directwrite-for-ui` command switch. This will force the top UI (tabs, address bar, toolbar) to render using MacType.
2. Install Stylish and create the following style (make sure “applies to everything” is checked):
```
* {
    -webkit-text-stroke-width:0.3px;
    text-rendering: geometricPrecision;
    text-shadow: 0px 0px 0.25px #999;
}
```

**Comment by kiwi0fruit** [comment]
@duprat I don't really care for menues - they look OK. I tried Stylish and it's not I want. It doesn't resemble MacType in other programs. And it definitely makes fonts look worse.

So it's a known limitation of MacType on Chrome, isn't it?

**Comment by duprat** [comment]
Yup, Chrome 52 removed [native GDI support](https://bugs.chromium.org/p/chromium/issues/detail?id=579678).

Your best bet is to use a GDI-compatible Chromium fork (e.g. Chengdu-based [Cent Browser](https://www.centbrowser.com/history.html) – which is unfortunately closed source, though nothing out of the ordinary happened during my extensive VM testing.) or to build your own.

**Comment by kiwi0fruit** [comment]
@duprat Cent Browser doesn't look enough trustworthy :) So the best solution seems to change to `NormalWeight=4` (from 16). So that all programs look the same.

**Comment by kiwi0fruit** [comment]
@duprat Thanks for help anyway! PS. I even start to like `NormalWeight=4` more than `NormalWeight=16`. I guess it can be OK even for CJK if using Noto fonts (just a guess).

**Comment by kiwi0fruit** [comment]
Nope. Less than `NormalWeight=8` is bad for rendering fonts like Times New Roman.

**Comment by kiwi0fruit** [comment]
Here is [the way I fixed](https://github.com/kiwi0fruit/open-fonts#stylebot) too thin fonts in Chrome (I used open source Stylebot extension to swap fonts).
