### ISSUE TITLE
FF vs Cent (AdvChrome): Cent has no shadows

### ISSUE THREAD

**Issue by Gentle888** [snowie2000/mactype#403]
![image](https://user-images.githubusercontent.com/32046895/36356020-082e6aa2-150e-11e8-842b-84d9c118ec63.png)

Right is Waterfox, left is Cent. As you can see, Cent renders no shadow. Advanced Chrome doing same. Is there any way to turn shadows, defined by my preset, on on any of these Chromium-based browsers?

**Comment by rudolphos** [comment]
This is how it looks for me
FF and Cent
https://i.imgur.com/30LS1aN.png

**Comment by Gentle888** [comment]
What preset you were using and what is your mactype setup?

**Comment by rudolphos** [comment]
I'm using Default profile and mactype is working in registry mode

**Comment by sammilucia** [comment]
As far as I know github never had text shadows ... this looks to be peculiar to waterfox.

Closing issue as I don't believe it's a bug in MacType, please let me know if I'm mistaken1 😜
