### ISSUE TITLE
Rendering failed in Age of Empires - Definitive Edition 在帝国时代-终极版 中导致字体渲染异常

### ISSUE THREAD

**Issue by tianzry** [snowie2000/mactype#406]
Once I turn on this app by Tray Mod with default config,  the font of the game Age of Empires - Definitive Edition rendered failed and even display strangely.
微软2月20日出的Age of Empires - Definitive Edition游戏中，托盘模式开启字体渲染会导致游戏文字显示异常以及无法显示的错误。使用托盘模式以及默认的配置。

**Comment by pzhg** [comment]
AOEDE的确不兼容mactype，在配置文件中exclude AOEDE.exe即可

**Comment by sammilucia** [comment]
Added this issue with #426 - closing duplicate.
