### ISSUE TITLE
在cmder下会把按键p变成e

### ISSUE THREAD

**Issue by tanhx** [snowie2000/mactype#407]
cmder: 1.3.5
mactpype: 1.2017.628.0
os: windows 10专业版16299
现象：
有一定几率出现在Cmder里把按键p变成e
更小的几率把r也变成e.
关闭mactype后没发现这个问题。

现在只好把Cmder和ConEmu放排除列表里了。

**Comment by snowie2000** [comment]
从hook的原理来说，根本就不可能修改键盘按键。

**Comment by tanhx** [comment]
我也纳闷呢，可这就发生了。

**Comment by vimcaw** [comment]
会不会是渲染出问题了，只是把p显示成了e，你新建个git项目试试 `git commit -m pppppprrrrrrrrrr`，关闭 Mactype 后看看 commit 信息是 p 还是 e。

**Comment by tanhx** [comment]
确认是"Clover 3"造成的。
这个软件还造成了双屏中第二个屏幕显示异常，现象是第二屏中，任务橍不在下端而是在屏幕中部。

**Comment by luantu** [comment]
> 确认是"Clover 3"造成的。
> 这个软件还造成了双屏中第二个屏幕显示异常，现象是第二屏中，任务橍不在下端而是在屏幕中部。

最终如何解决？卸载Clover3？

**Comment by luantu** [comment]
@tanhx

**Comment by luantu** [comment]
@tanhx  我这边也尝试过卸载clover3 但是问题依旧。。取消mactype渲染立刻就恢复。

**Comment by tanhx** [comment]
> > 确认是"Clover 3"造成的。
> > 这个软件还造成了双屏中第二个屏幕显示异常，现象是第二屏中，任务橍不在下端而是在屏幕中部。
> 
> 最终如何解决？卸载Clover3？

正解
