### ISSUE TITLE
MacType Tray crashing in Cairo Shell

### ISSUE THREAD

**Issue by Gentle888** [snowie2000/mactype#408]
Explained here:

https://github.com/cairoshell/cairoshell/issues/86

**Comment by mdmk** [comment]
Cairo Shell is an alternative shell for Windows.
It takes inspiration from macOS (and Cairo Dock I think,, hence the name).
Access violation errors happen when mactray icon is hovered in Cairo system tray.
The error is related to mactray app itself, not mactype font smoothing.
Even with font smoothing deactivated, mactray crashes when hovering tray icon in Cairo notification zone.

![35641166-b5c37192-06bf-11e8-989a-c53d720d2e93](https://user-images.githubusercontent.com/32496803/37371248-0a664aa2-270f-11e8-87c7-e878c0699e18.png)

**Comment by snowie2000** [comment]
That may be a problem from the TTrayIcon component I used in the mactray app. It obviously doesn't have the shell compatibility in mind when developed.

**Comment by Gentle888** [comment]
So, there is no workaround from this? Can there be option to hide tray icon and use tray mode?

**Comment by mdmk** [comment]
https://github.com/cairoshell/cairoshell/issues/86
A workaround has been found.
With the latest Cairo build Mactray does no longer crash.
You can close this issue.

**Comment by snowie2000** [comment]
Another workaround is to use service mode, which is almost identical to the tray mode with no tray icon.
However, the service mode is able to render logon window and doesn't need multiple instances to support multiuser.

**Comment by snowie2000** [comment]
Before the latest release, service mode is able to inject to more processes than tray mode simply because there are higher privileges for services. 
But as the latest version, I limited the ability to inject to system processes, and I think they are now much closer in behavior.
