### ISSUE TITLE
PDF Reader compatible with MacType

### ISSUE THREAD

**Issue by kiwi0fruit** [snowie2000/mactype#413]
I've noiticed that MacType font rendering is better that in Chrome PDF viewer and in Sumatra PDF. Do you any good PDF readers that use default Windows font renderer (ClearType) and is compatible with MacType so when using them together with MacType we would get the best font experience?

P.S. I guess it also should be either maintaned app (with rapid bugfixes) with rich functionality or non-maintained app with rather small funcionality (so that it cannot have vulnerabilities).

P.P.S. I haven't found such reader but among others the best seems to be Chrome Reader...

**Comment by InsOnYou** [comment]
福昕 PDF Reader

**Comment by kraml** [comment]
If you just need a PDF reader for reading without any fancy features, then browsers such as Firefox/Chrome/Edge actually provide better experience in terms of smoothness(scrolling and zooming, not font rendering) than those PDF readers.
