### ISSUE TITLE
Help with Mactype - Can't start programs

### ISSUE THREAD

**Issue by RW66** [snowie2000/mactype#415]
Hi - Apologies if this has been covered in previous threads. I'm not great with this program but love what it does.

I have installed MacType 2017_0628 and then used the MacTypePatch 1.20. With this it works with Firefox 59 which is important but unfortunately when its running I'm unable to open programs such as steam, adobe reader or origin. The second I disable MacType they all open again. 

Is there something I'm missing to get it working properly?

**Comment by snowie2000** [comment]
Try service mode or tray mode instead.
And I'm working on a better way to avoid injecting into system processes right now, a beta release is planned. Hope it will relieve this kind of problems.

**Comment by RW66** [comment]
Unfortunately neither of those modes work. Appreciate the hard work though and look forward to trying the beta when its ready.

**Comment by snowie2000** [comment]
Did you any error report for the applications you can't open?

**Comment by RW66** [comment]
I'm afraid not. Nothing happens at all when you click to open them. As soon as you disable mactype, they go back to working just fine.

**Comment by sammilucia** [comment]
Hey @RW66 ... For Steam you can modify the shortcut to add "-no-cef-sandbox", which fixes a conflict with the web engine in Steam and MacType. You will need to launch Steam from the icon each time, before loading a game, for this to work.

There is also an option in Steam Settings -> Interface -> Unitck "Enable DirectWrite" which then fully uses MacType / GDI for font rendering.

Adobe Reader can be solved by going back to an earlier version of Reader, or using a different program. I actually just use my browser.

**Comment by sammilucia** [comment]
@RW66 can you please try the latest MacType-Patch 1.26 from here https://silight.hatenablog.jp/entry/MacTypePatch and let us know if the problems continue.

Closing issue until we hear back.
