### ISSUE TITLE
Problem with horizontal lines using latest mactype

### ISSUE THREAD

**Issue by matthewadamsdk** [snowie2000/mactype#417]
Hey there folks, I'm using the latest mactype 1.17.0628 on a 64bit Windows 10 ver. 1709. The ini I'm using is the "LCD.W7.默认字体.仿Mac.ini".

We use the Mathematics program "Maple" extensively at my workplace, and - depending on the zoom used on the screen - the equals signs become illegible, ie. the second of the 2 horizontal lines fades away. As you might expect, this can pose a problem when showing my students how to solve a problem in Maple...

1. I can't disable mactype for Maple, because the fonts then look hideous.
2. I won't use another ini, as this one suits my preferences for the rest of my work on this computer perfectly.
3. It would be a huge help if the equals sign is legible for all zoom factors.

So my question: is there a particular setting in the ini file I can tinker with to make the equals signs more legible?

Thanks in advance
Matthew A.

![mactype-horizontal-lines](https://user-images.githubusercontent.com/22302334/38916975-98596ba0-42e9-11e8-8ebe-b313a480064f.png)

**Comment by matthewadamsdk** [comment]
Thanks a lot for your reply - I haven't seen the clipboxfix option before. I'll give it a try. 😊

**Comment by snowie2000** [comment]
I tried really hard to make new clipboxfix implementation compatible with every application and now I have to say, some programs are born to be not compatible with this option.
They simply arrange text layout strictly with clip box of every letter and characters. Any tiny change of clip box will affect their display. You can't maintain the clipbox of the font unchanged while you want your font display unhinted.
Yes, I'm talking about "Wolfram Mathematica". And there should be plenty of them.
Anyway, I'll still deliver the new implementation in the new release for it at least increased its effective range, but I wonder if I should set it enabled as the default option.

**Comment by IceMan81** [comment]
@snowie2000 Are you saying that the new implementation will be better than the existing one but there will still be a bunch of programs that are going to have clipped fonts?

**Comment by snowie2000** [comment]
I meant to create a solution that fits all scenarios. It will fix the font clip problem while maintaining its compatibility. But looks like it is not gonna happen anytime soon or it is impossible from the beginning.
Fonts will, of course, be clipped if the option is off as what it is right now. If the option is on, fonts won't get clipped, but some of the programs will have unexpected behavior.
As far as I know, the "Wolfram Mathematica" program will have a taller line gap than it should be as stated in issue #151. While other programs I tested so far behavior normally, there is really no guarantee.

**Comment by snowie2000** [comment]
And text actually not just got clipped on top and bottom, it also got clipped on left and right.
See image in this issue #282.

Currently, MacType only enlarges the Y value of API GetGlyphOuline, I don't know what will be the impact to other programs if I modify the X value at the same time.

**Comment by IceMan81** [comment]
Ah yes, you are referring to the issue I had with PragmatPro ligatures! 
I'll be more than happy to test your new impl when you are ready with it.

**Comment by rudolphos** [comment]
I'm having the same problem in matlab
![image](https://user-images.githubusercontent.com/4366810/39767581-c8933baa-52ef-11e8-9402-8d7fbf3da2b4.png)

**Comment by snowie2000** [comment]
I'm really want to help, but Matlab is real real real to big for me to install.

Sorry for that. :crying_cat_face:
