### ISSUE TITLE
UseInclude白名单选项BUG

### ISSUE THREAD

**Issue by langf** [snowie2000/mactype#418]
请教下，为何在加入白名单选项后，白名单外的程序状态在“已停用”“已启用“不停的切换刷新
系统为win10 1709  16299.431   程序版本为MacTypeInstaller_2017_0628_0
谢谢
[General]
UseInclude=1

[IncludeModule]
firefox.exe

**Comment by langf** [comment]
测试了一下，发现只是特定的几个进程会不停的切换状态，直接丢进白名单就好了
[IncludeModule]
ApplicationFrameHost.exe
explorer.exe
firefox.exe
RuntimeBroker.exe

**Comment by snowie2000** [comment]
Closing since the new process capture mechnism won't do polling anymore, this bug should be gone.
