### ISSUE TITLE
Mactype service mode may cause KB4100403 update failing.

### ISSUE THREAD

**Issue by guikarist** [snowie2000/mactype#421]
I had tried to update the second cumulative update for Windows 10 version 1803 (KB4100403) many times. However, at all times I failed to restart but saw a black screen with only a blue-circle 'busy' pointer on it.
Then I used system restoration to restore, stopped the Mactype service and updated again. This time everything worked fine.
I think probably Mactype service conflicts with this update.

**Comment by xbipin** [comment]
yes its an issue if u run mactype as service, to update system first disable mactype service, let update run and when rebooted u can enable service again but make sure u keep it at delayed start, this will prevent black screen with just blue circle at boot

**Comment by sammilucia** [comment]
Hi, this should be resolved by beta4 ... Please try https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4. and let us know if problems continue. Closing issue.
