### ISSUE TITLE
Update Chocolatey repo

### ISSUE THREAD

**Issue by privettoli** [snowie2000/mactype#423]
https://chocolatey.org/packages/mactype is outdated. It would be nice to support it.

**Comment by sammilucia** [comment]
@snowie2000 do you know who maintains the chocolatey?

**Comment by sammilucia** [comment]
Hey @privettoli ... Thank you, it would be nice! However we don't maintain it unfortunately.

Please get in touch with the maintainers listed on the chocolatey page (gummesson or cole.mike) to see if they'll update it. Remember new builds are experimental (and may even prevent Windows from starting)... Also there is a newer build available at mactype.net/station.

I'm happy to coordinate with the choco maintainers, they can log an issue here if they need anything. Closing this for now as out of scope.
