### ISSUE TITLE
MacType_CTP_171017.rar prevents login on Windows 10

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#431]
To reproduce on WIndows 10 latest:
1. Install MacTypeInstaller_2017_0628_0.exe in Typical mode
1. Replace the DLLs with those from MacType_CTP_171017.rar
1. Start MacWiz.exe and configure MacType to start as Registry mode
1. Reboot

Expected result:
- Windows 10 logs in correctly

Actual result:
- Windows 10 hangs on logon screen

Notes:
- Does not occur when MacType is running as Service mode (Delayed Startup) or Tray mode.

**Comment by Mahayu** [comment]
Use service mode in Win10 latest version please, as registry mode surly cause this bug.

**Comment by Mahayu** [comment]
#319

**Comment by snowie2000** [comment]
Try the new beta release and see if it alleviates the problem.

**Comment by Hazealign** [comment]
@snowie2000 It works in new beta. Thanks :) 
p.s. I'm using Windows 10 1803 Build.

**Comment by sammilucia** [comment]
closing as resolved in 1.2018.917.0-beta2
