### ISSUE TITLE
instalation problem... what does mean?

### ISSUE THREAD

**Issue by apek123** [snowie2000/mactype#435]
![snag-18091311511300](https://user-images.githubusercontent.com/43236684/45481878-fa53e600-b74c-11e8-8452-dca3be5a4dd8.png)

instalation problem... what does mean?

**Comment by snowie2000** [comment]
For some reason, some of the text have not been translated correctly.  This part of the text mean there's another installation undergoing your system. You have to wait till it's finished to start this one.

**Comment by sammilucia** [comment]
closing as this will be resolved in the next installer
