### ISSUE TITLE
Beta(2)版默认不渲染Wechat和资源管理器

### ISSUE THREAD

**Issue by Mahayu** [snowie2000/mactype#437]
系统是 Windows10 1803
Mactype Beta2,Service Mode.
配置文件未排除对应进程。
可以通过Macwiz启用，但是每次启动十分麻烦。这是为什么？

**Comment by snowie2000** [comment]
默认情况下不渲染服务。如果进程是被services.exe启动的，则不会被渲染。
您可以提供下process explorer的进程树截图吗？

**Comment by Mahayu** [comment]
明日有空的时候会附上信息:)

**Comment by Mahayu** [comment]
![default](https://user-images.githubusercontent.com/22572355/45927188-c86b2c80-bf61-11e8-8319-2e54fba2c96e.png)

![default](https://user-images.githubusercontent.com/22572355/45927191-cef9a400-bf61-11e8-811b-1f93755e7b1d.png)

Wechat 复现失败..

**Comment by snowie2000** [comment]
@Mahayu 资源管理器的父子关系图可以提供一下吗

**Comment by Mahayu** [comment]
使用 wmic 查找了 explorer.exe 的父程序PID……不言而喻
![default](https://user-images.githubusercontent.com/22572355/45935012-07889480-bfd9-11e8-890f-556afac8d6f7.png)
![default](https://user-images.githubusercontent.com/22572355/45935013-08212b00-bfd9-11e8-8101-095d273c807f.png)
![default](https://user-images.githubusercontent.com/22572355/45935016-0eafa280-bfd9-11e8-9551-dad00dcb9572.png)

所以这个不会修？那我还是手动启动好了。

**Comment by snowie2000** [comment]
mactray有个白名单，我暂时关闭了
我会把他重新打开来解决这个问题

**Comment by sammilucia** [comment]
@Mahayu did you mean to close this? @snowie2000

**Comment by snowie2000** [comment]
@sammilucia I believe he did. Because I said I will solve it by reactivating the internal whitelist in the tray app.

**Comment by snowie2000** [comment]
您可以提供一下您的配置吗？我这边无法重现问题，白名单我检查了代码后确定本来就是开启的

**Comment by Mahayu** [comment]
[MMConfig_clear.zip](https://github.com/snowie2000/mactype/files/2423443/MMConfig_clear.zip)

**Comment by snowie2000** [comment]
We're waiting for another user's feedback to release the next version.

**Comment by snowie2000** [comment]
Could be the same problem with #441. 
Reopen it if you're sure they are different.
