### ISSUE TITLE
mactype candy

### ISSUE THREAD

**Issue by jgsports** [snowie2000/mactype#438]
我在自己的windows 10 1803专业工作站版里使用了mactype的candy改版 (http://sky.candy.moe/tag/mactype/) ，配置文件是xhei 热替换，能完美渲染setting界面、chrome等比较难渲染的东西，作者能不能参考下。

**Comment by sammilucia** [comment]
谢谢@jgsports ...你知道作者吗？ 如果他们加入主项目这样每个人都可以受益，那将是理想的选择 
(auto-translated)
Thanks @jgsports ... do you know the author? It would be ideal if he would join the main project so everyone can benefit

**Comment by snowie2000** [comment]
The candy version is a combination of MacType and MacType-patch. MacType has already implemented most of the DirectWrite hooks the patch does except the fontstitute feature which is planned in the next release.
Other DirectWrite features can be activated by setting a toggle: https://github.com/snowie2000/mactype/wiki/DirectWrite and settings: https://github.com/snowie2000/mactype/wiki/DirectWrite-section

Candy版本就是mactype+mactype-patch的组合，目前mactype已经实现了除了字体替换外的所有patch支持的dw功能。只要设置directwrite参数即可，请参见wiki。

@sammilucia You just need to write down the answer in English and @me in the comment, I'll do the translation for you.

**Comment by sammilucia** [comment]
Gotcha. I thought it was a new build.

**Comment by sammilucia** [comment]
Closing as question was addressed
