### ISSUE TITLE
与 Forza Horizon 4 冲突

### ISSUE THREAD

**Issue by bruceCzK** [snowie2000/mactype#442]
即使排除 ForzaHorizon4.exe 仍然会导致启动闪退。

配置文件 https://pastebin.com/80uxQT7E

**Comment by Skyyblaze** [comment]
I don't understand Chinese but if you try to get Forza Horizon 4 to run with MacType you have to use the newest MacType 2018 Beta 2 and add the game to you MacType.ini like this:

`[UnloadDll]
VBoxSvc.exe
VirtualBox.exe
ForzaHorizon4.exe
`

**Comment by bruceCzK** [comment]
@Skyyblaze Thanks, it works. 
By the way, I'm already running the newest version 2018.09.17-beta2. 
I only added `ForzaHorizon4.exe` to `ini/default.ini` previously, so I guess I have to add the same config to `MacType.ini` as well.

**Comment by Ironman998** [comment]
我在Mactype.ini和ini/Default.ini里都添加了
[UnloadDll]
VBoxSvc.exe
VirtualBox.exe
ForzaHorizon4.exe
结果还是打开游戏就闪退，请问您是怎么解决的？

**Comment by bruceCzK** [comment]
我已经卸载 MacType 了，现在看不到了2333，可能你选的不是 Default.ini 对应的这个配置吧。
