### ISSUE TITLE
Cannot translate Tuner preview window title caption

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#444]
I think this is supposed to be [TForm6] Caption but I could be wrong
![image](https://user-images.githubusercontent.com/3295286/46269494-a0db1c00-c580-11e8-95ed-a5084fb474fe.png)

If not I can't see where to change the window caption.
![image](https://user-images.githubusercontent.com/3295286/46269457-76895e80-c580-11e8-9454-696e63934bd5.png)

Low-priority, assigned to 'next version'

**Comment by snowie2000** [comment]
I may have forgotten to add this window to the language control list.
Planned.

**Comment by sammilucia** [comment]
Thx. Good news is I didn't find any others

**Comment by sammilucia** [comment]
Resolved by https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4. Please let us know if problems continue. Closing issue.
