### ISSUE TITLE
MacType Tuner preview window doesn't update second time

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#445]
The preview window in MacType Tuner updates when you edit the text the first time, but doesn't update subsequent times.
To repro:
1. Open MacType Tuner
1. Click Advanced
1. Click to edit text, and edit it
1. Click to edit text again, and edit it

### Expected outcome:
- preview text changes twice

### Observed outcome:
- preview text only changes the first time

**Comment by snowie2000** [comment]
Confirmed. Will be fixed before final release.
