### ISSUE TITLE
MacType tray menu won't open on WIn 10 skip ahead 18247

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#447]
Noticed some problems on the latest skip ahead (18247) MacType tray menu won’t open (beta 2 test)

_Originally posted by @alxtr1bal in https://github.com/snowie2000/mactype/issues/420#issuecomment-425799962_

**Comment by snowie2000** [comment]
Should be the same problem with #441. A deadlock related problem with the tray app.
Closing.
