### ISSUE TITLE
Virus threat on Mactype64.dll

### ISSUE THREAD

**Issue by drxt** [snowie2000/mactype#448]
Nothing more to say, Defender just picked this up. I hope this is a false positive.

https://i.imgur.com/6poHv9G.png

Is this related to the issue HookChildProcesses=0 workaround is supposed to fix?

**Comment by CHN-STUDENT** [comment]
![image](https://user-images.githubusercontent.com/21209416/46384482-c5ea9e80-c6e8-11e8-92dc-8e786ca940c5.png)
Yes,i meet this issue too.My system version is  Win 10 17134(1803),hope you can fix it.

**Comment by CHN-STUDENT** [comment]
@sammilucia I downloaded it from the github release page.The the window defender told me it has virus.
![image](https://user-images.githubusercontent.com/21209416/46385460-da319a00-c6ee-11e8-9613-6265b6bad99c.png)

**Comment by sammilucia** [comment]
Thank you for confirming.

Yes, Microsoft is reporting this as a false-positive. I can confirm files here on github.com/mactype are safe.

@drxt and @CHN-STUDENT, could you please go to https://www.microsoft.com/en-us/wdsi/filesubmission and submit this file for further analysis, to get Microsoft to de-list it.

Unfortunately we don't have direct control over what antimalware companies report as malware, and sometimes they get it wrong. You can help by reporting it as a false positive.

![image](https://user-images.githubusercontent.com/3295286/46386222-5338ed80-c6ff-11e8-8921-33e06f0c56b2.png)

**Comment by CHN-STUDENT** [comment]
Yes,i submitted the false positive to Microsoft,Hope they can recheck it again.Thank you!
![image](https://user-images.githubusercontent.com/21209416/46386515-6f835d00-c6f4-11e8-80a0-c8f851236614.png)

**Comment by sammilucia** [comment]
Thank you so much for your help @CHN-STUDENT !

@snowie2000 I've submitted this to MS also as a software dev.

**Comment by drxt** [comment]
Submitted sample to Microsoft, thanks for the heads up.

**Comment by sammilucia** [comment]
Thanks so much for your help @drxt 😊 it all helps 😊

**Comment by sammilucia** [comment]
Hi again all. Just confirming that Microsoft has removed the detection.

To force an update of your definitions:

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run `MpCmdRun.exe -removedefinitions -dynamicsignatures`

The latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thanks for your patience 😊. closing issue

**Comment by kiravi** [comment]
Cylance is still continuing to block Mactype as of Dec. 18th 2019
