### ISSUE TITLE
Total Commander process gives "Access Denied" on 1.2018.908.0

### ISSUE THREAD

**Issue by FrankEBailey** [snowie2000/mactype#450]
I updated my MacType to allow it to work with Firefox versions after 57, and everything was fine until I rebooted, and now Total Commander is not allowing MacType to access its process. It was working fine on the previous version, so this is possibly a new bug.

https://www.ghisler.com/download.htm

I've tried with the latest version, both 32 bit and 64 bit, and both give the "access denied" error.

**Comment by snowie2000** [comment]
Which mode are you using?
I found that the service mode is a little weird that it can't access some process while the tray mode can.

**Comment by FrankEBailey** [comment]
I'm using the tray mode :(

**Comment by FrankEBailey** [comment]
Just FYI, it turned out that the Tray mode wasn't running as an Administrator (I'd clicked the box but it either didn't save or I unchecked it later without noticing). When I ran it as admin the issue went away, so I'm closing this one. Thanks for your response, and have a good weekend.
