### ISSUE TITLE
Mactype install failed on Win10 EN

### ISSUE THREAD

**Issue by fonlan** [snowie2000/mactype#451]
公司电脑是Win10英文版，运行0628的安装程序时如果语言选简体中文则出现以下错误：
![cn_error](https://user-images.githubusercontent.com/7898348/46992800-72dc0700-d13e-11e8-8e36-5bf8599ed39d.png)
如果选英文则在写入ini的时候出现以下错误：
![en_error](https://user-images.githubusercontent.com/7898348/46992825-9acb6a80-d13e-11e8-9832-71b29da11161.png)

还有啥别的办法安装Mactype吗？文件可以手动放置，能不能给个命令行添加mactype服务的方法？

**Comment by snowie2000** [comment]
可以下载便携版http://www.mactype.net/station/?dir=Portable
添加服务可以通过向导自动进行。

另外新版的安装程序已经在制作中，未来将不会有这个问题。

**Comment by sammilucia** [comment]
Hi @fonlan, sorry for your issue, please follow snowie's comments and let us know if you get stuck, there will be a new installer soon.

Closing as covered by #443

**Comment by snowie2000** [comment]
@sammilucia Actually fonlan is the first publisher(if I can call that) and installer provider. He made the first installer for mactype (it was gdi++ back then) with inno (if I remember it right).
Later I took over the publishment and moved to AI.
Greetings @fonlan

**Comment by sammilucia** [comment]
@snowie2000 oh wow! hey @fonlan ! 😊 now we're back to Inno Setup! 😊

**Comment by fonlan** [comment]
Sorry for so stupid question. Just because company laptop's strict policy. It's the first time for Me to know the portable version. Thank you very much!

**Comment by sammilucia** [comment]
@fonlan not at all that's what we're here for!
