### ISSUE TITLE
The new COD wont launch with MacType enabled lol.

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#453]
_Originally posted by @Plaer1 in https://github.com/snowie2000/mactype/issues/426#issuecomment-430526245_

**Comment by sammilucia** [comment]
@Plaer1 what COD is it specifically?

**Comment by sammilucia** [comment]
Can you please try beta4 released just now and let us know how you go? https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4

**Comment by snowie2000** [comment]
Call On Duty 4 I think

**Comment by tuhz** [comment]
Yes I have seen several recently released games won't launch with MacType enabled, including the latest Call of Duty, the latest Forza Horizon 4, etc.

**Comment by sammilucia** [comment]
Closing - refrenced in #426
