### ISSUE TITLE
Wiki description for DirectWrite parameters

### ISSUE THREAD

**Issue by extratype** [snowie2000/mactype#454]
I find some of them incomplete or misleading.. as compared to the reference [IDWriteFactory::CreateCustomRenderingParams](https://docs.microsoft.com/en-us/windows/desktop/api/dwrite/nf-dwrite-idwritefactory-createcustomrenderingparams), [IDWriteRenderingParams interface](https://docs.microsoft.com/en-us/windows/desktop/api/dwrite/nn-dwrite-idwriterenderingparams).

It says `EnhancedContrast` (called `Contrast` in MacType) is the amount to increase the darkness of text. It does not only affect the edge. In my experience it makes whole text darker. This makes text a bit thicker as a side effect. If it is tuned too high the edge will become too sharp (looks aliased?) and colorful.

`ClearTypeLevel` is the degree of subpixel anti-aliasing. 0 for Grayscale anti-aliasing, 1 for full ClearType subpixel anti-aliasing. Zero value does not mean no anti-aliasing. I played it around and discovered it mostly affected saturation values of outline pixels. This and `EnhancedContrast` can be tuned together to reduce colorful edges.

**Comment by snowie2000** [comment]
Thank you for pointing it out.
Try to fiddle with it when I got time, or next monday at least.

**Comment by extratype** [comment]
Oh, that reminds me of [DirectWriteTester](https://silight.hatenablog.jp/entry/DirectWriteTester_1_01). I hope it is useful for you.

**Comment by snowie2000** [comment]
Sure thing. I'm totally a newbie to directwrite world.

**Comment by sammilucia** [comment]
Hmm, I think we could combine the wiki, release notes, and DW information to the main website ...

**Comment by sammilucia** [comment]
@extratype do you want to help writing the wiki? 😁 😁

**Comment by extratype** [comment]
I'll edit the wiki if I have spare time. I don't know typography, for this issue I just wanted to share my informal thoughts.

**Comment by snowie2000** [comment]
@extratype Would you mind to join us? 
There is no any kinda forced contributions here. You're totally free.

**Comment by extratype** [comment]
Thanks but I won't be active for MacType for months. I'd just raise issues or pull requests from time to time.

**Comment by sammilucia** [comment]
Fixed
https://github.com/snowie2000/mactype/wiki/ClearTypeLevel
https://github.com/snowie2000/mactype/wiki/Contrast
https://github.com/snowie2000/mactype/wiki/GammaValue
