### ISSUE TITLE
Status for GDI+?

### ISSUE THREAD

**Issue by extratype** [snowie2000/mactype#456]
I don't know the history, it seems support for GDI+ (gdiplus) had been suspended.
Applications today rarely uses GDI+ though...

**Comment by snowie2000** [comment]
I was thinking to add support for Gdiplus months ago maybe years ago, but there are barely any documentation about it. 
Gdiplus used a proprietary font engine which the Microsoft published  almost nothing about it.

**Comment by sammilucia** [comment]
You've probably already seen these:

[GDI+ API overview](https://docs.microsoft.com/en-us/windows/desktop/gdiplus/-gdiplus-flatapi-flat)
[GDI+ examples for text](https://docs.microsoft.com/en-us/windows/desktop/gdiplus/-gdiplus-text-flat)
[GDI+ methods](https://docs.microsoft.com/en-us/windows/desktop/api/gdiplusgraphics/nl-gdiplusgraphics-graphics)
[More examples](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/using-fonts-and-text)
And a [book from 2003](https://ptgmedia.pearsoncmg.com/images/0321160770/supplements/chand_colorfigs.pdf)

**Comment by snowie2000** [comment]
> You've probably already seen these:
> 
> [GDI+ API overview](https://docs.microsoft.com/en-us/windows/desktop/gdiplus/-gdiplus-flatapi-flat)
> [GDI+ examples for text](https://docs.microsoft.com/en-us/windows/desktop/gdiplus/-gdiplus-text-flat)
> [GDI+ methods](https://docs.microsoft.com/en-us/windows/desktop/api/gdiplusgraphics/nl-gdiplusgraphics-graphics)
> [More examples](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/using-fonts-and-text)
> And a [book from 2003](https://ptgmedia.pearsoncmg.com/images/0321160770/supplements/chand_colorfigs.pdf)

The real problem is that the GDIPlus uses a different layout engine which arranges letter differently from GDI, and I didn't find anything useful for it.

**Comment by sammilucia** [comment]
Ok got it. Close?

**Comment by snowie2000** [comment]
Closing as supporting it is not currently planned and this technology is no longer heavily used today.
