### ISSUE TITLE
How to Enable Color Fonts? Please Help.

### ISSUE THREAD

**Issue by CrossbowDemon** [snowie2000/mactype#458]
I do not understand how to enable color fonts.
Please explain it for each individual step by step.

As in, Explain It Like I'm Five.

**Comment by snowie2000** [comment]
It's simple.
Append
```
[experimental]
Colorfont=1
[experimental@chrome.exe]
invertcolor=1
```
to your profile (the chrome.exe setting is optional if you don't use chrome or you use it with DirectWrite enabled).
Then, download any color font (I suggest [Segoe UI Emoji](https://www.wfonts.com/font/segoe-ui-emoji) as it's made by Microsoft and known to be compiled with Microsoft layered color font standard).

Now, you can try to run the charmap application and check symbols of Segoe UI Emoji, you should able to see color emojis.
You can also copy&paste those emojis to notepad or any text editor as long as their support custom font. 
This is what you normally see:
![222](https://user-images.githubusercontent.com/11767189/47262581-fd49af80-d51e-11e8-8abc-ae42ff64d4e4.png)

And this is what you're expected to see:
![default](https://user-images.githubusercontent.com/11767189/47262579-d55a4c00-d51e-11e8-8e5d-5d321670d54d.png)

**Comment by sammilucia** [comment]
:+1: added to the wiki

**Comment by sammilucia** [comment]
Closing as answered. @CrossbowDemon please let us know if you have any questions at all 😊
