### ISSUE TITLE
explorer crashes when using ctrl+del to delete any file while mactypes service is running

### ISSUE THREAD

**Issue by xbipin** [snowie2000/mactype#459]
when PC is booted and mactypes service is running and after a while you try to delete any file using ctrl+del keys on keyoard, explorer keeps crashing but as soon as explorer is reloaded and you try again then it works fine and using same key combo after that keeps working till PC is restarted again. I noticed this issue since the public release of mactypes last year till date and also present on the beta4

**Comment by snowie2000** [comment]
There was a similar issue #433 which is eventually a bug of FreeType.
Could you please do a mini memory dump for explorer.exe on crash to see if they are the same?

If they are the same bug, we have to wait until freetype team fixes it.

**Comment by sammilucia** [comment]
Closing as abandoned. @xbipin please let us know if you can get that memory dump and we'll reopen
