### ISSUE TITLE
Beta 2018 10 19 - New installer could not create shortcuts in Start Menu

### ISSUE THREAD

**Issue by IgnacioMD** [snowie2000/mactype#461]
Hi, i had MacType 2017.0628, running as service. Without uninstalling the old version, i stopped the MacType service, and installed the beta 2018 10 19. The installer gave an error indicating that it could not create the shortcuts in the start menu. I can't acces to the folder C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Mactype by the permissions.. Windows don't display the owner of the folder, and don't allow me to modify the permissions.

My PC has Windows 8.1 x64 with all the critical updates.

**Comment by sammilucia** [comment]
Thanks @IgnacioMD for the detailed description ... In your c:\users\<yourfolder>\appdata\local\temp folder there should be a file called "Setup Log ???????.log" ... can you please post in here or DM it to me?

From your description it doesn't sound like you've had this problem before with any other software?

**Comment by sammilucia** [comment]
@IgnacioMD can you please open the C:\ProgramData\Microsoft\Windows\Start Menu\Programs folder and try to manually create a folder in there? (doesn't matter what it's called) ... do you get an error?

**Comment by sammilucia** [comment]
Hi @IgnacioMD thanks for the testing!

Yes the installer doesn't create an icon for MacTray.exe - @snowie2000 should it create this?

Hmm, there's not a lot I can do without a log... I made sure everything gets written to the setup log so I could diagnose stuff like this 😜

@IgnacioMD it's possible under some circumstances profiles won't be deleted. if you look Apps and Features, or Programs and Features, is there two entries for MacType in there?

**Comment by IgnacioMD** [comment]
Only one entrie: MacType Version 1.18.10.19-beta4 Size 9.96 MB

**Comment by sammilucia** [comment]
Thanks @IgnacioMD ... it sounds like it's removed the old version correctly and installed properly (except for the icons). Thanks for your efforts!

I think you've had a temporary problem which prevented writing to the C:\ProgramData\Microsoft\Windows\Start Menu\Programs folder. It's not possible to diagnose without the log unfortunately - since it's now working 😜

I'll wait to hear from @snowie2000 on whether a MacTray icon should normally be created.

**Comment by snowie2000** [comment]
I used to create icons for all the possible applications although I think an icon for Wizard is usually enough for loading MacType.

**Comment by sammilucia** [comment]
That's what I thought. Okay, closing issue
