### ISSUE TITLE
Calendar in Outlook2016 display wrong

### ISSUE THREAD

**Issue by fonlan** [snowie2000/mactype#462]
![2018-10-24_111604](https://user-images.githubusercontent.com/7898348/47404263-31bba680-d77f-11e8-8903-f4af5981c5ef.png)
Version：1.2018.10.19-beta4
System：Win10 X64 EN
Mode：Service Mode

**Comment by snowie2000** [comment]
Is it working with the previous beta? Since I introduced a nasty bug in this beta :-1:

**Comment by fonlan** [comment]
Previous I use CTP_171017. It works correctly. This is the first time for Me to use the beta version. So I didn't try previous beta.

**Comment by kraml** [comment]
I noticed the same issue on the latest 1.2018.10.19-beta4r2, and I don't remember seeing this on previous versions.

Here is how it looks like on my system, with beta4r2, with MacType enabled for outlook.exe. It does not look as bad as the original reporter's though.

![snipaste_2018-10-25_13-58-05](https://user-images.githubusercontent.com/358679/47479034-4a4ebe00-d85e-11e8-8156-f8e42157b784.png)

First I thought it is clipbox problem, but set the ClipBoxFix option did't help.

![snipaste_2018-10-25_13-59-03](https://user-images.githubusercontent.com/358679/47479036-4a4ebe00-d85e-11e8-871b-2480be145501.png)

And this is how it looks like with MacType disabled.

![snipaste_2018-10-25_13-59-34](https://user-images.githubusercontent.com/358679/47479039-4a4ebe00-d85e-11e8-8ed4-1f8df5ef27d5.png)

**Comment by snowie2000** [comment]
It should be the fixed by commit https://github.com/snowie2000/mactype/commit/99391a2170392c19fcc1765f78a2f0abdf71bd1b

**Comment by kraml** [comment]
May I ask when the next version with this fix will be released?

**Comment by snowie2000** [comment]
There are some known bugs waiting to be fixed and I need to test the directwrite branch. So probably the end of the next week.

**Comment by sammilucia** [comment]
Agreed. Resolved by #472, closing
