### ISSUE TITLE
Cent browser on Win 7 freezes when typing in the address bar with v1.2018.10.19-beta4

### ISSUE THREAD

**Issue by IceMan81** [snowie2000/mactype#464]
I have not had this issue before this beta release : my Cent browser freezes frequently when I'm typing in the address and my only resolution is a forced kill. 

This has happened a couple of times yesterday. I can't think of anything else that has changed. 
I'll try to create a memory dump and upload next time this happens, in the mean time I wanted to see if others have experienced this.

**Comment by sammilucia** [comment]
Hi @IceMan81 ... extensions update in the background and can introduce problems. As a test can you please disable all extensions for a day or two and see if the problem still occurs?

**Comment by snowie2000** [comment]
I use centbrowser every day, and it never happens to me.

**Comment by IceMan81** [comment]
I realized there was an extension added - IETab by corporate policy. This may be the culprit. Can’t imagine why it would interfere with typing in the address bar. 
I observed that the main render process would peg cpu at 12-13 percent consistently why this happens and I’m about to kill the process tree.

**Comment by snowie2000** [comment]
Add a password to your zip file should bypass the detection of github. 

Maybe I need to install an IEtab next time~

**Comment by IceMan81** [comment]
It happened now even with IETab disabled.  
Will try uploading again with pwd.

**Comment by IceMan81** [comment]
@sammilucia I'm running the new Cent browser betas and I haven't seen the issue the last few days. I would like to keep the issue open till I can further confirm that this is not related to Mactype.

**Comment by sammilucia** [comment]
@IceMan81 that's interesting, my Cent Browser isn't auto updating to the latest stable... :thinking: 

No problems, thank you for the update 😊

**Comment by snowie2000** [comment]
> @IceMan81 that's interesting, my Cent Browser isn't auto updating to the latest stable... 
> 
> No problems, thank you for the update

Because as he said, it's a beta.

**Comment by IceMan81** [comment]
My comment may not have been clear - after I switched to the new Cent betas, so far I haven’t seen the issue.

Fingers crossed!

**Comment by snowie2000** [comment]
@IceMan81 The Cent Browser has published a new release recently. So, do you still have the problem with the latest version(s)?

**Comment by IceMan81** [comment]
@snowie2000 Looks good so far with the latest version. We can close this ticket.

**Comment by IceMan81** [comment]
@snowie2000 Is another release planned? And are you planning to merge the directwrite branch changes into the release or is that planned for later?

**Comment by sammilucia** [comment]
@snowie2000 send to me with a list of things to test, and/or I can run the Win 10 VM and give you remote control

**Comment by snowie2000** [comment]
I need to merge some code first and compile a "DirectWrite-powered" version then.

It's not kind of test this and that in a list, it's kind of testing while working. I'm working with MacType enabled, and debug when I encounter any error. You have to test MacType with everything you know and do everything possible. Very time-consuming.

So, the test object is simple:
- Download files
- Overwrite files
- Open your mind, and do everything you can imagine with MacType enabled.
- If something wrong happens, try again, and try again without mactype

😂😂😂

**Comment by sammilucia** [comment]
Yeah, do it @snowie2000 !! 😂

**Comment by snowie2000** [comment]
I created a new issue for the testing.
#472
