### ISSUE TITLE
最新的2018.10.19在win10 1607上无法渲染UWP程序。

### ISSUE THREAD

**Issue by Gokou-Ruri** [snowie2000/mactype#467]
包括自带的设置、天气等，以及第三方的程序如爱奇艺、网易云等。
![image](https://user-images.githubusercontent.com/26711804/47732817-ed119d00-dca1-11e8-9b3f-5561e38a56e9.png)
![image](https://user-images.githubusercontent.com/26711804/47732920-24804980-dca2-11e8-84aa-d0cfc512938a.png)
我使用的上一个版本是 MacTypeInstaller_2016_0904_0 ，当时使用了MacTypePatch，能够正常渲染所有UWP程序，但有部分使用了DirectWrite的传统桌面程序在替换字体后会出现字体堆叠的情况。然后就下载了最新的10.19试试能否解决这个问题，在安装新版前已卸载旧版，重启后再进行安装，之后再次重启系统。

但重启后发现UWP程序无法渲染，使用了MacTypePatch后依旧无法渲染。现在已删除MacTypePatch，恢复为原文件。
请问各位的UWP程序能够正常渲染吗？或者请教一下各位该如何解决？

操作系统：Windows 10 pro 1607 x64
配置文件：自带的【iOS.ini】配置文件（只修改了 FontSubstitutes=0 改为 1 ）

**Comment by snowie2000** [comment]
DirectWrite在ios.ini中默认是关闭的，你需要手动开启。

**Comment by Gokou-Ruri** [comment]
虚拟机里全新安装的Win10 1607 x64，路径默认。（实机里也是默认安装路径。）
![image](https://user-images.githubusercontent.com/26711804/47791948-d62c8280-dd55-11e8-87b2-59d33be606aa.png)

**Comment by jekoder** [comment]
我好像遇到了一样的问题,最新的10.19beta directwrite是enable的

**Comment by snowie2000** [comment]
今天稍晚我去弄一个虚拟机测试下。

**Comment by sammilucia** [comment]
@snowie2000 @jekoder that beta4r3 installer package from #455 I think has a diagnostic build of MacTray.exe from #346 ... I.e. @jekoder's MacTray.exe may be unique

**Comment by jekoder** [comment]
hmm, let me try beta4r2 then

**Comment by jekoder** [comment]
also my registration mode does apply to all program same as #455, since my motherboard don't even have a UEFI mode, pretty sure I don't have secure boot

**Comment by Gokou-Ruri** [comment]
@snowie2000 1809不知为何装完无法启动，只好装了1803。依旧和上面完全一样的效果（截图对比过）。
另：和上面那位用户 jekoder 一样，我的电脑也没有UEFI启动，因为BIOS不支持，旧电脑。

**Comment by snowie2000** [comment]
我刚在我很老的win10虚拟机上测试是可以用的，因为电脑性能比较差，安装新的虚拟机需要较长时间，估计要明天才能测试了

**Comment by Gokou-Ruri** [comment]
Windows 10 1803虚拟机测试截图：
测试过三项配置，分别为 Default.ini 、 iOS.ini 、 XMac.LCD.Default.ini 。
其中 Default.ini 和 iOS.ini 默认开启DirectWrite渲染，而 XMac.LCD.Default.ini 默认没有这项参数(故默认值为 0 )，手动添加后，依旧不能渲染UWP。

以上三项配置每次切换后都会手动重启一次系统，重启后依旧无法渲染UWP。

P.S. 1607和1709是用 vmware14 安装测试的，1803则是用 vmware15 安装测试的。均为官网下载的原版vmware，无任何修改或精简。

![image](https://user-images.githubusercontent.com/26711804/47837721-07559300-dde8-11e8-872d-3f636a7c4d16.png)
![image](https://user-images.githubusercontent.com/26711804/47837729-10defb00-dde8-11e8-9e23-855a7d1705c8.png)
![image](https://user-images.githubusercontent.com/26711804/47837901-95317e00-dde8-11e8-8469-a3433961f49f.png)

**Comment by Gokou-Ruri** [comment]
系统是在 msdn.itellyou.cn 下载的，文件名：
cn_windows_10_consumer_edition_version_1803_updated_sep_2018_x64_dvd_a3fcbed0.iso
cn_windows_10_multi-edition_vl_version_1709_updated_nov_2017_x64_dvd_100289920.iso

**Comment by snowie2000** [comment]
问题确认。
UWP支持并不存在问题，而是由于目前不清楚的原因导致MacType没有正确的加载。
托盘模式是可以用的，但也不稳定，时有时无。

**Comment by Gokou-Ruri** [comment]
谢谢！

**Comment by fonlan** [comment]
我这边是系统设置的mactype相关dll有加载，但是没有渲染，是同一个问题么？用的DirectWrite Power版本

**Comment by snowie2000** [comment]
是同一个问题。uwp程序只有在最开始的时候就加载才有效果，中途加载进去是无效的.
目前我正在处理另外一个重新启动以后无法生效的问题，等这个问题处理完了以后，会一并发布新的修正。

**Comment by fonlan** [comment]
Firefox好像也有类似的问题，MacType以服务模式加载，如果在Firefox运行的时候重启MacType的服务，在MacType服务重启完成后Firefox依旧无法恢复渲染。在不关闭当前Firefox的情况下新建一个Firefox窗口则新窗口的网页内容能被渲染，但Firefox的界面依旧无法渲染。应该是Firefox对新建的窗口使用了新的进程。

**Comment by snowie2000** [comment]
firefox和chrome一样对子进程都是有沙盒保护的。一旦进程启动，就没有办法注入进去。这是正常现象。

**Comment by fonlan** [comment]
> 
> 
> firefox和chrome一样对子进程都是有沙盒保护的。一旦进程启动，就没有办法注入进去。这是正常现象。

原来如此，好在这个问题影响不大

**Comment by snowie2000** [comment]
The UWP support for tray mode and service mode should work with the latest beta (with administrator privilege).
Reopen if it persists.
