### ISSUE TITLE
MacTray.exe balloon tips are not translatable

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#473]
E.g. change from Compatibility Mode to Standalone Mode, a balloon tip is displayed, but I can't see a way to translate it in English.lng.

There may be other balloon tips too.

![image](https://user-images.githubusercontent.com/3295286/48132477-9c262800-e2e3-11e8-8ae6-cddce30404e9.png)

**Comment by snowie2000** [comment]
It's hardcoded. fixing...

**Comment by snowie2000** [comment]
Closed as the latest version should have solved the problem.
