### ISSUE TITLE
Selecting a profile in MacTray doesn't change profile

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#474]
It seems like changing the profile from MacTray doesn't work, you have to use the Wizard.

To repro:
1. Use Standalone or Compatibility Modes
2. Right click MacTray, select a different profile
3. Re-open Cent Browser, Explorer, etc

Expected outcome:
- New profile is rendered

Observed outcome:
- Profile is the same

**Comment by snowie2000** [comment]
I may have found the reason,  it's related to environmental variables. when you click the finish on the wizard and update the environment variables. 
 I have updated the wizard so as should fix the problem with today's version

**Comment by snowie2000** [comment]
Check the mactype.ini file and see if the value of key `AlternativeFile` is changed accordingly.

**Comment by sammilucia** [comment]
No it's not changing

**Comment by snowie2000** [comment]
Did you run MacTray as Administrator? It is typically because of the permission problem.

**Comment by sammilucia** [comment]
No, but I'm using the new installer, so I have Modify privs on MacType.ini

**Comment by sammilucia** [comment]
Yes it works running MacTray as Administrator ... Just not as a User. I can't see any reason it shouldn't work running as User though.

**Comment by snowie2000** [comment]
> Yes it works running MacTray as Administrator ... Just not as a User. I can't see any reason it shouldn't work running as User though.

I think you only give sufficient permission to administrators, but as a non-elevated process, it has only at most power user privilege.

**Comment by sammilucia** [comment]
Yes however my point is User now has permission to change MacType.ini, so why wouldn't it work as User?

**Comment by snowie2000** [comment]
Try to give full control to everyone.  that's how I solve the problem every time it doesn't work with specific user privilege

**Comment by sammilucia** [comment]
Tested, no that didn't work either. It's not a permissions problem, MacTray.exe doesn't actually try to write MacType.ini when it's not running as Administrator...

Running as User - has an 'open if' condition and I assume it fails - because the actual read/write request doesn't fail (says REPARSE):
![image](https://user-images.githubusercontent.com/3295286/48310787-82872800-e5e4-11e8-9291-1ce001ccdb14.png)
So I think it's conditionally failing in code (via exception handling), not because of actual file permissions.

Running as Administrator - here's the write:
![image](https://user-images.githubusercontent.com/3295286/48310766-26bc9f00-e5e4-11e8-9259-c93bcea41853.png)

**Comment by snowie2000** [comment]
Yes, I do have a permission checking here. Can you give the file full control to everyone and try again?
Thanks.

**Comment by snowie2000** [comment]
@sammilucia Does it still happen after you freshly installed the new version? I tried with my Windows 10 VM, and it looks nothing wrong with profile switching without administrator privilege.

**Comment by sammilucia** [comment]
@snowie2000 will check shortly

**Comment by sammilucia** [comment]
@snowie2000 It seems to be working when MacTray is run from MacWiz. When you run it manually though (in non-admin mode), the profiles don't change.

**Comment by snowie2000** [comment]
Please use process monitor  to see which file to Mac tray is writing to. 

 I think the Mactype.ini is virtualize to to another folder because of the UAC.  When you run elevated the virtualization is disabled.

**Comment by sammilucia** [comment]
It's the same as my comment above (https://github.com/snowie2000/mactype/issues/474#issuecomment-437652480) MacTray doesn't actually attempt to write to MacType.ini unless it's running as Administrator

**Comment by sammilucia** [comment]
The problem will only occur if a user manually launches MacType from the icon. One other workaround is that the installer sets MacTray to run as Administrator always...

**Comment by snowie2000** [comment]
It shouldn't be done this way as some users don't have the administrator privilege, and windows with UAC turned on doesn't allow applications that require elevation to run at startup (unless via task schedule).

**Comment by sammilucia** [comment]
Yes I know ... But that doesn't mean users won't run it manually and then find they're not able to change profiles...

**Comment by snowie2000** [comment]
The problem is that it looks like you are the only one facing the problem so far.

**Comment by snowie2000** [comment]
@sammilucia Try this one. It gives you some message boxes on profile switching.
[MacTray-debug.zip](https://github.com/snowie2000/mactype/files/2660210/MacTray-debug.zip)

**Comment by sammilucia** [comment]
I do have a tendency to find weird bugs.
```
You clicked a menu item
You chose C:\Program Files\MacType\ini\extratype.ini
Writing string ini\extratype.ini to file C:\Program Files\MacType\MacType.ini
The operation completed successfully
Reloading
```

And it worked! Looks like adding debug code fixed the problem 😂

**Comment by snowie2000** [comment]
WTF.....
You're not alone, I fixed many bugs by only adding logs. 😁😁😁

**Comment by snowie2000** [comment]
[MacTray-debug-log2.zip](https://github.com/snowie2000/mactype/files/2660317/MacTray-debug-log2.zip)

Okay, so only one log left. See if it still works.

**Comment by sammilucia** [comment]
Yep it's still working.

I didn't replace MacType64.dll - did you want me to?

**Comment by snowie2000** [comment]
No, definitely not. It's really weird. 
I'm gonna remove every log see if the "log method" magically fixed the problem.

**Comment by snowie2000** [comment]
[MacTray-debug-nolog.zip](https://github.com/snowie2000/mactype/files/2660375/MacTray-debug-nolog.zip)
Here you go. The moment of truth.

**Comment by sammilucia** [comment]
What did you change? 😊

**Comment by sammilucia** [comment]
It's working! You'll probably tell me you didn't change anything 😂

**Comment by snowie2000** [comment]
Exactly what I am going to say.

**Comment by snowie2000** [comment]
Exactly what am I going to say.

**Comment by sammilucia** [comment]
Lol aaarrrrggghh!!

**Comment by snowie2000** [comment]
Did you forget to set your compatibility property back of  the mactray app.

**Comment by sammilucia** [comment]
No it's not using compatibility, it's just running as user.

**Comment by snowie2000** [comment]
So what should we say to this bug? Solved? Vanished? TBD?

**Comment by sammilucia** [comment]
Close as could not reproduce! (Aka - @snowie2000 secretly fixed it without admitting to it 😂)
