### ISSUE TITLE
Program started from context menu of shortcut in start menu not rendered by MacType

### ISSUE THREAD

**Issue by kraml** [snowie2000/mactype#476]
As shown in below screenshot, the app AnyDesk provides a context menu on its shortcut in start menu, to allow access of recent sessions.

When AnyDesk is started by clicking the icon in the start menu, it is rendered by MacType. When it started by clicking a session in the context menu, it is not rendered by MacType, this can be confirmed by visual and also DLLs in process explorer.

![snipaste_2018-11-16_15-18-59](https://user-images.githubusercontent.com/358679/48615950-3d406d00-e9cd-11e8-9d4b-3e748b649231.png)

BTW AnyDesk is smoother than TeamView or RDP in my environment so you may give it a try for the remote dev env as mentioned in #416 .

**Comment by kraml** [comment]
MacType is running in registry mode, btw.

**Comment by snowie2000** [comment]
Check the process tree and you'll probably find out that the process created by clicking the context menu is spawned from svchost.exe.

If that's the case, it will be fixed shortly as I'm working on it and kind of succeeded.

**Comment by snowie2000** [comment]
![qq 20181120144656](https://user-images.githubusercontent.com/11767189/48756231-3ff3d880-ecd3-11e8-9f3d-cc8e7b07db48.png)
It has been fixed as of the latest development version.

**Comment by snowie2000** [comment]
Closed as fixed by beta 5.
Reopen if you still have the problem.

**Comment by kailiu42** [comment]
I can confirm it is fixed in beta 5.

**Comment by snowie2000** [comment]
Thank you for confirming it.
