### ISSUE TITLE
MacType.net is broken

### ISSUE THREAD

**Issue by wmjordan** [snowie2000/mactype#479]
The site was inaccessible.
![ee16d73c-f4bd-4e91-8b6c-0d12b3d94289](https://user-images.githubusercontent.com/12182730/48998239-e0437480-f18d-11e8-9ccf-103abd6ba36a.png)

**Comment by snowie2000** [comment]
Thank you, checking on that...

**Comment by snowie2000** [comment]
It's back now. Thank you.

**Comment by wmjordan** [comment]
已捐赠 just now 💰 
Thank you for saving my eyes for these years!

**Comment by wmjordan** [comment]
I also recommended MacType within my VS Extension at 
https://marketplace.visualstudio.com/items?itemName=wmj.Codist#user-content-display-enhancements

**Comment by snowie2000** [comment]
Thank you for your donation and thank you for the recommendation. I'll give it a try.
