### ISSUE TITLE
MacType crashes pc to login screen.

### ISSUE THREAD

**Issue by Starfola** [snowie2000/mactype#481]
I tried using both the beta and the one from mactype website and they both causes pc to crash to login screen. The profile was LCD and it was Services. It worked fine once it was installed but after restarting and signing in is where things would flicker black and the apps would look unresponsive even though they aren't and eventually turning black and crashing to login screen. I also tried setting a delay on the MacType services and still same crash.

OS: Windows 10 Enterprise 2016 LTSB
Build Version: 1607

**Comment by snowie2000** [comment]
When does the crash happen? 
At the login screen or after you logged into the system and ran some applications?

**Comment by Starfola** [comment]
Happens after I login and a few apps have loaded in such as Whatpulse, Razer Synapse, Flux, ShareX.

**Comment by snowie2000** [comment]
The 1607build is pretty old and was proved to be working well with MacType. 
A lot of users have reported that they encountered problems after they upgraded their system from 1607. That's why we are busy fixing all the bugs.

**Comment by snowie2000** [comment]
Try to use tray mode as it won't load into system processes, makes it relatively safer. 

You can try to run non-elevated, if everything is working, then try elevated.

**Comment by Starfola** [comment]
Seems to have fixed the crashing problems. Thanks a lot. I tried it using elevated as well and is working as intended. Again thanks again I been trying to use this for the past year so I'm glad I'm able to now :D
