### ISSUE TITLE
请问类似这种字体堆叠的情况要如何解决？

### ISSUE THREAD

**Issue by Gokou-Ruri** [snowie2000/mactype#482]
似乎只要用WPF开发的程序都会出现这个情况，请问有办法解决吗？

![image](https://user-images.githubusercontent.com/26711804/49572881-afc2be00-f977-11e8-81f9-1aa170adf088.png)

![image](https://user-images.githubusercontent.com/26711804/49572872-a89bb000-f977-11e8-9811-dc1b8e514e5f.png)

**Comment by snowie2000** [comment]
请不要替换字体，尤其是UWP程序，很容易出问题。必须替换为参数一致的字体，这是替换字体的基本原则。

**Comment by Gokou-Ruri** [comment]
@snowie2000 谢谢！请问参数是指的什么？

（P.S. UWP程序并不会出现此情况，只有使用WPF开发的程序才会。上方截图两款程序都是WPF程序，不是UWP。）
https://docs.microsoft.com/zh-cn/previous-versions/dotnet/netframework-4.0/aa970268(v=vs.100)

**Comment by snowie2000** [comment]
字体有非常多的参数，比如高度宽度行间距字间距等等，不相同字替换容易出问题，因为程序并不知道你用的字体和他想要创建的不同。

但是不是所有程序使用的字体技术都对参数敏感，典型的比如记事本，随你怎么换都没问题

**Comment by Gokou-Ruri** [comment]
明白了，谢谢。

**Comment by Gokou-Ruri** [comment]
想请教一个不相关的问题：如何能查看某个软件使用了哪些字体？

**Comment by snowie2000** [comment]
process explorer查看软件加载了哪些字体文件。

具体用了什么字体无法查看到，除非进去mactype内部看调试日志
