### ISSUE TITLE
chrome渲染过虚,dw渲染字体锯齿过为严重

### ISSUE THREAD

**Issue by Innei** [snowie2000/mactype#483]
chrome 
![image](https://user-images.githubusercontent.com/41265413/49651619-ad8d5c00-fa6a-11e8-9078-92f501b94392.png)
word中的dw渲染
![image](https://user-images.githubusercontent.com/41265413/49651638-b7af5a80-fa6a-11e8-8c18-d95f7f6517b0.png)
锯齿..

**Comment by snowie2000** [comment]
word中的directwrite是灰度渲染，dw的灰度渲染效果极差。

由于使用什么渲染是软件本身决定的，无法改变（可以改变，但是会不兼容），所以无法解决

**Comment by snowie2000** [comment]
word中的directwrite是灰度渲染，dw的灰度渲染效果极差。

由于使用什么渲染是软件本身决定的，无法改变（可以改变，但是会不兼容），所以无法解决
