### ISSUE TITLE
Does HookChildProcesses still conflict with Windows 10 x64?

### ISSUE THREAD

**Issue by wegood9** [snowie2000/mactype#484]
HookChildProcesses is still conflicting with Windows 10 1809 x64. I'm using Mactype 2018.1-beta5 with default.ini.

Specific behavior is that the majority of programs crash. The processes of these applications and the related Windows Error Reporter do launch but their windows don't pop up. These exes can be launched by running as an Administrator or a third-party file manager such as Total Commander.

Examples of crashing applications :
`cmd
 7-Zip
Chrome
Firefox
winver`

It is HookChildProcesses that caused crashes. Listed as known issues, the problem can be solved by setting HookChildProcesses to 0. But disabling HookChildProcesses provides a limited experience of Mactype including not rendering Chrome and Firefox. And switching loading mode doesn't work for me.
I have no anti-virus software installed and even disabled Windows Defender when testing.
It has existing on my PC since the first time I used Mactype on Windows 10. There are old issues of the similar situation in old versions. Only after I read the release note 

> Better compatibility with Windows 10 (in theory... I've never encountered any incompatibility before)

 of the latest version did I decide to submit this duplicate issue to confirm whether it's a common problem or peculiar issue to me and whether it has been solved.
So I wonder how compatible Mactype currently is with Windows 10. Hope Windows 10 users could offer your Mactype working status for reference.

**Comment by snowie2000** [comment]
Personally, I've never encountered such crash in all my test VMs. 
So probably, I am not able to fix this issue without a working memory dump as the error reporting in your event log will almost certainly point to a temporary memory address that MacType allocates every time a program started.

**Comment by wegood9** [comment]
Here is a dump file generated by `procdump64.exe -ma -t -w 7zfm.exe`
Mactype was loaded as standalone mode.
[7zFM.exe_181209_104749.zip](https://github.com/snowie2000/mactype/files/2660203/7zFM.exe_181209_104749.zip)

**Comment by snowie2000** [comment]
Sorry, but this dump doesn't help because it doesn't break at the correct point.
A dump on the crash is what solves the problem. Please follow the procedures in https://stackoverflow.com/questions/20237201/best-way-to-have-crash-dumps-generated-when-processes-crash to let Windows do the dump for you.

Thank you for doing so much for MacType.💋

**Comment by wegood9** [comment]
Having regenerated dump file for notepad
[notepad.exe.8692.zip](https://guanghou-my.sharepoint.com/:u:/g/personal/shepiba_get365_pw/EbB98Lyk5mVDgsO9BXwatDsBD-WooYH1qI-9pWIuMDr2Vg)

**Comment by snowie2000** [comment]
Where did you launch these applications? From explorer or from something else like a 32bit launcher?
And if it is not the explorer, is the launcher elevated?

**Comment by wegood9** [comment]
Windows explorer or start menu. The given example happened when I tried to start notepad from context menu in explorer.

**Comment by wegood9** [comment]
Total Commander I use is a 64 bit file manager and not elevated. Applications launched from it simply won't crash and will get rendered properly.

**Comment by snowie2000** [comment]
I'm quite confused with what I see in the dump.
So I made a little change to try to fix the problem.
Extract and overwrite the mactype64.dll file, and see if the problem is solved. Thank you.

[MacType64.zip](https://github.com/snowie2000/mactype/files/2660305/MacType64.zip)

**Comment by wegood9** [comment]
It doesn't work.

**Comment by snowie2000** [comment]
Alright, there is what I would like you to do to make things clear.
Download Process Explorer and navigate to `explorer.exe`, on the lower panel, enable column `Base` and `ASLR`.
Find the base of `kernel32.dll` and `kernelbase.dll` like the picture shown below:
![qq 20181209151412](https://user-images.githubusercontent.com/11767189/49694455-6071cd00-fbc5-11e8-966f-0314e2fece80.png)

**Comment by wegood9** [comment]
![20181209152635](https://user-images.githubusercontent.com/16728159/49694527-d9255900-fbc6-11e8-8faf-666f9942c097.png)

**Comment by snowie2000** [comment]
Okay, I think I found the problem. You used `Locale Emulator` which faked the API addresses.
Disable it and try again.

**Comment by wegood9** [comment]
I tried disabling LE and rebooted, but the problem still exists. I'm pretty sure that it's not LE that causes crashes because Mactype had caused crashes before I installed LE.

new screenshot of process explorer
![1](https://user-images.githubusercontent.com/16728159/49694929-9915a480-fbcd-11e8-90cf-d3690f65c9f2.PNG)

**Comment by snowie2000** [comment]
[MacType64-msg.zip](https://github.com/snowie2000/mactype/files/2660355/MacType64-msg.zip)

Disable mactype
extract file
overwrite file
**Drag notepad.exe to macloader64.exe** to launch it manual, **DO NOT** enable mactype system-wide or you'll be flooded with message boxes.
Start a another program from open dialog of the notepad.

This way, you'll get a message box telling you information MacType got to do hooking.

**Comment by wegood9** [comment]
The programs can be launched successfully with msgbox attached below.
![2](https://user-images.githubusercontent.com/16728159/49695016-51901800-fbcf-11e8-8602-4534f5f53065.PNG)

**Comment by snowie2000** [comment]
So, the child process didn't crash? It only crashes when launched from explorer?
Then, only enable mactype to explorer.exe, launch a notepad, and disable mactype for explorer after msgbox immediately to avoid further popups.

**Comment by wegood9** [comment]
It seems that only child processes of explorer will crash.

![3](https://user-images.githubusercontent.com/16728159/49695199-4c809800-fbd2-11e8-8e59-1c8826a66db3.PNG)

**Comment by snowie2000** [comment]
See, the API address is not right compared to the value of the previous screenshot.
Can you give a full log of explorer.exe? 
Here is how:
- select explorer.exe in process explorer
- enable another column called `Mapped Size`
- file->save as...

You'll get a txt file. Please upload here.

Thanks.

**Comment by wegood9** [comment]
Here is it
[explorer.exe.txt](https://github.com/snowie2000/mactype/files/2660376/explorer.exe.txt)

**Comment by snowie2000** [comment]
No dll is allocated at address 0x7ffe00000000. This must a dynamically allocated by a file and god knows that.
I believe the `GetProcAddress` is hooked as well so can't be trusted anymore. I need to manually search for the real address.

**Comment by snowie2000** [comment]
Try this one, please. Msgbox is still there, so don't enable it system-wide unless you're prepared for a hard reset.

[MacType64-msg-customfunc.zip](https://github.com/snowie2000/mactype/files/2660454/MacType64-msg-customfunc.zip)

**Comment by wegood9** [comment]
notepad still crashes :(
The msgbox is the same as I posted before.

**Comment by snowie2000** [comment]
What does the dialog say?

**Comment by snowie2000** [comment]
Alright, while I am trying other ways, could you please use the tool `PCHunter` to check the hooks of the `explorer.exe`?
This is how you do it: https://github.com/snowie2000/mactype/issues/441#issuecomment-438945641

**Comment by wegood9** [comment]
PChunter refused to launch due to errors when loading its driver. My Windows version is Build 17763, while the free version of PChunter officially supports only up to Build 17134.
As far as I know, there is no public Anti-Rootkit tool which supports Windows 1809. It's a matter to use such a newly released Windows.

**Comment by snowie2000** [comment]
[MacType64-reloc.zip](https://github.com/snowie2000/mactype/files/2661373/MacType64-reloc.zip)

This build used a special way to get the API address. Try it to see if it works for you.

**Comment by snowie2000** [comment]
@wegood9 Hi, I would like to know if the last patch works for you.
PS: it is a version with popup, so please enable for explorer only.

**Comment by wegood9** [comment]
It doesn't work.
This is the msgbox that explorer gave:
![4](https://user-images.githubusercontent.com/16728159/49740321-e4fc4280-fcce-11e8-88aa-ca66f50c17a9.PNG)
This one is given by open dialog of notepad:
![5](https://user-images.githubusercontent.com/16728159/49740403-0ceba600-fccf-11e8-80ed-84d126e29762.PNG)
At this time, I can't launch programs by both explorer and the open dialog of notepad.

**Comment by snowie2000** [comment]
What does the msgbox say?

**Comment by snowie2000** [comment]
Thank you. This dialog tells me that it should work. It just needs a little tweak.

**Comment by wegood9** [comment]
I have no access to my computer during daytime, so please forgive me for the late replies.

**Comment by snowie2000** [comment]
It's ok. Thank you for replying at such a late time.

**Comment by snowie2000** [comment]
[MacType64-fixed.zip](https://github.com/snowie2000/mactype/files/2665771/MacType64-fixed.zip)

It should run as expected this time.

**Comment by wegood9** [comment]
It seems all right when I enable it only with explorer. The programs manage to get launched and render properly.

**Comment by snowie2000** [comment]
Good. Looks like my theory worked. I'll upload a version without msg box to finalize the problem. 

I still recommend you to check your system as the crash bug is not really a bug. It means your system is hijacked by some kind of software. Strangely enough, the hijack only happens to your explorer.

**Comment by wegood9** [comment]
Sure, I will check my system later. Maybe my computer needs a clean reinstallation.
By the way, is it normal that a few wired problems such as taskmgr refusing to be launched when I enable the patch system-wide?

**Comment by snowie2000** [comment]
If you are using the old mactype64.dll, based on your situation, it is probably normal. 

If you mean the new one, yes, it is still normal as some of the programs refuse to invoke messagebox API on startup.

**Comment by snowie2000** [comment]
If you are using the old mactype64.dll, based on your situation, it is probably normal.

For the new one, it should launch normally. Anyway, let's see what will happen with my final solution tomorrow.

**Comment by wegood9** [comment]
Okay, Thanks for your answer.
I will close this issue after testing the final solution.

**Comment by snowie2000** [comment]
[MacType64-final.zip](https://github.com/snowie2000/mactype/files/2670268/MacType64-final.zip)

Here it is.

**Comment by wegood9** [comment]
Everything seems to work as expected. Thanks for your great efforts.
