### ISSUE TITLE
Win10 LTSC 2019    TIM无法渲染

### ISSUE THREAD

**Issue by KeenShawn** [snowie2000/mactype#485]
操作系统：Win10 LTSC 2019  
最新版本：2018.1-beta5
Tim版本：2.3.1

**Comment by snowie2000** [comment]
TIM有qqprotect.sys保护（和电脑管家，如果你安装了的话），不能渲染完全正常。

QQ产品的保护策略一直都比较不稳定，似乎是有一定的判断逻辑在其中的，有些人的QQ被设置为高权限，无法被其他进程访问，而另一些人的却可以。

**Comment by Mahayu** [comment]
这里系统是 Windows Pro 1803
其他环境相同，并不能复现问题。

**Comment by KeenShawn** [comment]
> TIM有qqprotect.sys保护（和电脑管家，如果你安装了的话），不能渲染完全正常。
> 
> QQ产品的保护策略一直都比较不稳定，似乎是有一定的判断逻辑在其中的，有些人的QQ被设置为高权限，无法被其他进程访问，而另一些人的却可以。



> TIM有qqprotect.sys保护（和电脑管家，如果你安装了的话），不能渲染完全正常。
> 
> QQ产品的保护策略一直都比较不稳定，似乎是有一定的判断逻辑在其中的，有些人的QQ被设置为高权限，无法被其他进程访问，而另一些人的却可以。

原来是这样，我的就是无法渲染。感谢。

**Comment by KeenShawn** [comment]
> 这里系统是 Windows Pro 1803
> 其他环境相同，并不能复现问题。

我的之前也是好好的，搞不懂为何。
