### ISSUE TITLE
[Question] Will using this tool be charged as cheating by anti-cheats?

### ISSUE THREAD

**Issue by F-TD5X** [snowie2000/mactype#486]
You mentioned this hook will be marked as virus by some anti-virus methods, so what about anti-cheat methods?

Will users be charged as cheater for using this tool?

**Comment by snowie2000** [comment]
It is totally up to the anti-cheat software developer/company. They have the word to define what is a cheater.

So it is always recommended to not apply any kind of hook/injection to games.

**Comment by PeraSite** [comment]
I actually couldn't play COD4 Black Ops 4 with mactype hooked.
So just turn off for games.
