### ISSUE TITLE
MacType 2018.1-beta5偶尔使Cent Brower的网页崩溃

### ISSUE THREAD

**Issue by fforever14** [snowie2000/mactype#489]
Mactype版本: MacType 2018.1-beta5
Mactype加载方式: 服务加载
系统版本: WIN10 1809
浏览器: Cent Brower  3.7.2.33（正式版本） （64 位） (Chromium 70.0.3538.110)

Cent Brower禁用DirectWrite
在打开新的标签页时, 或者进入清空缓存的页面时, 偶尔会导致页面崩溃;

原先使用v1.2017.628.0 released版本时未发现类似问题
![mactype](https://user-images.githubusercontent.com/4794313/50198062-ed1a4900-0384-11e9-9374-5b9edccb1154.jpg)
![mactype](https://user-images.githubusercontent.com/4794313/50198064-edb2df80-0384-11e9-8321-3eb72c7e9714.jpg)

**Comment by snowie2000** [comment]
Cent browser是一个在不断升级的浏览器，所以崩溃并不一定是MacType引起的。
我这边即便不开MacType centbrowser也时不时就会崩溃掉。

**Comment by LitCcc** [comment]
Cent brower网页崩溃不是MC的锅，但是在开启 Cent browser的时候扩展会随机崩溃

**Comment by fforever14** [comment]
我这边退回了旧的版本, 并使用了新版本使用时存在问题的配置文件
截至目前已经使用接近2天, 没有再发生类似的问题
所以, 我认为新版本和发生问题的环境应该还是存在某些兼容性问题
希望雪大有时间的话可以查查

**Comment by snowie2000** [comment]
Chrome类浏览器的问题除非是稳定重现的或者高频率，否则无法追查。
Chrome在崩溃后不给你机会调试直接杀进程，所以根本无法调试的。

**Comment by fforever14** [comment]
多谢雪大回复
等正式版出来我更新了试试, 现在先安分在老版本吧
