### ISSUE TITLE
foxmail邮件内容部分无法渲染

### ISSUE THREAD

**Issue by TabrisKing** [snowie2000/mactype#490]
foxmail 和 mactype都是当前最新版。
使用效果foxmail界面全部正常渲染，但是邮件预览和浏览界面中邮件内容没有渲染。请老大看看什么原因？

**Comment by snowie2000** [comment]
foxmail 邮件正文多半用的是ie内核或者chrome内核，必须开启DirectWrite支持才可以。

**Comment by TabrisKing** [comment]
报告老大 肯定是开了的 还是不行啊

**Comment by snowie2000** [comment]
![qq 20181226104246](https://user-images.githubusercontent.com/11767189/50429714-0b3ef680-08fb-11e9-9ae7-6d53e15f0ef8.png)
Foxmail使用的很可能是ie内核，总之是完全可以支持的。如果不能支持肯定是设置不对。

**Comment by TabrisKing** [comment]
明白 对于ie内核 起作用的配置是directwrite中的参数么？如果需要加黑应该是增加gamma还是降低？试了半天没效果。。。 还请赐教

**Comment by snowie2000** [comment]
对DirectWrite生效的就是[directwrite]段的参数。

如果没有这个段，那么全局的GammaValue会生效。 Gamma越大就越浅。

**Comment by TabrisKing** [comment]
测试了一下 IE或Edge的渲染效果也几乎等同没有。。。。  就想文字加黑一下都不行 DW下的渲染效果看来还得继续努力了 辛苦老大

**Comment by snowie2000** [comment]
DirectWrite提供的参数目前来说只能做到这样了，另外DW的模式不可以是6（RenderingMode=6），在6的状态下一切参数都无效。
具体参见 https://github.com/snowie2000/mactype/wiki/RenderingMode

**Comment by arshcaria** [comment]
> foxmail 和 mactype都是当前最新版。
> 使用效果foxmail界面全部正常渲染，但是邮件预览和浏览界面中邮件内容没有渲染。请老大看看什么原因？

我试了下，应该是7.2.9之后的的Foxmail修改了邮件正文的渲染机制。
找一个7.2.8.379版本的Foxmail就可以正常渲染了。
