### ISSUE TITLE
部分软件界面中小字体渲染后堆叠在一起

### ISSUE THREAD

**Issue by TabrisKing** [snowie2000/mactype#491]
貌似很多老的windows标准对话框都有这个问题 比如notepad++的查找对话框
回头补图

**Comment by TabrisKing** [comment]
<img width="958" alt="_15458829241553" src="https://user-images.githubusercontent.com/10110860/50464846-61309e80-09ce-11e9-8d9f-d1570b2606d8.png">
请看图
我的配置文件：
[General]
Name=my3
HintingMode=3
AntiAliasMode=4
NormalWeight=0
BoldWeight=0
ItalicSlant=0
EnableKerning=1
WidthMode=0
BolderMode=2
GammaMode=0
LcdFilter=2
TextTuning=0
TextTuningR=0
TextTuningG=0
TextTuningB=0
GammaValue=1.4
Contrast=5.0
RenderWeight=2.0
Fontlink=1
HookChildProcesses=1
FontLoader=0
FontSubstitutes=0
Shadow=0,0,0,0x0,0,0x0
LoadOnDemand=0
UseMapping=0
MaxBitmap=8
MaxHeight=0
DirectWrite=1
HintSmallFont=0
CacheMaxFaces=256
CacheMaxSizes=12554432
CacheMaxBytes=20485760
[Exclude]
;【除外的字体】

[ExcludeModule]
;【不渲染的程序，但仍会加载DLL】
Q-Dir.exe

[Experimental@Firefox.exe]
ClipBoxFix=1

[experimental]
Colorfont=1

[experimental@chrome.exe]
invertcolor=1


[FontSubstitutes]
[Individual]
XSong=,,30,,,
XSong SimSun=,,30,,,
XSong Mono=,,30,,,
Batang=,,30,,,
MingLiU=,,30,,,
PMingLiU=,,30,,,
PMingLiU_HKSCS=,,30,,,
MingLiU_ExtB=,,30,,,
PMingLiU_ExtB=,,30,,,
PMingLiU_HKSCS_ExtB=,,30,,,
MS Mincho=,,30,,,
MS PMincho=,,30,,,
宋体=,,30,,,
新宋体=,,30,,,
SimSun=,,30,,,
微软雅黑=,,1,,,
Tahoma=,,1,,,
Microsoft YaHei UI=,,1,,,

[ExcludeSub]
javaw.exe
PPLive.exe
QQGame.exe
devenv.exe

[DirectWrite]
RenderingMode=6
Contrast=9.0
ClearTypeLevel=1
[UnloadDll]
avgnt.exe
AxureRP.exe
bleachbit.exe
devenv.exe
dota.exe
dota2.exe
dwm.exe
Fetion.exe
Flow.exe
FontCreator.cn.exe
FontCreator.exe
Fontforge_EN.exe
Fontforge_SC.exe
Fontforge_TC.exe
fontview.exe
gnucash-bin.exe
javaw.exe
mspdbsrv.exe
notecase.exe
notecaselauncher.exe
ollyice.exe
PlantsVsZombies.exe
PotPlayerMini.exe
PPLive.exe
QQGame.exe
sc2.exe
SearchFilterHost.exe
SearchProtocolHost.exe
SettingSyncHost.exe
Shadowsocks.exe
SmartAudio3.exe
Spotify.exe
ss_privoxy.exe
SynTPEnh.exe
SynTPHelper.exe
unsecapp.exe
VBoxSvc.exe
VirtualBox.exe
war3.exe
xdict.exe
YunDetectService.exe

**Comment by snowie2000** [comment]
请遵守替换字体的原则，只替换参数一致的字体。（如果你不知道什么叫参数一致，那就不要替换了……）
随意替换字体会导致五花八门的问题，这不是bug，这是必然的。（人家的软件根本就不是为这个字体设计的，根本就没有考虑过新字体的长宽，当然会乱掉）
