### ISSUE TITLE
Newest TIM Version is excluded by Mactype

### ISSUE THREAD

**Issue by Mahayu** [snowie2000/mactype#492]
TIM 2.3.1,Windows10 1803
MacType 2018.1-beta5

![default](https://user-images.githubusercontent.com/22572355/50571293-4e103b00-0de1-11e9-89c3-6b4c64713fb0.png)

I can switch it on manually and it runs smoothly.

**Comment by snowie2000** [comment]
Did you run the tray app as administrator?

**Comment by Mahayu** [comment]
> 
> 
> Did you run the tray app as administrator?

So Mactype works when I run this program as Administrator.
I will close the issue.
