### ISSUE TITLE
win10 彩色Emoji 相关。

### ISSUE THREAD

**Issue by xiabeizi** [snowie2000/mactype#493]
win10原生的彩色Emoji的渲染 需要开启DirectWrite，
关闭 DirectWrite，mactype渲染出来的效果才是最好的。

最新版本的 mactype ，关闭DirectWrite，渲染的 Emoji 是这样的

![image](https://user-images.githubusercontent.com/29277631/50626922-fe11af80-0f6b-11e9-8de4-eadc153430f1.png)

原生的是这样的
![image](https://user-images.githubusercontent.com/29277631/50626943-23062280-0f6c-11e9-9c95-54992ab8cef1.png)

想哭 悲伤 哭泣 委屈 ，这个有没有办法 ，在关闭 DirectWrite的情况下，渲染出原生的 Emoji

**Comment by snowie2000** [comment]
你用的是Chrome吧，你需要这个https://github.com/snowie2000/mactype/wiki/InvertColor ，如果仍有问题请重新打开此issue。

----------------

Looks like you're using Chrome, right? Here is what makes things right: https://github.com/snowie2000/mactype/wiki/InvertColor

**Comment by xiabeizi** [comment]
谢谢回复，关于更新wiki里的 ColorFont 和 InvertColor 这两篇我都看了，
InvertColor 没有作用呢，

360极速浏览器 关闭了DirectWrite, 没有修改过 chrome flags里面的东西
渲染的 ini 文件看了 ColorFont 和 InvertColor  都是1，

如果是我的个例，关掉ColorFont 算了，另外谢谢作者

内核版本：69.0.3497.100
极速浏览器基于Chromium开源项目，支持开源社区发展。

**Comment by snowie2000** [comment]
invertcolor=0

这个选项只有在你发现你的浏览器出现问题的时候才开启，如果你的浏览器都是正常的，那么它应该是关闭的。
