### ISSUE TITLE
Crash with font "Inter UI"

### ISSUE THREAD

**Issue by hyrious** [snowie2000/mactype#496]
the font: [rsms/inter](https://github.com/rsms/inter)
when I _the second time_ set the font(OTF format installed on my computer) as default in cent browser(which is being hooked by mactype),
![sp20190105_125754_807](https://user-images.githubusercontent.com/8097890/50720520-bd3fa500-10e9-11e9-84fb-8eff23a09bb3.png)
it suddenly crashes mactype and all things related -- all text on my computer are missing 😨.
all I could do is restart my computer.
weirdly, it was fine at the first time when I did the same thing,
so maybe you can't reproduce such a mess 🤔. I'm sorry for that.

**Comment by sammilucia** [comment]
Hi @hyrious, thanks for reporting this problem. Has it happened on your PC again since then?

**Comment by hyrious** [comment]
> Hi @hyrious, thanks for reporting this problem. Has it happened on your PC again since then?

No. I just uninstalled that font and _never_ use it widely (like making it as a default font in browser).

Inter UI works fine when it comes to single page(fewer words to draw) + webfont(not OpenType) e.g. on my blog site: https://hyrious.me.

Maybe this variable font makes something overflow in Mactype.

**Comment by sammilucia** [comment]
Thank you 😊. It's also very possible for fonts to be badly created. They're basically vectors, and some of them have far more complex paths than they need or other problems which can cause all sorts of weird problems.

I think I'll leave this open as there might be a problem with the FreeType version used with OpenType Variations, which Inter font utilises (https://rsms.me/inter/) ... @snowie2000 there might be a fix for FreeType engine

**Comment by sammilucia** [comment]
@hyrious could you please try beta6 https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6 and let me know if it still crashes? beta6 is upgraded to use FreeType 2.10.0 so the rendering problem may be fixed

**Comment by hyrious** [comment]
LGTM. I just tried Mactype [2019.1-beta6](https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6) released at yesterday with default profile, Inter UI [v3.7](https://github.com/rsms/inter/releases/tag/v3.7) released at 5/31 with OTF format installed. On my Cent Browser [74(32-bit)](https://www.centbrowser.com/history.html#4.0.9.112) and Windows 10 1903 18362.175 (after a clean installation). (All of them are under the latest stable version) It doesn't crash anymore. 🍻

**Comment by sammilucia** [comment]
Yay, thanks for getting back @hyrious, that's great news 😊
