### ISSUE TITLE
linux下能否支持下呢？

### ISSUE THREAD

**Issue by sikenali** [snowie2000/mactype#497]

**Comment by fonlan** [comment]
freetype本来就是从Linux下移植过来的你还想再移植回去？？？这是啥逻辑？

**Comment by sikenali** [comment]
@fonlan 不要误解 只是说linux提供更好的安装方式

**Comment by snowie2000** [comment]
linux下你可以编译一些组件来实现自定义字体渲染，但是我并不懂linux编程，而且MacType的代码也不是为linux设计的，linux下相关的排版和文字绘制API全部都不一样，支持linux约等于完全重写。

如果你有兴趣的话欢迎开一个项目，把MacType相关的渲染代码拿去用应该就可以了。

**Comment by sikenali** [comment]
谢谢
