### ISSUE TITLE
VAC BAN

### ISSUE THREAD

**Issue by douglasb78** [snowie2000/mactype#500]
Today I decided to play Team Fortress 2 on Steam, but I was unable to join any servers and then I noticed I got a VAC error . Firstly I was unsure about what triggered VAC anti-cheat, but after looking through all installed softwares in my computer I got suspicious about MacType. **Does it realize any kind of memory reading/writing on executables or dll injection?**

**Comment by Mahayu** [comment]
#486

**Comment by ghost** [comment]
In registry mode, Source Engine games like TF2 just work fine with MacType for me. I had joined official server with MacType enabled two weeks ago, but I did not get any VAC ban.
