### ISSUE TITLE
Many processes crash when selecting profile after upgrade to 2018.1-beta5 (Win7 64bit)

### ISSUE THREAD

**Issue by mjb2010** [snowie2000/mactype#501]
On Win7 64-bit, when I ran the installer to replace the running 2017_0628 version with 2018.1-beta5, I did not know whether to disable the old version first, so I left it running. It was running in registry mode, so it was hooked into just about every process. After the upgrade, in MacTray I selected registry mode and then selected a profile. When I got to the Finish stage, about 20 processes crashed, including Explorer, several services, apps with windows open, and things running in the system tray. So, I rebooted and tried again. This time, at the Finish stage, only one process crashed (IAStorIcon.exe). I added it to my profile's UnloadDLLs list for now.

It seems some more work is needed to make the upgrade seamless.

**Comment by mjb2010** [comment]
Upon further investigation, it seems there was a prior version of MacType which did not fully get removed from Program Files (x86) ... the 32-bit systray apps are using EasyHK.dll and MacType.dll from that folder. It is possible that the crashes were related to the concurrent versions in use.

**Comment by sammilucia** [comment]
Cool, thank you @mjb2010, to be clear were they in C:\program files (x86)\mactype ?

I'll have the installer remove those too. Thanks for your help

**Comment by mjb2010** [comment]
Yes exactly... I ended up removing as much as I could and then renaming the directory and rebooting in order to set free the remaining 2 DLLs. All seems to be working smoothly after that; no need to make an exception for IAStorIcon.exe or the other systray apps that somehow all were using that old MacType code.

**Comment by sammilucia** [comment]
@mjb2010 please try the new beta6 here https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6. I will close this issue as we believe it's resolved however if you still have problems please let us know (respond to this thread).
