### ISSUE TITLE
Incomplete rendering

### ISSUE THREAD

**Issue by tagorereddy** [snowie2000/mactype#503]
Some elements of any '**Properties**' window are incompletely rendered. As shown in the images, some text is darker(rendered) and the other isn't.

![capture1](https://user-images.githubusercontent.com/10401243/51458594-bf596300-1d7b-11e9-8438-8cc93c84ef53.JPG)
![capture2](https://user-images.githubusercontent.com/10401243/51458595-bff1f980-1d7b-11e9-98be-5e6b0f8e0154.JPG)

**OS**: Windows 10 Pro 1803 Build 17134 64-bit
**MacType**: 2018.1-beta5 (Service Mode & Tray Mode)
**Profile setting**: Clean
**DirectWrite**: Enabled

**Comment by extratype** [comment]
System Properties runs under admin rights, so MacType can't be loaded from the start. MacType Service injects MacType later. Now MacType only applies to redrawn elements.

Launch a command prompt as Admin, wait for MacType to load, then run "C:\Windows\System32\SystemPropertiesAdvanced.exe". You will see System Properties is properly rendered.

**Comment by tagorereddy** [comment]
I'd tried as suggested with no success. The window still looks semi-rendered. If it's the case of privileges, the window should've been completely non-rendered. I tried with admin preveliges and still the result is same.

**Comment by snowie2000** [comment]
@tagorereddy What will happen if you disable and reenable MacType for ~explorer.exe~ `SystemPropertiesAdvanced.exe` from the process manager?

**Comment by tagorereddy** [comment]
**SystemPropertiesAdvanced.exe** 

**Disabled** : Everything goes back to unrendered state.

**Enabled** : Semi-rendered state as mentioned above.

**Comment by tagorereddy** [comment]
This situation in not isolated to **SystemPropertiesAdvanced.exe**. Properties window of any folder or file is Semi-rendered. But rest of the elements of **Explorer.exe** are properly rendered.

**Comment by snowie2000** [comment]
Have you turned off your ClearType or changed your system fonts?

**Comment by tagorereddy** [comment]
No changes to any default system settings. Only MacType on top of stock Windows

**Comment by sammilucia** [comment]
I've also seen this problem. I believe extratype's https://github.com/snowie2000/mactype/issues/503#issuecomment-456763838 is correct

Referenced in $427

**Comment by tagorereddy** [comment]
Versión ** 2019.1-beta6** seems to have fixed this issue.

**Comment by tagorereddy** [comment]
Versión **2019.1-beta6** seems to have fixed this issue.

**Comment by sammilucia** [comment]
Thanks #tagorereddy
