### ISSUE TITLE
CPU consumption rate of WmiPrvSE

### ISSUE THREAD

**Issue by wmjordan** [snowie2000/mactype#504]
I found that WmiPrvSE was periodically consuming some CPU resources when MacType was in effect.
And I read that in the beta 4 release notes of MacType:

> Better process capture with WMI process capture, MacTray should now capture newly created process in less than 1s and no snapshot poll is required. So there should be no CPU use peak every 5s anymore

It was true that the MacType processes no longer caused CPU peaks, however, those peaks now transferred to WmiPrvSE which peaks every second.

Either Load by MacTray Mode or Service Mode, peaks of WmiPrvSE occurred. If MacType was disabled, those peaks no longer appeared.

OS: Win10 1809 with latest patches
MacType: Both beta 4 and 5 caused this problem

**Comment by snowie2000** [comment]
There is gonna be some way to capture the newly created processes, right?
Actually, this behavior is highly system dependent. Some users see no peak at all while others may see significant peaks.

Before I switched to the WMI way, there were also reports like #237 and #375 that report high CPU usage up to 20% on i5 CPU. I'm running MacType on an i5 mobile CPU with no obvious CPU usage observed. Therefore, as I said, it depends on your system and applications running on your system.

If you're highly concerned about it, set the Interval to 0 or switch to registry mode should fix it permanently with or without some disadvantages.

Please correct me if there are better ways to detect process creation. Thanks.

**Comment by wmjordan** [comment]
Thanks for replying.
It seems that it is already the best way to monitor creation and destruction of processes.
I will reply this comment if I find a better way.

**Comment by wmjordan** [comment]
The process pooling actually wastes quite some substantial of CPU power since most pooling does not return newly created processes.

Since it only makes sense rendering fonts on visually visible windows, is it possible to [hook window creation events](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwineventhook) and inject MacType DLL into that process corresponding to the window?
