### ISSUE TITLE
Beta 0.5 pixelated text

### ISSUE THREAD

**Issue by MariuzM** [snowie2000/mactype#506]
I have noticed that in some Windows elements i get pixelated text. Example Services:

Before:
https://imgur.com/a/j4Y8PP7

After:
https://imgur.com/a/UW2iIdp

**Comment by MariuzM** [comment]
So no one knows?

**Comment by snowie2000** [comment]
I'm on vacation right now.  I'll be back one week later. 
 Thank you as always

**Comment by sammilucia** [comment]
hi @MariuzM,

I believe this is the same issue as #416 ... does it look similar to you?

If you disable DPI scaling it should go away. It's a bit of a complicated problem to fix but may be addressed in a future version.

**Comment by MariuzM** [comment]
Disabling DPI scaling wont be really an option because everything is going to be to small. I think best option is to disable MacType on these type of Windows (legacy) elements, i'm just not sure how to do that.

**Comment by MariuzM** [comment]
Solved thanks i have excluded mmc.exe from the MacType working great now.
