### ISSUE TITLE
清空回收站导致资源管理器崩溃

### ISSUE THREAD

**Issue by Eveg0** [snowie2000/mactype#508]
开启后，在清空回收站时，会导致资源管理器崩溃。
MacType版本:	1.2017.628.0
MacTray版本:	1.0.5.2048
MacTuner版本: 1.0.2.350
Windows 10 1903版

**Comment by snowie2000** [comment]
您好，请更新到beta5后再试一下。谢谢

**Comment by Eveg0** [comment]
> 您好，请更新到beta5后再试一下。谢谢
使用测试版正常。不过貌似一些页面还没有做到兼容，比如任务管理器。

**Comment by Eveg0** [comment]
> 您好，请更新到beta5后再试一下。谢谢

**Comment by snowie2000** [comment]
请更新到beta6后再看一下，谢谢

**Comment by Eveg0** [comment]
链接能发下吗？谢谢！

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Wednesday, June 19, 2019 9:40:08 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; State change
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


Closed #508<https://github.com/snowie2000/mactype/issues/508>.

―

**Comment by snowie2000** [comment]
release页面下载

**Comment by Eveg0** [comment]
好的。谢谢！

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Wednesday, June 19, 2019 10:10:25 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; State change
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


release页面下载

―

**Comment by Eveg0** [comment]
你好，beta 6 版打开系统字体设置界面，会导致资源管理器重启。

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Wednesday, June 19, 2019 10:10:25 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; State change
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


release页面下载

―

**Comment by snowie2000** [comment]
这种类似的报告看过很多了，出现问题的原因几乎无一例外都是安装的字体有问题。某些字体不规范导致和freetype出现不兼容，所以只能一个个删字体排除吧。

**Comment by snowie2000** [comment]
如果确定是哪个字体导致的问题可以把问题报告给freetype开发组，他们解决后我们会跟进。

**Comment by Eveg0** [comment]
哦。好吧！

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Saturday, June 22, 2019 9:15:12 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


这种类似的报告看过很多了，出现问题的原因几乎无一例外都是安装的字体有问题。某些字体不规范导致和freetype出现不兼容，所以只能一个个删字体排除吧。

―

**Comment by Eveg0** [comment]
好的。谢谢！

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Saturday, June 22, 2019 9:15:40 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


如果确定是哪个字体导致的问题可以把问题报告给freetype开发组，他们解决后我们会跟进。

―

**Comment by snowie2000** [comment]
win10的字体对话框是dw的，理论上不可能受到mactype的影响而崩溃。

你可以试试滚动到哪里才会崩溃，然后关闭mactype看看是什么字体，然后告诉我们，我们再去测试.

**Comment by Eveg0** [comment]
是这个字体设置页面。

[cid:image001.png@01D5294B.E870A4C0]


________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Saturday, June 22, 2019 10:40:57 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


win10的字体对话框是dw的，理论上不可能受到mactype的影响而崩溃。

你可以试试滚动到哪里才会崩溃，然后关闭mactype看看是什么字体，然后告诉我们，我们再去测试.

―

**Comment by snowie2000** [comment]
请不在邮件中上传图片，github必须在网页上传

**Comment by Eveg0** [comment]
好的。

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Saturday, June 22, 2019 10:44:50 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


请不在邮件中上传图片，github必须在网页上传

―

**Comment by Eveg0** [comment]
打开字体设置页面，会导致资源管理器重启。
<img width="845" alt="Snipaste_2019-06-22_22-46-47" src="https://user-images.githubusercontent.com/33872980/59965378-b4c81300-953f-11e9-8941-04b269b63a0b.png">

**Comment by snowie2000** [comment]
你试试滚动到哪里就出错了，然后关闭mactype看看出错那行有什么字体

**Comment by snowie2000** [comment]
如果一打开就出错就说明这第一页就出错了，把窗口缩小点再进去

**Comment by snowie2000** [comment]
您好，请问是否找到了导致崩溃的字体？

**Comment by Eveg0** [comment]
没有。排查难度太大。因为打开字体设置页面就直接闪退。

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Monday, June 24, 2019 5:03:09 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


您好，请问是否找到了导致崩溃的字体？

―

**Comment by snowie2000** [comment]
打开控制面板，并把窗口缩小，然后再进入fonts面板，这样的话，界面就应该是类似这样的：
![fonts](https://user-images.githubusercontent.com/11767189/60006117-67b08200-96a2-11e9-89e5-5a9581021770.png)
排查就会很容易

**Comment by Eveg0** [comment]
嗯。我试试

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Monday, June 24, 2019 5:06:45 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


打开控制面板，并把窗口缩小，然后再进入fonts面板，这样的话，界面就应该是类似这样的：
[fonts]<https://user-images.githubusercontent.com/11767189/60006117-67b08200-96a2-11e9-89e5-5a9581021770.png>
排查就会很容易

―

**Comment by Eveg0** [comment]
集中在这几个字体上面。如果是四排列，到“constantia”一行就闪退了。如果是单列，到“courier”常规闪退。
[cid:image003.png@01D52AB1.F0027AD0]

发件人: snowie2000<mailto:notifications@github.com>
发送时间: 2019年6月24日 17:06
收件人: snowie2000/mactype<mailto:mactype@noreply.github.com>
抄送: Eveg Chan<mailto:chenchangqing@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


打开控制面板，并把窗口缩小，然后再进入fonts面板，这样的话，界面就应该是类似这样的：
[fonts]<https://user-images.githubusercontent.com/11767189/60006117-67b08200-96a2-11e9-89e5-5a9581021770.png>
排查就会很容易

―

**Comment by Eveg0** [comment]
[cid:image002.png@01D52AB2.D36514E0]
[cid:image006.png@01D52AB2.D36514E0]

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Monday, June 24, 2019 5:06:45 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


打开控制面板，并把窗口缩小，然后再进入fonts面板，这样的话，界面就应该是类似这样的：
[fonts]<https://user-images.githubusercontent.com/11767189/60006117-67b08200-96a2-11e9-89e5-5a9581021770.png>
排查就会很容易

―

**Comment by snowie2000** [comment]
…………
github不支持从邮件上传图片……………………
谢谢

**Comment by Eveg0** [comment]
好的。我重新上传下。

________________________________
发件人: snowie2000 <notifications@github.com>
发送时间: Monday, June 24, 2019 5:33:31 PM
收件人: snowie2000/mactype
抄送: Eveg Chan; Comment
主题: Re: [snowie2000/mactype] 清空回收站导致资源管理器崩溃 (#508)


…………
github不支持从邮件上传图片……………………
谢谢

―

**Comment by Eveg0** [comment]
如果是四排列，到“constantia”一行就闪退了。如果是单列，到“courier”常规闪退。
![12121](https://user-images.githubusercontent.com/33872980/60008415-a6e0d200-96a6-11e9-9e5d-5421af063ae6.png)
![4557485](https://user-images.githubusercontent.com/33872980/60008420-a8aa9580-96a6-11e9-86e0-ab1045e953d9.png)

**Comment by snowie2000** [comment]
Courier是一个点阵字体，遇到点阵MacType都是直接忽略，根本不参与输出……
这样的话，只能建议您生成dump文件来分析了，方法参考这个文章
http://www.pukuimin.top/post/89.html
