### ISSUE TITLE
2018.1-beta5版, chrome 72崩溃

### ISSUE THREAD

**Issue by Rhapsodyx2** [snowie2000/mactype#509]
雪大您好，

我看了类似的issues(#489 #498 )，觉得可能不是我的个别情况。 
如果发的问题重复了，请见谅。

使用MacType_2017_0628_0, chrome正常，但是字体不会渲染。
使用MacType_2018.1-beta5，chrome每次都崩溃，
试过了注册表加载和服务加载，没有安装第三方补丁。

系统是windows 8.1, 显卡是980m sli(应该无关)，我是小白。
很喜欢这款软件，谢谢。

![mactype](https://user-images.githubusercontent.com/47478583/52619656-3c8c7980-2edd-11e9-8f22-b3732105aec0.png)

**Comment by snowie2000** [comment]
试试托盘模式。
我这边没有办法让chrome每次都崩溃（基本不崩溃），由于chrome的特殊性，既不能生成dump也不能生成日志，所以如果我这边无法重现基本上就无法解决。

**Comment by Rhapsodyx2** [comment]
谢谢雪大，没能解决。
渲染效果很舒服，我把谷歌浏览器卸载了不用了，其他浏览器用的挺好的。

**Comment by Vstory** [comment]
使用**火绒安全软件**创建自定义防护规则，禁止 `MacTray.exe` 读取 `chrome.exe` 即可解决。

![Snipaste_自定义防护_2021-03-29_15-04-02](https://user-images.githubusercontent.com/20795557/112798811-064feb00-90a0-11eb-8b8e-043447738f03.png)

只能解决 Chrome 崩溃。
