### ISSUE TITLE
2018.1-beta5 选择“停用”后，对firefox 无法再次启用，需要重启firefox。

### ISSUE THREAD

**Issue by brucekiller** [snowie2000/mactype#512]
win7 x64 ，firefox64 65.0.1，独立加载模式。在firefox开启时，若暂时停用mactype，然后选择“启用”或“重新启用”，都无法对firefox再次渲染，需要重新启动firefox，才可以正常渲染。

![2019-02-22](https://user-images.githubusercontent.com/22873806/53197998-5acd4480-3656-11e9-9ab5-9aefaf4bda6d.jpg)

**Comment by snowie2000** [comment]
Firefox和chrome及Edge（老版本）一样，所有子进程均有沙盘保护。进程一旦初始化完成即进入沙盘状态，此后再也无法读取文件系统（或只能读取规定的部分内容）

所以MacType可以通过`HookChildProcess`的方式在进程受保护前加载，但是一旦firefox子进程已经开始运行，就无法再启用了。这是沙盘的正常保护特性，除非有漏洞（有也很快会被修复的），否则不能对运行中的firefox启用MacType是属于完全正常的。

**Comment by brucekiller** [comment]
谢谢答复，其实这个问题实际上也没什么影响，一般也不需要停用mactype。
