### ISSUE TITLE
Garbage fonts in Pale Moon

### ISSUE THREAD

**Issue by vikvaughn** [snowie2000/mactype#515]
Getting garbage fonts over my new tab page and a few other websites. Is there any way to solve this beyond going back to using it from the tray instead of the reg?
![](https://i.imgur.com/g2wy6PG.png)

**Comment by snowie2000** [comment]
Are you using font substitution? If so, disable it and try again.

**Comment by vikvaughn** [comment]
I already looked through the threads and disabled it and it didn't fix the problem. I had no issues until I updated to the beta today. It only seems to be on sites where I have set Helvetica Neue as the font via custom CSS, but I use that as my system font and the default sans serif for Pale Moon so I don't see why that would cause an issue.

**Comment by snowie2000** [comment]
Does it only happen in registry mode?

**Comment by sammilucia** [comment]
@vikvaughn did you see Snowie's question?

Also that looks like DirectWrite rendering. Please try the Firefox steps in Pale Moon (if it has them) and see if that helps? See https://github.com/snowie2000/mactype/wiki/Mozilla-Firefox

**Comment by sammilucia** [comment]
@vikvaughn did you have any luck with the questions above?

**Comment by vikvaughn** [comment]
I've since moved over to a different machine and had no issues, I never managed to solve the problem and went back to using it from the tray. On my new PC I've been using it in service mode. Sorry for the slow reply, I don't check my github all that often.

**Comment by snowie2000** [comment]
I'm closing the issue. Feel free to reopen it if it occurs again.
