### ISSUE TITLE
使用同样的jre64, 对idea字体渲染的有效但是对pycharm的无效果

### ISSUE THREAD

**Issue by trim21** [snowie2000/mactype#516]
![qq 20190304022127](https://user-images.githubusercontent.com/13553903/53699581-e5672e00-3e24-11e9-9d9c-0ef4fa6c2261.png)
同样的字体设置, pycharm看着字体偏细, 应该是因为mactype没有起效
今天把pycharm更新到3.5之后mactype就不再起效了. (不记得原来的版本号了)

之前也有过类似的情况, 是pycharm起效但是goland没有起效.
在mactype的详细信息里看到pycharm的状态是已启用.

这是mactype所用的设置
https://paste.ubuntu.com/p/7r2GRr7pSZ/

不确定到底是哪里的问题, 希望能得到一些帮助

**Comment by snowie2000** [comment]
你再写几个中文字试试看，我的感觉是pyCharm是基于DirectWrite编写的了，和vsCode一样。

如果是dw的话，你需要想办法禁用dw（如果可以），无法禁用的话，那就没办法了。

**Comment by trim21** [comment]
中文的效果是这样的
![qq 20190304151425](https://user-images.githubusercontent.com/13553903/53717060-ee421900-3e91-11e9-8013-844bac81bfed.png)
我正在找禁用DW, 看看能不能有效

**Comment by snowie2000** [comment]
似乎就是dw了，你可以试试调整directwrite段相关的参数，不过很难获得和freetype完全一样的效果的。

**Comment by ddzy** [comment]
> 似乎就是dw了，你可以试试调整directwrite段相关的参数，不过很难获得和freetype完全一样的效果的。

vscode的显示效果也不好, 有什么解决办法么?

**Comment by snowie2000** [comment]
vscode有一些说法是可以关闭dw，不过我并不确定。如果无法关闭的话，那么和pyCharm一样，没得救。

**Comment by trim21** [comment]
惨剧，找不到办法关掉dw
之前有一段时间goland也出现了同样的mactype无法渲染的问题，但是现在又可以，希望pycharm后几面也能切回来…

**Comment by snowie2000** [comment]
goland似乎还是gdi的，至少我这边的版本2018.3.2是的。

**Comment by snowie2000** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000720724-phpstorm-open-directwrite-font-rendering-api-in-windows-7

这边解释了intellj的字体渲染依赖于jdk，可以用命令行的方法启用DirectWrite，我猜测也可以用类似的方法禁用DirectWrite。

**Comment by trim21** [comment]
这个我试过了，没有效果…

**Comment by trim21** [comment]
一个月之后, 突然又对pycharm起效了, 而且pycahrm仍然是3.5版本, 也不知道是发生了什么...

**Comment by kaynAw** [comment]
> https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000720724-phpstorm-open-directwrite-font-rendering-api-in-windows-7
> 
> 这边解释了intellj的字体渲染依赖于jdk，可以用命令行的方法启用DirectWrite，我猜测也可以用类似的方法禁用DirectWrite。
设置 -Ddirectwrite.font.rendering=false 后亲测Goland2022.1.2生效

**Comment by knwgo** [comment]
> https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000720724-phpstorm-open-directwrite-font-rendering-api-in-windows-7
> 
> 这边解释了intellj的字体渲染依赖于jdk，可以用命令行的方法启用DirectWrite，我猜测也可以用类似的方法禁用DirectWrite。

设置 -Ddirectwrite.font.rendering=false 后亲测Goland2022.1.2生效
