### ISSUE TITLE
Add option to include only specific fonts

### ISSUE THREAD

**Issue by sbatten** [snowie2000/mactype#517]
Maybe this is already an option, but I can only find the option to exclude certain fonts. I would rather be able to specify fonts that should be rendered with MacType and let everything else render normally.

Most monospaced fonts for programming look terrible on Windows, but Windows' built-in fonts render pretty well and MacType makes them blurry. So, I would like to only render these monospaced fonts with MacType.

**Comment by snowie2000** [comment]
I think Windows makes most of the fonts looking bad, so only exclude function is available.

Anyway, it's always good to have choices and it seems not so hard to implement. I'll add it to the plan.

**Comment by sbatten** [comment]
Thanks @snowie2000 ... I tried to make a PR but I'm still having troubles testing changes. I'm using vs2017 even though I got things to build, dropping in the output dll to my installation of mactype resulted in mactray opening and never enabling.

**Comment by snowie2000** [comment]
You could write a little demo program and let it manually load MacType.core.dll via `LoadLibrary`. It's much easier to figure out what has happened inside the MacType core in this way.

**Comment by sammilucia** [comment]
@sbatten please try the new beta6 here https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6. I will close this issue as we believe it's resolved however if you still have problems please let us know (respond to this thread).

**Comment by sbatten** [comment]
@sammilucia Thanks for the update. I was able to test this out and it works well with certain applications. I was curious what the current status of chromium based app support is with MacType. I was testing this new setting with VS Code and I see that MacType does affect font rendering within the app, but this new `Include` setting does not seem to have any affect. i.e. All fonts are still affected.

**Comment by snowie2000** [comment]
For directwrite based applications such as vscode, chrome, the `Include` doesn't affect them.

**Comment by lakshits11** [comment]
** HACK FONT IS NOT RENDERED CORRECTLY **

Hello There, So basically what should one do to include/exclude only specific fonts on the latest version of MacType? Please answer. Thank You.

**Comment by snowie2000** [comment]
@lakshits11 
https://github.com/snowie2000/mactype/wiki/Include-section
and 
https://github.com/snowie2000/mactype/wiki/Exclude-Section
fulfill your needs.

**Comment by lakshits11** [comment]
Yes but can you please tell me where can I find these inclusion and exclusion sections  in the application ?

**Comment by snowie2000** [comment]
In the profile you are using, you may find one and modify it to fit your need.
If they didn't exist, just make one.

**Comment by lakshits11** [comment]
![a](https://user-images.githubusercontent.com/54276661/113988975-9c88cb80-986d-11eb-842d-0cf2a0178218.PNG)

See I opened MacTuner But I can't find the INCLUDE section..please help..

**Comment by snowie2000** [comment]
I'm sorry but the mactunner hasn't updated for quite a while. There are a bunch of new features missing.
You have to edit the profile with a text editor to use those new features.

**Comment by lakshits11** [comment]
Ok so what I should do is to Open the .ini file in a text editor then Modify **_ONLY_** fonts written under [Include] and [Exclude] keywords ?

**Comment by lakshits11** [comment]
Also I want only 2 fonts to be modified in My machine so should what should I remove and add from default.ini file when opened in a text editor..Please help

**Comment by snowie2000** [comment]
Yes. Or create a [include] section if it doesn't exist.
Also, you don't have to use include and exclude at the same time. For your needs, an include section should be enough.

Like:
```
[Include]
fontname1
fontname2
```

Nothing needs to be removed if you are referring to the default.ini profile.

**Comment by lakshits11** [comment]
So I removed [Exclude] section and added 

[Include]
;Hack
;Hack Nerd Font

Before it was like:

[Exclude]
;【除外的字体】


is it correct ?

**Comment by snowie2000** [comment]
`;` starts a comment line in the ini format. 
Never start a line with a semicolon unless that's what you want.

**Comment by lakshits11** [comment]
ok thank you But I had a doubt that when nothing was there in the [Include] section, it rendered all fonts, so if we define a include section then it will render only those fonts  and nothing else, right ?

**Comment by lakshits11** [comment]
And also if font name have space between words should I write them between brackets or not.

Thank You

**Comment by snowie2000** [comment]
You don't need any quotations or other things. The font names are read line-based.

**Comment by lakshits11** [comment]
And please clear my doubts about the other comment too. Thanks!

**Comment by lakshits11** [comment]
> But I had a doubt that when nothing was there in the [Include] section, it rendered all fonts, so if we define a include section then it will render only those fonts and nothing else, right ?

Please tell me about it. It would be a great help since yesterday I installed MacType and everything was going smoothly but some fonts were rendered very poorly and they were rendered correctly before. So that's why I wanted to render only necessary fonts

**Comment by lakshits11** [comment]
Hello please answer this as soon as you can. It would really be a great help. Please!

**Comment by snowie2000** [comment]
Please attach a screenshot to illustrate the issue.

**Comment by lakshits11** [comment]
Unfortunately I dont have a screenshot now as I deleted mactype yesterday due to issues and Today I reinstalled it with settings as above described but It is still causing problems to my other fonts which are not in the [Include]

**Comment by snowie2000** [comment]
Please upload a screenshot of your messed font rendering.
