### ISSUE TITLE
Why does MacType start unsecapp.exe now?

### ISSUE THREAD

**Issue by gatolanudo** [snowie2000/mactype#520]
I know this is a Windows process -although its description is quite ambiguous and foggy- but why now?

On compatibility mode it doesn't start, though.
Thanks.

(Windows 10 v.1803)

**Comment by snowie2000** [comment]
It's part of the Windows system and it is responsible for WMI subsystem interaction.

From the beta5 on, MacType relies on WMI system to capture process creations, that's why the process is started.

**Comment by gatolanudo** [comment]
I see. Thank you so much for the quick and detailed answer.
