### ISSUE TITLE
DirectWrite feature crashes Chrome

### ISSUE THREAD

**Issue by a0193143** [snowie2000/mactype#522]
Using the latest 2018.1-beta5
Noticed if the DirectWrite enabled, Chrome will keep crashing

OS: Windows 8.1 64bit

**Comment by snowie2000** [comment]
This usually caused by some anti-malware software as the DirectWrite support is the simplest one: it only changes the parameters of the DirectWrite engine.

**Comment by a0193143** [comment]
I had a clean install Win8.1(64bit), with only Chrome(73.0.3683.86 64bit) and Mactype
It still crashes Chrome, or do I need to provide logs?

![DW1](https://user-images.githubusercontent.com/32773311/54987585-cdcc3100-4fef-11e9-98be-415b648634bf.png)
![DW0](https://user-images.githubusercontent.com/32773311/54987586-cdcc3100-4fef-11e9-9609-07f5352fb415.png)

**Comment by Garry050** [comment]
Can you try other chromium based browser? like... Cent Browser, Chromium, Brave etc etc

**Comment by rudolphos** [comment]
I have unrelated problem where Brave and Brave Dev is the only chromium browser where mactype doesn't work.

![image](https://user-images.githubusercontent.com/4366810/55231853-7f57a600-522c-11e9-9f28-177cad76caa9.png)

![image](https://user-images.githubusercontent.com/4366810/55231861-82529680-522c-11e9-90ee-bc18c6d66d79.png)

**Comment by snowie2000** [comment]
The quality of your screenshots is too bad to see details.

**Comment by a0193143** [comment]
> 
> 
> The quality of your screenshots is too bad to see details.

I recorded a video for more details.
https://youtu.be/wQIfxs9NFow

**Comment by snowie2000** [comment]
Did you modify any part of the profile?

**Comment by a0193143** [comment]
Nope, just "DirectWrite", and the other built-in profiles like XMac have the same problem.

**Comment by sammilucia** [comment]
@a0193143 is the issue still occurring with Chrome 74?

**Comment by a0193143** [comment]
> 
> 
> @a0193143 is the issue still occurring with Chrome 74?

@sammilucia Still the same

**Comment by sammilucia** [comment]
@a0193143 thank you! I'm sorry for the delay.

Interesting, can anyone else confirm this?

In the meantime @a0193143, Cent Browser is the recommended browser for MacType, it's based on Chrome but still supports GDI (or DirectWrite) font rendering, plus a number of other enhancements.

**Comment by snowie2000** [comment]
@a0193143 Hi, I would like to know if you are available for some tests.
I would like to compile new versions for you with some of the directwrite features disabled so that we can locate the problematic code.

**Comment by a0193143** [comment]
> 
> 
> @a0193143 Hi, I would like to know if you are available for some tests.
> I would like to compile new versions for you with some of the directwrite features disabled so that we can locate the problematic code.

Sure

**Comment by snowie2000** [comment]
Ok, the first build I would like you to try is this one:
[MacType-no-replace.zip](https://github.com/snowie2000/mactype/files/3151622/MacType-no-replace.zip)

This one has the latest process injector and has DirectWrite font substitution disabled which, I believe, most likely caused the problem.

**Comment by a0193143** [comment]
> 
> 
> Ok, the first build I would like you to try is this one:
> [MacType-no-replace.zip](https://github.com/snowie2000/mactype/files/3151622/MacType-no-replace.zip)
> 
> This one has the latest process injector and has DirectWrite font substitution disabled which, I believe, most likely caused the problem.

Unfortunately, the problem still there.

**Comment by a0193143** [comment]
Plus, I've tested previous beta versions, this problem occured since beta4.
Beta 1 and 2 are fine.

**Comment by snowie2000** [comment]
Thank you. this helps narrowing down the problem a lot.

**Comment by snowie2000** [comment]
This will definitely work for you.
[MacType-W8.zip](https://github.com/snowie2000/mactype/files/3156627/MacType-W8.zip)

-----------------

I ended up building my own Windows 8.1 VM and it took me several hours to realize why Windows 8 is well known as Windows bug 8.
It has too many bugs in all aspects. A lot of common APIs don't work correctly or simply crashed when called when the app is sandboxed, such as `GetDC`, `GetStockObject`, `DeleteDC`, and DirectWrite also doesn't work as expected. GDI interop crashed on use, cast interface from `IDWriteFont3` to `IDWriteFontFaceReference` succeeded but returned an empty result to me which caused another crash...

I've added some more checks to MacType and fully disabled font substitution of DirectWrite on Windows 8/8.1. And finally, it works.

**Comment by a0193143** [comment]
> 
> 
> This will definitely work for you.
> [MacType-W8.zip](https://github.com/snowie2000/mactype/files/3156627/MacType-W8.zip)
> 
> I ended up building my own Windows 8.1 VM and it took me several hours to realize why Windows 8 is well known as Windows bug 8.
> It has too many bugs in all aspects. A lot of common APIs don't work correctly or simply crashed when called when the app is sandboxed, such as `GetDC`, `GetStockObject`, `DeleteDC`, and DirectWrite also doesn't work as expected. GDI interop crashed on use, cast interface from `IDWriteFont3` to `IDWriteFontFaceReference` succeeded but returned an empty result to me which caused another crash...
> 
> I've added some more checks to MacType and fully disabled font substitution of DirectWrite on Windows 8/8.1. And finally, it works.

Yep, it does work.
Thanks
Looking for stable release! :)

**Comment by sammilucia** [comment]
Can I just take a moment to acknowledge what a kick-ass coder @snowie2000 is? I've worked with a lot of coders snowie and you're amazing 😊

**Comment by sammilucia** [comment]
Please try the new beta6 here https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6. I will close this issue as we believe it's resolved however if you still have problems please let us know (respond to this thread).
