### ISSUE TITLE
Does not work with Centbrowser 3.9.2.45

### ISSUE THREAD

**Issue by sorakirahk** [snowie2000/mactype#526]
Useing Centbrowser 3.8 , everything was fine. Mactype worked.
But when I  upgrade the Centbrowser to 3.9.2.45 (Chromium 72.0.3626.121)
Mactype don't work any more.
Is there a way to solve this?
Or juest reinstall the Centbrowser 3.8?

**Comment by sammilucia** [comment]
That's interesting! Mine is working here
![image](https://user-images.githubusercontent.com/3295286/56625778-06f2d200-667e-11e9-8aeb-b45868d74d0f.png)

Have you followed the settings mentioned here? https://github.com/snowie2000/mactype/wiki/Google-Chrome

**Comment by sorakirahk** [comment]
> That's interesting! Mine is working here
> ![image](https://user-images.githubusercontent.com/3295286/56625778-06f2d200-667e-11e9-8aeb-b45868d74d0f.png)
> 
> Have you followed the settings mentioned here? https://github.com/snowie2000/mactype/wiki/Google-Chrome

Thanks a lot, it's worked!
Sorry I don't konw the setting will change to default after upgrade (last few times I upgrade, mactype worked)

**Comment by sammilucia** [comment]
The settings shouldn't have changed! But who knows!

Okay great, thank you for confirming 😊. Closing Issue.
