### ISSUE TITLE
Can MacType be configured to take effect only for individual applications?

### ISSUE THREAD

**Issue by arfaWong** [snowie2000/mactype#528]

**Comment by sammilucia** [comment]
Related to #517 Thank you for the suggestion @arfaWong

**Comment by snowie2000** [comment]
@sammilucia It is not the same as #517 as that proposal is for individual fonts.

This function has been implemented already with a rarely known option: [UseInclude](https://github.com/snowie2000/mactype/wiki/UseInclude)
Take a look at the wiki page.
