### ISSUE TITLE
getting error messages and not working with Firefox 66

### ISSUE THREAD

**Issue by JimFlasch** [snowie2000/mactype#532]
MacType is not working with Firefox 66. I have skia removed from gfx.canvas.azure.backends and  gfx.content.azure.backends and have gfx.webrender.force-disabled set to true.

**Comment by JimFlasch** [comment]
I have also had it give me an error message on startup - "invalid image size" and also another message saying "Exception EOutOfResources in module MacTray.exe st 000386D0. The Window does not have scroll bars." That last sentence does not make sense, since MacTray does still work in apps that have scrollbars, like WPS Office.
An attempt to repair the program did not fix those errors.

**Comment by snowie2000** [comment]
> I have also had it give me an error message on startup - "invalid image size" and also another message saying "Exception EOutOfResources in module MacTray.exe st 000386D0. The Window does not have scroll bars." That last sentence does not make sense, since MacTray does still work in apps that have scrollbars, like WPS Office.
> An attempt to repair the program did not fix those errors.

This is a known bug for Raize component that it doesn't work properly on some third-party themes especially those with small title bars, but it should not affect your actual uses.
Please try to switch to a different theme to see if it back to work.

**Comment by JimFlasch** [comment]
I'll try that, but what about it no longer working with Firefox?

**Comment by snowie2000** [comment]
This is most likely related to a configuration problem since it is really tricky to tweak the firefox settings.
And I am not a user of Firefox, hence I don't have enough experience to tell you what you might need to change to make it work again. sigh.

**Comment by JimFlasch** [comment]
Tried your advice and everything's back to normal! Thanks.

**Comment by sammilucia** [comment]
Closing issue. @JimFlasch please let us know if we can be of any further help 😊
