### ISSUE TITLE
部分软件界面出现字体重叠

### ISSUE THREAD

**Issue by TANKEZHUANXIU** [snowie2000/mactype#537]
尊敬的开发者你好！
mactype Beta5版在“Internet Download Manager6.33”版软件界面上存在部分字体渲染后出现字体重叠的现象！
PS:本人使用windows10专业版 1809
![1558708959(1)](https://user-images.githubusercontent.com/50994896/58336584-8d195880-7e76-11e9-94d4-abec95211db2.jpg)

**Comment by snowie2000** [comment]
你好，请不要随意使用字体替换
字体替换原则上只能用相同参数的两种字体来做替换（网上有达人专门做了一些用于替换的字体），随便按喜好替换的话，是否能正常工作只能看运气了

替换从原则上说是要看具体软件对字体的要求的一些软件如记事本之类对字体没什么要求，他们就可以随便替换，其他很多软件对字体排版是有要求的，替换后很容易乱掉。
