### ISSUE TITLE
Cause Extensions of Chromium Browser crash

### ISSUE THREAD

**Issue by Youxikong** [snowie2000/mactype#538]
Some extensions of chromium browser will crash whenever browsers are added to excludemodule list. For example, [Aria2助手](https://chrome.google.com/webstore/detail/mbceplmgodfokjalhafchlhdfamccdbn).

一些chromium浏览器的扩展会崩溃，无论浏览器有没有添加到除外的程序的列表中，比如[Aria2助手](https://chrome.google.com/webstore/detail/mbceplmgodfokjalhafchlhdfamccdbn)这个扩展。

**Comment by snowie2000** [comment]
等待下一个版本发布。
我们解决了一系列的崩溃问题。

**Comment by sammilucia** [comment]
May not be related, but please also be aware there is a bug in the latest hotfix of Windows 10 1809, and 1903 with Control Flow Guard (CFG) that can cause Chrome, Cent Browser, Edge, and anything else based on Chromium, to crash. That particular problem is not a MacType problem.

**Comment by snowie2000** [comment]
![QQ截图20190527121529](https://user-images.githubusercontent.com/11767189/58395129-48a9da80-8079-11e9-8f16-017c329f15fc.png)
我刚做了一下测试，新版下1903并不会出现你说的崩溃的问题。

**Comment by Youxikong** [comment]
我昨天给chrome和edge（chromium版）关了CFG。今天日常使用时还是有这种情况。崩溃出现在打开或者打开新标签页时，我一会儿统计一下会出现崩溃的扩展的列表。
其他人没报issue，我觉得可能是我的个别问题。

**Comment by snowie2000** [comment]
你是什么加载模式？注册表？

**Comment by Youxikong** [comment]
我是用的服务模式和托盘模式。使用的配置是LCD.ini（有自己修改过）。

**Comment by snowie2000** [comment]
关掉mactype能正常，但是排除unloaddll却不行？

**Comment by Youxikong** [comment]
对，只有mactype运行时才会发生扩展崩溃。

**Comment by snowie2000** [comment]
那你只能等待新版发布了，新的loader很可能解决了这个问题

**Comment by Youxikong** [comment]
非常感谢！

**Comment by wmjordan** [comment]
> 其他人没报issue，我觉得可能是我的个别问题

我也遇到插件崩溃的问题，但不能确定是否与 MacType 有关。

Win1809，服务加载。

**Comment by Qeynos** [comment]
我也遇到一样的问题，不论是服务模式还是独立加载模式，加入Unloaddll无效，目前针对某些应用采用手动加载模式还行，新版这个月会发吗

**Comment by snowie2000** [comment]
samantha一直在忙碌着准备着新版本的发布，我们会尽快解决发布的问题的。应该在这几天发布

**Comment by sammilucia** [comment]
Please try the new beta6 here https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6. I will close this issue as we believe it's resolved however if you still have problems please let us know (respond to this thread).
