### ISSUE TITLE
wierd behaviour on some app with font replacing on

### ISSUE THREAD

**Issue by TTTPOB** [snowie2000/mactype#542]
![image](https://user-images.githubusercontent.com/19909103/59218883-cf22f800-8bf3-11e9-8d9c-b2e197ab72e3.png)
![image](https://user-images.githubusercontent.com/19909103/59219423-0a71f680-8bf5-11e9-9553-c3e59e5587b8.png)

```ini
[FontSubstitutes]
SimSun-ExtB=Sarasa UI SC
Microsoft YaHei=Sarasa UI SC
Microsoft YaHei Light=Sarasa UI SC Light
Microsoft YaHei UI=Sarasa UI SC
Microsoft YaHei UI Light=Sarasa UI SC Light
Tahoma=Sarasa UI SC
STKaiti=Sarasa UI SC

新宋体=Sarasa UI SC
SimSun=Sarasa UI SC
Times New Roman=Sarasa UI SC
```

no matter FontSubstitutes=1 or 2, problem persists.
I am on the latest beta(beta 5)

**Comment by snowie2000** [comment]
Font substitution has compatibility problems with some applications and most of them cannot be solved.

Some of them have font validations that check for the font they created. Some of them simply not designed for your font and display incorrectly with it.
