### ISSUE TITLE
[Feature Request] Different config for different app

### ISSUE THREAD

**Issue by TTTPOB** [snowie2000/mactype#543]
I want to use font replacement in some app, but not in apps like word or photoshop. Is there any possibility that I can specify different configuration depending on the process?

**Comment by snowie2000** [comment]
Looks like it hasn't been documented yet. 😕
But yes, it's there long ago. It's called per-app configuration.

Generally speaking, you can always use [sectionname@app.exe] to override values listed in the [sectionname]
Values missing in the per-app section will use the values from the global section.

Also, you can group applications with `Alternative`, e.g.
```ini
; define ie as a member of the group browser
[General@iexplore.exe]
Alternative=Browser
; chrome =>browser
[General@chrome.exe]
Alternative=Browser

;and set options for the group browser
[General@Browser]
Hinting=1 
```

Section `UnloadDll` and `ExcludeModule` cannot be used this way, and nor do they need to.

**Comment by TTTPOB** [comment]
Yes I think this can suit my need, thank you
