### ISSUE TITLE
unable to open or run programs after installing Mactype windows 10

### ISSUE THREAD

**Issue by aubreyzulu** [snowie2000/mactype#545]
Hello
i am unable to run or open certain programs after installing MacType on my windows 10 laptop. But when i disable MacType they all run and open smoothly, how do i fix this. i love the program

**Comment by snowie2000** [comment]
This should be related to #519 and #531 and should be solved in the coming beta6.

While we are still busy preparing the publish of the beta, you can try the loader I posted here:
https://github.com/snowie2000/mactype/issues/531#issuecomment-489964349
If it worked for you, so will be the beta.

**Comment by sammilucia** [comment]
@Aubrey-Zulu please try the new beta6 here https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6. I will close this issue as we believe it's resolved however if you still have problems please let us know (respond to this thread).
