### ISSUE TITLE
Is registry mode now safe to use?

### ISSUE THREAD

**Issue by caulmseh** [snowie2000/mactype#546]
I've read the releases and it is said to the previous build that Windows 10 users should not be using registry mode.

**Comment by snowie2000** [comment]
There’s no guarantee. every system is different.  you can’t be too careful.

**Comment by caulmseh** [comment]
i have accidentally have been. before, the first time i knew this existed i tried to use registry on my first try without too much reading, after restart most of my apps won't start even the MacType apps but thank goodness my Virtualbox updated few days before so i can get back to a restore point. though i'm just using service mode until everything is fixed. i'm just sharing my experience so that others start reading first and stop mindlessly clicking "next" on setups.

still though, this is a very useful app and i can't live without it!

**Comment by snowie2000** [comment]
We keep improving the compatibility with the latest system.  But after all it integrate with your system too deeply. 

It is always good to get prepared before you apply the registry mode.
