### ISSUE TITLE
带空格文件路径不替换字体样式

### ISSUE THREAD

**Issue by SplitGemini** [snowie2000/mactype#547]
### 使用配置：LCD.W7.默认字体.仿Mac

举例，在WinRAR中选择解压路径时，有空格的路径没有进行样式替换
如12 34；123 456比下面的不带空格的文字更细
![image](https://user-images.githubusercontent.com/34861918/59465790-422fa700-8e5e-11e9-8af1-2ca49450c118.png)

我在[Individual]把相关宋体替换成较粗样式
宋体=3,2,15,,,
仿宋=3,2,15,,,
新宋体=3,2,15,,,
华文宋体=3,2,15,,,
华文中宋=3,2,15,,,
华文仿宋=3,2,15,,,

**Comment by snowie2000** [comment]
显然对这些带空格的文字MacType根本就没有渲染，上面直接就是点阵状态。
具体的原因我也没办法知道，这在很早以前就出现过，不过应该是早就修复过的

**Comment by snowie2000** [comment]
另外我专门在win10下进行了测试，win10下的winrar右侧目录默认并不会使用宋体显示……
所以我不知道你的情况是怎么实现的，是自定义主题？
![QQ截图20190614113212](https://user-images.githubusercontent.com/11767189/59481781-4c6e9700-8e98-11e9-8201-cca3cdea04ff.png)

**Comment by SplitGemini** [comment]
和WinRAR主题没有关系，好像不是宋体替换问题，WinRAR里所有界面带空格都没有渲染
![image](https://user-images.githubusercontent.com/34861918/59507290-38995400-8edd-11e9-9f6f-3b83521d8cd7.png)
而且不只是WinRAR，一些其他的程序也会出现这个情况，只是情况比较少出现，且只在特定程序出现

**Comment by SplitGemini** [comment]
和WinRAR主题没有关系，好像不是宋体替换问题，WinRAR里所有界面带空格都没有渲染
![image](https://user-images.githubusercontent.com/34861918/59507290-38995400-8edd-11e9-9f6f-3b83521d8cd7.png)
而且不只是WinRAR，一些其他的程序也会出现这个情况，只是情况比较少出现，且只在特定程序出现

**Comment by SplitGemini** [comment]
![image](https://user-images.githubusercontent.com/34861918/59508173-a47cbc00-8edf-11e9-8b4e-593333783c8e.png)
我更改配置再换回来又可以了，但是这个问题之前是一直存在的

**Comment by SplitGemini** [comment]
重启后这个问题暂时没有再出现了
