### ISSUE TITLE
MacType 2019.1-beta6 Bug

### ISSUE THREAD

**Issue by Stzx** [snowie2000/mactype#549]
### 系统

Windows 10 1903

卸载 `MacType 2018.1-beta5` 后安装 `MacType 2019.1-beta6`

### 问题

* MacTray 
  * 语言列表丢失
![MacType00](https://user-images.githubusercontent.com/19950702/59768722-6dd7e480-92d7-11e9-815e-2daf557411a1.png)
---

* MacTuner
  * 语言列表丢失
  * 无预览字体
  * 提示框内容丢失
  * 高级模式，液晶优化无法正常显示
![MacTuner00](https://user-images.githubusercontent.com/19950702/59768786-834d0e80-92d7-11e9-9f5a-2dd5e892a99d.png)
![MacTuner01](https://user-images.githubusercontent.com/19950702/59768795-85af6880-92d7-11e9-8405-f4eec0449883.png)
![MacTuner02](https://user-images.githubusercontent.com/19950702/59768803-89db8600-92d7-11e9-8859-312d5fe0b778.png)
![MacTuner03](https://user-images.githubusercontent.com/19950702/59768810-8d6f0d00-92d7-11e9-8a71-132e56f31b82.png)
![MacTuner04](https://user-images.githubusercontent.com/19950702/59768812-8f38d080-92d7-11e9-8bbf-709ff67387f2.png)
---

* MacWiz
  * 语言列表丢失
![MacWiz00](https://user-images.githubusercontent.com/19950702/59768759-7af4d380-92d7-11e9-905d-4b2ea5c60af3.png)
![MacWiz01](https://user-images.githubusercontent.com/19950702/59768764-7cbe9700-92d7-11e9-9e1a-3fb5011e48c4.png)

**Comment by sammilucia** [comment]
Hi @Stzx how come you closed this?

**Comment by Stzx** [comment]
I found #527

**Comment by sammilucia** [comment]
Ok cool, thank you 😊
