### ISSUE TITLE
Won't start after upgrade to beta6

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#552]
> try this one.
> It gives a popup of your dcom pid or the reason why it fails to get the pid.

It correctly displayed the PID of the service.
![shot](https://user-images.githubusercontent.com/12182730/59809495-6514fc00-9333-11e9-9c2a-8fbeea0507a3.png)

However, it somehow popped up an error box after that.
[bugreport.txt](https://github.com/snowie2000/mactype/files/3308285/bugreport.txt)

This file could not work either in tray mode or service mode.

_Originally posted by @wmjordan in https://github.com/snowie2000/mactype/issues/518#issuecomment-503792151_

Additional info from email:
>@sammilucia I downloaded the beta 6 and installed it over beta 5.
>The installer prompted me to reboot.
>After the reboot, MacType could not start up.

>Here's the file list of the directory. Are they up to date?

>2019/06/20  08:24    <DIR>          .
>2019/06/20  08:24    <DIR>          ..
>2019/06/19  16:07            13,239 ChangeLog.txt
>2018/10/01  05:22           248,832 EasyHK32.dll
>2018/12/05  23:55           317,440 EasyHK64.dll
>2019/03/03  11:42            80,896 GdiBench.exe
>2019/05/24  00:29               716 GdiBench.ini
>2019/06/19  14:53    <DIR>          ini
>2018/11/21  15:27    <DIR>          languages
>2019/04/24  13:34            35,823 license.txt
>2018/09/30  15:03            15,872 MacLoader.exe
>2018/09/30  15:03            69,632 MacLoader64.exe
>2019/06/19  20:25         2,629,632 MacTray.exe
>2018/10/17  11:07         2,291,200 MacTuner.exe
>2018/10/01  05:22           124,928 MacType.bak.dll
>2019/05/23  22:03           863,232 MacType.Core.dll
>2019/05/23  22:03           120,832 MacType.dll
>2019/06/20  08:26             1,624 MacType.ini
>2018/10/01  05:22           151,040 MacType64.bak.dll
>2019/05/23  22:03         1,047,040 MacType64.Core.dll
>2019/05/23  22:03           154,624 MacType64.dll
>2019/03/03  11:42            69,120 MacWiz.exe
>2018/09/30  15:03           103,424 mt64agnt.bak.exe
>2019/05/22  17:55           104,960 mt64agnt.exe
>2019/06/20  08:21            45,680 unins000.dat
>2019/06/20  08:19         1,291,175 unins000.exe
>2019/05/23  22:03           686,080 updater.exe
>2019/06/20  08:21               333 updater.ini
>2019/06/20  08:21    <DIR>          updates
>2017/01/13  21:48             6,962 UserParams.ini
>I am going to uninstall and then reinstall MacType since I can't work without it.

**Comment by sammilucia** [comment]
> However, it somehow popped up an error box after that.

Thank you for sending a bug report. @wmjordan what did the error box say?

**Comment by wmjordan** [comment]
Please close this issue and reopen #518.

It is due to the failure of the test build @snowie2000 posted in #518 which built after your beta6.

**Comment by wmjordan** [comment]
> what did the error box say?

The box said something went wrong, I hit a button and went to the detail page, the bugreport.txt should contain useful information.

**Comment by wmjordan** [comment]
It was weird that when I put back and restarted the version @snowie2000 built last night, the error box no longer appeared.
