### ISSUE TITLE
v1.2018.10.19-beta4 在 Windows 10 1903 上無法渲染 UWP.

### ISSUE THREAD

**Issue by ForGx3** [snowie2000/mactype#554]
剛在最新的 Windows 10 1903 上測試 v1.2018.10.19-beta4 , 發現無法渲染 UWP.
只是 UWP 無法渲染 , 其他都正常 , 已經試了全部模式.

**Comment by snowie2000** [comment]
请打开mactype.ini，搜寻svchost.exe并将他删除。
这是本次发布的一个严重bug。

Looks like we have to update your setup to remove the svchost.exe from the exclusion list @sammilucia

**Comment by ForGx3** [comment]
在 MacType.ini 底下沒有發現 svchost.exe
[UnloadDll] 只有這兩個 .exe

[UnloadDll]
VBoxSvc.exe
VirtualBox.exe

**Comment by snowie2000** [comment]
抱歉没有注意到您还在使用beta4.
请升级到最新的beta6，并删掉svchost后再试一下。

**Comment by ForGx3** [comment]
原來出到了 beta6 , 在首要的連結是 beta4 已為是最新了~
更新到了 beta6 刪除 svchost.exe 後 , UWP 可以正常渲染 , 但文字渲染效果有點怪怪的 , 不像普通應用的渲染 , 毛刺好像很多~

https://i.imgur.com/95bKaFh.png

**Comment by snowie2000** [comment]
确实有不少反应说对dw有劣化，具体原因还没有找到呢。。。

**Comment by ForGx3** [comment]
好的
感謝你
