### ISSUE TITLE
v1.2018.10.19-beta4 在 Windows 7 SP1 64Bit 無法渲染視窗標題.

### ISSUE THREAD

**Issue by ForGx3** [snowie2000/mactype#555]
在 Windows 7 SP1 64Bit 上 , 開啟 Aero 後 無法渲染視窗標題文字 , 不知道有沒有方法解決 ?

如下圖.

https://i.imgur.com/ySsVcqs.png

**Comment by snowie2000** [comment]
由于DWM的特殊性，微软强制标题文字为单色（mono），无法使用次像素渲染。
freetype可以支持单色文字的渲染，但是效果远不及cleartype，所以MacType禁用了对单色文字的支持。

**Comment by ForGx3** [comment]
所以在 Windows 7 SP1 64Bit 下沒有辦法渲染視窗標題文字了 ?
MacType 可以強制開啟對單色文字的支持嗎 ?

**Comment by snowie2000** [comment]
对于任何开启了aero效果的视窗，都是不能渲染标题的。
不能开启对单色文字的支持，我们早就测试过了，freetype对单色文字的支持差到离谱，彻头彻尾的劣化

**Comment by ForGx3** [comment]
好的
感謝你

**Comment by snowie2000** [comment]
![scaled_cascade](https://user-images.githubusercontent.com/11767189/59831483-6dd9f200-9374-11e9-9799-bfbc67d8d0be.png)
FreeType+单色文字基本上就是如图的样子，真是不忍直视

**Comment by ForGx3** [comment]
剛發現在 Internet Download Manager 的下載視窗中 , 在 Aero 下視窗標題文字居然有渲染

https://i.imgur.com/bICKSLe.png

**Comment by snowie2000** [comment]
确实是这样的，例如Office 2007在Windows7下的标题栏也是可以渲染的。
部分窗体的标题并非真正的标题栏，他们只是利用aero glass做出来的，并不是dwm的一部分。

真正的标题栏有个特殊的特性，他们在程式崩溃挂起时不会变灰，因为他们本质上是dwm.exe的一部分，并不属于程式本身

**Comment by ForGx3** [comment]
原來是這樣 , 明白 , 感謝你

**Comment by ForGx3** [comment]
@snowie2000 想問問 , 安裝完 MacType 後 , 裡面的 字體預設設定檔.
哪裡可以找到 用在這些預設設定檔的全部字體 ?

**Comment by snowie2000** [comment]
其中的xhei和xsong部分是themex论坛的max制作的，原始链接已经失效
有人已经补档了，可以从百度下载到
https://pan.baidu.com/s/1-w_i7jUMcnDDqWp5fcXcew

其他字体需要你自己去找了

**Comment by ForGx3** [comment]
好的
感謝
