### ISSUE TITLE
请问如何为DirectWrite软件开启字体阴影？

### ISSUE THREAD

**Issue by Mother-Ship** [snowie2000/mactype#556]
最近才知道MacType支持了DirectWrite，开启后发现和GDI程序有明显区别，似乎DirectWrite没有加上字体阴影？
![image](https://user-images.githubusercontent.com/26121316/59959086-363d8800-94e3-11e9-8d07-fadd0689949a.png)

**Comment by snowie2000** [comment]
Directwrite 只能算优化，原理和gdi完全不同，参数都是独立的，不支持阴影
