### ISSUE TITLE
编译失败，未定义标识符 "FT_Glyph_To_BitmapEx"

### ISSUE THREAD

**Issue by wzv5** [snowie2000/mactype#558]
感谢作者提供了如此伟大的程序，但是当我尝试编译时，遇到了这个错误：

> 未定义标识符 "FT_Glyph_To_BitmapEx"

https://github.com/snowie2000/mactype/blob/59a53aba0d32b9c5b662a098cdfb0c2dffcd9abe/ft.cpp#L2003-L2004

来自提交 https://github.com/snowie2000/mactype/commit/7520232cbdd139d5b87fc636c3b167c0a343c670 ：

> Hmm, I'd like to keep the commit content secret.
> This commit makes mactype uncompilable with standard FreeType.

希望作者只是粗心忘记了这个细节，并且能够补全代码，或者 freetype 补丁。

再次感谢。。

如果开源代码仅供学习交流性质，也请提前说明，免得别人像我一样把依赖关系都搞起来后发现无法编译，浪费了一个美好的周末。

**Comment by snowie2000** [comment]
很抱歉其实由于direcrwrite分支是从master过来的，所以commit会少一些东西

缺少的内容在master中是有的
https://github.com/snowie2000/mactype/commit/8f8896a5c96e03eb9446a8311167e431dd71e44b

**Comment by snowie2000** [comment]
这个commit发生在某个beta发布前，打算是在发布时才说明支持彩色字体的新特性，所以故意在commit中不写更新内容

**Comment by wzv5** [comment]
@snowie2000 感谢解答，是我暴躁了，非常抱歉。

因为已经见识过很多“假开源”，就是提供的源码与实际程序并不相符，而 mactype 又是一个需要注入到几乎所有进程中的插件，如果它不安全，那么后果不堪设想，我看到这种情况的第一感觉就是有什么真相被隐藏了，对不起误解了作者。

之后我会尽量在阅读代码后参与进来，帮助优化代码和改进功能，让我们一起把 mactype 变得更好吧！
