### ISSUE TITLE
新版idea EAP 中文渲染异常

### ISSUE THREAD

**Issue by horou-dsk** [snowie2000/mactype#560]
![image](https://user-images.githubusercontent.com/23204548/59986301-d96bda00-9668-11e9-87c7-52c9f049165a.png)

中文字符一粗一细

**Comment by snowie2000** [comment]
如果你没有使用字体替换的话，那么很明显你用的字体有问题。

图中很容易看出来渲染的部分是无衬线字体（类似黑体），而无渲染部分是点阵的宋体，出现这种情况无非就是这个字体里面不含有你的文字，所以需要换用别的字体来显示，例如某些小众字体经常发生缺字的情况，罕见字只能变成宋体。

**Comment by horou-dsk** [comment]
我不是很懂这个。￣▽￣有没有办法解决啊，我没有自己改过字体什么的，用的都是默认的。

**Comment by snowie2000** [comment]
关掉MacType重启idea EAP，相同的内容再截图一下传上来我们看一下

**Comment by horou-dsk** [comment]
我把MacType 卸了，现在变成这样了 ￣▽￣
![image](https://user-images.githubusercontent.com/23204548/59993975-c830c680-9684-11e9-959f-81eafe5f3e75.png)

我同事没用过mactype的是正常显示的

**Comment by snowie2000** [comment]
图上看也很明显是两种不同的字体，你的idea应该修改过字体设置了
或者你的系统被修改过了，例如硬替换了字体

**Comment by horou-dsk** [comment]
╮(￣▽￣)╭，我把idea字体设置里面的fallback font 设置成微软雅黑就正常了。
不过我之前确实没改过也没替换过什么字体，会不会是mactype修改了什么注册表导致的默认字体被替换了。

**Comment by snowie2000** [comment]
mactype除了自启动外并不会修改注册表。

话说MacType难道专门为了idea写个特例去替换idea中的某个设置？那也太闲了。。。你可以自行查看代码看看有没有这种魔术设计……
