### ISSUE TITLE
mactype详细信息界面，cpu效率保持在20%，界面响应迟钝，请给予检查完善。

### ISSUE THREAD

**Issue by wangxiya** [snowie2000/mactype#561]
mactype详细信息界面，cpu效率保持在20%，界面响应迟钝。
beta6出现的新问题，beta5里没有出现。
win10 1903

**Comment by snowie2000** [comment]
目前当你打开详细信息时会每秒刷新，所以占用资源会较多，但是……beta5和beta6是完全一样的
不建议没事老开着详细信息界面。

**Comment by snowie2000** [comment]
占用资源的量和系统以及电脑的配置有很大关系，并不是说你配置高就占用低，原因不清楚，似乎是和Windows的一些进程枚举机制有关，无法解决。
正是由于枚举进程在部分用户机器上占用很多资源，所以mactype现在使用wmi来捕捉进程，只要你不开详细信息就不会枚举进程，也就不存在占用资源的问题。对于枚举进程在某些电脑上会比较吃cpu的问题，目前是不能解决的。

**Comment by snowie2000** [comment]
类似以前的issue有 #540  #375 #237 #178

**Comment by wangxiya** [comment]
感谢您及时的回复，不过似乎在beta6里出现的频繁些，我再观察一下！
再次致谢！

**Comment by snowie2000** [comment]
因为mactray程序编写时间比较早，很多代码现在想要改都挺困难的。暂时这些不会有大的动作，而且当时写的时候也并不知道这些API在某些电脑上居然会占用这么多资源。
在我的系统上最多也就3%CPU而已
