### ISSUE TITLE
Firefox dev/nightly 69已删除cairo，无法渲染

### ISSUE THREAD

**Issue by info-69** [snowie2000/mactype#565]
gfx.direct2d.disabled已设为true
gfx.canvas.azure.backends和gfx.content.azure.backends手动添加cairo无效
默认参数↓
![skia](https://user-images.githubusercontent.com/11392608/60557144-e1b5ca80-9d76-11e9-84b2-9a5e5bda38c3.png)
dev 69
https://ftp.mozilla.org/pub/devedition/releases/69.0b1/win64/en-US/Firefox%20Setup%2069.0b1.exe
nightly 69
https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-69.0a1.en-US.win64.installer.exe

**Comment by snowie2000** [comment]
请等待firefox发布正式版后再确定。

**Comment by IceMan81** [comment]
@snowie2000 I’m experiencing the same issue with the new Developer edition.

**Comment by snowie2000** [comment]
Maybe they are changing something that may come back in the stable release. We aren't sure about it.

**Comment by perfecblue** [comment]
Hi I'm experiencing MacType rendering failure in stable release version 68 now.  I've put Cairo in front at **gfx.content.azure.backends** but it didn't do anything.  Is there anything that needs to be done to ensure MacType compatibility in 68?  Thank you!

**Comment by Galuis** [comment]
Reference:
[Bug 1559810 - disallow Cairo as content/canvas backend. r?jrmuizel](https://hg.mozilla.org/mozilla-central/rev/46aad88d3b36)

**Comment by IceMan81** [comment]
Oh boy!

**Comment by snowie2000** [comment]
Great. They learned my way of solving problems: If it can't be solved, remove it.

**Comment by IceMan81** [comment]
Anyone come across a solution that enables MacType to work with FF 69? So far, I cannot change the azure backend, what ever I set its always skia. 

_Didn't really want to comment on a closed ticket, but this was the most relevant one._

**Comment by snowie2000** [comment]
@IceMan81 They have removed the Cairo backend. So, looks like it is the end of the GDI era of firefox.

**Comment by snowie2000** [comment]
After upgrading to firefox 68.0.1, my firefox is ruined... completely.
It looks horrible!
![ff](https://user-images.githubusercontent.com/11767189/61942102-51f8ea00-afcb-11e9-8a19-efe1698ebd8d.png)
looks like they ain't even using directwrite. IE11 works 100 times better than firefox
![ie](https://user-images.githubusercontent.com/11767189/61942163-7228a900-afcb-11e9-91ef-5e38e7a35638.png)
What are they thinking🤬

**Comment by Galuis** [comment]
Since Cairo backend has been disallowed, I changed my Firefox font configuration and enable direct2d for a better look (still not good).
![](https://user-images.githubusercontent.com/15099895/61989392-3c360400-b061-11e9-92c7-e9a67c3dc49e.png)
Following https://bugzilla.mozilla.org/show_bug.cgi?id=1557961#c8 suggestion,change `gfx.webrender.all=true` `gfx.webrender.enabled=true`, it seems affect mactype rendering (not obvious in the picture).
![](https://user-images.githubusercontent.com/15099895/61989188-18bd8a00-b05e-11e9-80b6-1cb75f95fbd7.png)
Hope and wait better rendering change by Mozilla Gfx team.

Edit: DirectWrite is enable in MacType profile.

**Comment by sammilucia** [comment]
Hi @LeeJayl ... Not all MacType profiles turn on Mactype's rendering for DirectWrite. Can you please try one of the following:
ChicoThorn
Clean Sharp
Clean Soft
extratype
mufunyo

And see how you go?

**Comment by Galuis** [comment]
@sammilucia Sorry, the previous description is not clear. I've enabled DirectWrite function in profile. My preferences is not good, so it's not obvious in screenshots.

**Comment by snowie2000** [comment]
I've confirmed that starting from firefox 68, MacType (and any other third-party renders) stopped working on firefox, `cause an extra protection of dll injection was added.

What you're going to observe to that the MacType can't apply to firefox.exe (except in registry mode). So, looks like the registry mode is the only way to render firefox so far.

**Comment by snowie2000** [comment]
After taking hours digging into firefox mozglue.dll, I finally made MacType comply with its standard again. Tray mode is back to work again now.

**Comment by a0193143** [comment]
Well, cairo removed in stable 69.
Maybe it's time to move to ESR version.

**Comment by IceMan81** [comment]
> After taking hours digging into firefox mozglue.dll, I finally made MacType comply with its standard again. Tray mode is back to work again now.

Is there a mactype update for this to work?

**Comment by jmbattle0** [comment]
Firefox updated itself to v69 today and MacType no longer works.

Fingers crossed this functionality can be restored.

**Comment by snowie2000** [comment]
> > After taking hours digging into firefox mozglue.dll, I finally made MacType comply with its standard again. Tray mode is back to work again now.
> 
> Is there a mactype update for this to work?

No patch is needed as it is a bug that raised during my test. The current public version is compatible with all Firefox versions.

@jmbattle0 cairo is removed in the final release and you have to enable DirectWrite support to make it work for Firefox.

**Comment by JimFlasch** [comment]
Closed too soon - I've done everything in this thread and MacType still won't work with Firefox 69!

**Comment by IceMan81** [comment]
@snowie2000 Are you enabling Direct Write flags in FF ?

**Comment by FrankEBailey** [comment]
Has anyone gotten MacType working in FF 69? If so can you please share your ini, about:config and FF options settings to get it to work?

**Comment by snowie2000** [comment]
Simply use the default.ini and reset everything in about:config to their default values  should work

**Comment by JimFlasch** [comment]
@snowie2000 I had to CHANGE about:config and other settings to get MacType to work in Firefox originally (specifically dropping ",skia" from gfx.canvas.azure.backends and gfx.content.azure.backends values and unchecking "use hardware acceleration when available" under General/Performance in the Options menu). Why would resetting them to default make it work now?

**Comment by jmbattle0** [comment]
It's working here on my Win7 box.

I uninstalled the previous public release of MacType (pretty old), then installed the latest MacType beta.  Then I reset the Firefox profile and everything is working fine.  I'm currently using the default MacType .ini, but may tweak it later.

**Comment by JimFlasch** [comment]
@jmbattle0 I now have the latest MacType beta, and it does nothing to make text look better in Firefox.

**Comment by snowie2000** [comment]
@JimFlasch They are two different approaches.

With all default values, firefox uses DirectWrite to render its page which is supported by MacType, but not good and customizable enough. That's why we suggested users disable DirectWrite (direct2d) in firefox and switch its backend to cairo which is based on Windows GDI.

However, due to their lack of interests fixing a bug in cairo (https://bugzilla.mozilla.org/show_bug.cgi?id=1559810), the development team decided to remove cairo. Now in firiefox69, the cairo is still there in the option, but no longer works. You have to switch back to Directwrite to make it work in another form.

**Comment by JimFlasch** [comment]
I did - and it's not quite as good as it used to be.

**Comment by jmbattle0** [comment]
>  it does nothing to make text look better in Firefox.

>  it's not quite as good as it used to be.

Which is it?

**Comment by FrankEBailey** [comment]
Text looks a lot more washed out than it did under GDI, though closer examination reveals that it's definitely working with all default settings. I've tried tuning the options for the profile and it doesn't seem to affect the look of the font at all, so that's a real shame. 

Is there any hope for increased configurability under FF in future releases of MacType?

**Comment by snowie2000** [comment]
DirectWrite rendering has its own configuration section [DirectWrite] https://github.com/snowie2000/mactype/wiki/DirectWrite-section

**Comment by FrankEBailey** [comment]
Thanks snowie2000, that'll teach me to read the documentation more carefully eh! ;)

**Comment by snowie2000** [comment]
Haha, it's just happened to be there. Mactype is not well documented in fact. Shame on me🙈

**Comment by jmbattle0** [comment]
Am I correct in thinking that only the parameters in the DirectWrite section will influence how text appears in Firefox (69)?  Changing the rest of the parameters will have no effect, yes?

**Comment by sur0g** [comment]
Found a perfect solution (many thanks to the redditor @TurbanatorUSA). Works on FF 69.0.1 on windows 10.

All you need is to set `gfx.font_rendering.cleartype_params.rendering_mode` to `5` in `about:config`.

[Original thread](https://www.reddit.com/r/firefox/comments/cz6nys/firefox_69_breaks_windows_font_rendering/)

**Comment by sammilucia** [comment]
Thank you @sur0g ... I'll add it to the wiki!

**Comment by sammilucia** [comment]
Done, please let me know any corrections (I don't use Firefox 🙄) https://github.com/snowie2000/mactype/wiki/Mozilla-Firefox

**Comment by flysn0w** [comment]
改了gfx.font_rendering.cleartype_params.rendering_mode之后mactype一样渲染不了,这只是一个微调directwrite的功能

**Comment by jmbattle0** [comment]
I tried setting [gfx.font_rendering.cleartype_params.rendering_mode] to 5, but do not see any difference.
I'm using Firefox 69 under Windows 7 and MacType seems to work okay.

Is this parameter only required for Windows 10?
