### ISSUE TITLE
svchost on ignore (running) 1903

### ISSUE THREAD

**Issue by asejfh** [snowie2000/mactype#566]
hi,
currently with my registry install of mactype it wont render in uwp apps or anything electron
![this is my mactype.ini currently](https://emel.s-ul.eu/vR5EetI1)

and i am using decency english

**Comment by snowie2000** [comment]
Please open the process manager from mactype wizard, and check the status of DCOM `svchost.exe` from there.
The pid of the DCOM service can be retrieved from taskmanager->service tab->Dcomlaunch like this:
![QQ截图20190705144115](https://user-images.githubusercontent.com/11767189/60702955-fa6adf80-9f32-11e9-9e82-85d92f060674.png)

**Comment by fonlan** [comment]
My svchost.exe is always disable even I try to enable it via MacType process manager. But it still disabled soon. svchost.exe is not in UnloadDll list.

**Comment by asejfh** [comment]
![MacTray_2019_0705](https://user-images.githubusercontent.com/9170133/60720324-54af7480-9f22-11e9-904c-45bc0fd82466.png)

**Comment by snowie2000** [comment]
Did you turn off the hookchildprocess?

**Comment by asejfh** [comment]
I don't believe so.

**Comment by snowie2000** [comment]
Please start a UWP app and recursively check its parent processes (via process explorer) to see which of them have Mactype loaded.

**Comment by asejfh** [comment]
I think I fixed it, not sure how at all. Not working on discord still but that's okay.

**Comment by sammilucia** [comment]
hi @asejfh 

if you edit c:\program files\mactype\mactype.ini, can you see svchost.exe listed under [UnloadDll] ?
