### ISSUE TITLE
Doesn't work on almost all apps after updating to beta6

### ISSUE THREAD

**Issue by JiaChen-Zeng** [snowie2000/mactype#569]
I have been using beta4. After updating to beta6, it seems to break completely. I am still using my old profile. My windows version is 1803.

I see the notes that `svchost.exe` should be removed in `MacType.ini`. I can't find it in that file and neither in my profile, but in Process Manager, `svchost.exe` is ignored, and all processes are disabled.

![image](https://user-images.githubusercontent.com/3676278/60780677-05f81980-a172-11e9-8f45-14c67ef505eb.png)

How to fix this problem?

**Comment by snowie2000** [comment]
Are you using `useinclude` mode?
And please make sure you completely uninstalled mactype before reinstall and check your installation directory to ensure that you have all the necessary files: 
* mactype.dll
* mactype64.dll
* mactype.core.dll
* mactype64.core.dll
* easyhk32.dll
* easyhk64.dll


PS: the buggy svchost.exe item has been removed in the beta6 published after 21-June-19, you don't need to do it again.

**Comment by JiaChen-Zeng** [comment]
Thanks for your quick response.

I checked my profile. There is no `useinclude`.
Also, I am sure I completely uninstalled old mactype. I even installed to a different directory. The old is in D: while the new is in C:. 

The DLL files are all present.
![image](https://user-images.githubusercontent.com/3676278/60781156-caf6e580-a173-11e9-981f-460e264cdb60.png)

**Comment by JiaChen-Zeng** [comment]
I tried to change my profile to default `Win7.ini`. The processes are still disabled and `svchost.exe` is ignored.
Then, tried to change registry mode to service mode. Now seems it is working.

Possibly it is because the registry is corrupted?

I changed back to registry mode and now it works normally.

**Comment by snowie2000** [comment]
Registry mode won’t work if security boot is enabled. 

After reinstall, you have to reenable the registry mode.
