### ISSUE TITLE
Recent betas break Outlook date chooser in appointments 

### ISSUE THREAD

**Issue by Cowlippie** [snowie2000/mactype#570]
Recent betas break Outlook 2007 date chooser in appointments. Beta from Oct 2018 at least onwards. This in in Win 7.  The date chooser number text in the dropdown is unreadable. 

Reverted to late 2017 official and it works fine.

**Comment by snowie2000** [comment]
Please attach a screenshot of your issue.

**Comment by Cowlippie** [comment]
Seems to be working now after another uninstall and reinstall. I'll let you
know if it stops working again

**Comment by snowie2000** [comment]
I'm closing it. Feel free to reopen if the problem happens again.
