### ISSUE TITLE
Firefox stable release version 68 MacType redering failure

### ISSUE THREAD

**Issue by perfecblue** [snowie2000/mactype#572]
Hi I'm experiencing MacType rendering failure in Firefox stable release version 68. I've already disabled Direct2D and put Cairo in front at **gfx.content.azure.backends** and **gfx.canvas.azure.backends** but firefox is still not redered.  Is there anything that needs to be done to ensure MacType compatibility in 68? Thank you!

**Comment by perfecblue** [comment]
![d2d](https://user-images.githubusercontent.com/8471025/60910504-9427e900-a2b3-11e9-9fe0-896851f25271.PNG)

**Comment by perfecblue** [comment]
![d2d1](https://user-images.githubusercontent.com/8471025/60910590-d0f3e000-a2b3-11e9-9885-0221dd96a556.PNG)

**Comment by snowie2000** [comment]
Possible duplication of #565?

**Comment by perfecblue** [comment]
> 
> 
> Possible duplication of #565?

Actually, someone referred me to #565 first and I found out that v.68 already can't be rendered (at least from my setup).  I've wiped it clean with a brand new profile and still cannot render.

**Comment by snowie2000** [comment]
Tested on my Firefox 68.0 and it works normally.
My firefox uses `cairo` as the only backend for canvas and content.

**Comment by perfecblue** [comment]
I tried the "Re-Start with Addon-on Disabled" option in the Support and now it's rendering properly.  I'm going to go thru my addon-on and see which one's the culprit, will report back here.  Thanks again!

**Comment by perfecblue** [comment]
Weird.  I went ahead a disabled each and every addon one by one and then restart each time, still not rendering properly.  Even when I've disabled everything in the list and restart, it still wouldn't render.  It's only until I use the "Re-Start with Addon-on Disabled" option again then it would render properly.  I'm not sure what's going on now.

**Comment by perfecblue** [comment]
By the way, I'm using Windows 10 1709, I've seen two other ppl claiming their setups are fine under v.68, but both of them are still on Windows 7, not sure if this makes a difference.

**Comment by perfecblue** [comment]
Hi, I ended up using the REFRESH feature and started over with a brand new profile after realizing not even deleting prefs.js was helping with the situation.  Probably due to the current profile being upgraded over and over since version 36 or so.  Anyway, after refreshing and doing all the necessary steps (cairo in gfx.content/canvas, turn off D2D and hardware acceleration), version 68 on my Windows 10 1709 is now rendering MacType properly again.  Never figure out why but at least it's working right now.  Thanks for the help and please keep up the great work with MacType!

**Comment by yisishoujo** [comment]
i just updated firefox and had this issue, it is solved by uncheck use recommended performance settings then uncheck use hardware acceleration when available

**Comment by perfecblue** [comment]
Thanks for the tip, unfortunately I've also tried that and still no avail.  Must be something in the about:config as it was all good after I started over with a refresh.
