### ISSUE TITLE
Win10用了之后系统某些图标会显示不正常

### ISSUE THREAD

**Issue by Ironman998** [snowie2000/mactype#573]
之前1809版本就存在这个问题，现在更新到1903版本后还是存在这个问题，不知道是怎么回事。
具体情况如下图所示，只是其中一部分。
![批注 2019-07-10 033922](https://user-images.githubusercontent.com/50072517/60917859-71520080-a2c4-11e9-93de-1547b366702b.jpg)
![批注 2019-07-10 033957](https://user-images.githubusercontent.com/50072517/60917864-731bc400-a2c4-11e9-971d-55a229b36c68.jpg)

**Comment by snowie2000** [comment]
从图上可知，MacType根本就没开……建议重装系统

**Comment by zane-ng** [comment]
本人使用 Win 10 1903 配合最新 beta 版本 MacType 并不存在这个问题。

**Comment by Ironman998** [comment]
那应该是我搞错了，重装系统试一下。

**Comment by snowie2000** [comment]
如果重装后或者别的电脑也出现了类似的问题，请重新打开此问题。

**Comment by Ironman998** [comment]
重装系统后问题就解决了。
