### ISSUE TITLE
Colon sign becomes garbage after font substitute

### ISSUE THREAD

**Issue by kailiu42** [snowie2000/mactype#574]
I have below font substitute in my ini:
Segoe UI=Roboto
Segoe UI Bold=Roboto Bold
Segoe UI Black=Roboto Black
Segoe UI Light=Roboto Thin
Segoe UI Semilight=Roboto Light
Segoe UI Semibold=Roboto Medium

The colon sign(:) of the system clock popup menu then becomes garbage, see below screenshots. However, there is no such problem in traditional win32 applications(GDI rendered?).

![Snipaste_2019-07-11_12-55-51](https://user-images.githubusercontent.com/358679/61023421-85892100-a3dc-11e9-8ac1-ec6e677b825e.png)
![Snipaste_2019-07-11_12-58-58](https://user-images.githubusercontent.com/358679/61023423-8621b780-a3dc-11e9-82da-454106c14bc7.png)

Windows 10 1903, MacType 2019.1-beta6

**Comment by snowie2000** [comment]
That's mean the ":" symbol in Segoe UI is not a regular colon. The font Roboto doesn't have that symbol.
Solution
1. Edit the Roboto to add the missing "colon"
2. Find another font which has the symbol builtin as your substitution target.

**Comment by kailiu42** [comment]
But the substitution works OK in other apps like I mentioned.

For example, in EverEdit, an text editor:
![Snipaste_2019-07-11_19-53-03](https://user-images.githubusercontent.com/358679/61048849-a0c45280-a415-11e9-9017-419b72a5070d.png)

In Firefox (DirectWrite):
![Snipaste_2019-07-11_19-55-16](https://user-images.githubusercontent.com/358679/61048976-ea14a200-a415-11e9-8aeb-b0177cb106cc.png)

In Chrome 75:
![Snipaste_2019-07-11_19-55-38](https://user-images.githubusercontent.com/358679/61048977-ea14a200-a415-11e9-854d-924042a231ff.png)

**Comment by snowie2000** [comment]
It’s a special colon, not the regular one you are using. 

They look similar but they are not the same glyph.

**Comment by kailiu42** [comment]
‎You are right. I used the Textify tool to copy the time string out from that menu, it was a different symbol. But it still displays OK in Firefox, it might have some font fall back mechanism that overcame it?

![Snipaste_2019-07-11_20-25-03](https://user-images.githubusercontent.com/358679/61050614-00246180-a41a-11e9-91b2-42da641d0bb6.png)

Can the font substitution function be enhanced to fall back to the original font if a glyph can't be found in the substitution?

**Comment by snowie2000** [comment]
Firefox does have a font fallback mechanism. 
It is not a bad idea to have font glyph fallback in MacType but I think there are way more problems if you replaced a font with another one which is not fully compatible with. And it should not be done on the first place.

**Comment by kailiu42** [comment]
As a user I really have no way to tell whether two fonts have the same coverage of glyphs. Even if I had, it is basically impossible to find a substitution font that is 1) have the look I love 2) have the same or bigger glyph coverage than the original one and 3) affordable.

**Comment by snowie2000** [comment]
Closed as we are moving our discussion to the issue #576
