### ISSUE TITLE
系统空载时CPU波动

### ISSUE THREAD

**Issue by WYknhh** [snowie2000/mactype#575]
![QQ截图20190713165420](https://user-images.githubusercontent.com/21954176/61169368-efe1c300-a58e-11e9-82ce-9a5788642d3c.png)
![QQ截图20190713165438](https://user-images.githubusercontent.com/21954176/61169374-f40de080-a58e-11e9-8710-3a21ef6bb9ad.png)
Mactype在系统空载的时候也会波动占用CPU，请问有什么解决方法吗

**Comment by snowie2000** [comment]
请使用beta6，不要使用2018版本
