### ISSUE TITLE
Installer stalls on Windows 2000 SP4

### ISSUE THREAD

**Issue by GrandAdmiralThrawn** [snowie2000/mactype#580]
I wouldn't normally report a Windows 2000 incompatibility issue anymore, but [sammilucia said](http://wp.xin.at/archives/4702#comment-160552 "sammilucia said!") that I should! ;) This is for version 2019.1-beta6:

The installer is broken and stalls immediately. This also seems to happen on my 32-bit Windows XP machines, but for those, the stall only lasts for 1-2 minutes at the beginning and another 1-2 minutes at the end. It does complete cleanly in the end however. On Windows 2000 it seems to be stuck forever (I let it sit there for 10min, no dice, same, fast hardware underneath, so that's not it).

Looks like this:

![installer-on-windows2000](https://user-images.githubusercontent.com/12556133/61219009-8d65ff80-a713-11e9-97f1-a1d2317bce6e.png)

In that state, the window can no longer get and lose focus properly, and the "Cancel", "_" and "x" buttons won't work and remain frozen. The Window is unmovable too. Only thing it still does is to refresh, so you cannot create a "hall of mirrors" effect on it by dragging other windows over it.

Only way to kill it is to send it a nice `TerminateProcess()` (e.g. via task manager).

It doesn't even create the installation folder.

For the brief period that it appears to be similarily stuck on 32-bit XP, there is one difference: On XP, the window can still get & lose focus during that period.

About the "fast hardware" for both operating systems: It's virtual machines on top of Linux. SSD RAID + i7 980X CPU, so that shouldn't be the problem as all operating systems are compared on the same hardware & the same hypervisor (VirtualBox).

**Comment by snowie2000** [comment]
I think the installer has never thought it would be running on such an ancient system and it's confused about what to do next.😜

**Comment by sammilucia** [comment]
Thanks @GrandAdmiralThrawn this is actually my issue to fix (if it's fixable) lol!

**Comment by sammilucia** [comment]
Note to self, check w2k compatibility on InnoSetup past versions

**Comment by GrandAdmiralThrawn** [comment]
Although, it's likely not going to work anyway. I haven't done a dependency walk on the installed binaries yet (not on Windows 2000), but I assume that there'll be a lot of unsupported function calls to the Kernel32 API and other DLLs...

**Comment by snowie2000** [comment]
MacType has never been tested on Windows 2000. It is presumably unable to run on it (or completely freezes your system).

**Comment by GrandAdmiralThrawn** [comment]
Alright, so that's a "Won't fix" then, I presume.

Just for giggles, I copied over the installed program files, and here's what I see missing:

EasyHK32.dll (to kernel32.dll) => `DecodePointer()`, `EncodePointer()`, `GetModuleHandleExW()`, `InitializeSListHead()`, `InterlockedFlushSList()`
MacTray.exe (to kernel32.dll) => `GetProcessId()`, `CheckRemoteDebuggerPresent()`
MacTuner.exe (to user32.dll) => `MessageBoxTimeoutW()`
MacType.Core.dll & MacType.dll (to kernel32.dll) => `DecodePointer()`, `EncodePointer()`, `GetModuleHandleExW()`, `InitializeSListHead()`, `InterlockedFlushSList()`, `IsWow64Process()`
updater.exe (to msi.dll) => Non-public function with ordinal #224 (0x00E0)
updater.exe (to kernel32.dll) => `DecodePointer()`, `EncodePointer()`, `GetModuleHandleExW()`, `InitializeSListHead()`, `InterlockedPopEntrySList()`, `InterlockedPushEntrySList()`

Alright then, no font smoothing on Windows 2000. ;)

**Comment by snowie2000** [comment]
Cool, it misses so many famous APIs. I am totally surprised at how we did programming in the old days.

Maybe we have to compile mactype with VC6 since today's modern compilers don't provide a windows 2000 toolkit anymore~

**Comment by GrandAdmiralThrawn** [comment]
VC9 is still possible actually (I compiled some stuff for 2000 myself way back using VC9). The corresponding redistributable exists for Windows 2000.

But yeah, I'll just forget about this one... ;)

**Comment by snowie2000** [comment]
I believe if you remove all the x64 related manipulation code and tweak the code to conform with the standard of  VC9, Mactype should have a chance working on the Windows 2000 32bit.

I've never seen the Windows 2000 x64 so I assume it doesn't exist, does it?

**Comment by GrandAdmiralThrawn** [comment]
There is no x86_64 or x64 version, no. Earliest Windows to support that architecture are Server 2003 and XP.

There is only a weird DEC Alpha (RISC) 64-bit version, but that OS was never officially released. So not just for the DEC Alpha microarchitecture, but also an "alpha" version, software-wise. It's even more niche than anything I'm using... and that says a lot.

Anyway, for me, #578 is more significant at the moment anyway.
