### ISSUE TITLE
Is there any option to configure DirectWrite?

### ISSUE THREAD

**Issue by hwooo** [snowie2000/mactype#581]
I want to apply MacType only to desktop applications.
Can I disable DirectWrite settings for Web browsers?

**Comment by snowie2000** [comment]
You can categorize all the browsers to a group and disable DirectWrite for the group.
e.g.
```ini
[general@chrome.exe]
Alternative=browser
[general@firefox.exe]
Alternative=browser
; more browser definitions

[general@browser]
DirectWrite=0
```

**Comment by hwooo** [comment]
@sammilucia Do I have to configure it in `win7.ini` file?

**Comment by snowie2000** [comment]
Please add it to the profile you're using.
