### ISSUE TITLE
mactype 2019 beta6 无法渲染chromium内核版edge浏览器

### ISSUE THREAD

**Issue by qile3897** [snowie2000/mactype#585]
系统是win10 1903， edge版本为 77.0.218.4 (Official build) dev (64-bit)
chrome可以正常渲染，chrome版本75.0.3770.142（正式版本） （64 位）
是内核版本原因？
附与chrome对比图
edge:
![image](https://user-images.githubusercontent.com/48940841/61573170-958bb980-aadc-11e9-9eb2-eb56b2cbfe7d.png)
chrome:
![image](https://user-images.githubusercontent.com/48940841/61573201-16e34c00-aadd-11e9-897f-a2a08ca8b940.png)

**Comment by qile3897** [comment]
注册表加载，服务加载都试过了

**Comment by qile3897** [comment]
关掉了。。。我换成EDGE CANARY版本之后好了。。。

**Comment by snowie2000** [comment]
edge哪里没有渲染了？宋体≠不渲染，请先弄明白这个概念

**Comment by qile3897** [comment]
> edge哪里没有渲染了？宋体≠不渲染，请先弄明白这个概念

你看上面那张edge的截图，有的笔画太细了根本看不清啊。同样字体同样配置。如果是宋体的问题。那为何edge dev和edge canary会有如此差距呢。canary截图如下
![image](https://user-images.githubusercontent.com/48940841/61576146-90dcfa80-ab08-11e9-92e9-8c3405a722f5.png)

**Comment by snowie2000** [comment]
宋体在directwrite本来就是这样的，你这个canary是宋体？？
至于为什么换了个浏览器字体都变了我就不清楚了

**Comment by qile3897** [comment]
额，我搞错了。canary把字体换到微软雅黑了。

**Comment by tonierlu** [comment]
我的也没法渲染，请问是如何配置的？

**Comment by tonierlu** [comment]
谢谢！

加了，好像也没效果。。

Edge 浏览器也没效果，有办法吗？

________________________________
差出人: qile3897 <notifications@github.com>
送信日r: Friday, September 27, 2019 5:13:38 PM
宛先: snowie2000/mactype <mactype@noreply.github.com>
CC: tonierlu <tonier.lu@live.com>; Comment <comment@noreply.github.com>
件名: Re: [snowie2000/mactype] mactype 2019 beta6 无法渲染chromium内核版edge浏览器 (#585)


chrome新内核之后好像需要加上这个
--disable-features=RendererCodeIntegrity
[image]<https://user-images.githubusercontent.com/48940841/65757585-0b01af00-e14a-11e9-9100-2606964704fb.png>

―

**Comment by snowie2000** [comment]
@tonierlu Chrome和Edge是两个东西，edge没有那个参数。

不要以为和以前不一样就是没渲染，dw的渲染效果目前就是这样，不是很好，你要和关闭mactype的时候做对比。

原版Edge不可渲染，无解。微软做了特别的设计，除了签名DLL外，无法注入。

**Comment by qile3897** [comment]
上面那个是防止页面崩溃的。。。无法渲染好像是chromium新版内核有个啥新特性，之前其他帖子有讨论过英文的。但是@snowie2000大佬好像不确定这个新特性会不会保留。。。反正是要改个东西但是我忘了。。

**Comment by tonierlu** [comment]
@snowie2000 感谢大佬回复，先这么用着了，期待您有更好的解决办法！再次感谢！
