### ISSUE TITLE
issue in CFontLinkInfo

### ISSUE THREAD

**Issue by wzv5** [snowie2000/mactype#586]
https://github.com/snowie2000/mactype/blob/501a192a335ea181d3374d130d2d679abcbc4250/settings.cpp#L1174-L1176

Should `return` here? The code below uses `h1`, and `h1` may have been closed.

**Comment by snowie2000** [comment]
Yes, it should return. It just never happened since every Windows copy had at least one font installed.

**Comment by wzv5** [comment]
But it may fail to open due to permission denied.

**Comment by snowie2000** [comment]
Theoretically, yes, but practically, no. Denying access to this key would result in too many problems that no one would do it.

**Comment by wzv5** [comment]
Well, whatever.
（“又不是不能用” ^_^）

**Comment by snowie2000** [comment]
Code updated.
