### ISSUE TITLE
Win10 1903 桌面阴影异常

### ISSUE THREAD

**Issue by mr-cn** [snowie2000/mactype#587]
![image](https://user-images.githubusercontent.com/19818121/61719505-a4ea5b80-ad97-11e9-8fc3-770cbcadaad0.png)

可以明显看到文字的阴影有的地方多 有的地方少

**Comment by snowie2000** [comment]
很抱歉，此阴影是windows加的

**Comment by mr-cn** [comment]
请问有办法解决吗？

另外VSCode的宋体感觉很不清楚，一些偏旁细的都看不见了，不知道是不是正常现象

![image](https://user-images.githubusercontent.com/19818121/61720065-b2541580-ad98-11e9-9234-437b05a20234.png)

**Comment by mr-cn** [comment]
是不是因为VSCode是electron，所以没有渲染？但是最新版本不是支持DW了嘛

**Comment by snowie2000** [comment]
宋体渲染后就是这个很丑的样子的，不过你可以修改vscode的字体

桌面的阴影在 系统设置 高级 性能 在图标下显示阴影，不过如果你关闭这个选项，图标下文字的阴影是没了，但是文字会变得不透明，直接出来一块背景色，更丑
