### ISSUE TITLE
why font monaco, size 8 is different between visual studio and sublime

### ISSUE THREAD

**Issue by swordday** [snowie2000/mactype#589]
# visual studio 2019
![image](https://user-images.githubusercontent.com/2648243/62094896-451d1480-b2b1-11e9-9a05-02f90dbebb3f.png)
# sublime
![image](https://user-images.githubusercontent.com/2648243/62094972-6978f100-b2b1-11e9-9d18-99bc4194b3d6.png)
i know the render way in sublime is freetype, in vs is directwrite, but how can i make the same

**Comment by snowie2000** [comment]
![QQ截图20190730100839](https://user-images.githubusercontent.com/11767189/62095136-0cca0600-b2b2-11e9-9781-641ca65593f8.png)
After overlaying your two images in Photoshop, you can see that they are the same in size.
The texts in sublime are just a little thicker and smoother. You can adjust parameters to makes them look close but it would be very hard to make DirectWrite look exactly the same way as FreeType.

**Comment by swordday** [comment]
> The texts in sublime are just a little thicker and smoother. You can adjust parameters to makes them look close but it would be very hard to make DirectWrite look exactly the same way as FreeType.

it feel like is font shadow or hinting problem in directwrite,  by the way, which parameter i can change to make more the same like? tks!

**Comment by snowie2000** [comment]
There ain't many parameters available for DirectWrite and they are all listed in the [wiki](https://github.com/snowie2000/mactype/wiki/DirectWrite-section)

The hinting of directwrite goes along with the global setting, however, they may not behave exactly the same.

**Comment by swordday** [comment]
i use the fontcreator to bold the original font, contrast change from 1.0 to 1.4, it looks better than before

**Comment by snowie2000** [comment]
Wow, that's a little overkill I think...
