### ISSUE TITLE
The 2019.1 Beta6 has issue with Visual Studio 2019

### ISSUE THREAD

**Issue by cdytoby** [snowie2000/mactype#594]
Windows 10 1903, 
Visual Studio 2019 v16.2.0
MacType 2019.1-beta6

With MacType 2019.1 Beta, as soon as VS launches, VS have extremely high CPU usage (more than 60% on my i7), and it's not going down even VS is idle. At the same time, git view is not initialized in VS. And if I close and  relaunch VS, it won't visually launch, and its process in task manager remains, with high CPU usage. 

As long as the VS window is showed, its font is correctly rendered with MacType.

Launch VS without MacType don't have issue, and switch back to Mactype 2018 Beta also solves this issue.

Here is the setting ini.
[settingini.zip](https://github.com/snowie2000/mactype/files/3470950/settingini.zip)

MacType is in System Tray mode, and it's in include mode (whitelist mode).

**Comment by snowie2000** [comment]
Try:
1. Stop using include mode
2. Disable directwrite

see if any of the operations solve the problem.

**Comment by cdytoby** [comment]
> Try:
> 
> 1. Stop using include mode
> 2. Disable directwrite
> 
> see if any of the operations solve the problem.

I can confirm that:
- Disable directwrite doesn't work
- UseInclude=0 works and solve the problem.

But I only want to use MacType with code editing like Visual Studio or Jetbrain. I prefer use include mode.

**Comment by snowie2000** [comment]
I'm so sorry. There was a serious bug in the include mode that it will fall into a dead loop on load.
Overwriting the following two files should fix it.

[MacType_inc_fix.zip](https://github.com/snowie2000/mactype/files/3474985/MacType_inc_fix.zip)

**Comment by cdytoby** [comment]
Thanks, these dlls solved the problem.

Don't forget to merge.
