### ISSUE TITLE
Unable to Enable Thunderbird

### ISSUE THREAD

**Issue by tordenflesk** [snowie2000/mactype#595]
Windows 7, Thunderbird 60.8.0, MacType 2019.1-beta6

Thunderbird settings:
gfx.canvas.azure.backends;direct2d1.1,cairo,skia
gfx.content.azure.backends;direct2d1.1,cairo,skia

ini:
https://pastebin.com/raw/7q0FcuYt

**Comment by a0193143** [comment]
gfx.direct2d.disabled true

**Comment by tordenflesk** [comment]
Yup, that's the default for that value, which it's set to.

Of course it started working again shortly after posting this issue.

**Comment by tordenflesk** [comment]
And as soon as this issue was closed it stopped working again...
Switching to a "blank" Thunderbird profile, then back to my regular profile seems to (at least temporary) fix it...

**Comment by tordenflesk** [comment]
So far it's only when I receive e-mails from github that rendering stops working and I'm force to do the workaround.
