### ISSUE TITLE
Cent Browser 4.0.9.112 on Win10 1809+ problems?

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#596]
Is anyone having problems with Cent Browser (x64 or 32-bit) 4.0.9.122 crashing after long use, or 20+ tabs (especially YouTube) open?

Our other computer doesn't have MacType (but otherwise very similar setup) but doesn't have this problem. I've just disabled MacType to check if this is the issue but thought I'd ask as well.

- MacType beta6 using 'Clear Soft' profile
- Updated to Win10 1903 no change.

The problem presents as Cent becoming unstable, the entire screen (not just Cent) flashes black momentarily, and after there the problem gets worse, eventually ending in a crash message (I think "invalid instruction" error).

Also getting in AppLog:
- (Several) The Desktop Window Manager process has exited. (Process exit code: 0x8007001f, Restart count: 5, Primary display device ID: Intel(R) HD Graphics 620)
- Faulting application name: dwm.exe, version: 10.0.18362.267, time stamp: 0x6468b8f9, Faulting module name: dwmcore.dll, version: 10.0.18362.267, time stamp: 0x216e9e9f, Exception code: 0xc00001ad, Fault offset: 0x000000000015b68a

**Comment by snowie2000** [comment]
That means the DWM was crashed, which crashed a lot...
Try to disable MacType for DWM.exe (which should be disabled by default, I think).

**Comment by sammilucia** [comment]
Thank you, done and testing

**Comment by sammilucia** [comment]
Disabling DWM.exe for MacType seems to have made things more stable. Interestingly explorer.exe is reserving 18 GB of memory (apparently)

![image](https://user-images.githubusercontent.com/3295286/63071036-29398580-bee3-11e9-928e-a859a5935dfa.png)

**Comment by sammilucia** [comment]
@snowie2000 do you want me to disable DWM.exe in the release MacType.ini?

**Comment by snowie2000** [comment]
Rendering `dwm.exe` has no meaning in Windows7 and the process is access denied by default in Windows 10. I think we have no reason to not exclude it.

**Comment by sammilucia** [comment]
okay thank you done! 😊

**Comment by sammilucia** [comment]
Hi @snowie2000 I'm about 90% sure MacType is crashing CentBrowser and Chrome for me. With or without DirectWrite enabled. I've reproduced it on two different PCs.

I think it's actually the DirectWrite injection that's crashing,, NOT GDI... ??? I also suspect it might be a memory leak, or possibly video memory problem. I'm only guessing.

The test is not affirmative. However to reproduce:
1. Install MacType on Win 10x64 1809 or 1903
2. Use a profile with `AntiAliasMode=-1` set or not
3. Use CentBrowser with DirectWrite disabled or enabled, or use Chrome
4. Browse for 10+ hours, and open 20+ tabs, especially YouTube tabs

Expected outcome:
- Works as normal and looks beautiful 😊

Observed outcome:
- After a several hours, the whole screen flashes black for a tab
- Some tabs start saying "Aw, snap" error message
- In a few instances I've seen what looks like graphics corruption (a small square on screen with junk)
- After another several minutes of continued use in this state all of Windows becomes unresponsive

I can't reproduce this with MacType unloaded (Manual Mode) ... not so far anyway.

**Comment by snowie2000** [comment]
Thank you for the testing. 

I suggest doing another test in the registry mode. This allows us to test mactype cleanly without the influence from the tray app or service.

**Comment by sammilucia** [comment]
I've also noticed another weird thing:
1. Open 20+ tabs in Chrome / Cent
2. Close Chrome / Cent
3. Reopen it, so all tabs are unloaded
4. Quickly tab through all tabs to start them loading

With MacType installed (and I THINK GDI rendering is disabled)
- With MacType enabled, the Chrome/Cent UI gets really slow, sometimes freezes. Some tabs fail to completely load
- With MacType disabled, all tabs load quickly and don't freeze

**Comment by sammilucia** [comment]
@snowie2000 will do

**Comment by sammilucia** [comment]
@snowie2000 it still happens exactly the same in registry mode

**Comment by sammilucia** [comment]
never mind ... it happened without MacType running ... the issue is not MacType related

still so weird, it happens on two PCs ... must be something else I'm running 😜

closing issue
