### ISSUE TITLE
Taskbar calendar App can't be rendered

### ISSUE THREAD

**Issue by hopana** [snowie2000/mactype#599]
I have an taskbar calendar app which replace the system calendar frame, but the font in this app can't be rendered. as bellow image shows (mactype is the latest version) :

![image](https://user-images.githubusercontent.com/13976824/63069411-4e60df00-bf49-11e9-852c-5649a95a6e6b.png)

**Comment by snowie2000** [comment]
What's the name of the application?

**Comment by hopana** [comment]
> What's the name of the application?
I checked the tasklist, the application process is loaded. The application called yxcalendar, as bellow:

[yxcalendar_v1.9.8.14.zip](https://github.com/snowie2000/mactype/files/3504413/yxcalendar_v1.9.8.14.zip)

**Comment by snowie2000** [comment]
Very interesting software.
It draws its interfaces with GDIPlus, an outdated UI library made by Microsoft which hasn't been updated since 2009.

Microsoft didn't release sufficient information about its proprietary font engine embedded in the Gdiplus, so it can't be support right now.

**Comment by snowie2000** [comment]
I believe the reason why the software is stilling using this old tech is that GDIPlus is the only 2d engine that handles graphics with translucency under Windows XP.

**Comment by hopana** [comment]
OK, I got it, Thank you!!!
