### ISSUE TITLE
应用程序换字体闪退

### ISSUE THREAD

**Issue by durandal1981** [snowie2000/mactype#600]
2019.1 beta6，win10 1903，应用程序换字体闪退，打开一些记事本、eclipse等程序，打开换字体窗口后，拖动一下换字体下拉列表，然后，应用程序就闪退了

**Comment by snowie2000** [comment]
> 打开换字体窗口后，拖动一下换字体下拉列表

"换字体窗口" 是什么窗口？ 下拉列表是什么列表？
