### ISSUE TITLE
What is the difference between LCD and Light-LCD?

### ISSUE THREAD

**Issue by hwooo** [snowie2000/mactype#601]
`Anti-Aliasing: LCD(RGB) / Light-LCD(RGB)`

What is the difference between these two options?

**Comment by snowie2000** [comment]
No difference after adobe contributed its auto hinting engine to FreeType.

**Comment by IceMan81** [comment]
@snowie2000 That's interesting. Seems like there is a visual difference when using AntiAliasMode=2 vs AntiAliasMode=4.

@NDelt Do you find that there is no visual difference between the two options? 

@snowie2000 @sammilucia Do you think we could document the various combinations of 
HintingMode & AntiAliasMode and what they mean? For me, this is a constant source of confusion and I end up with trial and error without understanding what I'm doing.

**Comment by snowie2000** [comment]
@IceMan81 Light mode is basically the `FT_LOAD_TARGET_LIGHT` in freetype.

Check the official document for more details.
https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_load_target_xxx

`FT_RENDER_MODE_LIGHT` can be used together with different rendering mode: https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_render_mode

If you combine `FT_LOAD_TARGET_LIGHT` with `FT_RENDER_MODE_LIGHT`, you got light mode in mactype.
If you combine `FT_LOAD_TARGET_LIGHT` with `FT_RENDER_MODE_LCD`, you got light LCD mode in mactype.

**Comment by snowie2000** [comment]
There is another article talking about the "slight" hinting mode:
https://www.freetype.org/freetype2/docs/text-rendering-general.html

For mactype, the light mode and grayscale mode do have a difference when hinting is enabled. However when lcd rendering mode is engaged, I could tell of no noticeable difference so far after FreeType upgraded several years ago.

**Comment by hwooo** [comment]
@IceMan81 I've tried to find difference, but I couldn't.
