### ISSUE TITLE
Has compatibility issiue with ModOrganizer

### ISSUE THREAD

**Issue by arenekosreal** [snowie2000/mactype#603]
When I use this with ModOrganizer,  If I execute BodySlide program through ModOrganizer, I will get an error about loading files. This problem can be disappeared if I disable MacType.

**Comment by snowie2000** [comment]
What does the error message say?

**Comment by arenekosreal** [comment]
It says "Failed to load Setup.xrc file"

**Comment by snowie2000** [comment]
I downloaded the modOrganizer and looks like you have to have the game to use it, which I don't.

I'm sorry I can't solve it.

**Comment by arenekosreal** [comment]
I mean I have the game and I have configured the game correctly, if I start BodySlide in ModOrganizer, it will give me that error message. When I disable MacType or even add ModOrganizer to the exception list, all the things are right. The author of ModOrganizer told me that it was MacType's problem and only you can fix this. This is the address of his reply: https://github.com/ModOrganizer2/modorganizer/issues/826#issuecomment-527357792

**Comment by snowie2000** [comment]
What I meant is that I don’t have the game so I can’t test the mod organizer for you and fix problems caused by Mactype.

**Comment by arenekosreal** [comment]
ok,anyway,thanks for your help. Now, one solution of this problem is add ModOrganizer to MacType's whitelist.
