### ISSUE TITLE
Service mode doesn't work as expected

### ISSUE THREAD

**Issue by validatedev** [snowie2000/mactype#608]
It's glitchy for me. When I open the task manager and hover on the elements that are categories such that Processes, Performance, App History etc, it turns to Mactype font style but when the initial screen is not. Processes are rendered correctly.

**Comment by snowie2000** [comment]
If you start the task manager with ctrl alt delete, it is created by winlogon.exe which is not supported by service mode. 

If you started task manager from the task bar and it still does not get rendered on the first second, you should check your profile too see if you have svchost.exe in you exclusion list. It Shouldn’t be there.

**Comment by validatedev** [comment]
> If you start the task manager with ctrl alt delete, it is created by winlogon.exe which is not supported by service mode.
> 
> If you started task manager from the task bar and it still does not get rendered on the first second, you should check your profile too see if you have svchost.exe in you exclusion list. It Shouldn’t be there.

Using the default Default.ini and can't see any exclusion for svchost. Starting the task manager on the taskbar but no luck, same thing has happened.

**Comment by snowie2000** [comment]
Please provide a full list of running process status so we can have a better understanding of the issue.

**Comment by validatedev** [comment]
Reinstalled the OS, problem solved.
