### ISSUE TITLE
让MacType更早启动

### ISSUE THREAD

**Issue by fonlan** [snowie2000/mactype#609]
目前Win10上Load with MacTray是通过计划任务启动的，不过需要等用户登陆后才会启动。导致很多在MacType启动前就已经启动了的程序没有被渲染，需要手动关闭并重启这些程序，所以我进行了以下尝试：

- Seccurity options改为Run whether user is logged on or not
![image](https://user-images.githubusercontent.com/7898348/65655361-9433bb80-e04e-11e9-967c-8f3ed9180d5f.png)
- 把Triggers改为At startup
![image](https://user-images.githubusercontent.com/7898348/65655414-b88f9800-e04e-11e9-83a0-e0e871bb9c77.png)
这样改动后MacType的启动优先级就很高了，甚至感觉锁屏界面也被渲染了。

不过目前这样改后还有一个问题，MacTray的托盘图标不见了，应该是因为在用户登陆前启动导致的。

所以是不是可以把后台渲染的进程和托盘程序进行分离？后台渲染的进程不需要界面，以这种高优先级的方式启动，而托盘图标程序就以普通程序用户登陆后再启动就行，托盘图标程序用某种进程间通信的方式（比如socket）对后台渲染进程进行控制。这样就能实现高优先级启动和托盘图标两不误了，如果不需要托盘图标的那么托盘程序不启动就行了，渲染依旧在。理论上后台渲染进程通过系统服务方式启动的这样也能通过托盘图标进行操作了。

**Comment by snowie2000** [comment]
如果你要实现在系统启动时就能渲染的效果，你需要的应该是服务模式。

托盘模式就是为了方便的进行交互。如果要改成双进程通信的模式，当然也是可以的，但是需要对整个托盘程序进行重新设计，需要很大的工作量，目前不会考虑。

至于为什么要用计划任务呢？很简单……因为UAC
为了渲染高权限的进程（如任务管理器等），mactray必须以管理员权限启动，而Windows无法自启动一个管理员权限的进程，唯一的办法就是计划任务。

在Win7下，很多人是关闭uac的，mactray就可以直接作为自启动项启动，速度比计划任务块不少

**Comment by fonlan** [comment]
还不是因为你说的Win10下服务模式有时候还没有托盘模式权限高所以才用的托盘模式嘛。。。所以这种方案就是兼具高优先级和高权限的。不过改动的工程量确实是挺大的。

**Comment by snowie2000** [comment]
谁知道呢，微软团队把Windows改来改去的也不知道怎么改了就搞成了服务模式有的时候还不如普通进程的权限高。

服务模式不能加载到explorer简直是家常便饭

**Comment by fonlan** [comment]
所以如果以后如果有重构的计划的话可以考虑下这种方案哈
