### ISSUE TITLE
一直不能将excel2016的界面字体"微软雅黑"替换为"宋体"

### ISSUE THREAD

**Issue by zingisme** [snowie2000/mactype#612]
如题。
系统：WIN7-64位企业版
软件：excel2016 64位
MACTYPE 2019.1-B6，以及MACTYPE 2018.1-B5

配置里将"微软雅黑"替换为"宋体"，多数软件都生效，但是EXCEL2016的界面就是替换不了。
恳请支招。

**Comment by snowie2000** [comment]
我并没有2016，所以我不确定以下我说的都是正确的。

如果excel用的是DirectWrite界面，那么针对dw的字体替换目前并不完整，有一些情况是不会被替换的，目前暂时不能解决。
如果excel的是普通界面的，在Windows中有一类特殊的字体创建方式，也是无法被替换的。你需要设置Fontsubsitute=2来开启强制替换，强制替换可以替换掉这类特殊的字体，但是强制替换并不安全，对于部分情况可能会导致乱码，如果要使用的话，建议只针对个别程序开启。

**Comment by zingisme** [comment]
感谢这么快的回复。
实际情况是，我的确可以用Mactype替换这个字体，家里电脑就是可以的（以上是我单位电脑的情况）。
家里电脑配置我记不清了，等我稍晚提供。
目前我最大的疑点在64位上，翻阅有个issue提到过（https://github.com/snowie2000/mactype/issues/478），是否会是这个有关呢？
谢谢！

**Comment by snowie2000** [comment]
如果是上面这个问题，所有64位程序都会不能正常加载。

**Comment by snowie2000** [comment]
@zingisme 请问是否有查找到问题或者有其他线索，没有的话此issue将被关闭

**Comment by zingisme** [comment]
就这样对付用吧，正文可以替换宋体，菜单没法替换。
关闭吧。
