### ISSUE TITLE
chrome升级78.0.3904.70版，汉字非常糟糕

### ISSUE THREAD

**Issue by karelyang** [snowie2000/mactype#613]
chrome在77版上显示和Edge最新版上显示效果一致，但升级V78.0.3904.70版，汉字就非常奇怪，和和未渲染差不多，但chromium内核Edge的V78.0.276.20显示正常。

1. chrome显示效果图
![chrome](https://user-images.githubusercontent.com/4417146/67628524-d47e9780-f8a1-11e9-81b1-cc0369f196b5.png)

2. Edge显示效果图
![Edge](https://user-images.githubusercontent.com/4417146/67628525-e95b2b00-f8a1-11e9-97a6-675970482b01.png)

**Comment by snowie2000** [comment]
duplicate as #597.

**Comment by snowie2000** [comment]
请使用参数启动chrome，暂时没有其他办法解决。

**Comment by karelyang** [comment]
感谢，添加参数后正常了。
