### ISSUE TITLE
Does MacType work with Chrome/Firefox?

### ISSUE THREAD

**Issue by xSwagboy69x** [snowie2000/mactype#618]
Hi guys,

I use Cent Browser (and MacType works great there) — I'm curious as to whether it works as well with Google Chrome/Firefox.

I've seen people talking here as if MacType **DOES** work with Chrome/Firefox, but I've never personally ever been able to get it to (not since Google disabled the Directwrite flag); am I doing something wrong with my Chrome/Firefox?

Just want some definitive clarity so I can stop wondering if I'm missing something.

Thanks!

**Comment by snowie2000** [comment]
Sort of supported before the latest release of Chrome but not anymore. (refer: #597)
Old versions of firefox are fully supported with cario frontend but new versions are not, because the cario frontend has been blocked due to compatibility issue (refer: #565). But since directwrite is still there and there is no such strict injection prevention as chrome did, Firefox can still be rendered in DirectWrite mode.

**Comment by xSwagboy69x** [comment]
@snowie2000 

Thank you for your response! I'll try to make sure my Directwrite settings are correct to see if Firefox works.

So, does this mean that Cent Browser is the only other browser that's fully and correctly compatible with MacType?

I've tried Vivaldi and Edge beta as well;  have not been able to get it working, I assume they are not compatible.

**Comment by snowie2000** [comment]
Edge has two versions (although I believe the Microsoft version is dead). The chrome based version is partially supported with direct write tweak. 

The Microsoft version is not supported at All.

**Comment by wzhudev** [comment]
> Hi guys,
> 
> I use Cent Browser (and MacType works great there) — I'm curious as to whether it works as well with Google Chrome/Firefox.
> 
> I've seen people talking here as if MacType **DOES** work with Chrome/Firefox, but I've never personally ever been able to get it to (not since Google disabled the Directwrite flag); am I doing something wrong with my Chrome/Firefox?
> 
> Just want some definitive clarity so I can stop wondering if I'm missing something.
> 
> Thanks!

Thanks! I will consider using CentBrowser.

**Comment by sammilucia** [comment]
Sometimes there's long delays between Cent Browser releases which can cause a concern 'cause of Chromium security patches. Lately I've been using Cent beta installers (http://static.centbrowser.com/beta_64/) and not had any problems 😊

**Comment by IgnacioMD** [comment]
> 
> Edge has two versions (although I believe the Microsoft version is dead). The chrome based version is partially supported with direct write tweak.
> 

@snowie2000. Can you explain me which is the direct write tweak, please ?
