### ISSUE TITLE
Win10 LTSC 1809下极限竞速：地平线4闪退

### ISSUE THREAD

**Issue by rsxiaopu** [snowie2000/mactype#621]
你好！

在开启MacType并使用注册表加载的情况下，一旦打开极限竞速：地平线4在载入过程中直接闪退，不使用加载的话就能正常进入游戏，目前只发现这一个游戏会有这种情况！

最新的MacTypeInstaller_2019.1-beta6也是一样

附上事件属性，不知道有帮助没？

日志名称:          Application
来源:            Application Error
日期:            2019/12/16 20:53:17
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-N20786L
描述:
错误应用程序名称: ForzaHorizon4.exe，版本: 0.0.0.0，时间戳: 0x5deea370
错误模块名称: ForzaHorizon4.exe，版本: 0.0.0.0，时间戳: 0x5deea370
异常代码: 0xc0000005
错误偏移量: 0x00000000008a1954
错误进程 ID: 0x3344
错误应用程序启动时间: 0x01d5b40fc4ef2e9d
错误应用程序路径: C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.377.172.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.377.172.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
报告 ID: 6b4768c8-0cb0-45d0-9f3b-819fd39a207b
错误程序包全名: Microsoft.SunriseBaseGame_1.377.172.2_x64__8wekyb3d8bbwe
错误程序包相对应用程序 ID: SunriseReleaseFinal
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-12-16T12:53:17.645518400Z" />
    <EventRecordID>24758</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-N20786L</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ForzaHorizon4.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5deea370</Data>
    <Data>ForzaHorizon4.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5deea370</Data>
    <Data>c0000005</Data>
    <Data>00000000008a1954</Data>
    <Data>3344</Data>
    <Data>01d5b40fc4ef2e9d</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.377.172.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.377.172.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe</Data>
    <Data>6b4768c8-0cb0-45d0-9f3b-819fd39a207b</Data>
    <Data>Microsoft.SunriseBaseGame_1.377.172.2_x64__8wekyb3d8bbwe</Data>
    <Data>SunriseReleaseFinal</Data>
  </EventData>
</Event>

**Comment by snowie2000** [comment]
请试一下把exe的名字放在excludemodule里面（不是unloaddll）里面。

**Comment by rsxiaopu** [comment]
好的，搞定了，谢谢

**Comment by LCLx** [comment]
请问是怎么解决的？我已经将ForzaHorizon4.exe放入ExcludeModule里面了 但是还是会闪退
使用的是Service mode

**Comment by rsxiaopu** [comment]
@LCLx 我使用的是注册表加载方式，当时直接添加就好了，刚刚又重新看了下ini文件，好像[UnloadDll]和[ExcludeSub]下面都有ForzaHorizon4.exe，你看下：

[UnloadDll]
AdobeIPCBroker.exe
audiodg.exe
CCXProcess.exe
fontforge.exe
forza_x64_release_final.exe
ForzaHorizon4.exe
igfxCUIService.exe
igfxEM.exe
igfxHK.exe
lass.exe
MsMpEng.exe
node.exe
NVDisplay.Container.exe
OfficeClickToRun.exe
pia-service.exe
QHActiveDefense.exe
QHSafeTray.exe
QHWatchdog.exe
RuntimeBroker.exe
SearchFilterHost.exe
SearchIndexer.exe
SearchProtocolHost.exe
services.exe
spoolsv.exe
stacsv64.exe
SynTPEnh.exe
SynTPHelper.exe
taskhostw.exe
VBoxSVC.exe
VirtualBox.exe
vmnat.exe
vmnetdhcp.exe
vmware-authd.exe
vmware-usbarbitrator64.exe
vmware-vmx.exe
[ExcludeSub]
forza_x64_release_final.exe
ForzaHorizon4.exe

**Comment by LCLx** [comment]
感谢您的回复。然而我在将这两个进程写入ini之后还是会闪退，还是不知原因。现在只能在forza之前把mactype手动关闭才行。

**Comment by snowie2000** [comment]
@LCLx ExcludeModule是不够的，必须UnloadDll

**Comment by LCLx** [comment]
@snowie2000 感谢您的回复。我在ExcludeModule、UnloadDLL、ExcludeSub里面均添加了，但是还是会出现闪退的情况

**Comment by LCLx** [comment]
@snowie2000 修改之后重启生效了 感谢
