### ISSUE TITLE
bugreport.txt

### ISSUE THREAD

**Issue by imba-tjd** [snowie2000/mactype#624]
点击下图时发生的（之前自动变成“不使用自动加载”了），但我重启之后再点又正常了。因此如果错误报告没有用可以直接close。

![图片](https://user-images.githubusercontent.com/24759802/71148878-db090a00-2267-11ea-9625-75abe291f3e9.png)

[bugreport.txt](https://github.com/snowie2000/mactype/files/3981923/bugreport.txt)

**Comment by snowie2000** [comment]
根据错误报告，被杀毒软件拦截了，注册表不让写入。

请检查下想办法允许MacType写入就行了。
