### ISSUE TITLE
'UseInclude/IncludeModule' will hang up some App like PyCharm

### ISSUE THREAD

**Issue by foobarjohnny** [snowie2000/mactype#630]
Environment
-  MacType : ver 2019.1-beta6, use Default.ini, and add this

            [General]
            UseInclude=1

            [IncludeModule]
            pycharm64.exe
            pycharm.exe

- PyCharm : ver 2018.3.6

Test
-    When launch PyCharm, it will be hung up in the startup window.

**Comment by snowie2000** [comment]
Useinclude seems buggy in beta6. Stay away from it for now.
