### ISSUE TITLE
Applications not starting (correctly) on Win 10 1903

### ISSUE THREAD

**Issue by itsTyrion** [snowie2000/mactype#633]
When MacType is active, anything I launch just silently crashes (can be seen through Windows Error Reporting appearing in TaskManager). 
example: https://streamable.com/g2ijf (I think the console can still start because MacType doesn't need to change any font rendering)
(This is just a basic hello world program written in Rust, but it also applies to Discord, Telegram, Steam, Games, Even parts of Windows.. I just didn’t feel like showing telegram chats ;))

**Comment by snowie2000** [comment]
Please provide your profile for debugging. Thanks.

**Comment by itsTyrion** [comment]
The profile does not matter, it happens with all profiles, with registry mode, service mode and tray mode 
According to a news article from 2018(19?), MacType is supposed to be broken since build 1709

**Comment by snowie2000** [comment]
No, mactype is working well on all versions of Windows 10 so far.
You have something installed on your system that conflicts with Mactype.

You may want to try this method:
1. set HookChildProcesses=0 to your profile
2. set loading mode to registry
3. reboot

See if it works for you.

**Comment by lalo311** [comment]
Try disabling avast, it has given me this sort of problems with Mactype, switched to windows defender and never had this problem again.

**Comment by itsTyrion** [comment]
> Try disabling avast, it has given me this sort of problems with Mactype, switched to windows defender and never had this problem again.

I will NOT switch to defender. Avast was already disabled for testing btw. 
Defender let’s 20%+ of viruses through (tested) and the performance impact is greater

**Comment by lalo311** [comment]
> 
> 
> > Try disabling avast, it has given me this sort of problems with Mactype, switched to windows defender and never had this problem again.
> 
> I will NOT switch to defender. Avast was already disabled for testing btw.
> Defender let’s 20%+ of viruses through (tested) and the performance impact is greater

Your call chief
EDIT : However the avast icon in your taskbar doesn't seem disabled in the streamable
