### ISSUE TITLE
Where should I put exe names for exclusion?

### ISSUE THREAD

**Issue by validatedev** [snowie2000/mactype#634]
I don't want to VAC-banned from Steam->CS:GO so want to exclude these but I don't know where should I write these exe names and cannot find any related information about that. Using Registry Mode with Default.ini. Thanks in advance!

**Comment by snowie2000** [comment]
There are two sections that do a similar job:
[[UnloadDll]](https://github.com/snowie2000/mactype/wiki/UnloadDll) and [[ExcludeModule]](https://github.com/snowie2000/mactype/wiki/ExcludeModule)

In your situation, Unloaddll is the way to go as it completely disables mactype for all its processes.

**Comment by validatedev** [comment]
Thanks for the explanation!
