### ISSUE TITLE
Firefox Developer Edition(74.0b7) MacType 设置无法生效

### ISSUE THREAD

**Issue by super-keys** [snowie2000/mactype#638]
不好意思. 我在issue里面找了很久. 尝试了很多设置. 但是我的火狐dev版本任然不起作用. 麻烦贴一下Firefox MacType 的正确配置. 感谢感谢~~~

**Comment by super-keys** [comment]
我按照wiki里面的配置好后重启电脑.依然没效果. 重启电脑也试过. 我也看过之前的issue里面已经关闭的关于火狐的问题. 依然未解决.

**Comment by snowie2000** [comment]
请给出截图说明没有生效是什么情况的。

**Comment by super-keys** [comment]
> 请指定截图说明没有效力是什么情况的。

![image](https://user-images.githubusercontent.com/8650578/75645459-ed002380-5c80-11ea-81ed-cb8f1d392c74.png)

左边的是火狐右边的是Cent Browser
看起来差异很大. 和关闭Mac Type 显示效果一样. 所以我认为我设置的无效.

**Comment by snowie2000** [comment]
请截图展示开启MacType前的firefox和开启后的firefox即可。最好能附上配置文件

**Comment by super-keys** [comment]
> 请截图展示开启MacType前的firefox和开启后的firefox即可。最好能附上配置文件
开启效果
![open](https://user-images.githubusercontent.com/8650578/75645761-29804f00-5c82-11ea-8e5e-19b1e872f4f0.png)

 关闭效果
![close](https://user-images.githubusercontent.com/8650578/75645735-11103480-5c82-11ea-8628-d19dd2063ff2.png)

配置文件
; Only for MacType (NOT SUPPORT THE OLD VERSION OF GDI++/HE)
; maxchow@qq.com

[Preview]
Font=Tahoma
Color=$990088
Text=卍 XMac.LCD @XHei (Android, Boldface, Ubuntu)
Size=10
Align=Center

[General]
Name=XMac.LCD.HotShift@XHei(Android^Boldface^Ubuntu)
Icon=XMac\XMac.ico,0

;【自动挂钩子进程】
;[0:Disable]  1:Enable
HookChildProcesses=1

;【字体微调】
;0:Normal 1:NoHinting 2:AutoHinting 3:Light+AutoHinting
HintingMode=1

;【抗锯齿方式】
;-1:Disable 0:Normal 1:Light 2:LCD(RGB) 3:LCD(GBR) 4:Light-LCD(RGB) 5:Light-LCD(GBR)
AntiAliasMode=2

;【常规体调整】
;-32:+32
NormalWeight=16

;【粗体字的调整】
;-16:+16
BoldWeight=2

;【斜体字的倾斜角度微调】
;-16:+16
ItalicSlant=0

;【只有在FontLoader=0（在下面）时此项设置才有效。建议选0，选1会占用大量内存，也没看出有什么好处。】
;0:Disable 1:Enable
UseMapping=0

;【Gamma模式开关】
;-1：关闭；0：使用设置的Gamma值（GammaValue）；1：使用sRGB的Gamma值；2：不明
GammaMode=0

;【Gamma值】
;GammaMode=0的时候此项设置才有效
;sRGB ≒ 2.2 CT-Default = 1.4
;windows的cleartype的Gamma值是1.4
GammaValue=1.4

;【对比度】
;数字越大越锐利，数字越小越发虚
Contrast=1.0

;【字体轮廓】
;数字越大字体就越粗越黑
RenderWeight=1.0

;【文字边界设置】
;数字越大越强调背景（类似文字边界被侵蚀的感觉），强调背景会有中字体锐利的感觉。适当降低对比度，提高TextTuning，可以使文字周围的颜色看起来“淡一点”
;再加上RenderWeight，把这三个设置的微妙平衡调节好的话，能得到不输给Mac的效果
;0:12

;AntiAliasMode=1时，通过TextTuning分量来调节
TextTuning=0

;AntiAliasMode=2时，通过TextTuning的RGB分量来调节
TextTuningR=0
TextTuningG=0
TextTuningB=0

;【字体加粗模式】
;对NormalWeight和BoldWeight有效
;0：Weight值大时横向加粗，值小时双向加粗，主要是避免Weight值过大时，模式3中在小字号时加粗过度出现斩头的现象；
;1：总是横向加粗；
;2：总是双向加粗，也就是freetype本身的粗体渲染。
;注意：通过加大GammaValue、TextTuning的值，可以减少Weight值过大的造成的效果问题，即可以在BolderMode=2时也可以避免转接头
BolderMode=0

;【字体的载入方法】
;（注意是载入方法，不是渲染方法）
;0：用freetype载入字体
;1：用windows的绘图核心载入字体
;很多freetype的设置需要此项选0才能生效
FontLoader=0

;【字体链接】
;当FontLoader=0时
;0：什么都不做；
;1：使用注册表里的字体链接设置，通过FreeType的字符表进行查找
;2：使用注册表里的字体链接设置，使用Windows的转换函数直接查找
;当FontLoader=1时
;会保持启用的状态，但是所有字体链接的处理会交由WIN32API完成。
FontLink=2

;【字体替代】
;当FontLoader=0时
;0：什么都不做；
;1：安全替换方案（兼容性较好），根据以下FontSubstitutes的配置进行替换；
;2：完全替换方案（效果较全面，如替换后出现乱码，请尝试使用1），根据以下FontSubstitutes的配置进行替换；
;当FontLoader=1时
;会保持启用的状态，但是所有字体替代的处理会交由WIN32API完成
FontSubstitutes=1

;【让freetype处理的最大的字体尺寸，单位是像素，0的话就是全尺寸】
;交付 gdi++ 处理的最大尺寸（单位为像素）
;0-2147483647
MaxHeight=0

;【阴影设置】
;格式：水平偏移,垂直偏移,深色文字的阴影透明度(0-100),深色文字的阴影颜色，浅色文字的阴影透明度(0-100),浅色文字的阴影颜色
;颜色值格式：BBGGRR 
Shadow=1,1,60,FFFFFF,30,000000

;【液晶显示器的优化配置】
;[0:None]  1:Default  2:Light  16:Legacy
LcdFilter=2

;【微调LcdFilter】
;LcdFilter>0，且AntiAliasMode>-1时，该微调才生效
;这5个值分别代表文字笔划中从左到右的笔划浓度，最小为0，最大为255
;注释掉这个参数则恢复使用
;LcdFilter=1，默认值为“16,64,112,64,16”
;LcdFilter=2，默认值为“0,85,86,85,0”
;LcdFilterWeight=16,64,128,64,16

;【字体缓存、内存的设置】
LoadOnDemand=1
CacheMaxFaces=256
CacheMaxSizes=33554432
CacheMaxBytes=67108864
EnableKerning=0

;【强制使用某一个字体】
;无视所有其他字体，全系统的字体都会被这里设置的字体代替
;ForceChangeFont=华文中宋

;【优先使用点阵】
;小于指定字号的文字将优先使用内嵌点阵
MaxBitmap=0

[Individual]
;【单独设置的字体】
;格式＝Hinting, AAMode, NormalWeight, BoldWeight, ItalicSlant, Kerning
XHei=,,12,2,,,
XHei Style.Android=,,12,2,,,
XHei Style.Boldface=,,12,2,,,
XHei Style.Ubuntu=,,12,2,,,
XHei Mono=,,12,2,,,
XHei Mono.Droid=,,12,2,,,
XHei Mono.Heiti=,,12,2,,,
XHei SimSun=,,12,2,,,
XHei NSimSun=,,12,2,,,
XHei SimSun.Droid=,,12,2,,,
XHei NSimSun.Droid=,,12,2,,,
XHei SimSun.Heiti=,,12,2,,,
XHei NSimSun.Heiti=,,12,2,,,

XSong=,,28,0,,
XSong SimSun=,,28,0,,
XSong NSimSun=,,28,0,,
XSong Sharp=,,28,0,,
XSong Sharp.SimSun=,,28,0,,
XSong Sharp.NSimSun=,,28,0,,
XSong Harmony=,,28,0,,
XSong Harmony.SimSun=,,28,0,,
XSong Harmony.NSimSun=,,28,0,,
XSong Classical=,,28,0,,
XSong Classical.SimSun=,,28,0,,
XSong Classical.NSimSun=,,28,0,,
XSong Tradition=,,28,0,,
XSong Tradition.SimSun=,,28,0,,
XSong Tradition.NSimSun=,,28,0,,

宋体=,,28,0,,
新宋体=,,28,0,,
SimSun-ExtB=,,28,0,,
仿宋_GB2312=,,28,0,,
仿宋=,,28,0,,
华文仿宋=,,28,0,,
华文宋体=,,28,0,,
华文中宋=,,28,0,,
Batang=,,28,0,,
MingLiU=,,28,0,,
MingLiU-ExtB=,,28,0,,
PMingLiU=,,28,0,,
PMingLiU-ExtB=,,28,0,,
PMingLiU_HKSCS=,,28,0,,
PMingLiU_HKSCS-ExtB=,,28,0,,
MS Mincho=,,28,0,,
MS PMincho=,,28,0,,

[Exclude]
;【除外的字体】

[ExcludeModule]
;【不渲染的程序，但仍会加载DLL】

[ExcludeSub]
;【排除不替换字体的程序】
;以下程序不会被进行字体热替换
Fetion.exe
kugoo.exe
iTunes.exe
ChatHall.exe
guagua.exe
XLDoctorUI.exe
CorelDRW.exe

[UnloadDll]
;【不渲染的程序，同时完全不加载DLL】
fontview.exe
MainType.exe
AxureRP.exe
FontCreator.exe
FontCreator.cn.exe
notecaselauncher.exe
notecase.exe
gnucash-bin.exe
bleachbit.exe
Fontforge_TC.exe
Fontforge_SC.exe
Fontforge_EN.exe
NexusFont.exe
dwm.exe

[FontSubstitutes]
;【字体替代】
;系统在调用“=”前面的字体时会忽视“=”前面的字体，而去直接调用“=”后面的字体
Fixedsys=XHei NSimSun
SimSun=XHei SimSun
@SimSun=@XHei SimSun
NSimSun=XHei NSimSun
@NSimSun=@XHei NSimSun

[FontSubstitutes@Office]
;【字体替代 for Office】
Fixedsys=XSong Sharp
SimSun=XSong Sharp
@SimSun=@XSong Sharp
NSimSun=XSong Sharp
@NSimSun=@XSong Sharp

[General@EXCEL.EXE]
Alternative=Office
[General@POWERPNT.EXE]
Alternative=Office
[General@WINWORD.EXE]
Alternative=Office
[General@et.exe]
Alternative=Office
[General@wps.exe]
Alternative=Office
[General@wpp.exe]
Alternative=Office

**Comment by snowie2000** [comment]
你没有开启DirectWrite，所以对firefox自然是不生效的。
wiki中的设置只对老firefox生效，高版本的firefox已经屏蔽了cario，强制DirectWrite了

**Comment by super-keys** [comment]
> 你没有开启DirectWrite，所以对firefox自然是不生效的。
> wiki中的设置只对老firefox生效，高版本的firefox已经屏蔽了cario，强制DirectWrite了

开启后效果
![open1](https://user-images.githubusercontent.com/8650578/75646092-6436b700-5c83-11ea-9c16-46d9f4bece03.png)
![image](https://user-images.githubusercontent.com/8650578/75646111-77498700-5c83-11ea-82e8-7404cff85611.png)

**Comment by snowie2000** [comment]
没错，这就是DirectWrite渲染后的结果了，如果你不满意……

那也没办法……DirectWrite只能这样了

**Comment by snowie2000** [comment]
dw有他单独的一个section可以做调节，你也可以试试看能不能达到你想要的效果
https://github.com/snowie2000/mactype/wiki/DirectWrite-section

**Comment by super-keys** [comment]
> 没错，这就是DirectWrite渲染后的结果了，如果你不满意……
> 
> 那也没办法……DirectWrite只能这样了

浏览器那块需要设置吗? 我看了下设置. 不是默认的. 被我修改过. 有影响吗?

配置
![image](https://user-images.githubusercontent.com/8650578/75646195-c5f72100-5c83-11ea-9028-bdd0ee96b8f4.png)
![setting1](https://user-images.githubusercontent.com/8650578/75646199-c98aa800-5c83-11ea-90ce-62fb855de6c9.png)

**Comment by snowie2000** [comment]
不需要设置，无论你怎么设置，现在永远都是dw了

**Comment by super-keys** [comment]
> 不需要设置，无论你怎么设置，现在永远都是dw了

好的. 看来火狐只能备胎了.
感谢了!!!
