### ISSUE TITLE
Font Files locked when Mactype enabled

### ISSUE THREAD

**Issue by a0193143** [snowie2000/mactype#641]
Ran into a weird issue, I opened a font file, but not install, closed the font viewer, and the font file locked cannot be deleted.

I'm using service mode, stop the Mactype service and the font file can be deleted just fine.

Is this fixable?

**Comment by snowie2000** [comment]
It's a really old bug and has been fixed for years. It shouldn't happen. I have no idea what's gone wrong...

**Comment by a0193143** [comment]
> 
> 
> It's a really old bug and has been fixed for years. It shouldn't happen. I have no idea what's gone wrong...

Sorry, my fault, I confused with old version's situation.

Now the issue is, I installed some new fonts, just install not using in any programs, when deleting these fonts, the message shows the fonts is being using and cannot delete.
