### ISSUE TITLE
When UseInclude=1,vscode will take up high cpu

### ISSUE THREAD

**Issue by LarkinZero** [snowie2000/mactype#643]
设置UseInclude=1时，将vscode放到白名单中，会造成VScode启动后有个code.exe进程占用25%左右的CPU，并且vscode会卡死，最终提示需要重新加载窗口。
```
[IncludeModule]
Code.exe
```

**Comment by snowie2000** [comment]
You should try to avoid using the include mode.  this more is not heavily tested.
