### ISSUE TITLE
matlab 中乱码

### ISSUE THREAD

**Issue by potoo0** [snowie2000/mactype#645]
## 1. 问题：
matlab乱码，在文件地址栏(图中红色区域)、文件管理(图中绿色)、变量工作区(图中橘色)的中文英文均有乱码，编辑器和命令行(图中黑色)英文没有乱码中文乱码，如下图1所示。
![image](https://user-images.githubusercontent.com/34411681/77761648-54887380-7073-11ea-9fa5-61717674d9b9.png)
*图1 matlab乱码情况*

## 2. 我的环境：
- os: win10 专业版 1903 - 18362.535
- 屏幕分辨率:	1920 x 1080
- MacType版本:	2019.1 
- MacTray版本:	1.0.2019.1
- MacTuner版本:	1.0.2.361
- Mactype 字体：XHei Intel（如下图2）

![image](https://user-images.githubusercontent.com/34411681/77761085-6ae1ff80-7072-11ea-91d3-81b85ef600e2.png)
*图2 XHei Intel 字体*

**Comment by potoo0** [comment]
如果您有时间的话麻烦解答下，谢谢啦

**Comment by snowie2000** [comment]
请不要替换字体

**Comment by potoo0** [comment]
我不太明白... :)
不要替换字体？是指 matlab 中不支持这个 *XHei Intel* 字体吗？还是 matlab 不支持大部分字体呢？

**Comment by snowie2000** [comment]
你使用的配置是一个热替换字体的配置文件，热替换字体就是有可能乱码的

**Comment by potoo0** [comment]
好的，谢谢，我试试其他字体。
