### ISSUE TITLE
MacType导致安装Excel Tab插件的Excel崩溃

### ISSUE THREAD

**Issue by reaCodes** [snowie2000/mactype#652]
安装了Excel Tab插件的Excel是可以正常打开的，也可以渲染，但是每次用到Excel Tab插件，Excel就会崩溃，例如点Excel Tab的设置按钮，准崩溃。

请问这个问题如何解决？

**Comment by snowie2000** [comment]
你没有提供具体的excel版本和系统环境。并且我没有找到excel tab是什么软件。

在这种情况下，你可能需要按照 https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm 的步骤开启崩溃时创建minidump的功能，然后把dump传上来

**Comment by reaCodes** [comment]
@snowie2000 有点大，不好上传，做成了压缩包
Excel版本和系统环境在里边

[EXCEL.EXE.8372.zip](https://github.com/snowie2000/mactype/files/4501060/EXCEL.EXE.8372.zip)

**Comment by snowie2000** [comment]
Not found。无法下载

**Comment by reaCodes** [comment]
@snowie2000 请从这个地址下载，[<下载地址>](http://47.98.145.97:8080/)

**Comment by reaCodes** [comment]
![image](https://user-images.githubusercontent.com/13817254/79713133-691cfc00-82ff-11ea-8f64-60c631ca63a1.png)
貌似这边有 点问题

**Comment by snowie2000** [comment]
Oops

This site can’t be reached47.98.145.97 refused to connect.

**Comment by reaCodes** [comment]
不好意思，我发到你的`mactype.feedback@gmail.com`邮箱了

**Comment by snowie2000** [comment]
可以看到崩溃发生在OfficeTabLoader64.dll中，但是由于我没有在网上找到这个文件，所以这个dump的其他信息完全看不到。

**Comment by snowie2000** [comment]
经过分析，这个问题的原因在于officetab这个软件经过了混淆和加密，为了防止被分析，内部动态复制了部分系统API的代码来进行模拟和反跟踪，这个直接导致了和MacType的hook不兼容。

实际上本质上说是officetab使用的技术存在问题。这个问题在新版本的officetab已经不存在了。
如果你要继续使用当前版本，你可以在配置文件中添加
```
[general@winword.exe]
HookChildProcesses=0
```
来关闭部分hook，解决兼容性问题。

由于officetab技术上的问题，这个问题无法用其他方法解决。

**Comment by reaCodes** [comment]
你好，我使用的是最新版本的officetab，但是还是有这个问题

**Comment by snowie2000** [comment]
这个问题是因为officetab使用了一些比较复杂的反调试技术，这些技术的特性就是很容易导致和hook不兼容。我们不可能对这种技术做太多的支持，因为反调试技术五花八门，放弃现有的hook方式的话我们暂时也没有更好的办法来接管windows字体渲染。

你可以用我刚才提供的配置来绕过去。

**Comment by reaCodes** [comment]
请问这个设置有什么其他的影响

**Comment by snowie2000** [comment]
这个一个仅针对word的配置，所以没有别的影响。

如果你要全局使用的话，这个设置将导致MacType不能hook子进程。常见的影响就是不能第一时间渲染新的进程，另外将不能渲染chrome等大多数多进程浏览器。

关闭这个设置会让MacType不再hook CreateProcessInternalW这个API。具体officetab为什么会和这个hook冲突的问题比较复杂，你可以搜索反调试，API模拟等文章了解。
