### ISSUE TITLE
WmiPrvSE.exe (WMI Provider Host) CPU consumption abnormally raised

### ISSUE THREAD

**Issue by wmjordan** [snowie2000/mactype#653]
I was tweaking the INI configurations recently.
I encountered this issue after reloading INI files with MacTray.

Here are the reproduction steps:
1. Start MacType via service.
2. Launch MacTray.exe and change the start up mode to _Load with MacTray_ (without Administrator privilege).
3. Edit and save an ini file. (I was comparing various `HintingMode`s)
4. Right click the MacTray icon in the notification area and choose the above config from the menu items.
5. Repeat step 3 and 4 for several times. (Between each reload, I changed the `HintingMode` in the ini file)
6. The average CPU consumption WmiPrvSE.exe will rise from less than 2% to more than 10%.
7. The consumption would remain high even after MacTray.exe is exited. Switching launch mode from MacTray to service can tame the CPU usage of the WmiPrvSE.exe process back to normal.

If I restarted the Windows Management Instrumentation service, WmiPrvSE.exe was disappeared from the process list, but MacType seemed to be working properly still.

Windows 10, 1809.
MacType beta6.

**Comment by snowie2000** [comment]
Look like you re-raised an issue that you have already raised long ago: #504

**Comment by snowie2000** [comment]
Plus, it makes no sense if the CPU usage stays high after mactray exit. When mactray exits, all the WMI resources it requested will be released.

**Comment by wmjordan** [comment]
I don't think they are the same.

In that issue, the CPU consumption peaked and then dropped, again and again.
In this issue, after step 5, the consumption remained high.

**Comment by wmjordan** [comment]
I have not encountered #504 any more after upgrading to beta6.

**Comment by snowie2000** [comment]
> If I restarted the Windows Management Instrumentation service, WmiPrvSE.exe was disappeared from the process list, but MacType seemed to be working properly still.

this is impossible. MacType can still work without WMI, but its "process capture" function won't work.  (which means if you start a process from a "non-mactyped" parent process, it won't get captured and rendered)

I'll check if I did release wmi request on config reload.

**Comment by wmjordan** [comment]
> if you start a process from a "non-mactyped" parent process, it won't get captured and rendered

You are right.

I found that the new instance of Task Manager (taskmgr.exe) no longer got rendered after that, until the MacType service was restarted and WmiPrvSE.exe process emerged again.

**Comment by snowie2000** [comment]
Ok, problem confirmed.
I did forget to stop the previous wmi eventsink when reloading profiles (and created a new one).

Thanks!

**Comment by wmjordan** [comment]
I found some event logs which occurred when the CPU consumption remained high in the Windows Event Viewer/WMI-Activity:

> Id = {00000000-0000-0000-0000-000000000000}；ClientMachine = WMJ；用户 = WMJ\WMJ；ClientProcessId = 1244；组件 = Core；操作 = Start IWbemServices::ExecNotificationQuery - ROOT\CIMV2 : SELECT * FROM __InstanceCreationEvent WITHIN 1 WHERE TargetInstance ISA 'Win32_Process'；ResultCode = 0x800706BA；PossibleCause = Could not send status to client
> Id = {00000000-0000-0000-0000-000000000000}；ClientMachine = WMJ；用户 = WMJ\WMJ；ClientProcessId = 1244；组件 = Unknown；操作 = Start IWbemServices::ExecNotificationQuery - ROOT\CIMV2 : SELECT * FROM __InstanceCreationEvent WITHIN 1 WHERE TargetInstance ISA 'Win32_Process'；ResultCode = 0x80041032；PossibleCause = Unknown

**Comment by snowie2000** [comment]
> I found some event logs which occurred when the CPU consumption remained high in the Windows Event Viewer/WMI-Activity:
> 
> > Id = {00000000-0000-0000-0000-000000000000}；ClientMachine = WMJ；用户 = WMJ\WMJ；ClientProcessId = 1244；组件 = Core；操作 = Start IWbemServices::ExecNotificationQuery - ROOT\CIMV2 : SELECT * FROM __InstanceCreationEvent WITHIN 1 WHERE TargetInstance ISA 'Win32_Process'；ResultCode = 0x800706BA；PossibleCause = Could not send status to client
> > Id = {00000000-0000-0000-0000-000000000000}；ClientMachine = WMJ；用户 = WMJ\WMJ；ClientProcessId = 1244；组件 = Unknown；操作 = Start IWbemServices::ExecNotificationQuery - ROOT\CIMV2 : SELECT * FROM __InstanceCreationEvent WITHIN 1 WHERE TargetInstance ISA 'Win32_Process'；ResultCode = 0x80041032；PossibleCause = Unknown

That's because I forgot to stop the previous eventsink and the receiver is not there anymore when the WMI tries to send me an event.

**Comment by AbraxasVi** [comment]
try this:
https://palvelimet.net/wmi-provider-host-wmiprvse-exe-using-high-cpu-because-of-check_mk_agent-reset-wmi-performance-counters/

at least, it works on my computer, with win10 1909 and beta6

**Comment by wmjordan** [comment]
> That's because I forgot to stop the previous eventsink and the receiver is not there anymore when the WMI tries to send me an event.

Has this bug been fixed in the RC version?

**Comment by wmjordan** [comment]
Has this bug been fixed in the RC2?

**Comment by snowie2000** [comment]
~~I am not completely sure, cuz it never happened on my system, but it did fix some problems with the WMI event sink which might help.~~

Oh, I thought you were asking about the CPU usage problem.

Yes, the event sink problem should be fixed in RC2 and it should work in almost all cases unless WMIPrvse.exe is killed abnormally. Stop/restart the WMI service should be fine.

**Comment by wmjordan** [comment]
Thanks for answering. Great! I will keep an eye on it.

**Comment by wmjordan** [comment]
I monitored the CPU and memory usage of the WmiPrvSE.exe process and confirmed that this bug was fixed in the RC2.
