### ISSUE TITLE
Telegram Desktop v2.1 无法替换字体

### ISSUE THREAD

**Issue by Gokou-Ruri** [snowie2000/mactype#655]
在我和朋友的电脑上均如此，系统版本是LTSC2019 x64，具体是哪个telegram版本开始这样我不清楚，但是我记得v1.8.15仍旧可以替换字体的。
顺带一提似乎连那个[TG-FONTS](https://github.com/TG-Techie/TG-Fonts)项目也无法替换字体了。

**Comment by snowie2000** [comment]
其实是可以的，但是telegram似乎是有我还没有发现的字体检测，他能发现你更改了字体，从而切换到备用字体，所以你需要同时替换多个字体才行。
![tg](https://user-images.githubusercontent.com/11767189/80601396-596c8880-8a60-11ea-88bb-16357483e42f.png)
```
微软雅黑=方正舒体
SimSun=方正舒体
PMingLiu=方正舒体
```

**Comment by snowie2000** [comment]
经过检查，telegram会调用GetFontData来判断字体是否被替换，发现被替换后会创建备用字体。所以如上一个回复，你必须替换掉所有备用字体，强制telegram按照你的要求创建字体。

GetFontData方法目前无法被模拟。

**Comment by Gokou-Ruri** [comment]
> ```
> 微软雅黑=方正舒体
> SimSun=方正舒体
> PMingLiu=方正舒体
> ```

@snowie2000 感谢您的回复！我看了下，我的配置文件里本身就包含了这三种字体的替换，但是我这边却替换不了。
然后我试着把ini精简了一下，删掉了很多其它字体，只替换这三种字体，重启telegram后发现依旧无法替换。
精简后的ini我上传了，不过后缀名改成了txt，可以请您帮忙看看吗？
[宋体.txt](https://github.com/snowie2000/mactype/files/4560671/default.txt)

Mactype版本：
`ApplicationVersion=2019.1-beta6`
服务渲染和注册表渲染我都试过了。
![image](https://user-images.githubusercontent.com/26711804/80748626-cca4f600-8b57-11ea-94f3-f919464c351d.png)

**Comment by Gokou-Ruri** [comment]
补充：我发现在telegram中，“等宽”样式的字体实际显示为被替换后的样式（不是精简后的ini文件），而其它样式则仍然没有被替换。
