### ISSUE TITLE
装了以后无法打开任何其他软件 只能用chrome浏览器

### ISSUE THREAD

**Issue by cmliaoied** [snowie2000/mactype#661]
并且 点开 开始栏 以后，必须自己手动再点击才会关闭 否则就一直打开 但是点里面任何程序都无法launch   （求解 感激）

**Comment by snowie2000** [comment]
无解，和你系统中的其他软件冲突了
chrome有沙盘，其他软件进不来就没问题

只能自己一个个试

**Comment by cmliaoied** [comment]
好的 谢谢
