### ISSUE TITLE
Conflict with the game

### ISSUE THREAD

**Issue by iAndyPC** [snowie2000/mactype#662]
After I installed this program, Call of Duty Modern Warfare 2019 stopped working.

**Comment by sticsk** [comment]
I was about to open the same issue, I was actually amazed that I have to turn off MacType to make CoD : MW working.

I wonder what's causing this the problem

**Comment by snowie2000** [comment]
It's always a bad idea to use MacType on games.

MacType heavily relies on API hooks which are the top target of most anti-cheat systems and may conflict with some anti-debug mechanisms.

**Comment by Skyyblaze** [comment]
Add these two entries under [UnloadDLL] in MacType.ini

ModernWarfare.exe
Modern Warfare Launcher.exe

the restart the MacType service and the game will work again.

**Comment by fishstik** [comment]
For Call of Duty Warzone I also had to add `bootstrapper.exe` to the `[UnloadDll]` section.
