### ISSUE TITLE
任务栏渲染问题 Taskbar rendering issues

### ISSUE THREAD

**Issue by Rereyuop** [snowie2000/mactype#672]
![image](https://user-images.githubusercontent.com/56964252/85942955-68d45900-b95f-11ea-97bd-7b2ac67e955a.png)
中文输入法的「中」字变成白色方格
正常情况下是这样↓
![image](https://user-images.githubusercontent.com/56964252/85943055-1b0c2080-b960-11ea-9931-76d6de8a7c44.png)
之前也没有这种情况，有可能是配置文件或者是我之前添加的实验性dll所为，总之有点蛋疼。

**Comment by snowie2000** [comment]
实验性dll 是什么东西……

**Comment by Rereyuop** [comment]
> 实验性 dll 是什么东西……

有视频介绍 Patch 项目。把两个 dll 文件放到根目录里去，说这样可以把 UWP 也渲染上，18年的视频了，现在没作用。额，然后我对照着其他的配置文件写法改了改，把 ForceChangeFont=Sarasa Gothic SC 这行删掉就好了。啊...汗
