### ISSUE TITLE
Titlebars not rendered anymore

### ISSUE THREAD

**Issue by kcohar** [snowie2000/mactype#678]
Hi, I've noticed that, since updating to Windows 10 2004 (19041.388), my titlebars don't get rendered using MacType in Registry mode anymore. For example, in Notepad:
![image](https://user-images.githubusercontent.com/47360019/88465182-c7fd8e80-ce75-11ea-95f0-f01b29f7c006.png)
mpv:
![image](https://user-images.githubusercontent.com/47360019/88465190-cdf36f80-ce75-11ea-9d1f-ac9df0fbeff6.png)
vlc:
![image](https://user-images.githubusercontent.com/47360019/88465194-d481e700-ce75-11ea-8b47-d570bdca682a.png)
The titlebar seems to be using ClearType.

But they are rendered in File Explorer's titlebar for example:
![image](https://user-images.githubusercontent.com/47360019/88465205-f8ddc380-ce75-11ea-8cbb-8d5a6c46f53a.png)

**Comment by 13-beta2** [comment]
> titlebars don't get rendered using MacType in Registry mode anymore

A lot of statics seems "broken" since version 2004 but titles work fine in my case.
Did you checked permissions for DWM user?

**Comment by kcohar** [comment]
I've been having issues with 2004, so I installed an earlier build of Windows and it works now.
It could have been an issue with my setup, not with MacType - I'll check 2004 again and write back in a couple of days (been busy lately :/)

Do you experience this issue?

**Comment by sammilucia** [comment]
mine hasn't updated to 2004 yet and I'm absolutely finnneee with that 😂. I thought about forcing it but yep I think I'll leave it. I'd be interested if anyone's MacType on 2004 is working.

**Comment by snowie2000** [comment]
I have just moved my system to Windows 10 (Windows 2019 LTSC to be precise), and I have encountered some of the problems reported. 

I'm already on them now and let's see what I can make at last.

**Comment by kcohar** [comment]
Y'know it's funny I installed LTSC too (and the cumulative update for July) and MacType runs great :D No titlebar glitches.
I'm gonna try installing 2004 again to see if anything pops up.

**Comment by snowie2000** [comment]
> Y'know it's funny I installed LTSC too (and the cumulative update for July) and MacType runs great :D No titlebar glitches.
> I'm gonna try installing 2004 again to see if anything pops up.

The first pop up thing you're going to see after your installation is Windows update.
For sure.😝

**Comment by kcohar** [comment]
Of course, at least initially :D 
Ironically, after blocking Windows Update (with NetLimiter) for a while, it won't update anymore. So much for forced updates 😆

**Comment by snowie2000** [comment]
I have been updated at least 4 times in the first week of my installation.
It's a Windows Update 10 instead of Windows 10 for me.

**Comment by kcohar** [comment]
Ouch...

**Comment by kcohar** [comment]
False alarm. I just installed 2004 and it works now. Something was probably wrong with my setup.

**Comment by sammilucia** [comment]
Thanks for confirming @kcohar 😊

**Comment by LoganDark** [comment]
On 2004 and titlebars don't render with mactype. Using registry installation method and dwm.exe is not in the MacType.ini blacklist
