### ISSUE TITLE
楷体_GB2312、仿宋GB_2312加粗后显示异常

### ISSUE THREAD

**Issue by VG-Loda** [snowie2000/mactype#686]
老问题，楷体_GB2312和仿宋GB_2312适配不好，普通国标字体没问题，加粗后显示模糊。
具体见下图：
![image](https://user-images.githubusercontent.com/34614839/94329611-29191e00-ffef-11ea-91fe-250cb291b1cb.png)

**Comment by snowie2000** [comment]
这是这些衬线字体和Freetype兼容性问题。在freetype解决这些问题之前无解。

**Comment by johnsteveabc** [comment]
那是字体本身的问题，没开mactype那两个字体加粗也这样
