### ISSUE TITLE
mactype渲染qbit会导致系统严重卡顿+右键空白+重命名看不到预览。

### ISSUE THREAD

**Issue by lisansas** [snowie2000/mactype#697]
已解决，解决方法：将qbit加入mactype的排除列表。

提交这个issues的问题是方便一下有同样问题的人，以及想问问作者为什么这样，按理说qbit作为一个bt下载软件，不至于有这么大的威力吧。

**Comment by snowie2000** [comment]
这不太可能………

**Comment by lisansas** [comment]
我又测试了一下，只有将qbit在兼容性里面勾选使用管理员模式运行才会出现这个状况，不勾选则不会。

**Comment by snowie2000** [comment]
那么我可以推测qbit在启动后很可能使用了全局hook，非管理员没那么大权限所以影响不大。

**Comment by sym233** [comment]
我也觉得qbit很卡，经常无响应，排除一下试试看

**Comment by snowie2000** [comment]
下载了最新版qb进行了测试，无论是否管理员运行均没有发生任何奇怪的事情。
请附上配置文件和mactype的启动方式。

**Comment by lisansas** [comment]
> 下载了最新版qb进行了测试，无论是否管理员运行均没有发生任何奇怪的事情。
> 请附上配置文件和mactype的启动方式。

是hashtab的原因 卸载了hashtab就没问题了
