### ISSUE TITLE
Chrome registry edit (RendererCodeIntegrityEnabled = 0) no longer valid

### ISSUE THREAD

**Issue by kcohar** [snowie2000/mactype#698]
Hey guys

So, a botched Windows Update forced me to reset my PC and I installed a fresh build of Chromium (86.0.4240.183) onto a fresh build of Windows 10 (20H2). The registry string RendererCodeIntegrityEnabled = 0 (DWORD) doesn't work anymore, not in HKLM or in HKCU. It works if I run the executable (or edit the shortcut) and append --disable-features=RendererCodeIntegrity.

I think Snowie mentioned a while back there was a different way of getting Chromium (and its derivatives) to run MacType, without the need to resort to disabling features. Is there any way we're going to be able to use that method instead?

**Comment by snowie2000** [comment]
In issue #488 I've uploaded a new bootstrap and it should work for Chrome in Windows 10 without any further setup.
https://github.com/snowie2000/mactype/issues/488#issuecomment-714879581

**Comment by kcohar** [comment]
Awesome!

Chromium and its other derivatives (Edge) too?
This'll be included in the next MacType release?

**Comment by snowie2000** [comment]
Yes, all the chromium derivatives should work with the new loader and yes, it will be included. 

Does it work for you?

**Comment by kcohar** [comment]
Yes! It works perfectly, no more registry or shortcut editing, ah so
refreshing.

So sorry to bother you with this, thanks for the link :D
