### ISSUE TITLE
优酷视频客户端渲染效果很差，但是能替换字体

### ISSUE THREAD

**Issue by oahnaLiew** [snowie2000/mactype#700]
优酷视频客户端渲染效果很差，但是能替换字体。

还有一些其他的软件（比如迅雷）也是一样的状况。

win10 2004，注册表加载。

![QQ截图20201121025622](https://user-images.githubusercontent.com/26448604/99839397-9c7d7d00-2ba5-11eb-8c0c-3c803f7820c1.png)

**Comment by oahnaLiew** [comment]
竟然是 [DirectWrite] RenderingMode=0 的问题，改成 5 就好了。。默认的选项那么拉胯的吗。。。

**Comment by snowie2000** [comment]
这个值的默认值是5。你的配置文件可能是别人改的。

具体的值参考 https://github.com/snowie2000/mactype/wiki/RenderingMode

简单来说5=Nohinting, 0=Windows默认。
