### ISSUE TITLE
IDEA 2020.2.3 中左右 Tool window bars 字体渲染异常

### ISSUE THREAD

**Issue by eldicn** [snowie2000/mactype#701]

**Comment by snowie2000** [comment]
旋转文字不支持。
这类文字的绘制属于坐标系转换后进行绘制。Windows允许对坐标系进行各种转换，包括旋转和扭曲，可以旋转任意角度，在这桩情况下绘制好看的文字十分困难。freetype没有现成的方法可以支持，还是交给Windows自己处理比较好
