### ISSUE TITLE
绿屏死机，怀疑与 MacType 有关

### ISSUE THREAD

**Issue by oahnaLiew** [snowie2000/mactype#704]
使用 CentBrowser 看视频时，电脑经常绿屏死机。
之前一直以为是显卡驱动和浏览器内核版本的问题，因为使用 Edge 和 Cent 新内核版本时，绿屏的概率会降低，但偶尔还是会有。
Cent 的论坛上有人说，绿屏可能与 MacType 有关，并让我添加启动命令行 --num-raster-threads=1，但是效果并不明显。
今天重启资源管理器时（从某个 Windows 版本开始，必须重启一下资源管理器才能替换任务栏的字体），也突然绿屏死机了。
所以怀疑绿屏死机还是和 MacType 有关。

**Comment by ddzy** [comment]
我 win10-1909 一直蓝屏

**Comment by rpzone** [comment]
Do not use **registry mode**, service mode is working well on 19042.630 and above windows version.
