### ISSUE TITLE
Latest build

### ISSUE THREAD

**Issue by iamr8** [snowie2000/mactype#707]
Hi! Can you please make a new build of MacType based on last changes ?

**Comment by TabrisKing** [comment]
谁能帮忙编译一个？

**Comment by wmjordan** [comment]
There's a [build compiled in October here](https://github.com/snowie2000/mactype/issues/488#issuecomment-714879581).
Unzip it into the MacType folder.

**Comment by TabrisKing** [comment]
前两天又更新了啊

**Comment by wmjordan** [comment]
> 前两天又更新了啊

Don't treat it seriously. It simply dealt with comments in the code.
