### ISSUE TITLE
一個神奇的問題

### ISSUE THREAD

**Issue by htwong737** [snowie2000/mactype#713]
我把SecretProject-RGB_Larger改名成SecretProject-RGB_larger後，需要刷新才能顯示更改後的，但未刷新前再按改名顯示的是正確的。
把文件從E:/Library複製到Downloads後就沒這個問題，E:/有問題，F:/沒問題，D:/沒問題。
把SecretProject-RGB_Larger改名成SecretProject-RGB_Large，沒問題，
把SecretProject-RGB_Larger改名成SecretProject-RGB_LargeR，有問題。
我之前在這個盤裏裝過很多次linux（現在沒了），在win10下用過很多次diskpart洗盤，重加回分區，請問以下有沒有可能管這個事？

**Comment by htwong737** [comment]
我剛剛又洗了一次，還是這樣，我試試改一下盤符。

**Comment by htwong737** [comment]
補充一下：把SecretProject-RGB_Larger改名成SecretProject-RGB_LarGG.png，沒問題。

**Comment by htwong737** [comment]
我把盤符從E改成P就沒問題了！

**Comment by htwong737** [comment]
不知道是關win10事還是mactype，或是其他

**Comment by htwong737** [comment]
我用的是service mode

**Comment by htwong737** [comment]
等等，我進到Library文件夾似乎還是這樣，只是根目錄和根目錄下其他文件夾裏似乎沒事

**Comment by htwong737** [comment]
破案啦！！！我把資源管理器查看方式從large icons改成details，就沒問題了！！！！

**Comment by htwong737** [comment]
我在我自己的筆記本上，沒用mactype也發現了這個問題。

**Comment by htwong737** [comment]
甚至我爸的電腦我也發現了這個問題......請問一下在您的電腦是不是也有？這是正常的嗎？

**Comment by snowie2000** [comment]
这是完全正常的，因为windows的NTFS格式是一个档案名大小写不敏感的档案系统，修改大小写是会被忽略的，但是拷贝到另一个盘符就不会了。

Linux常用的ext？系列的档案系统是一个大小写敏感的系统，所以不会出现这个问题。

**Comment by htwong737** [comment]
謝謝！但神奇的是把文件查看方式從large icons改成details就沒問題了，我覺得這可能是bug吧，應該不會那麽神奇的吧。

**Comment by snowie2000** [comment]
Windows作業系統對檔案名和圖示有一些奇怪的緩存機制，這應該屬於feature~

**Comment by htwong737** [comment]
謝謝！
