### ISSUE TITLE
MacType64.dll is either not designed to run on Windows or contains an error

### ISSUE THREAD

**Issue by ghost** [snowie2000/mactype#726]
Starting MacType process, ProcessHacker (https://processhacker.sourceforge.io/) outputs error from attached image.
![U55SlkMX9k](https://user-images.githubusercontent.com/47119623/109398603-3c356e80-793e-11eb-9b58-0288cd001537.png)

What could be the issue here and how to fix it?

**Comment by snowie2000** [comment]
0xc0000428 means the digital signature of a file is invalid and mactype doesn't even have that.

**Comment by ghost** [comment]
> 
> 
> 0xc0000428 means the digital signature of a file is invalid and mactype doesn't even have that.

Do you have any plans to add one?

**Comment by snowie2000** [comment]
> > 0xc0000428 means the digital signature of a file is invalid and mactype doesn't even have that.
> 
> Do you have any plans to add one?

No. You need a company to apply for a codesign. I don't think the signature check of the process hacker is forced.

**Comment by ghost** [comment]
> 
> 
> > > 0xc0000428 means the digital signature of a file is invalid and mactype doesn't even have that.
> > 
> > 
> > Do you have any plans to add one?
> 
> No. You need a company to apply for a codesign. I don't think the signature check of the process hacker is forced.

Thanks snowie
