### ISSUE TITLE
部分网页符号有乱码

### ISSUE THREAD

**Issue by istonel** [snowie2000/mactype#727]
比如淘宝：
![image](https://user-images.githubusercontent.com/65379227/110432913-c1611600-80ea-11eb-8b73-bf9687284ac2.png)

Chrome浏览器没有此问题：
![image](https://user-images.githubusercontent.com/65379227/110433131-0b49fc00-80eb-11eb-8683-7063ca9e9bde.png)

操作系统是Windows 10 20H2
浏览器是Maxthon5
请问有解决办法吗？

**Comment by snowie2000** [comment]
不要替换字体。淘宝的>使用的是webfont，强制替换字体当然会乱码。

**Comment by istonel** [comment]
谢谢您，我把系统字体和浏览器字体都替换为XHei_Solid了，是不是XHei_Solid字体缺少字符的原因？

**Comment by snowie2000** [comment]
永远不要强制指定字体。webfont使用自己符号，任何字体都无法替代他们。

**Comment by istonel** [comment]
谢谢您，另外微信电脑版聊天框里字体没渲染是啥原因呀？

![image](https://user-images.githubusercontent.com/65379227/110434435-c6bf6000-80ec-11eb-95c3-dc6af9559c7c.png)

**Comment by snowie2000** [comment]
抱歉我没看出来哪里没有渲染，请关掉mactype做一下对比。

**Comment by istonel** [comment]
不对，不是没渲染，是没有替换

**Comment by snowie2000** [comment]
首先，替换并不总是可行的，在部分情况下，mactype会无法替换，例如程序在被mactype捕获前已经创建好了字体，或者程序使用了stock字体，这种情况下替换就不可能了。也有可能是程序使用了另一种长得很像雅黑的字体，例如Segoe UI

**Comment by istonel** [comment]
有点强迫症了，确实日常使用无影响，再次感谢您！
