### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Antiever** [snowie2000/mactype#728]
Where can I find [this file](https://github.com/snowie2000/mactype/blob/999790b93b39d96545860cbc20d5b79dda62907b/hook.cpp#L28)? (`freetype/ftenv.h`)

It's not part of mactype or Freetype but `INFINALITY` require...

**Comment by snowie2000** [comment]
I don't remember where the file came from. It was there back on year 2018, this is the content of it:
```
#include <freetype/config/ftstdlib.h>
#include <freetype/config/ftconfig.h>

FT_EXPORT_DEF(void) FT_initEnv();

FT_EXPORT_DEF(void) FT_freeEnv();

FT_EXPORT_DEF(void) FT_PutEnv(const char* key, const char* value);

FT_EXPORT_DEF(void) FT_DelEnv(const char* key);

const char* FT_GetEnv(const char* key);
```

**Comment by Antiever** [comment]
Thanks!
