### ISSUE TITLE
manual loading howto not clear enough

### ISSUE THREAD

**Issue by xuijuthub** [snowie2000/mactype#730]
mactype wizard tells user that you can load mactype into a program by dragging the programs icon into the mactray gui.
issues:
1) running windows 7 mactray exe loads mactype for all programs, using disable option, have to reboot computer
2) cannot drag and drop into mactray gui, neither .lnk nor .exe of chromium.exe

tried macloader64.exe, told need to drag exe, made a shortcut to pass it as argument, program runs, but no effect.
started mactype wizard, then it worked (or was it applied to all programs?:S)

it is hard to understand the mechanism behind this. simple new users definitely would feel mislead many times. mactype needs a better description for simple uses. (by the way, applying to all programs seem to deny some programs working, so it is better that it is not applied to all by simple means.)

**Comment by snowie2000** [comment]
There is a mistake in the description. You need to drag the application (program icon) to the macloader.exe or macloader64.exe to make it work, not the mactype wizard gui or any other Window.

Macloader.exe is only capable of handling x86 executables while macloader64.exe is capable of both.

Shortcut files work with loaders as they will be parsed to their real destinations. (but the shortcut of msinstaller icons will not)
