### ISSUE TITLE
MacType is causing Edge browser to crash due to CET

### ISSUE THREAD

**Issue by bhkumar007** [snowie2000/mactype#731]
After installing MacType in Standalone mode, Edge browser crashes. Looks like it is caused by MacType doing return address hijacking from gdi32full.dll

The issue is for Edge 90.*, 91.* builds on machines running Intel TigerLake processors as these have CET (Control flow Enforcement Technology) enabled.

I see the error message in event viewer ->

Process '\Device\HarddiskVolume2\Program Files (x86)\Microsoft\Edge Internal\Application\msedge.exe' (PID 6464) has encountered a shadow stack return address mismatch. The process will be terminated.
Process shadow stack strict mode: false
Appcompat options: 0x0
 
Return instruction executed from module '\Device\HarddiskVolume2\Windows\System32\gdi32full.dll'.
(Instruction address: 0x7ffe27b7e9bb, module offset: 0x1e9bb, module compatible with shadow stacks: true)
 
Attempting to return to module '(null)'.
(Instruction address: 0x7ffe295d0347, module offset: 0x0, module compatible with shadow stacks: false)

**Comment by snowie2000** [comment]
Hi, I'm actively solving the problem, however, I don't own a computer with a processor supporting it (CET or its variation).
Could you please upload the `gdi32full.dll` somewhere so I can inspect it and make more meaningful trials?

You can also mail the file to me for copyright concerns.

Thanks.

**Comment by bhkumar007** [comment]
gdi32full.dll is part of Windows Operating System so you should be able to access it from System32 folder

**Comment by snowie2000** [comment]
I know. But it differs in every version. And my version in my windows 10 doesn't match with the version you are using and doesn't support shadow stack so I have no way to figure out the actual error location.

**Comment by bhkumar007** [comment]
Ah, I thought you might have meant that way.  One thing I would like to point out is that the dll is not going to have any additional code for CET support but just an additional PE header bit. I am using windows Insider bits so not sure if I can share the binary directly(from the repro). Let me figure it out on my end and I will get back to you.

**Comment by bhkumar007** [comment]
Here is some additional information (no update on the binary sharing yet).

There is no crash if I run the browser under a debugger. Crash is in the crashpad-handler process as !peb shows

CommandLine:  '"C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe" --type=crashpad-handler

Also the call-stack points to only two frames

0:004> k
\# Child-SP          RetAddr               Call Site
00 00000096`0adfe678 00000000`00000050     gdi32full!GetStockObject+0x8b
01 00000096`0adfe6a8 00000000`00000000     0x50

Looks like the return address from GetStockObject is being overwritten with 0x50 on the stack?

**Comment by snowie2000** [comment]
I'm still learning about the CET internals. To my understanding, there should be `endbr32` or `endbr64` instructions added for far jmp and far calls so that the CPU IBT can trace, but... I didn't find anything useful when I recompile mactype with CETCompat on.

**Comment by snowie2000** [comment]
~Would you please kindly try mactype with the following file? I made a little adjustment to the hooking trampoline.
[Easyhk64_CET_test.zip](https://github.com/snowie2000/mactype/files/6283337/Easyhk64_CET_test.zip)~

PS: MacType detects debugger and disables mactype for programs being debugged. So with a debugger, you are pretty much running a program without MacType.

**Comment by bhkumar007** [comment]
No difference in behavior with the new binary. Windows doesn't support IBT from CET. It only checks for shadow stack return address mismatch. these instructions you pointed should be applicable for Linux.

I see the following warning log in the eventvwr, just before the error log

_**Process '\Device\HarddiskVolume2\Program Files (x86)\Microsoft\Edge Internal\Application\msedge.exe' (PID 4104) has encountered a shadow stack return address mismatch. The process will be allowed to continue execution because: the process is running in compatibility mode, and the mismatch occurred in a module that is not compatible with shadow stacks.
Process shadow stack strict mode: false
Appcompat options: 0x0

Return instruction executed from module '\Device\HarddiskVolume2\Program Files\MacType\MacType64.dll'.
(Instruction address: 0x7ffcca124831, module offset: 0x4831, module compatible with shadow stacks: false)

Attempting to return to module '(null)'.
(Instruction address: 0x7ffcdf9c0347, module offset: 0x0, module compatible with shadow stacks: false)**_

**Comment by snowie2000** [comment]
Sounds like the problem lies in the Mactype64.dll instead of eashk64.dll. Weird.
Which version of mactype64.dll are you using? Do you mind uploading it here? cuz I'm keeping messing up files and don't have all the different versions at hand.

**Comment by bhkumar007** [comment]
[MacType64.zip](https://github.com/snowie2000/mactype/files/6283938/MacType64.zip)

Here is the version of mactype64.dll that I have installed on my machine

**Comment by snowie2000** [comment]
Thanks. Got the problem. The trampoline of easyhook manipulated the stack and used ret as a jump.
I'll get back to you when it's ready. It shouldn't be too late next Monday.

**Comment by snowie2000** [comment]
[Easyhk64_CET_test2.zip](https://github.com/snowie2000/mactype/files/6285433/Easyhk64_CET_test2.zip)
Please give this patch a try. It should at least fix the problem your event viewer reported.

**Comment by bhkumar007** [comment]
Thanks @snowie2000 for the quick fix. I no longer see the crash with the patched binary

**Comment by bhkumar007** [comment]
@snowie2000: When is the latest one can expect a new release with the CET fixes?

**Comment by HugoPresents** [comment]
在 Chrome 下同样的报错，我用了上面的补丁也可以正常使用了 :)
