### ISSUE TITLE
Mactype does not work in Edge browser with Chromium core

### ISSUE THREAD

**Issue by ziranjiang** [snowie2000/mactype#732]
Is there any solution?

**Comment by chawyehsu** [comment]
Have you tried the workaround mentioned in the [wiki](https://github.com/snowie2000/mactype/wiki/Google-Chrome)?

**Comment by srisar** [comment]
Adding a command line shortcut didn't work for me, but adding the registry key did work. Try that.

**Comment by sammilucia** [comment]
closing as abandoned
