### ISSUE TITLE
Mactype changes a registry entry that causes application errors 0xc0000142 on ryzen 5600x and x570 chipset

### ISSUE THREAD

**Issue by skareel** [snowie2000/mactype#733]
I was using the intel 8700k before with a z390 motherboard and I just changed to a ryzen 5600x and a x570 chipset and I began having issues pop up with windows like "Application error 0xc0000142" on a variety of programs like cmd.exe, updaters for programs like battlenet and creative cloud, etc". I found out that mactype when turned to registry mode is changing this registry entry at this location to a 1 instead of a 0 and creates all of these issues. Even in photoshop if that is set to 1 instead of 0, the video card won't be detected. Here is the location:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\Windows\LoadAppInit_DLLs

I know its mactype changing this number because when I change the number back and forth from 1 to 0, it turns mactype registry mode on and off. If I set registry mode on mactype then all of these errors pop up. 

Do you have any idea on why this is happening? I want to use registry mode because it applies mactype to firefox when service mode doesn't and service mode has an issue as well with Call of Duty Black Ops Cold War where it will block the game from running if the mactype service is on. If I turn the service off, then the game runs again.

**Comment by snowie2000** [comment]
According to [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/win7appqual/appinit-dlls-in-windows-7-and-windows-server-2008-r2), LoadAppInit_DLLs is required to make AppInitDlls work after Windows 7.

I believe the problem is the same as #731 because of the enhanced protection introduced with the new CPU. I think the problem could be within the easyhook library mactype is using which hasn't been updated for quite a while.

**Comment by skareel** [comment]
Is there any way I can use mactype then in this case? I really like the program and used it in registry mode before and would like to do that again. I would use it in service mode but like I said it prevents some games from working and it doesn't apply mactype to firefox.

**Comment by digiant** [comment]
是的我也碰到同样的问题，ZEN3 5800X+MSI X570 UNIFY，WIN10 21H1 19043.906, 选择注册表模式没法进入系统，只能使用服务模式加载，但感觉服务模式优先级不如注册表模式高，有些界面无法渲染。

**Comment by snowie2000** [comment]
应该是和新cpu的安全特性不兼容，我正在研究。注册表模式将在下个版本被移除。

**Comment by ssssssbbb** [comment]
> 应该是和新cpu的安全特性不兼容，我正在研究。注册表模式将在下个版本被移除。

我对你的敬仰真是如滔滔江水,连绵不绝,又有如黄河泛滥一发不可收拾。

十二年老粉丝请求给注册表留个可选版本

**Comment by snowie2000** [comment]
The file in https://github.com/snowie2000/mactype/issues/731#issuecomment-816621955 seems to have fixed part of the CET compatible problem.
I will continue to improve it.

**Comment by snowie2000** [comment]
> > 应该是和新cpu的安全特性不兼容，我正在研究。注册表模式将在下个版本被移除。
> 
> 我对你的敬仰真是如滔滔江水,连绵不绝,又有如黄河泛滥一发不可收拾。
> 
> 十二年老粉丝请求给注册表留个可选版本

注册表模式依然是可用的，但将会以wiki教程的形式提供给高级用户。直接提供注册表会让大量用户使用，从而带来问题。

**Comment by TabrisKing** [comment]
听说有更新了，真是欣喜若狂啊。
