### ISSUE TITLE
能否为不同程序设置替换不同字体？

### ISSUE THREAD

**Issue by digiant** [snowie2000/mactype#734]
尊敬的开发者你好，
FontSubstitutes=1之后，现在只能全局替换成同一个字体，能不能为不同的程序设置替换不同字体？

谢谢！

**Comment by snowie2000** [comment]
你好，FontSubstitutes是一个替换开关，启用后可以在FontSubtitutes段中设置多种字体替换。
如果需要对不同程序使用不同的替换配置，你需要使用@语法。
```
[FontSubstitutes@程序exe名称]
内容...
```
可以对绝大多数段使用此语法。
需要使用程序exe的完整名称，例如notepad.exe，不需要包含路径。

**Comment by digiant** [comment]
好的谢谢，原来是支持的！
