### ISSUE TITLE
Mactype not working at all on Kate app

### ISSUE THREAD

**Issue by taprobane99** [snowie2000/mactype#737]
Kate is a great app on Linux, and in fact the default text editor on KDE.

On windows it doesn't seem to have any anti-aliasing at all!

Can anyone test their system with Kate and Mactype? Are there any workarounds to get Mactype working on this app?

https://www.microsoft.com/en-us/p/kate/9nwmw7bb59hw?activetab=pivot:overviewtab

**Comment by snowie2000** [comment]
Transcoded win32 store apps are known to have compatibility issues with mactype. 

I'll test it out tomorrow.

**Comment by snowie2000** [comment]
Just as I suspected, the standalone kate works perfectly with MacType while the kate from MS Store doesn't work at all.
![kate](https://user-images.githubusercontent.com/11767189/116171776-00e7ce00-a73c-11eb-9b4f-b5e14a933e18.png)

**Comment by taprobane99** [comment]
yes, i discovered that too! problem solved
