### ISSUE TITLE
Win32 Build错误：无法解析的外部符号 _InitWow64ext

### ISSUE THREAD

**Issue by me0106** [snowie2000/mactype#738]
环境如下：
> * winodw: 10.0.19041.964
> * VS 2019
> * freetype:2.10.4 ，freetype.lib (/MT) 

* x64可以生成dll。

按照之前的 [https://github.com/snowie2000/mactype/issues/366](url) ，freetype和mactype都是MT编译的。
依旧出现该错误:
![image](https://user-images.githubusercontent.com/22869648/116650424-a22c8980-a9b3-11eb-83a2-019d73aa0a4e.png)

对C++/VS2019不太熟，过程日志不太会搞。

**Comment by snowie2000** [comment]
你需要 wow64ext

**Comment by me0106** [comment]
![image](https://user-images.githubusercontent.com/22869648/116653519-f63a6c80-a9b9-11eb-8d64-ba7be5db063c.png)

应该是这些Lib吧，已经放啦

**Comment by me0106** [comment]
> 你需要 wow64ext

target 为x64 可以构建成功。

target为Win32情况下，我试着把`hook.cpp`的`InitWow64ext()`注释掉也能构建。

对这块很疑惑啊

**Comment by snowie2000** [comment]
你用的库是从我的repo拉的吗
别的库的不行

**Comment by me0106** [comment]
> 你用的库是从我的repo拉的吗
> 别的库的不行

是的，直接用的bin/下面的lib

**Comment by snowie2000** [comment]
> > 你用的库是从我的repo拉的吗
> > 别的库的不行
> 
> 是的，直接用的bin/下面的lib

不要使用直接提供的lib，从源代码重新编译。那些lib可能是很早以前的。

**Comment by me0106** [comment]
> > > 你用的库是从我的repo拉的吗
> > > 别的库的不行
> > 
> > 
> > 是的，直接用的bin /下面的lib
> 
> 不要使用直接提供的lib，从源代码重新编译。那些lib可能是很早以前的。

构建成功了，多谢大佬 :)
