### ISSUE TITLE
Security vulnerability found in FreeType 2.10

### ISSUE THREAD

**Issue by ghost** [snowie2000/mactype#739]
Since [the vulnerability](https://sourceforge.net/projects/freetype/files/freetype2/2.10.4/) has been found in FreeType, we need to update to version 2.10.4.

**Comment by sammilucia** [comment]
thank you @konan8205

**Comment by sammilucia** [comment]
I don't think this is going to be a likely attack vector on Windows, because malware creators probably won't expect FreeType to be running on Windows, however as best practice it should be addressed.

**Comment by snowie2000** [comment]
Mactype is not affected, but I've upgraded to the latest version anyways.
