### ISSUE TITLE
MacType与Chrome存在冲突，会导致Chrome 124错误

### ISSUE THREAD

**Issue by iruletheworld** [snowie2000/mactype#745]
Windows 10 专业版
版本号	20H2
操作系统内部版本	19042.985

Chrome 版本： 90.0.4430.212（正式版本） （64 位）

MacType版本： 2019.1-beta6

如果已经安装了Chrome，那MacType会导致Chrome不能启动。如果没有安装Chrome，那在安装过程会被提示Chrome 124错误，并且安装会失败。

试验过托盘模式和服务模式，都会引起以上错误。

**Comment by snowie2000** [comment]
应该是你用的是新的CPU导致的。
这个问题已经修复了，新的版本已经准备好，Samantha正在准备发布。

**Comment by iruletheworld** [comment]
CPU的确是新的，是AMD的5950X

**Comment by TabrisKing** [comment]
期待新版本

**Comment by FanhuaCloud** [comment]
期待新版本

**Comment by CurtisWong458** [comment]
> 应该是你用的是新的CPU导致的。
> 这个问题已经修复了，新的版本已经准备好，Samantha正在准备发布。

下个月儿童节发布吗？哈哈

**Comment by gcfkhy** [comment]
确实  在win10 19043版本下 google浏览器91版本  CPU R75800H 环境中 google浏览器打不开 vscode 终端报错 停用了 mac type就正确了

**Comment by JoveYu** [comment]
请问什么时候可以release，amd ryzen 5800 等待中

**Comment by liuweiisme** [comment]
请问新版本什么时候发布

**Comment by mmqmzk** [comment]
临时解决办法, 排除 Chrome: 用文本编辑器打开 ini, 在 UnloadDll 部分加入 Chrome.exe, 然后重启就行了.
