### ISSUE TITLE
如何替换任务栏图标？

### ISSUE THREAD

**Issue by HowardKwan** [snowie2000/mactype#746]
替换成自定义图标，或者替换成其他方案图标？
![屏幕截图 2021-05-26 221340](https://user-images.githubusercontent.com/82563029/119675597-c4f57500-be6f-11eb-9d0a-e64957312fcc.png)
![屏幕截图 2021-05-26 221358](https://user-images.githubusercontent.com/82563029/119675607-c757cf00-be6f-11eb-92ba-b6c241aa085a.png)

**Comment by snowie2000** [comment]
```
[General]
Icon=Path\to\icon\file,IconIndex
```
路径从ini文件夹开始，似乎是支持exe和dll的，我有点记不清了。索引从0开始

**Comment by HowardKwan** [comment]
> ```
> [General]
> Icon=Path\to\icon\file,IconIndex
> ```
> 
> 路径从ini文件夹开始，似乎是支持exe和dll的，我有点记不清了。索引从0开始

OK，我试试看，感谢雪大！
