### ISSUE TITLE
2021.1-RC1的MacTray.exe被卡巴斯基误报为病毒

### ISSUE THREAD

**Issue by iruletheworld** [snowie2000/mactype#751]
2021.1-RC1的 MacTray.exe 被卡巴斯基认为是 Trojan.Win32.Generic 。

虽然我知道这应该是误报，但麻烦看看有没有能够解决地方法？上一个版本不会导致误报。

**Comment by snowie2000** [comment]
这个没有办法的。时间长了自然会加入白名单
