### ISSUE TITLE
Google Chrome 运行时插件崩溃

### ISSUE THREAD

**Issue by Vstory** [snowie2000/mactype#755]
Windows: 21H1 19043.985
Chrome 版本：93.0.4530.5 dev （64 位）
MacType版本:	2021.1 
MacTray版本:	1.0.2021.1
MacTuner版本:	1.0.2.361
问题：我已添加了注册表项目和值，但是每次启动时，经常出现某某插件已停止运行。
为了解决问题，我尝试设置不处理 Chrome 进程，但是问题还是会出现。
除非，我彻底停用 MacType。

**Comment by snowie2000** [comment]
Mactype的版本是什么。
新版已经无需注册表。

**Comment by Vstory** [comment]
> Mactype的版本是什么。
> 新版已经无需注册表。

版本如下：
MacType版本:	2021.1 
MacTray版本:	1.0.2021.1
MacTuner版本:	1.0.2.361

**Comment by snowie2000** [comment]
请尝试ArmBreaker选项。

**Comment by Vstory** [comment]
> 请尝试ArmBreaker选项。

好的，谢谢。

> As of RC1, this option doesn't work in mactype.ini globally, you need to add it to your in-use profile.

这里的配置文件指的是用户的注册表吗？

**Comment by snowie2000** [comment]
MacType的配置文件。注册表的话会专门说明是注册表

**Comment by Vstory** [comment]
> MacType的配置文件。注册表的话会专门说明是注册表

谢谢

**Comment by Vstory** [comment]
![image](https://user-images.githubusercontent.com/20795557/121034685-c7e15580-c7df-11eb-91be-931adb20a2b9.png)
![image](https://user-images.githubusercontent.com/20795557/121034811-e7787e00-c7df-11eb-9dd3-2d8d600322ab.png)

此问题，还是偶尔出现。

**Comment by snowie2000** [comment]
抱歉但你似乎是唯一报告此问题的人。所以不太可能被解决，我也完全不能重现。

**Comment by Vstory** [comment]
😭
好的，谢谢

**Comment by Vstory** [comment]
已测试，问题来源 火绒安全软件。

Windows: 21H1 19043.1055
Chrome 版本：93.0.4542.2 dev （64 位）
MacType版本: 2021.1
MacTray版本: 1.0.2021.1
MacTuner版本: 1.0.2.361
ArmBreaker 值：2
启用的扩展：
![image](https://user-images.githubusercontent.com/20795557/122533975-ae000800-d054-11eb-8df7-68a2b313df2a.png)

![Snipaste_Snipper - Snipaste_2021-06-18_16-45-46](https://user-images.githubusercontent.com/20795557/122534055-be17e780-d054-11eb-9a5e-4ef1995c37eb.png)

经常崩溃的扩展程序：
Tab Muter、Tampermonkey、书签侧边栏、uBlock Origin

卸载火绒安全软件后，无论是在 MacType 中排除 Chrome，还是启用管理 Chrome 进程，均不在出现 Chrome 插件崩溃问题。

设备不使用火绒安全软件时：
将 ArmBreaker 设为 1 时，反复打开媒体网站，先前的静音标签页的扩展还是偶现崩溃。
将 ArmBreaker 设为 2 时，反复打开媒体网站，扩展不出现崩溃。

设备使用火绒安全软件时：
将 ArmBreaker 设为 1 或者 2 时，反复打开媒体网站或者任意网站，扩展插件随机性崩溃。

**Comment by snowie2000** [comment]
我猜测的原因是这样的。正常情况下，火绒其实无法加载到chrome中。￼￼但是启用armbreaker以后火绒可以加载进去了，但是火绒没有考虑过在Chrome的沙盘中运行的问题，于是执行了一些沙盘不允许的事情导致崩溃。

**Comment by Vstory** [comment]
火绒论坛提交了个帖子，回复说转交测试人员了。

**Comment by Vstory** [comment]
> 我猜测的原因是这样的。正常情况下，火绒其实无法加载到chrome中。￼￼但是启用armbreaker以后火绒可以加载进去了，但是火绒没有考虑过在Chrome的沙盘中运行的问题，于是执行了一些沙盘不允许的事情导致崩溃。

一语惊醒梦中人！
~~关闭此功能，则一切正常。~~

![image](https://user-images.githubusercontent.com/20795557/122564057-85d5d080-d077-11eb-8375-2026e78b739f.png)

**Comment by Vstory** [comment]
更新解决方案：

~~火绒安全软件 -> 安全设置（右上角菜单） -> 系统防护 -> 应用加固，
项目下，加固类型中取消勾选  浏览器。~~

~~火绒安全软件 -> 安全设置（右上角菜单） -> 系统防护 -> 浏览器防护，
项目下，取消勾选所有选项。~~

卸载火绒安全软件。
