### ISSUE TITLE
如何针对特定程序默认启用 Mactype ？

### ISSUE THREAD

**Issue by MarkImaginist** [snowie2000/mactype#756]
Win32 转制的 `QQ桌面版` 和 `Telegram` 经测试可以正常渲染，但每次使用都需要在进程管理中手动启用。如何针对这些软件默认启用 Mactype ？

**Comment by snowie2000** [comment]
你的配置文件存在问题，正常可以自动捕获。
另外所有转置版的程序都不能通过父进程自动加载。

**Comment by MarkImaginist** [comment]
> 你的配置文件存在问题，正常可以自动捕获。
> 另外所有转置版的程序都不能通过父进程自动加载。

我用的就是自带的 `XMac.LCD.HotShift@XHei(iOS^MacOS)` ，另外加上了 DirectWrite 。能帮忙看看哪里有问题吗？非常感谢。
[XMac.LCD.HotShift@XHei(iOS^MacOS).zip](https://github.com/snowie2000/mactype/files/6601787/XMac.LCD.HotShift%40XHei.iOS.MacOS.zip)

**Comment by snowie2000** [comment]
你在使用什么模式。￼

**Comment by MarkImaginist** [comment]
> 你在使用什么模式。￼

服务加载模式

**Comment by snowie2000** [comment]
发一下mactype.ini中的内容吧

**Comment by MarkImaginist** [comment]
> 发一下mactype.ini中的内容吧

[MacType.zip](https://github.com/snowie2000/mactype/files/6601867/MacType.zip)
