### ISSUE TITLE
"Access denied" while MacType running

### ISSUE THREAD

**Issue by saugstauberr** [snowie2000/mactype#758]
G'Evening,

I always get errors when MacType is running and I want to do something with NPM, Node.js or any other file. It always tells me "Access denied", but only when MacType is running.

Also it doesn't matter if it's on the exception list or not, it still claims the process.

Hopefully you can help me. I want to use MacType soon again.

With best regards,
Martin

**Comment by snowie2000** [comment]
I work with NPM every day and I've seen any kind of warning like that.

Can you provide me a screenshot or a sample of how the error looks like?

**Comment by saugstauberr** [comment]
Hey,

so to give you some more details: I was running in Service Mode and always except of 1 or 2 times when I typed in "npm i" or "node -v", it gave me this error: "Access denied".

I already made an issue on the Node GitHub, but then I've found out that it's an issue with MacType.

**Comment by sammilucia** [comment]
hi @ItsMartin030. what antivirus are you running?

**Comment by saugstauberr** [comment]
I use Windows Defender.

**Comment by saugstauberr** [comment]
With MacType:
![grafik](https://user-images.githubusercontent.com/57033944/121094677-4abddc80-c7ef-11eb-8c23-812bd0e46492.png)

Without MacType:
![grafik](https://user-images.githubusercontent.com/57033944/121094813-8062c580-c7ef-11eb-8b54-218a1e57240e.png)

**Comment by snowie2000** [comment]
So it happens all the time or it happens rarely or intermittently?

**Comment by saugstauberr** [comment]
Almost always.

**Comment by snowie2000** [comment]
Could you provide the profile you're using?

**Comment by snowie2000** [comment]
And looks like you're not using the standard windows CMD shell?

**Comment by saugstauberr** [comment]
It doesn't matter which shell I use. Even if it's PowerShell. I think I use the default profile, I'll look it up tomorrow again.

**Comment by snowie2000** [comment]
should be fixed by v2024 and later
