### ISSUE TITLE
winver窗口无法被渲染

### ISSUE THREAD

**Issue by digiant** [snowie2000/mactype#759]
雪大你好，装了最新版的mactype 2020 rc1，服务模式加载，系统是windows 10 21H1(19043.1024)，运行里输入"winver"弹出的关于对话框无法被渲染，之前用的mactype 2016+日本补丁是可以渲染的，不知道是何原因。

**Comment by snowie2000** [comment]
DirectWrite的支持默认是关闭的，需要手动开启。

**Comment by CurtisWong458** [comment]
> DirectWrite的支持默认是关闭的，需要手动开启。

敢问下大佬这个在哪里打开？配置文件没找到啊

**Comment by snowie2000** [comment]
https://github.com/snowie2000/mactype/wiki/DirectWrite

**Comment by digiant** [comment]
> 
> 
> DirectWrite的支持默认是关闭的，需要手动开启。

我看了下都是DirectWrite=1开启的，但是没有效果，好奇怪。

**Comment by CurtisWong458** [comment]
> https://github.com/snowie2000/mactype/wiki/DirectWrite

![QQ图片20210606140550](https://user-images.githubusercontent.com/78467561/120917177-3939df00-c6e0-11eb-989e-f1f886f0383c.png)

**Comment by CurtisWong458** [comment]
> https://github.com/snowie2000/mactype/wiki/DirectWrite

![QQ图片20210606155920](https://user-images.githubusercontent.com/78467561/120917187-51116300-c6e0-11eb-8120-621500f911bc.png)

**Comment by CurtisWong458** [comment]
这样子应该是有效果的吧，雪大

**Comment by digiant** [comment]
> 
> 
> 这样子应该是有效果的吧，雪大

你这个效果是对的，难道是因为我没有用administrator的原因？我是新建了一个本地账户登录的。

**Comment by snowie2000** [comment]
你说的就是这个界面？这个界面根本就不是DirectWrite的，和日本的补丁一点关系都没有

**Comment by digiant** [comment]
> 
> 
> 你说的就是这个界面？这个界面根本就不是DirectWrite的，和日本的补丁一点关系都没有

我找到规律了，打开任务管理器->文件->运行新任务，输入winver, 不勾选“以系统管理权限创建此任务”的情况下，弹出来的关于windows对话框不会被渲染。勾选后反而会被正常渲染，奇怪啊。

**Comment by snowie2000** [comment]
> > 你说的就是这个界面？这个界面根本就不是DirectWrite的，和日本的补丁一点关系都没有
> 
> 我找到规律了，打开任务管理器->文件->运行新任务，输入winver, 不勾选“以系统管理权限创建此任务”的情况下，弹出来的关于windows对话框不会被渲染。勾选后反而会被正常渲染，奇怪啊。

你等几秒钟就会了。

原因很简单，你的任务管理器是以管理员权限运行的（默认如此），不勾选的话创建出来的进程是非管理员的，所以需要穿越UAC。这个做不到
