### ISSUE TITLE
Settings app crashes instantly with MacType enabled

### ISSUE THREAD

**Issue by silv3rcat** [snowie2000/mactype#760]
As per title,

Edition	Windows 10 Pro
Version	20H2
Installed on	‎14/‎05/‎2021
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Comment by snowie2000** [comment]
That's too complicated. I'm sorry but I can't try that specific system myself.

Which mactype version are you on? Is there any crash report in the event log?

**Comment by silv3rcat** [comment]
Event Log:

- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2021-06-07T02:40:15.7141709Z 
 
   EventRecordID 5075 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  0 
   [ ThreadID]  0 
 
   Channel Application 
 
   Computer DESKTOP-CO57I07 
 
   Security 
 

- EventData 

   SystemSettings.exe 
   10.0.19041.789 
   4aa1ce82 
   unknown 
   0.0.0.0 
   00000000 
   c0000005 
   00007ffa4d740072 
   4040 
   01d75b4672697c50 
   C:\Windows\ImmersiveControlPanel\SystemSettings.exe 
   unknown 
   5456dd90-f89d-4779-9c91-670855a99d68 
   windows.immersivecontrolpanel_10.0.2.1000_neutral_neutral_cw5n1h2txyewy 
   microsoft.windows.immersivecontrolpanel

**Comment by snowie2000** [comment]
Sorry, but this log is totally useless.

**Comment by silv3rcat** [comment]
is there another log I can get from somewhere that might help identify the problem?

**Comment by Optinux** [comment]
Excluding the Settings App from the MacWizard Process Manager fixed it for me and should fix it for you too.
Well, if you are okay with not having mactype in the Settings App, that is.
