### ISSUE TITLE
webstorm编辑器无法渲染

### ISSUE THREAD

**Issue by cjlhll** [snowie2000/mactype#761]
菜单可以渲染。就是编辑器区域无法渲染，已经添加了配置文件的代码了。
[Experimental@webstorm64.exe]
ClipBoxFix=1

**Comment by snowie2000** [comment]
请提供截图，我一直用webstorm，从来都没有问题

**Comment by cjlhll** [comment]
![QQ截图20210608091418](https://user-images.githubusercontent.com/26736892/121107170-07d52680-c83a-11eb-9101-8595d40879b2.png)
![QQ截图20210608091522](https://user-images.githubusercontent.com/26736892/121107195-10c5f800-c83a-11eb-9ba3-478a6d99d6fe.png)

**Comment by cjlhll** [comment]
> 请提供截图，我一直用webstorm，从来都没有问题

你好，已经贴图了。

**Comment by snowie2000** [comment]
这不是很正常吗？

**Comment by cjlhll** [comment]
> 这不是很正常吗？

这是已经渲染了吗。咋还这么细呢。跟没渲染一样啊

**Comment by snowie2000** [comment]
webstorm默认字体就是很细的呀，你关掉mactype重启webstorm对比下就知道了

**Comment by cjlhll** [comment]
> webstorm默认字体就是很细的呀，你关掉mactype重启webstorm对比下就知道了

好吧。谢谢
