### ISSUE TITLE
Traditional Chinese not replacing

### ISSUE THREAD

**Issue by ak1976** [snowie2000/mactype#762]
It worked poperly in previous version, but it's not been replacing by this RC1 version

This only happen in the file explorer, file name with chinese characters, now it's been replaced wrongly from "Microsoft JhengHei" to 
"MingLiu"(or PMingLiu).

Both last version and this RC1 version, I use the same profile. (And both using registry mode)

Others like chrome is working better then before, by the way. 

It's almost perfect, if this issue can be fixed, or maybe some adjustment is needed in the profile?

here is the screenshot. 

Previous version
![previous version](https://user-images.githubusercontent.com/28253609/121286661-bba9e500-c912-11eb-9e61-8a4077ef76ff.png)

RC1 version
![rc1 version](https://user-images.githubusercontent.com/28253609/121286691-c795a700-c912-11eb-9bec-92a0d296b166.png)

my profile
[Tony Win10 PingFang - San Francisco.txt](https://github.com/snowie2000/mactype/files/6620835/Tony.Win10.PingFang.-.San.Francisco.txt)

**Comment by snowie2000** [comment]
What's the original font being used to display the filename in explorer?

**Comment by ak1976** [comment]
> What's the original font being used to display the filename in explorer?

Should be "Microsoft JhengHei"(微軟正黑體)

**Comment by snowie2000** [comment]
And it happens to the file explorer ONLY? All the other apps that utilize the same font are properly replaced?

**Comment by ak1976** [comment]
> And it happens to the file explorer ONLY? All the other apps that utilize the same font are properly replaced?

Yes, it is. 

I also tried the new ArmBreaker=1 , still the same

**Comment by snowie2000** [comment]
> > And it happens to the file explorer ONLY? All the other apps that utilize the same font are properly replaced?
> 
> Yes, it is.
> 
> I also tried the new ArmBreaker=1 , still the same

It has nothing to do with font replacement.

**Comment by snowie2000** [comment]
Looks like you're using an English system? With MSJH as the default font? How did you archive that?

**Comment by ak1976** [comment]
> Looks like you're using an English system? With MSJH as the default font? How did you archive that?

Somthing like this. 

![image](https://user-images.githubusercontent.com/28253609/121301696-2bc46500-c92b-11eb-95f5-20e3c33bf697.png)


And it seems like, the program is actually replacing the font, but just the wrong one, it should be replaced from "Microsoft JhengHei"(微軟正黑體) to "PingFang TC", but it's now "Microsoft JhengHei"(微軟正黑體) to "PMingLiu"(新細明體)

By the way, some correction of the above info, it's not only happened to file explorer, it also happens to some portion of the system, ex "Services", not all by part of it, as below

![image](https://user-images.githubusercontent.com/28253609/121302459-4ea34900-c92c-11eb-8612-701e54cd41ce.png)

**Comment by snowie2000** [comment]
![Untitled](https://user-images.githubusercontent.com/11767189/121309806-38e65180-c935-11eb-8414-1b0539233b85.png)
With the help of the WhichFont app, it's clear that the font Windows Explorer is using to paint the filenames is `Segoe UI`, and the target font you specified for it is `SF Pro Display Regular`

**Comment by ak1976** [comment]
> ![Untitled](https://user-images.githubusercontent.com/11767189/121309806-38e65180-c935-11eb-8414-1b0539233b85.png)
> With the help of the WhichFont app, it's clear that the font Windows Explorer is using to paint the filenames is `Segoe UI`, and the target font you specified for it is `SF Pro Display Regular`

Ok...The SF Pro Display Regular only have latin characters...anyway, I will give it a try later, and let you know. 

Just wondering why previous version is working properly, I mean, work as I expected...

**Comment by snowie2000** [comment]
Maybe that's because the previous version doesn't replace font properly, and the improper result resulted the result you expected.😄

**Comment by ak1976** [comment]
> Maybe that's because the previous version doesn't replace font properly, and the improper result resulted the result you expected.😄

Yeah, just tested it, it's now actually working properly, but not as I expected...but at least I know the reason. 

Thanks for your great help!

Cheers.

**Comment by snowie2000** [comment]
If you want to use `SF Pro Display Regular` as your substitution target font, always remember that you can create font links manually for it. You are free to link any font you like to it.

**Comment by ak1976** [comment]
> If you want to use `SF Pro Display Regular` as your substitution target font, always remember that you can create font links manually for it. You are free to link any font you like to it.

How do I do that? could you give me an example? Please.

**Comment by snowie2000** [comment]
Bring up regedit, and navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink`

And there are plenty of examples to imitate.

The way it works is that when Windows can't find a glyph in a font, it searches through the fontlink list, and use the first font that has that glyph to display the text. That's why you're able to display Chinese characters with Segoe UI which is basically only an English font.

**Comment by ak1976** [comment]
> Bring up regedit, and navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink`
> 
> And there are plenty of examples to imitate.
> 
> The way it works is that when Windows can't find a glyph in a font, it searches through the fontlink list, and use the first font that has that glyph to display the text. That's why you're able to display Chinese characters with Segoe UI which is basically only an English font.

Great! good to learn something. 

Does that mean I could set the "Segoe UI=SF Pro Display Regular" in the mactype ini file as before, then set the "SF Pro Display Regular" in the fontlink with some other fonts with Chinese characters? 

![image](https://user-images.githubusercontent.com/28253609/121328712-237a2300-c947-11eb-895e-6534a846f480.png)

**Comment by snowie2000** [comment]
Exactly, this is how Tahoma, Arial, and all other Latin and symbol fonts display CJK characters.

**Comment by ak1976** [comment]
> Exactly, this is how Tahoma, Arial, and all other Latin and symbol fonts display CJK characters.

Got it. Just tried, and now it's working perfectly!

Thanks a lot.
