### ISSUE TITLE
mactype启用时，应用商店版地平线四无法启动

### ISSUE THREAD

**Issue by llwwbb** [snowie2000/mactype#764]
service模式和托盘模式都一样，停用mactype后地平线四可以正常启动

将Forza horizon 4和Runtime Broker进程添加例外也不行。

**Comment by snowie2000** [comment]
查看事件管理器有没有错误报告，是不是使用的rc1版本。

**Comment by llwwbb** [comment]
版本是rc1

游戏启动后看到多出了两个错误。 
`日志名称:          Application
来源:            Application Error
日期:            2021/6/15 0:25:22
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-DLTTICJ
描述:
错误应用程序名称: ForzaHorizon4.exe，版本: 0.0.0.0，时间戳: 0x60ad0b8b
错误模块名称: ForzaHorizon4.exe，版本: 0.0.0.0，时间戳: 0x60ad0b8b
异常代码: 0xc0000005
错误偏移量: 0x0000000000399794
错误进程 ID: 0x343c
错误应用程序启动时间: 0x01d76139dcb82904
错误应用程序路径: C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
错误模块路径: C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
报告 ID: fbf97148-ee1c-4193-9536-4a038e5eada3
错误程序包全名: Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe
错误程序包相对应用程序 ID: SunriseReleaseFinal
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-06-14T16:25:22.4164435Z" />
    <EventRecordID>817</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-DLTTICJ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ForzaHorizon4.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>60ad0b8b</Data>
    <Data>ForzaHorizon4.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>60ad0b8b</Data>
    <Data>c0000005</Data>
    <Data>0000000000399794</Data>
    <Data>343c</Data>
    <Data>01d76139dcb82904</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe</Data>
    <Data>fbf97148-ee1c-4193-9536-4a038e5eada3</Data>
    <Data>Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe</Data>
    <Data>SunriseReleaseFinal</Data>
  </EventData>
</Event>`

`日志名称:          System
来源:            Microsoft-Windows-DistributedCOM
日期:            2021/6/15 0:25:25
事件 ID:         10010
任务类别:          无
级别:            错误
关键字:           经典
用户:            DESKTOP-DLTTICJ\lwb02
计算机:           DESKTOP-DLTTICJ
描述:
服务器 Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe!SunriseReleaseFinal 没有在要求的超时时间内向 DCOM 注册。
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10010</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2021-06-14T16:25:25.7987536Z" />
    <EventRecordID>2160</EventRecordID>
    <Correlation ActivityID="{d2ceaeab-1df6-40d0-a995-83adabe7d01d}" />
    <Execution ProcessID="1068" ThreadID="3416" />
    <Channel>System</Channel>
    <Computer>DESKTOP-DLTTICJ</Computer>
    <Security UserID="S-1-5-21-1229923793-458788826-3219207779-1001" />
  </System>
  <EventData>
    <Data Name="param1">Microsoft.SunriseBaseGame_1.470.573.2_x64__8wekyb3d8bbwe!SunriseReleaseFinal</Data>
  </EventData>
</Event>`

**Comment by llwwbb** [comment]
另外多试了几次发现，对游戏进程添加例外似乎有时候可以有时候不行，找不到规律。

游戏正常启动的时候，在mactype进程管理那里对游戏进程点击启用会立即导致闪退

**Comment by CurtisWong458** [comment]
借楼问下雪大，服务模式下开机到桌面的图标不是马上渲染的，而是要等几秒或者几分钟才会渲染是正常的吗？？？

**Comment by snowie2000** [comment]
> 另外多试了几次发现，对游戏进程添加例外似乎有时候可以有时候不行，找不到规律。
> 
> 游戏正常启动的时候，在mactype进程管理那里对游戏进程点击启用会立即导致闪退

直接添加排除是不完整的，添加排除后需要重启服务。因为排除需要由服务和父进程同时进行，添加排除后父进程虽然不再加载子进程，但服务并不会刷新配置，依然会尝试去加载，导致崩溃。只有重启服务后排除才会真正生效。

**Comment by snowie2000** [comment]
> 借楼问下雪大，服务模式下开机到桌面的图标不是马上渲染的，而是要等几秒或者几分钟才会渲染是正常的吗？？？

可能需要等待几秒，几分钟不至于，但是由于目前服务模式存在的一些问题，界面并不会自动刷新，可能需要手动按一下f5.

另外如果你用的是2019版本的话，桌面有一定概率不会被捕捉到从而不会被渲染。2021版本解决了这个问题。
