### ISSUE TITLE
NOT working on Desktop&Chrome

### ISSUE THREAD

**Issue by raylu0910** [snowie2000/mactype#767]
雪大您好,

大部分的程式是可以正常運作的，不過我發現桌面上的文字以及開始選單是沒有被替代的
![image](https://user-images.githubusercontent.com/86159997/122721632-7935c000-d2a3-11eb-91f7-8a5fea7ad5d9.png)
我覺得是ini檔案設定的問題，因為在檔案總管裡面是正常運行的，我有嘗試著讓許多字體`=RayPingFang`，但是仍然沒有作用

_更正1:我發現檔案總管只有右半邊是正常運行的，左半邊則是沒有。_
_更正2:檔案總管似乎很不穩定，有時可以完全正常運行，有時只運行在右半邊，又有時完全不會運行。桌面文字、開始選單也是不穩定，有時會運行但有時不會_

在Chrome瀏覽器也遇到了一些問題
有一些字不會正常運行，以github為例子(有點多，只標示部分文字)，中文有些許部分沒有運作，英文在特定方塊裡似乎是完全不會被替代的:
![image](https://user-images.githubusercontent.com/86159997/122710285-8d24f600-d292-11eb-9b44-dfe85d813b3c.png)
這些文字我有使用FontForge檢查我的ttf檔案，不過我沒有發現任何問題。

另外，我有嘗試使用 [whichfont app](https://github.com/snowie2000/WhichFont) 來找出未成功替換的字體，但似乎沒有用，他一直顯示 `------Process exited------`
![image](https://user-images.githubusercontent.com/86159997/122682125-3c79b280-d22a-11eb-9d23-d6ea49fa636b.png)

順帶一問，有沒有在不調整系統設定的前提下強制變更字體大小的指令?我發現Mactype讓字變小了，但是我只想增加字體大小，不想改變整個系統顯示比例

My ini file:[RayPingFang.txt](https://github.com/snowie2000/mactype/files/6684761/RayPingFang.txt)

**Comment by digiant** [comment]
老哥说中文就行，开发者雪大是中国的。

**Comment by raylu0910** [comment]
> 老哥说中文就行，开发者雪大是中国的。

原來如此，已經全部換成中文了

**Comment by snowie2000** [comment]
😅英文有助於其他國家地區的朋友搜尋和解決問題，所以如果沒有英文障礙的話，建議優先使用英文哦。

開始選單的問題在釋出新版本的時候就有注意到了，記得曾經是可以的，不知道從哪個版本開始就不行了，未來應該會被修復的。
檔案總管是有正常被渲染的，你可以打開一個含有中文的資料夾查看，應該能看到不同。

替代字形是有風險的，並且會造成你看到的錯誤，這個是因為fontlink的關係。當你選用的新字形中不包含有網頁需要的某個單字時，Chrome（和其他一切程式）都會自動嘗試尋找一個fallback字形來顯示。例如你可以在Tahoma字體下輸出中文而Tahoma本身其實並不包含有中文字形。這個尋找fallback字形的過程由一個fontlink表顯示，具體信息可以參考issue #762 而被你替代的新字體並沒有正確的fontlink，當然就會胡亂link到默認字體了。

WhichFont可以用於偵測一個process使用的字體，但他不能偵測該process的child process，例如Chrome就是典型的多進程程式。不過對於Chrome有更直觀方便的方法：使用devtools

滑鼠右擊文字選inspect就可以展開devtools，在右側pane選擇computed，然後就可以在右下角看到當前應用的字體名稱了。
![QQ截图20210621153734](https://user-images.githubusercontent.com/11767189/122724681-c0718000-d2a6-11eb-8f69-6c9e7cab6bc3.png)

另外MacType不能改變字體大小，他只能改變字體的外觀呈現。

**Comment by raylu0910** [comment]
謝謝 @snowie2000 大的解答，解決了部份的問題
但是還是有些問題想請教一下:
桌面(Desktop)的文字沒有被渲染也是正常的嗎?
![image](https://user-images.githubusercontent.com/86159997/122739035-25cc6d80-d2b5-11eb-94d0-2e16debb972b.png)


另外，檔案總管"有時候"只有右半部被渲染，左半部則完全沒有被渲染到
![image](https://user-images.githubusercontent.com/86159997/122738780-e140d200-d2b4-11eb-8a11-8c257dbcd0a9.png)
可以清楚的看見，兩邊的字體(中文、英文)是不一樣的

**Comment by snowie2000** [comment]
不是很清楚為什麼左右兩邊的字重會有這麼大的差別，不過可以確定的是確實Mactype是有作用到的，你可以完全關閉掉Mactype再截圖試試，肯定是不一樣的。

**Comment by raylu0910** [comment]
問題似乎解決了，我想應該是兩邊文字渲染的時間不一樣(?)，因為過一段時間就好了。謝謝雪大的幫助

**Comment by raylu0910** [comment]
Oops，我發現檔案總管左邊的文字要經過許久時間(大約半小時)之後才會被渲染，但這似乎不太正常。
另外，我桌面上的文字卻始終不會被渲染(我已經開機半天了)，不過開始選單已經有渲染成功了，看來桌面這邊似乎是出了些問題。
![image](https://user-images.githubusercontent.com/86159997/122926951-f5f79580-d39a-11eb-9fe4-6d1c295764a2.png)
經過比較，可以清楚的看到，桌面上的文字是沒有被渲染的。
不過我的檔案是有這行的:`Segoe UI=RayPingFang`

不太清楚是哪裡出了問題，還請雪大幫忙看一下。(我使用的是服務加載模式)
我的設定檔:[RayPingFang.txt](https://github.com/snowie2000/mactype/files/6694279/RayPingFang.txt)

**Comment by TabrisKing** [comment]
桌面图标、菜单、标题栏等字体替换最好不要用mactype  用这个软件winaero tweaker

**Comment by berlaychen** [comment]
樓主 有沒有其他的方式可以聯絡你~
我mactype不知道有沒有設定正確 你的設定看起來很棒 我需要你的支援QQ

**Comment by raylu0910** [comment]
> 樓主 有沒有其他的方式可以聯絡你~
> 我mactype不知道有沒有設定正確 你的設定看起來很棒 我需要你的支援QQ

大大你可以先透過我留在github上的email來聯絡我 之後再看要用什麼方式聯絡，不過我不確定能不能幫助到你，因為我自己也有一些問題還沒有解決😅
