### ISSUE TITLE
在雪大beta1906的基础上更新了日本人补丁以及其他优化补丁，可以完美渲染edge，chrome浏览器最新版本。

### ISSUE THREAD

**Issue by lemon-we** [snowie2000/mactype#772]
[MacType-1906.zip](https://github.com/snowie2000/mactype/files/6713250/MacType-1906.zip)

**Comment by snowie2000** [comment]
谢谢你的努力，但是2019版本存在大量问题，不建议任何人继续使用。你可以在你的fork版本中更新，但发布在这里会引起不必要的麻烦。
例如在新的CPU中使用2019版本将必然导致系统崩溃等。
该issue将被关闭。

**Comment by digiant** [comment]
我也是一直在用1906+日本补丁，服务模式加载，居然UWP界面都能接管渲染到，太神奇了，也挺稳定的，win10 dev 21390都能用。

**Comment by snowie2000** [comment]
uwp界面一直都可以。你没事是因为你的cpu不够新
