### ISSUE TITLE
在 Win10 Dev 和 Win11 中导致“设置”部分项打开崩溃

### ISSUE THREAD

**Issue by ghost** [snowie2000/mactype#773]
问题系统：
* Win10 21390.2025 开发预览版
* Win11 21996.1 Leaked 版（应该是泄漏还是泄露？）

问题复现：
* 启用服务模式的 MacType
* 打开“设置”应用
* 选择“辅助功能”
* 选择“鼠标指针”
* 此时设置应用进入卡死状态且不可操作

问题解除：
* 在 MacType 向导中为“设置 SystemSettings.exe”排除进程
* 重新打开“设置”应用
* 问题消失
* 但是这样不能渲染设置应用中的字体了

MacType：
* MacType 版本为 2021 版
* 字体为 XHei Android 系列

**Comment by snowie2000** [comment]
如果方便的话，打开任务管理器，然后找到卡死的设置进程，选择生成转储或者create dump file。
系统会形成一个相当大的文件，大约500M…………
压缩后找地方传上去然后把链接发上来，看一下应该能找到问题。

不接受百度网盘链接……

**Comment by ghost** [comment]
@snowie2000 转储文件：https://cowtransfer.com/s/50c1e5f6f9a840

**Comment by gettinwet** [comment]
win11的渲染引擎有什么进步吗？还是需要mactype吗？

**Comment by ghost** [comment]
> 
> 
> win11的渲染引擎有什么进步吗？还是需要mactype吗？

缩放在 150 以下，跟 win10 没区别，依然需要 mactype，如果你是 amd 的显卡或者核心显卡，可以开虚拟 4k，然后调到缩放 200%，就不需要 mactype 了。

**Comment by gettinwet** [comment]
> > win11的渲染引擎有什么进步吗？还是需要mactype吗？
> 
> 缩放在 150 以下，跟 win10 没区别，依然需要 mactype，如果你是 amd 的显卡或者核心显卡，可以开虚拟 4k，然后调到缩放 200%，就不需要 mactype 了。

4k显示器也可以用虚拟4k来改善吗？另外win11的字体还是有hinting吧？Windows的没品位主要就在hinting上呢

**Comment by ghost** [comment]
> 
> 
> > > win11的渲染引擎有什么进步吗？还是需要mactype吗？
> > 
> > 
> > 缩放在 150 以下，跟 win10 没区别，依然需要 mactype，如果你是 amd 的显卡或者核心显卡，可以开虚拟 4k，然后调到缩放 200%，就不需要 mactype 了。
> 
> 4k显示器也可以用虚拟4k来改善吗？另外win11的字体还是有hinting吧？Windows的没品位主要就在hinting上呢

必须 DPI >= 150% 才能用 win10/11 自带的新渲染模式，否则还是得用 mactype 改善渲染

**Comment by gettinwet** [comment]
> > > > win11的渲染引擎有什么进步吗？还是需要mactype吗？
> > > 
> > > 
> > > 缩放在 150 以下，跟 win10 没区别，依然需要 mactype，如果你是 amd 的显卡或者核心显卡，可以开虚拟 4k，然后调到缩放 200%，就不需要 mactype 了。
> > 
> > 
> > 4k显示器也可以用虚拟4k来改善吗？另外win11的字体还是有hinting吧？Windows的没品位主要就在hinting上呢
> 
> 必须 DPI >= 150% 才能用 win10/11 自带的新渲染模式，否则还是得用 mactype 改善渲染

看来相比win10是没有啥进步了，我猜在字体渲染部分win11也不会有什么改进的计划了，哪怕在win11把重点放在改进UI的情况下。感觉微软的人根本就意识不到字体渲染和hinting的问题有多么严重，没品真是灾难。

**Comment by ghost** [comment]
> 
> 
> > > > > win11的渲染引擎有什么进步吗？还是需要mactype吗？
> > > > 
> > > > 
> > > > 缩放在 150 以下，跟 win10 没区别，依然需要 mactype，如果你是 amd 的显卡或者核心显卡，可以开虚拟 4k，然后调到缩放 200%，就不需要 mactype 了。
> > > 
> > > 
> > > 4k显示器也可以用虚拟4k来改善吗？另外win11的字体还是有hinting吧？Windows的没品位主要就在hinting上呢
> > 
> > 
> > 必须 DPI >= 150% 才能用 win10/11 自带的新渲染模式，否则还是得用 mactype 改善渲染
> 
> 看来相比win10是没有啥进步了，我猜在字体渲染部分win11也不会有什么改进的计划了，哪怕在win11把重点放在改进UI的情况下。感觉微软的人根本就意识不到字体渲染和hinting的问题有多么严重，没品真是灾难。

微软的侧重点在工作效率上，很多单位还是很烂的显示器，而windows的渲染方式可以在很烂的显示器上依然可以看清字。所以微软只对 DPI >= 150% 使用新渲染方式

**Comment by ghost** [comment]
最近重新装回了 WIN11，跟 #775 一样，是由于旧版第三方 mactype 卸载不干净导致的。

**Comment by snowie2000** [comment]
感谢反馈

**Comment by zhaoqingqing** [comment]
666，看起来在win11下还是可以使用mactype的。
