### ISSUE TITLE
Jumbled, incoherent text on open/save window in browsers (Win10 21H1)

### ISSUE THREAD

**Issue by AwesomeAwesomeAwesome** [snowie2000/mactype#777]
As seen below, this only happens on Chrome/Edge/Firefox (so not just Chromium), but no other applications so far:

![Screenshot 2021-07-04 193517](https://user-images.githubusercontent.com/47180044/124394277-1dd1ec00-dcff-11eb-91f1-e28acb3112b4.png)

**Comment by AwesomeAwesomeAwesome** [comment]
Notepad too:
![Screenshot 2021-07-04 201501](https://user-images.githubusercontent.com/47180044/124395461-8bcce200-dd04-11eb-9bdf-ad0f3a5809f3.png)

**Comment by snowie2000** [comment]
Apparently, you're using fontsubstitution and probably with fontsubsitute=2, please don't do it unless your 100% know the font your using.

**Comment by AwesomeAwesomeAwesome** [comment]
Thanks for the tip. I decided to substitue the font through regedit now (all Segoe -> my own) and now it works.

![Screenshot 2021-07-05 185553](https://user-images.githubusercontent.com/47180044/124501970-d3b23e80-ddc2-11eb-9bac-4d8088c4188e.png)
