### ISSUE TITLE
请问怎样排除目录或通过通配符排除

### ISSUE THREAD

**Issue by klinxun** [snowie2000/mactype#780]
呃，小弟比较菜，见笑了。新版本是说增加了目录排除。那么是在配置.ini，还是在mactype.ini里面设置？具体公式是什么？

**Comment by snowie2000** [comment]
在unloaddll中配置的，使用/做为结尾就可以了

**Comment by klinxun** [comment]
成功了。看来是我英语太渣，理解错误……

**Comment by bestv5** [comment]
那个版本支持目录排除？  windows中目录排除格式是D:\abc\bcd\  ？

**Comment by snowie2000** [comment]
现有的版本都支持

**Comment by bestv5** [comment]
> 现有的版本都支持
 windows中目录排除格式是下面这样吗 
[UnloadDll]
D:\abc\bcd\

**Comment by snowie2000** [comment]
是的
