### ISSUE TITLE
Windows 11 下， Vivaldi 无法使用 mactype

### ISSUE THREAD

**Issue by Badonti** [snowie2000/mactype#783]
Windows 版本：21H2 build 22000.65
Vivaldi 内核版本：91.0.4472.114

开启前效果：
https://i.loli.net/2021/07/15/g3y7NZiYEVepkM2.png

开启后效果（附 process explorer 截图）：
https://i.loli.net/2021/07/15/fI7tgjbRmrYX1iU.png

没有启用 service mode 的原因：
不知道如何在 service mode 下调出 mactray 的 process manager 来查看 hook 的程序，选用了其他模式。

尝试过的方法：注册表添加 dword、添加快捷方式参数，均无效。

**Comment by snowie2000** [comment]
从process explorer中可以看到已经启用了。因为你的分辨率非常高，所以对于dw来说并不会有多少明显的效果。

在service mode下，可以打开向导，向导中有一个进程管理可以看到hook状态。

Windows11没有经过任何测试，所以存在不兼容的情况纯属正常。至于注册表模式，说不定win11已经禁用了呢，反正目前没人知道。。。

**Comment by Badonti** [comment]
好的，感谢回复
