### ISSUE TITLE
服务窗口有问题

### ISSUE THREAD

**Issue by PIndividual** [snowie2000/mactype#785]
使用mactype后，运行services.msc出来的窗口里面糊成了一片，包含旗下的任何子窗口

**Comment by TabrisKing** [comment]
没设好呗。。  截个图  发个ini配置文件啊 不然怎么给你定位问题

**Comment by PIndividual** [comment]
![image](https://user-images.githubusercontent.com/62368342/126477922-94d88455-31b4-4e9e-9fac-babbd318fe9a.png)

**Comment by PIndividual** [comment]
[New Compression.zip](https://github.com/snowie2000/mactype/files/6855028/New.Compression.zip)

**Comment by snowie2000** [comment]
我现在找不到了。有一个问题和这个说的是一样的。mactype不支持增强缩放。￼￼

**Comment by PIndividual** [comment]
所以目前是无解的？

**Comment by snowie2000** [comment]
在有人贡献相关支持代码之前或者找到相关解决方法之前没有任何办法￼。

**Comment by snowie2000** [comment]
> 所以目前是无解的？
> 
> 

￼没错
微软对增强缩放提供的支持非常差。没有相关文档或API。￼
