### ISSUE TITLE
Not working on latest Windows 10

### ISSUE THREAD

**Issue by steve1412** [snowie2000/mactype#786]
Hi there,

I've  recently updated to the latest windows 10 and noticed there are areas not being injected properly with MacType, I tried Armbreak in a profile but here's what i'm getting. What should I do?

![Capture](https://user-images.githubusercontent.com/16667877/127007521-bf1ccc7c-df62-4757-a764-c6957e9128f0.PNG)
![Capture2](https://user-images.githubusercontent.com/16667877/127007524-e6c0b881-008a-4d84-bd77-e0c85790f88d.PNG)
![Capture3](https://user-images.githubusercontent.com/16667877/127007528-3e5ee8bf-1fac-448d-8efa-513c4ca653af.PNG)

**Comment by steve1412** [comment]
你好，我使用最新版本的Winodws 10无法激活Mactype。文字看起来会特别的模糊。使用的是1680x1050，会出现明显的锯齿。当使用2520x1575的时候高分屏已经无法看出端倪了。

**Comment by snowie2000** [comment]
@steve1412 如果你正在使用的程序是老式程序，不支持高分屏，并且你尝试使用了“增强缩放（系统）”，那么很抱歉，mactype并不支持这种缩放模式，他只能以标准dwm缩放的方式来运行。

**Comment by snowie2000** [comment]
对于上面的截图的问题，目前的情况是这样的：
1、开始菜单和任务栏部分没有渲染到，我自己这里也是一样的，但是有些系统却可以，目前暂时没有解决方案，我还没搞清楚是为什么。
2、对于截图3已经正常工作了，但是标题栏没有渲染到。这是一个bug，你可以在#768找到一个补丁来解决这个问题。
3、对于截图2，我不清楚这是什么程序，无法回答。

**Comment by steve1412** [comment]
> @steve1412 如果你正在使用的程序是老式程序，不支持高分屏，并且你尝试使用了“增强缩放（系统）”，那么很抱歉，mactype并不支持这种缩放模式，他只能以标准dwm缩放的方式来运行。

是这样子的，我在之前的版本里面，（大约2019）使用100%比例或者是175%的时候，之前的旧windows10是可以看出明显效果的。但是最新升级的windows10之后失去效果了。最新尝试的RC这个也无法调用。尝试过Armbreak和服务加载。服务加载对比可以托盘加载可以覆盖一些地方（如windows explorer）。但是不完全 （如MacType向导，Taskmanager）

**Comment by snowie2000** [comment]
我不清楚你说的失去效果具体是指哪些地方，需要截图来分析。

taskmanager的标题我已经在上面的回答中给出解决方案了。
mactype向导有专门的代码设计，不会渲染。这是防止由于用户设置了奇怪的参数导致看不清文字，从而无法禁用或切换配置而设计的。你无法对他使用mactype。

**Comment by solife2020** [comment]
能出一个支持WIN11全局的配置文件吗》？

**Comment by snowie2000** [comment]
测试版系统不再支持和测试之列。
目前来说win11和win10相似度很高，mactype基本上可以正常运行。但是具体到系统组件，肯定会存在一些兼容性问题。
只有当win11成熟并广泛使用后，我们才会尝试支持它。（如果可以的话:sad）

**Comment by steve1412** [comment]
> 我不清楚你说的失去效果具体是指哪些地方，需要截图来分析。
> 
> taskmanager的标题我已经在上面的回答中给出解决方案了。
> mactype向导有专门的代码设计，不会渲染。这是防止由于用户设置了奇怪的参数导致看不清文字，从而无法禁用或切换配置而设计的。你无法对他使用mactype。

我看到你关于1截图的答复已经回答到了。然后尝试了一下 768的 hotfix。已经会更好的照顾到了。谢谢！
