### ISSUE TITLE
MacType 在 Intellij Idea 上「等距更纱黑体」斜体字体渲染效果不完全

### ISSUE THREAD

**Issue by seyoatda** [snowie2000/mactype#788]
使用的字体为 Sarasa Mono SC ，也就是「等距更纱黑体」，regular字体渲染没有问题，但是斜体有一些字母没有渲染成功，还是原来的样式。
![image](https://user-images.githubusercontent.com/24985838/127419784-a5a12d76-fca3-4a06-819b-5a872fef37aa.png)

**Comment by snowie2000** [comment]
I've installed Sarasa Mono SC but for some reason, they did not appear in my webstorm font settings dialog.

**Comment by digiant** [comment]
> 
> 
> I've installed Sarasa Mono SC but for some reason, they did not appear in my webstorm font settings dialog.

windows10&11可能需要安装字体时，右键选择“为所有用户安装”才能体现字体

**Comment by seyoatda** [comment]
> I've installed Sarasa Mono SC but for some reason, they did not appear in my webstorm font settings dialog.

我是从github上下载安装的字体，https://github.com/be5invis/Sarasa-Gothic/releases/
不确定是否和安装的版本 or hinted/unhinted 相关，我尝试换一下版本测试一下，目前暂用`consolas`作为英文字体，斜体渲染是完整的。
![image](https://user-images.githubusercontent.com/24985838/127427759-179ee757-1743-46d5-8577-720989730bc2.png)
另外，可以帮忙看一下这个issue下我的问题吗，感谢~，照着前面所有的comment都试过仍然无法在edge上渲染。https://github.com/snowie2000/mactype/issues/754#issuecomment-887275814

**Comment by seyoatda** [comment]
> I've installed Sarasa Mono SC but for some reason, they did not appear in my webstorm font settings dialog.

测试后发现，我之前是在 Microsoft store 上安装的字体。我卸载后从 github 仓库下载的最新 release，无论是 hinted 还是 unhinted 版本，都全部无法渲染。之前的字体只是部分缺失。

**Comment by snowie2000** [comment]
你说的没错，就是要为所有用户安装才能在webstorm中看到。
但我没有发现任何显示问题。。。
![QQ截图20210730101125](https://user-images.githubusercontent.com/11767189/127589446-cdf5d32d-27e9-4001-a992-c4ddf65cdc27.png)

**Comment by snowie2000** [comment]
关于754的问题，你没有提供任何渲染截图，也没有提供进程状态的截图，所以我无法作出任何判断。

**Comment by seyoatda** [comment]
> 关于754的问题，你没有提供任何渲染截图，也没有提供进程状态的截图，所以我无法作出任何判断。

你好。已经在 754 issue下提供了这些信息，如果还有什么需要补充的请告诉我。感谢~
