### ISSUE TITLE
difference between windows metro and explorer

### ISSUE THREAD

**Issue by virgoan** [snowie2000/mactype#789]
why is there such a difference between the rendering of the fonts in metro interface vs the explorer fonts

![explorer_pkay7WmCj8](https://user-images.githubusercontent.com/40710091/127623896-05b269fa-e6ed-4bb5-85d1-5e2e42f58682.png)
![ApplicationFrameHost_PpkasJY08B copy](https://user-images.githubusercontent.com/40710091/127624723-50ca1e47-afb3-4790-9098-d81d6876fe98.png)

is there a setting i need to change? (this was happening on w10 aswell)

**Comment by ssssssbbb** [comment]
Explorer: GDI rendering
Metro: Directwrite

There's no way to be identical.

**Comment by virgoan** [comment]
is it possible to bypass mactype for directwrite, but still use it on gdi?

**Comment by sammilucia** [comment]
yes make sure to use
`DirectWrite=0` in the INI file you're using

**Comment by ssssssbbb** [comment]
no way

**Comment by virgoan** [comment]
thankyou… feel free to delete this thread 🙃
