### ISSUE TITLE
Should I turn off Cleartype when using Mactype?

### ISSUE THREAD

**Issue by Markimoo0714** [snowie2000/mactype#790]
As the title said.
Should I turn off Cleartype off when using Mactype?
I can't find the answer elsewhere.

**Comment by snowie2000** [comment]
The answer is no. You should never turn off Cleartype.

Other than that some applications don't work well with mactype, ClearType also changes the way how GDI works. Without cleartype, some GDI APIs work in a completely different way.

**Comment by Markimoo0714** [comment]
> The answer is no. You should never turn off Cleartype.
> 
> Other than that some applications don't work well with mactype, ClearType also changes the way how GDI works. Without cleartype, some GDI APIs work in a completely different way.

Thank you so much!

**Comment by coolrecep** [comment]
Is this still valid as of 2025 for WOLED panels?

**Comment by snowie2000** [comment]
Just try it yourself. Microsoft may or may not have changed the way GDI rendering works. They never mentioned anything about it.

**Comment by jabberwockxeno** [comment]
> The answer is no. You should never turn off Cleartype.
> 
> Other than that some applications don't work well with mactype, ClearType also changes the way how GDI works. Without cleartype, some GDI APIs work in a completely different way.

To clarify, you're saying that without Cleartype turned on, Mactype has less compatibility? Or are you saying there are benefits with GDI applications(?) even without Mactype with Cleartype turned on?

So if we don't have cleartype turned on to begin with before using Mactype, should we just pick a random set of Cleartype settings in the normal Windows cleartype wizard? What about [Better Cleartype Tuner](https://github.com/bp2008/BetterClearTypeTuner)?
