### ISSUE TITLE
Chrome字体渲染似乎没有生效

### ISSUE THREAD

**Issue by iloook** [snowie2000/mactype#793]
版本：
Windows 10  (build 19042)
MacType版本:	2021.1 

设置：
ArmBreaker=2（1也试过）

现象：
Chrome的字体效果有细微改变，但是仍然发虚，和预览效果差别比较大，如下图：
![image](https://user-images.githubusercontent.com/4929180/128873559-7b8eae81-3610-456d-a2ac-0def2568b8cd.png)

**Comment by iloook** [comment]
补充：
[DirectWrite]
RenderingMode=6

**Comment by snowie2000** [comment]
Directwrite效果和gdi不同，不再赘述。想要在Chrome中使用gdi目前唯一的办法就是cent browser。
