### ISSUE TITLE
Windows 10 / 11 ARM中无法使用，导致绿屏

### ISSUE THREAD

**Issue by alaya129** [snowie2000/mactype#794]
各种加载方式都试了，或者绿屏或者不能用。测试环境是Macbook Air M1 + Parallels Desktop 16.5，Windows 10 / 11 ARM各版本均不行。

**Comment by snowie2000** [comment]
不要想多了，mactype只支持x86

**Comment by alaya129** [comment]
转译后也不行，是和系统结合太紧密了吧

**Comment by snowie2000** [comment]
转译是不行的，hook类应用必须是原生的。

**Comment by alaya129** [comment]
明白了，谢谢。只能放弃了...
