### ISSUE TITLE
Unable to run cygwin programs (BLODA).

### ISSUE THREAD

**Issue by hyrious** [snowie2000/mactype#796]
Original issue & how I came here:
msys2/MSYS2-packages#2620 &rarr; msys2/MSYS2-packages#393 &rarr; [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda)

### Problem

Cygwin programs (including the `pacman.exe` and other exe provided by MSYS2, the clang.exe provided by LLVM) are facing the [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda) issue, which means these programs throw **Random fork() failures** and unable to work. A typical output look like this:

```
C:\Users\hyrious>ridk exec pacman -Syuu
      0 [main] pacman 411 dofork: child -1 - CreateProcessW failed for 'C:\Users\hyrious\AppData\Local\MSYS2\usr\bin\pacman.exe', errno 13
      1 [main] pacman 417 dofork: child -1 - CreateProcessW failed for 'C:\Users\hyrious\AppData\Local\MSYS2\usr\bin\pacman.exe', errno 13
      0 [main] pacman 423 dofork: child -1 - CreateProcessW failed for 'C:\Users\hyrious\AppData\Local\MSYS2\usr\bin\pacman.exe', errno 13
```

The original issue suggests [Put `gpg.exe` and `pacman.exe` lines under the `[UnloadDll]` section](https://github.com/msys2/MSYS2-packages/issues/393#issuecomment-159196510), however it does not work perfectly. I'll explain what happens:

1. I have added them to `[UnloadDll]`, but they **still throw error after rebooting** my pc.
   Attachment: [Default.ini](https://github.com/snowie2000/mactype/files/7072112/Default.ini.txt).
2. I then tried `(R)estart` to restart mactype, but no lucky.
3. I then click `(D)isabled`, wait a second, then click `(E)nabled`. **Now it works**.

That's why I call it _not perfect_.

### Additional Context

- You can find more output example in my [original issue](https://github.com/msys2/MSYS2-packages/issues/2620) to msys2.
- OS: Windows 10 Pro version 21H1 64bit (19043.1165)
- MacType: 2021.1-RC1

**Comment by lededev** [comment]
I find not only gpg.exe and pacman.exe, you need add `p11-kit.exe` to [UnloadDll] also, which is called by update-ca-trust script, when pacman -Suy

**Comment by hyrious** [comment]
I think maybe a workaround is to add an option `[ExcludeDir]` or likewise to apply `[UnloadDll]` to every program under some folders, so that we can add MSYS2 and LLVM's path into it.

It's maybe not a constant problem, but at least it always happen on my PC. Adding every program (*.exe) in MSYS2 seems not easy because there are thousands, some of them even have no extname.

@snowie2000 What do you think?

**Comment by snowie2000** [comment]
@hyrious You already can do that in the latest release, and it's usage is stated in the release note.

`A folder and its subfolders can now be included/excluded, it just needs to be ended with a "\"`

**Comment by lededev** [comment]
@snowie2000 请问我这么设置对吗？
```ini
[exclude]
D:\msys64\
[include]
D:\msys64\usr\bin\mintty.exe

```

**Comment by snowie2000** [comment]
Noon. When a file is both included and excluded, it's excluded.

**Comment by lededev** [comment]
那么如果我想排除一个目录，但其中某个执行文件需要豁免，该怎么设置呢？

**Comment by snowie2000** [comment]
这个似乎是做不到的……

**Comment by lededev** [comment]
希望以后能支持吧，一刀切的排除会误杀不少需要mactype的程序，而mintty.exe又必须在usr/bin里面没法挪位置。

**Comment by snowie2000** [comment]
当一个文件同时被排除和包含时，基本上常见设计都是否决权优先。
不管怎么设计总要有个优先嘛

**Comment by lededev** [comment]
要不然整个白名单也行，例如文件名叫mintty.exe的，如果放入白名单，无论是否在排除目录内，都加载dll。

**Comment by snowie2000** [comment]
mactype默认是工作在黑名单下的，include默认完全不生效的，写什么都没用，只有强制开启useinclude之后会才生效。

**Comment by lededev** [comment]
有黑名单也可以有白名单嘛。

**Comment by hyrious** [comment]
Since it was already be resolved, I'll close this issue.

Feel free to re-open it if you find other solutions to BLODA.

**Comment by chawyehsu** [comment]
`[UnloadDll]` 加了 `gpg.exe` 和 `pacman.exe` 如果还是报错，把 Windows Defender 实时防护关掉试试。

If errors still occur after adding `gpg.exe` and `pacman.exe` to `[UnloadDll]`, turn off the real-time protection of Windows Defender and try again.
