### ISSUE TITLE
MacType 2021 not working well with "Files" app

### ISSUE THREAD

**Issue by ghost** [snowie2000/mactype#798]
The "Files" app is a 3rd file manager uwp app. and MacType 2021 not working with it.

* No Font Rendering
* No Font Substituting
* Not running in Administrator mode

[![hDDluQ.png](https://z3.ax1x.com/2021/09/02/hDDluQ.png)](https://imgtu.com/i/hDDluQ)

Here is the Files app dl link:
https://www.microsoft.com/store/productId/9NGHP3DX8HDX

Tested uwp apps working with MacType:

* Windows Settings App
* Coolapk UWP Client
* Windows Terminal App
* Microsoft Store
* Mail App
* Adobe XD App

Thanks to author for provided the awesome application 😄

**Comment by snowie2000** [comment]
All transcoded win32 UWP apps have intermittent rendering with MacType due to the way they are launched.

**Comment by ghost** [comment]
@snowie2000 thank you 😄
