### ISSUE TITLE
Win11+AMD Zen3 5800x启用注册表模式成功

### ISSUE THREAD

**Issue by digiant** [snowie2000/mactype#799]
Mactype版本是最新的2021.rc1。
之前系统win10时，好像是由于新的CPU安全策略之类的问题，macwiz里启用注册表模式会导致无法进入系统。现在升级了最新的win11 22449之后，手动开启注册表加载可以成功进入系统并启用了全局渲染，有些窗口服务模式渲染不到，现在注册表模式下也可以渲染了，特来报告。

**Comment by ssssssbbb** [comment]
好事……

**Comment by biankobe24** [comment]
怎么启用？谢谢

**Comment by digiant** [comment]
前提可能是我关闭了BIOS里的安全启动，只开启了TPM 2.0。
