### ISSUE TITLE
buffer overun

### ISSUE THREAD

**Issue by Crescr** [snowie2000/mactype#801]
Installing Rc1 causes a buffer overrun on ctfmon.exe and taskhostw.exe.
It does not occur at all in Beta6.

Windows10 19043.1167
Windows11 22000.184
Occurs on both operating systems.

Error log:
アプリケーション ポップアップ: taskhostw.exe - システム エラー : このアプリケーションで、スタック ベースのバッファーのオーバーランが検出されました。このオーバーランにより、悪質なユーザーがこのアプリケーションを制御できるようになる可能性があります。 

アプリケーション ポップアップ: ctfmon.exe - システム エラー : このアプリケーションで、スタック ベースのバッファーのオーバーランが検出されました。このオーバーランにより、悪質なユーザーがこのアプリケーションを制御できるようになる可能性があります。 

Use ＩＮＩ:
[Preview]
Font=MaruGoAA-SR
Color=$000000
Text=MaruGoAA-SR 春夏秋冬 あいうえお ABCDEFG abcdefg 1234567890!@#$%^&*()
Size=10

[General]
Name=MaruGoAA-SR
AntiAliasMode=4
BoldWeight=0
BolderMode=0
CacheMaxFaces=256
CacheMaxSizes=12554432
CacheMaxBytes=12108864
ClipBoxFix=1
Contrast=0.8
DirectWrite=1
EnableKerning=0
FontLink=2
FontLoader=0
FontSubstitutes=2
GammaMode=0
GammaValue=1.0
HintingMode=1
HintSmallFont=1
HookChildProcesses=1
ItalicSlant=0
LcdFilter=2
LcdFilterWeight=0,85.33333,85.33333,85.33333,0
LoadOnDemand=1
MaxBitmap=0
MaxHeight=0
NormalWeight=0
RenderWeight=0.85
Shadow=0.8,0.8,0.8,0.8x0,0,0x0
TextTuning=0
TextTuningR=0
TextTuningG=0
TextTuningB=0
UseMapping=0

[DirectWrite]
RenderingMode=5
GammaValue=1.3
Contrast=0.6
ClearTypeLevel=0.7

[Experimental]
ColorFont=1
ArmBreaker=2

[General@chrome.exe]
ForceChangeFont=MaruGoAA-SR2
GammaValue=1.8
Contrast=1.2
HintingMode=1
AntiAliasMode=4
RenderWeight=1.2
ClearTypeLevel=1

[General@msedge.exe]
ForceChangeFont=MaruGoAA-SR2
GammaValue=1.8
Contrast=1.2
HintingMode=1
AntiAliasMode=4
RenderWeight=1.2
ClearTypeLevel=1

[Experimental@chrome.exe]
clipboxfix=1
InvertColor=1
ArmBreaker=2

[Experimental@msedge.exe]
clipboxfix=1
InvertColor=1
ArmBreaker=2

[FontSubstitutes]
Meiryo Bold=MaruGoAA-SR
Meiryo=MaruGoAA-SR
Meiryo UI Bold=MaruGoAA-SR
Meiryo UI=MaruGoAA-SR
Microsoft JhengHei=MaruGoAA-SR
MS UI Gothic=MaruGoAA-SR
MS Gothic=MaruGoAA-SR
MS Mincho=MaruGoAA-SR
MS PGothic=MaruGoAA-SR
ＭＳ Ｐゴシック=MaruGoAA-SR
MS PMincho=MaruGoAA-SR
メイリオ=MaruGoAA-SR
ＭＳ ゴシック=MaruGoAA-SR

[FontSubstitutes@CurtainsConfig.exe]
MaruGoAA-SR=Microsoft Sans Serif

[Exclude]
System

[ExcludeSub]
Dashboard.exe
Discord.exe
[UnloadDll]
AdobeIPCBroker.exe
AISuite3.exe
ATFSVR32.EXE
ATOK32IB.EXE
ATOK32OM.EXE
audiodg.exe
CCXProcess.exe
CompPkgSrv.exe
ctfmon.exe
DipAwayMode.exe
dllhost.exe
DTAgent.exe
DTShellHlp.exe
FantasyTaleClient.exe
FEzero_Client.exe
ffxiv_dx11.exe
fontforge.exe
GameBarPresenceWriter.exe
helper.exe
IEMonitor.exe
igfxCUIService.exe
igfxEM.exe
igfxHK.exe
ImeBroker.exe
jusched.exe
lass.exe
LDTA.exe
MsMpEng.exe
NahimicSvc32.exe
NahimicSvc64.exe
NativeLauncher.exe
node.exe
NVDisplay.Container.exe
OfficeClickToRun.exe
Oracle.SPF
pia-service.exe
QHActiveDefense.exe
QHSafeTray.exe
QHWatchdog.exe
RPG_RT.exe
RtkAudUService64.exe
rundll32.exe
RuntimeBroker.exe
SasaraPad.exe
SearchFilterHost.exe
SearchIndexer.exe
SearchProtocolHost.exe
services.exe
SettingSyncHost.exe
spoolsv.exe
stacsv64.exe
SynTPEnh.exe
SynTPHelper.exe
System40.exe
taskhostw.exe
TERA.exe
TextInputHost.exe
U3BoostSvr64.exe
VBoxSVC.exe
VirtualBox.exe
vmnat.exe
vmnetdhcp.exe
vmware-authd.exe
vmware-usbarbitrator64.exe
vmware-vmx.exe
XIVLauncher.exe
xxd-0.xem
xxd-1.xem
xxd-2.xem

**Comment by snowie2000** [comment]
This is an infamous error message: https://devblogs.microsoft.com/oldnewthing/20190108-00/?p=100655

A STATUS_STACK_BUFFER_OVERRUN in most cases has nothing to do with buffer underrun.

I've managed to trigger this error in a process called `ShellExperience.exe` which is responsible for the start menu in Windows 10/11. My guess is that Microsoft has implemented some sort of method to detect if a critical process is being hooked on startup, and then raise an exception to halt itself afterward.

I've deleted almost everything in MacType and even made it a total dummy DLL with no working code at all, and it still crashed with the same error. Maybe there are some problems with my dll loader assembly code that I can't fully figure out for now.

**Comment by Crescr** [comment]
22000.184 / beta6 + MacType-deadloop-fix.zip
It also happened in this environment.

The following customizations have been made to the OS, but it is unknown whether it is related.
[](url)

[batch.zip](https://github.com/snowie2000/mactype/files/7153659/batch.zip)
