### ISSUE TITLE
Uninstalling MacType doesn't revert to the Windows 10 default font.

### ISSUE THREAD

**Issue by Zhythe** [snowie2000/mactype#804]
As the title says. Quite annoying and tried everything I could to fix this but no hope so far. 

I hope there is a fix for this. Thanks in advance.

**Comment by sammilucia** [comment]
hi,

MacType doesn't actually alter the Windows font substitutions at all. are you sure it's not running still?

**Comment by snowie2000** [comment]
Mactype never does anything physically to your system. 

I guess that you may have launched  some program that does alter your system's font. And because the font is managed by mactype or maybe you've substituted it with mactype, that program used the wrong font and modified your system unexpectedly.

**Comment by Zhythe** [comment]
@sammilucia It actually does even tweaking things to get it back or just straight uninstalling it. Here is how it looks like. 

![image](https://user-images.githubusercontent.com/16560383/134828951-bd4ea6bd-fb84-4320-b5ba-9965819eda5b.png) 
![image](https://user-images.githubusercontent.com/16560383/134829007-38699224-e61b-438c-a46b-d9aee06b1be7.png)

And suppose to look like this. 

![1](https://user-images.githubusercontent.com/16560383/134829166-d6d591d9-ad42-48bc-b180-78b151713755.PNG)
![2](https://user-images.githubusercontent.com/16560383/134829172-5ac5750a-d95f-45fb-9457-7aa2ea11a357.png)

**Comment by Zhythe** [comment]
> 
> 
> Mactype never does anything physically to your system.
> 
> I guess that you may have launched some program that does alter your system's font. And because the font is managed by mactype or maybe you've substituted it with mactype, that program used the wrong font and modified your system unexpectedly.

Unfortunately, no. The only thing I've installed is just MacType and nothing else.

**Comment by snowie2000** [comment]
Could you show us how your system looks like now?￼

**Comment by Zhythe** [comment]
> 
> 
> Could you show us how your system looks like now?￼

**Comment by Zhythe** [comment]
> 
> 
> > Could you show us how your system looks like now?￼

- MacType **Enabled**
![v1c89C6las](https://user-images.githubusercontent.com/16560383/134829766-e06e7dba-a45e-43db-bcbf-304c56724020.png)

- MacType **Disabled**
![evP0XHnIxs](https://user-images.githubusercontent.com/16560383/134829789-b8de535e-e7b1-4f49-b6ef-1ae74e5d0c83.png)

- MacType **Uninstalled**  (What it looks like now)
![Fjmguj8IMh](https://user-images.githubusercontent.com/16560383/134829794-9bf32bca-31bf-4d48-9f2b-a18a5abdfe4b.png)

**Comment by Zhythe** [comment]
Basically, it shows the same as how it was when disabled if uninstalled.

**Comment by Zhythe** [comment]
Let me know if you need more info. Will gladly provide it right away.

Edit: Oops, accidentally closed it. My bad.

**Comment by snowie2000** [comment]
I personally didn't see anything abnormal in your screenshot 🤔 
Could you point me out where the problem lies?

**Comment by Zhythe** [comment]
> 
> 
> I personally didn't see anything abnormal in your screenshot 🤔
> Could you point me out where the problem lies?

Kindly refer to my previous post for the difference on how it is supposed to be and font changes when even uninstalling MacType.

Again, here is the example. 

What it looks like in mines now: 
![image](https://user-images.githubusercontent.com/16560383/134866795-c2fbc890-21f1-4444-b60c-570f216bbbce.png)

How it should look like:
![image](https://user-images.githubusercontent.com/16560383/134866852-be1c52a5-bab8-4514-aa03-d0f3f501596b.png)

I hope you can see it now.

**Comment by Zhythe** [comment]
Font size is a bit smaller than usual. This applies for Windows Explorer, Date & Time, even in reg edit and etc. 

![image](https://user-images.githubusercontent.com/16560383/134867090-1a21e7fa-b9f2-4c52-a02e-1a3fe1b18813.png)

Default should look like this.
![image](https://user-images.githubusercontent.com/16560383/134867305-5cb1c23d-601c-466d-89dc-8086b8e024e7.png)
_(ignore the arrow this is just a screenshot from google images)_

**Comment by snowie2000** [comment]
Ya, I see.

I compared my system with your images and yes, they look a bit different.

Your system's fonts are actually the same font size, they just look a bit "shorter" than they should be. Looks like the way the ClearType hinting works is somehow changed.

Could you have a try to run the Microsoft Cleartype tuner? It can be launched by typing "cttune" from the run dialog. Maybe it can help you set things back.

**Comment by sammilucia** [comment]
just to be clear, MacType does not modify any Windows font settings. if it's not running, it's not doing anything.

a few things to note:
- can you please check `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes` for any references to Segoe UI
- Microsoft did update Segoe UI with Segoe UI Variable on the Windows 10 Insider build. Segoe UI Variable has a different x height like we are seeing (I don't know if this is now in the main release of Windows 10, or only Windows 11)

**Comment by Zhythe** [comment]
> 
> 
> just to be clear, MacType does not modify any Windows font settings. if it's not running, it's not doing anything.
> 
> a few things to note:
> 
>     * can you please check `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes` for any references to Segoe UI
> 
>     * Microsoft did update Segoe UI with Segoe UI Variable on the Windows 10 Insider build. Segoe UI Variable has a different x height like we are seeing (I don't know if this is now in the main release of Windows 10, or only Windows 11)

This is the first time this has happened to me in my whole experience using a PC. Tried troubleshooting it and doing solutions that I have in my experience and also searched online but it still stays the same. The first question in my mind was, what caused it? By using MacType and tried uninstalling it (ps: just tried it for a day and didn't install any other programs just that) and stuck with it ever since (didn't want to see it uninstalled). But I figured that I should uninstall it since I am having some conflicts (problems) with certain apps that I'm using at my work. What else was the problem then? 

Apologies for the things that might have offended you or for what I've said and just wanted to be straightforward especially me being frustrated for months now trying to get everything back to normal. I just want this to be solved and nothing else. Just to be clear with that as well. 

Alright, I will try doing those. Will get back to you in a while.

**Comment by Zhythe** [comment]
![image](https://user-images.githubusercontent.com/16560383/134917036-a7b0050f-b7cb-4564-89de-f7b05b157c17.png)

Currently, this is what I see. No Segoe UI.

**Comment by Zhythe** [comment]
Also used this as .reg but no luck.

Windows Registry Editor Version 5.00

```
;Restore the default font mappings in Windows 10. Tested on v20H2
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts]
"Segoe MDL2 Assets (TrueType)"="segmdl2.ttf"
"Segoe Print (TrueType)"="segoepr.ttf"
"Segoe Print Bold (TrueType)"="segoeprb.ttf"
"Segoe Script (TrueType)"="segoesc.ttf"
"Segoe Script Bold (TrueType)"="segoescb.ttf"
"Segoe UI (TrueType)"="segoeui.ttf"
"Segoe UI Black (TrueType)"="seguibl.ttf"
"Segoe UI Black Italic (TrueType)"="seguibli.ttf"
"Segoe UI Bold (TrueType)"="segoeuib.ttf"
"Segoe UI Bold Italic (TrueType)"="segoeuiz.ttf"
"Segoe UI Emoji (TrueType)"="seguiemj.ttf"
"Segoe UI Historic (TrueType)"="seguihis.ttf"
"Segoe UI Italic (TrueType)"="segoeuii.ttf"
"Segoe UI Light (TrueType)"="segoeuil.ttf"
"Segoe UI Light Italic (TrueType)"="seguili.ttf"
"Segoe UI Semibold (TrueType)"="seguisb.ttf"
"Segoe UI Semibold Italic (TrueType)"="seguisbi.ttf"
"Segoe UI Semilight (TrueType)"="segoeuisl.ttf"
"Segoe UI Semilight Italic (TrueType)"="seguisli.ttf"
"Segoe UI Symbol (TrueType)"="seguisym.ttf"

;Remove the font substitutes, if any.
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"Segoe UI"=-
"Segoe UI Symbol (TrueType)"=-
```

**Comment by vikoprez** [comment]
Hi there!

You can try run it as service (if haven't) and apply any profile, then run wizard again and choose load with MacTray, apply Default profile, then exit MacTray in the taskbar. My workaround is for removing its service and run in hooking mode. It worked for me so it's my pleasure to help you out.

**Comment by sammilucia** [comment]
heya @Zhythe, I'm so sorry for the delay, work has been crazy.

I'm not offended! 😊 are any MacType* processes running in Task Manager?

**Comment by Zhythe** [comment]
It seems like MacType broke some of the files of gdipp that are currently installed on my PC or there is a conflict between the two. Just uninstalled both gdipp & MacType and reinstalled gdipp. Everything seems to be fine now. 

Consider this fixed. Thanks to all those who helped/replied for this issue that I've been struggling to fix since last year.

**Comment by snowie2000** [comment]
Gdipp and mactype are kinda like the same type of things, so they can't be both installed and effective at the same time.

**Comment by sammilucia** [comment]
as the creator of the installer, I can tell you it hunts for possibly conflicting files and removes them.

really it's hunting for old MacType files from before the installation/removal process was consistent. we need to make sure everything is removed, otherwise anything could happen once MacType is running.

someone going back to gdipp is not something we've ever planned for.

can I ask.... what's the reason you've gone back to gdipp? is there something MacType doesn't do well for you? this seems like a backwards step.

**Comment by garoto** [comment]
I recall `gdipp` having some serious memory leak issues on my computer back then.

**Comment by Zhythe** [comment]
> as the creator of the installer, I can tell you it hunts for possibly conflicting files and removes them.
> 
> really it's hunting for old MacType files from before the installation/removal process was consistent. we need to make sure everything is removed, otherwise anything could happen once MacType is running.
> 
> someone going back to gdipp is not something we've ever planned for.
> 
> can I ask.... what's the reason you've gone back to gdipp? is there something MacType doesn't do well for you? this seems like a backwards step.

Ah I see. In the end, I ended up uninstalling gdipp as well on my Gaming PC. 

Nothing in particular. I love MacType don't get me wrong. Though I'm not using MacType on my gaming PC and having conflicts with other games (not being able to run at all such as Forza and etc can't recall the others). Right now, I'm using MacType on my work PC. Just IMO, I like using MacType if I'm in my work mood. 

But yeah thanks for the info guys! No idea gdipp and MacType and Gdipp aren't friends. 😅

**Comment by sammilucia** [comment]
@Zhythe ah that makes sense. thanks for the update 😊
