### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by o62** [snowie2000/mactype#809]
Hi, it seems Firefox support is still hit or miss. Is there anything I can do to fix?

**Comment by lededev** [comment]
you need let cairo first. Default using skia never work with mactype.

![image](https://user-images.githubusercontent.com/30518126/136637318-f4b0145e-b334-4f99-a278-d33eaf75255c.png)

**Comment by snowie2000** [comment]
As stated in the latest wiki, `cairo` has already been removed. So, say hello to DirectWrite.
