### ISSUE TITLE
Edge小字体渲染不正常

### ISSUE THREAD

**Issue by istonel** [snowie2000/mactype#810]
系统是Windows11
左边是Edge，右边是Chrome
左边Edge页面中，小字体感觉渲染不正常，有谁知道怎么解决吗？谢谢！
![微信截图_20211008125819](https://user-images.githubusercontent.com/65379227/136500959-88a4f207-6177-4e62-be82-472483d61bbf.png)

**Comment by snowie2000** [comment]
Armbreaker设置了吗

**Comment by istonel** [comment]
设置之后好了，谢谢！
