### ISSUE TITLE
使用Mactype后重启时会卡在正在启动，并且过一会出现蓝屏报错并自动重启，卸载后正常

### ISSUE THREAD

**Issue by traoearth** [snowie2000/mactype#811]
终止代码：DRIVER_POWER_STATE_FAILURE

**Comment by snowie2000** [comment]
注册表模式？
mactype并不能在Windows启动时运行。

**Comment by traoearth** [comment]
服务模式

**Comment by snowie2000** [comment]
这个神奇的问题恐怕我无能为力。

**Comment by traoearth** [comment]
以前用都没这个问题，我总感觉是跟驱动或者啥巨硬的更新冲突了，但是又很难排查

**Comment by snowie2000** [comment]
这种奇葩的驱动问题要排查太难了，你都无法找到问题，我这边没人能重现的，根本无从查起。
只能用托盘模式没办法。

按理说服务在Windows启动时是不能运行的，只有在完全启动后才开始服务。

**Comment by snowie2000** [comment]
你的错误是发生在重启关机时，还是在重启已经结束Windows开始启动时

**Comment by traoearth** [comment]
发生在重启关机时

**Comment by snowie2000** [comment]
看看日志中有没有说明具体的驱动名称

**Comment by traoearth** [comment]
[100921-8890-01.zip](https://github.com/snowie2000/mactype/files/7315132/100921-8890-01.zip)
是这个吗？我搞不来这个日志

**Comment by traoearth** [comment]
是C++的问题。使用DX修复工具修复C++之后问题解决。
