### ISSUE TITLE
注销后重新登录会失效。

### ISSUE THREAD

**Issue by billowssun** [snowie2000/mactype#812]
注销后重新登录会失效，用的服务加载模式，查看服务正常运行，需要重新打开一次软件设置，才会生效，生效后还是有小部分之前有效的软件不能没有效果。

**Comment by snowie2000** [comment]
感谢。描述很准确，很容易重现。之前有好多个类似的report但都是偶发难以稳定的重现。你这个方案非常稳定

**Comment by lonznt** [comment]
我也碰到了这种情况。

**Comment by snowie2000** [comment]
最新版本已经解决了服务模式不稳定的问题了

**Comment by billowssun** [comment]
测试版本吗？

**Comment by snowie2000** [comment]
是的

**Comment by billowssun** [comment]
好的，谢谢。
