### ISSUE TITLE
MacType does not work transform:rotate()

### ISSUE THREAD

**Issue by quroe** [snowie2000/mactype#816]
MacType with GDI rendering does  not work transform:rotate() (e.g. "transform:rotate(2.0deg)") with web browser.

sample:
https://iosys.co.jp/guide/support/guaranteeperiod.html

Enviromment:
Windows 8.1 x64
MacType MacType 2021.1-rc1
Waterfox Classic 2021.10
CentBrowser x64 4.3.9.248
Sleipnir 4.7.13 test3

**Comment by snowie2000** [comment]
MacType doesn't work with any rotation operations. It's simply too complicated to apply a proper sub-pixel rendering in these cases.

**Comment by quroe** [comment]
OK, I understand.
Thanks reply!
