### ISSUE TITLE
Coolapk-UWP在Win10中使用MacType 2021.1-RC1渲染效果不好，请问作者大神有办法解决吗？

### ISSUE THREAD

**Issue by WrathGluttony** [snowie2000/mactype#818]
①系统：Win10 21H1
②Coolapk-UWP在Win10中使用MacType 2021.1-RC1渲染效果不好，请问作者大神有办法解决吗？
③Coolapk-UWP在github上的链接：https://github.com/Coolapk-UWP/Coolapk-UWP
④MacType 2021.1-RC1使用的是服务加载模式

**Comment by snowie2000** [comment]
UWP程序一般使用DirectWrite，目前DW的渲染就这样了。

**Comment by WrathGluttony** [comment]
作者大神，您好
①Win10 21H1中安装完MacType 2021.1-RC1，就自动支持DirectWrite了吧？用的加载模式，不需要另外设置或下载其它补丁文件了吧？
②记得以前的MacType要下载另外的补丁文件，放到相应的目录里，现在不需要了吧？最新版的MacType 2021.1-RC1已经集成补丁了吧？

**Comment by snowie2000** [comment]
上个正式发布的版本开始就已经集成了dw补丁了，但是UWP的启动方式十分怪异，目前都没有搞明白到底是怎么启动的，所以UWP程序并不能保证总是能渲染成功的。

**Comment by WrathGluttony** [comment]
谢谢作者大神的无私付出，其实这样已经很好了，打搅了
