### ISSUE TITLE
和极限竞速-地平线5冲突

### ISSUE THREAD

**Issue by PIndividual** [snowie2000/mactype#824]
开启程序的同时会导致地平线5启动报错，而且将其让添加到禁止列表似乎不能像地平线4那样解决问题，而必须完全关闭mac type，建议手动添加规则

**Comment by PIndividual** [comment]
自己解决了，在排除列表里直接添加了uwp启动命令
explorer.exe shell:appsFolder\Microsoft.624F8B84B80_8wekyb3d8bbwe!Forzahorizon5

**Comment by Extreme-Icer** [comment]
我添加了但是无效。依旧不能启动

**Comment by PIndividual** [comment]
> 我添加了但是无效。依旧不能启动

我购买的是Windows商店版，steam版可能不一样

**Comment by Extreme-Icer** [comment]
我也是商店版本，现在上了就报错 042b

**Comment by PIndividual** [comment]
这个我也有，没办法，多试几次总有一次能进去
