### ISSUE TITLE
Windows 11 22000.318 注册表模式成功，但有点疑问

### ISSUE THREAD

**Issue by Jason-LJQ** [snowie2000/mactype#827]
之前从未成功。尝试了一下注册表加载发现不行，重启以后注册表被改回去了，不知道是系统自动的还是杀软（Lenovo Antivirus）干的。把父目录（Windows）的权限拒绝继承，直接禁止Administrators和SYSTEM的权限中的更改数值和删除。
![image](https://user-images.githubusercontent.com/36041971/141614679-e1789878-7fea-49ad-9b82-7e9bbeac3e50.png)
重启后成功，没有MacTray运行，原来渲染不到的Process Lasso GUI也渲染到了，MMC也不糊了,甚至原来根本渲染不了的Edge和网页字体都渲染到了。再也不用纠结WMI高CPU占用的问题了。完美！
![image](https://user-images.githubusercontent.com/36041971/141614644-c246b22d-e815-4ec8-aa61-2541170056d8.png)

由#799 给予信心。参考http://blog.sina.com.cn/s/blog_50a7a62e010088tf.html

**Comment by Jason-LJQ** [comment]
不知道这样会不会影响系统更新，也就是会不会导致系统对其他子项的修改被拒绝而有异常？
![image](https://user-images.githubusercontent.com/36041971/141614615-d5867fa2-adef-4ef4-aee7-5a5a0f13f040.png)
这些项一般会被修改吗？

**Comment by tim-wang-tmp** [comment]
<img width="838" alt="微信截图_20211118205728" src="https://user-images.githubusercontent.com/1762601/142419587-89c8f66f-9f5c-48df-b3b7-9d7d12698780.png">
我用的是administrator登录的，Administrators的权限都是勾选的，还是无法启用注册表模式呢😂

**Comment by Jason-LJQ** [comment]
所有者改成你

**Comment by Jason-LJQ** [comment]
> 不知道这样会不会影响系统更新，也就是会不会导致系统对其他子项的修改被拒绝而有异常？ ![image](https://user-images.githubusercontent.com/36041971/141614615-d5867fa2-adef-4ef4-aee7-5a5a0f13f040.png) 这些项一般会被修改吗？

实测月度累积更新不会影响，成功安装。其他待测。
![image](https://user-images.githubusercontent.com/36041971/142436037-d1d7428a-3f02-44e2-9e6c-47c9c36ebd5a.png)

**Comment by tim-wang-tmp** [comment]
> > 不知道这样会不会影响系统更新，也就是会不会导致系统对其他子项的修改被拒绝而有异常？ ![image](https://user-images.githubusercontent.com/36041971/141614615-d5867fa2-adef-4ef4-aee7-5a5a0f13f040.png) 这些项一般会被修改吗？
> 
> 实测月度累积更新不会影响，成功安装。其他待测。 ![image](https://user-images.githubusercontent.com/36041971/142436037-d1d7428a-3f02-44e2-9e6c-47c9c36ebd5a.png)

能说下怎么设置的不？

**Comment by snowie2000** [comment]
我没有win11，但是一般来说除非你主动设置了拒绝权限，系统更新的权限都比你本身的用户权限更高。

**Comment by Jason-LJQ** [comment]
确实，系统更新都是使用TrustedInstaller用户进行的。曾经更新失败就是因为拒绝了TrustedInstaller对于Program Files某个文件夹的权限。因此对于该注册表目录我没改变它的权限。鉴于很多安全软件和系统本身都是以SYSTEM用户运行的，我修改了其权限，以及Administrators组。

**Comment by Jason-LJQ** [comment]
目前使用非常完美，除了不能针对某个系统共用进程（Shell Experience还是Runtime Broker还是其他的我忘了）的排除，使用 MMC操作控制台的系统应用（如任务计划程序、磁盘监视程序、计算机管理）都会模糊，可能与特殊的渲染机制冲突，因为本身这些界面自己的字体渲染都很好。
![image](https://user-images.githubusercontent.com/36041971/142440250-3b0ebf6f-ef32-424a-8fb1-e25086d46e25.png)

**Comment by digiant** [comment]
> 
以下代码导入到注册表可以解决MMC控制台模糊问题


Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Windows\\System32\\mmc.exe"="~ HIGHDPIAWARE"

**Comment by Jason-LJQ** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        很遗憾，实测没用。reg导入后重启电脑依旧模糊。
        
    
        
            
        
    
    
        
        

        
    

    在2021年12月20日 ***@***.***> 写道： 








以下代码导入到注册表可以解决MMC控制台模糊问题

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]

"C:\Windows\System32\mmc.exe"="~ HIGHDPIAWARE"

**Comment by digiant** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 很遗憾，实测没用。reg导入后重启电脑依旧模糊。 在2021年12月20日 ***@***.***> 写道： 以下代码导入到注册表可以解决MMC控制台模糊问题 Windows Registry Editor Version 5.00 [HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers] "C:\Windows\System32\mmc.exe"="~ HIGHDPIAWARE" —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

这个对125%缩放dpi有效果，详细可以看论坛讨论：https://bbs.pcbeta.com/viewthread-1915366-1-3.html

**Comment by 369258147tes** [comment]
想请问一下具体的操作方法，以及当前win10最新版是否适用。我是thinkpad，同样遇到了开启注册表模式失败的问题。

**Comment by Jason-LJQ** [comment]
> > font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 很遗憾，实测没用。reg导入后重启电脑依旧模糊。 在2021年12月20日 _**@**_._**> 写道： 以下代码导入到注册表可以解决MMC控制台模糊问题 Windows Registry Editor Version 5.00 [HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers] "C:\Windows\System32\mmc.exe"="~ HIGHDPIAWARE" —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: _**@**_.**_>
> 
> 这个对125%缩放dpi有效果，详细可以看论坛讨论：https://bbs.pcbeta.com/viewthread-1915366-1-3.html

今天上你提供的论坛网址上看了一下，你提供的代码与论坛提供的代码有出入，mmc.exe地址中应为//而非/，因此无效。使用更正后的注册表文件确实可以很好地解决mmc模糊的问题。

**Comment by 0verleaves** [comment]
> //

这个没影响的
