### ISSUE TITLE
启用Mactype后会导致twinkle tray失效

### ISSUE THREAD

**Issue by hanw233** [snowie2000/mactype#834]
版本	Windows 10 专业版
版本号	21H1
操作系统内部版本	19043.1348
Mactype版本   2021.1-RC1

本人一直在用twinkle tray调节外接显示器的亮度，非常方便。但是在启用mactype后发现twinkle tray无法识别显示器了。
既不想放弃mactype的字体渲染，也不想放弃twinkle tray的方便亮度调节，请问有同用这款软件的朋友吗，有没有啥解决方法呢？

<img width="265" alt="image" src="https://user-images.githubusercontent.com/56722028/146029572-54495d4d-2a5c-4212-a56a-b51d6e76a811.png">

**Comment by Rehoni** [comment]
目前也是这种情况，但是也可能是显示器比较旧的原因（因为近期更换了显示器），要不你试试在mactype中把twinkle tray的渲染去掉？

![image](https://user-images.githubusercontent.com/19381903/146102435-67d554b3-7298-4060-a2ef-c6a399ea46e2.png)

**Comment by hanw233** [comment]
非常感谢，将twinkle tray加入到不渲染的配置中后可以正常使用了。
