### ISSUE TITLE
请问默认字体的名字是什么？

### ISSUE THREAD

**Issue by BobbyatGithub** [snowie2000/mactype#837]
我想在word里打出 配置为default的系统显示字体，请问应该选择哪个字体？

**Comment by BobbyatGithub** [comment]
I would like to type the system display font in word, configured as "default" in MacType , which font should I choose?

**Comment by billowssun** [comment]
不行的，word不是使用独立的渲染引擎，和系统字体渲染引擎不一致，该软件只能代替系统渲染引擎。
