### ISSUE TITLE
Some apps will not even open in Windows 11

### ISSUE THREAD

**Issue by cssobral2013** [snowie2000/mactype#841]
Version: 2021.1 rc1

**Comment by ghost** [comment]
I'm using dual 4k screen at 150% dpi and Windows 11 had a lot of issues rendering fonts. I thought the screens were bad.

I installed this (as a service)  and wow the fonts are beautiful now. I just don't know where else to compliment the team behind this! But if you need to me test anything in Windows 11, let me know what apps you can't open and I'll try to open it too.
