### ISSUE TITLE
能否只对部分应用启用配置

### ISSUE THREAD

**Issue by Hsnico** [snowie2000/mactype#844]
搜狗输入法在 TIM 中文字会有严重的锯齿感，需要使用 mactype 来改善。
能否设置为只对有需要的应用启用渲染？
目前我的方法是先对所有应用停用，然后手动对有需要的应用启用渲染
![20220210_211042](https://user-images.githubusercontent.com/59398077/153414996-85bdc0ae-be88-4eed-b691-6ce616033c8a.jpg)

**Comment by sde31c** [comment]
在配置文件里设置UseInclude为1，然后在IncludeModule下列出需要渲染的程序。
https://github.com/snowie2000/mactype/wiki/UseInclude
