### ISSUE TITLE
Premiere Pro Loudness Radar display issue

### ISSUE THREAD

**Issue by Lingjun328** [snowie2000/mactype#857]
<img width="210" alt="Snipaste_2022-05-03_11-18-09" src="https://user-images.githubusercontent.com/32685284/166512643-ee2df147-be4d-4fa7-af1d-7474c30e824f.png">
If I enable MacType, it will happen as shown in the picture. 打开MacType后，Pr的Loudness Radar的数据会出现显示错误。

**Comment by sammilucia** [comment]
hi @Lingjun328. you'll need to add LoudnessRadar to the [UnloadDll] section of MacType.ini. They're doing something unusual with their fonts and we can't control for that unfortunately.

**Comment by Lingjun328** [comment]
Thanks!

**Comment by snowie2000** [comment]
According to the way the texts are distorted, I guess you can set "clipboxfix" to 0 for this app to make it happy.

**Comment by Lingjun328** [comment]
> According to the way the texts are distorted, I guess you can set "clipboxfix" to 0 for this app to make it happy.

Thanks! I just disable Premiere Pro in Process Manager, is that the same? I dont know how to  set "clipboxfix" to 0 😂

**Comment by snowie2000** [comment]
Clipboxfix is a tweak mactype introduced to fix clipping issues in some applications. By disabling it, only the tweak is disabled while the mactype itself is still functional. 

Just append 
[experimental@your-exe-file-name.exe]
ClipboxFix=0

to your profile and restart your radar

And don't forget to remove radar app from the unloaddll section.
