### ISSUE TITLE
VS2019 crashes when Mactype is in use

### ISSUE THREAD

**Issue by perdrix52** [snowie2000/mactype#868]
Mactype causes VS2019 to crash.

With Mactype installed (service mode) VS2019 crashes just after displaying the "splash screen" or the list of recent projects.

David

**Comment by wmjordan** [comment]
I've been using MacType from VS2008 and upgrading thru every VS versions.
Now I am using VS 2022 17.3 preview.
I never experienced anything wrong in VS caused by MacType.

What's your MacType configuration?
Do you use font substitution that usually causes problems?

**Comment by perdrix52** [comment]
I removed Mactype and VS2019 stopped crashing.   I'm rather busy ATM so don't really have the time to try Mactype again :(

**Comment by perdrix52** [comment]
Additional info VS2022 also wouldn't install.

**Comment by snowie2000** [comment]
If you're testing my second last patch in https://github.com/snowie2000/mactype/issues/864#issuecomment-1165148711, it's buggy. Please update your file to this one: https://github.com/snowie2000/mactype/issues/864#issuecomment-1182794113
