### ISSUE TITLE
开启mactype无法运行部分微软游戏

### ISSUE THREAD

**Issue by billowssun** [snowie2000/mactype#870]
打开地平线4、5无反应。

**Comment by snowie2000** [comment]
是从商店下载的正版吗？

**Comment by billowssun** [comment]
是的 steam正版

**Comment by billowssun** [comment]
下面列出的软件应用程序可能会导致Forza Horizon 4在播放时无法启动或崩溃。请确保您禁用或卸载，以确保成功的游戏。
1.罗技G中心（Logitech G Hub）

2.MSI加力燃烧室/Riva调谐器统计服务器（MSI Afterburner / Riva Tuner Statistics Server）

3.显卡超频软件（EVGA Precision）
4.OBS公司（OBS)

5.X分裂（Xsplit）

6.Discord

7.MacType公司(MacType)

8.华沙银行应用程序(Warsaw Banking App)

9.壁纸引擎(Wallpaper Engine)

10.蜗壳录音室(A-Volute Sound studio)
11.纳希米语音频(Nahimic Audio)
11.声波音频(Sonic Audio)
如果您正在使用OBS、Xsplit或任何其他流媒体程序，请将源代码设置为显示捕获。

我们建议在Windows中禁用游戏模式，并在您玩游戏时关闭任何超频、硬件监控、流媒体、录制和任何不必要的应用程序。

mactype在官方推荐关闭软件内，但是我需要两个都用，有什么办法规避吗？

**Comment by snowie2000** [comment]
然而我只有微软正版，没有steam呢。。。

**Comment by billowssun** [comment]
> 然而我只有微软正版，没有steam呢。。。

但是steam其他游戏也没有这种情况，就很困惑

**Comment by snowie2000** [comment]
不同的游戏有不同的引擎和反盗版反作弊设计，一般都是由于这类原因导致的。

我测试了windows store的forza4 demo，完全没有问题。

**Comment by FasterVermont** [comment]
我也出现了这一状况，极限竞速地平线4，请问将来会不会做个白名单之类的功能来解决这种问题呢

**Comment by FasterVermont** [comment]
我是微软正版

**Comment by snowie2000** [comment]
> 我也出现了这一状况，极限竞速地平线4，请问将来会不会做个白名单之类的功能来解决这种问题呢

https://github.com/snowie2000/mactype/wiki/UnloadDll

另外可以试一下新的预览版，有一些改进，也许会有用。注意保存资料，预览版没有经过大量测试

**Comment by FasterVermont** [comment]
谢谢！

**Comment by billowssun** [comment]
> 谢谢！

是否有用呢？请给个答复

**Comment by billowssun** [comment]
已解决，再次打开MacType Wizard 排除相关游戏 并且重启电脑，就可以进入游戏。

**Comment by i-am-not-able-to-code** [comment]
现在地平线5又打不开了，ForzaHorizon5.exe在ini里写入了[ExcludeModule][UnloadDll][ExcludeSub]依旧会报错找不到序数。“无法定位序数345于动态链接库（游戏文件路径）上。”停用MacType后就能顺利进入游戏。（我用的是独立加载模式）

**Comment by i-am-not-able-to-code** [comment]
> > 我也出现了这一状况，极限竞速地平线4，请问将来会不会做个白名单之类的功能来解决这种问题呢
> 
> https://github.com/snowie2000/mactype/wiki/UnloadDll
> 
> 另外可以试一下新的预览版，有一些改进，也许会有用。注意保存资料，预览版没有经过大量测试

现在地平线5又打不开了，ForzaHorizon5.exe在ini里写入了[ExcludeModule][UnloadDll][ExcludeSub]依旧会报错找不到序数。“无法定位序数345于动态链接库（游戏文件路径）上。”停用MacType后就能顺利进入游戏。（我用的是独立加载模式，版本为20230531）

**Comment by snowie2000** [comment]
序数345老问题了，只在部分电脑上出现，原因不明
