### ISSUE TITLE
MacType doesn't work and open on various programs

### ISSUE THREAD

**Issue by Rock-n-Roll-CRC** [snowie2000/mactype#872]
1) MacType doesn't open WebStorm + Chrome + Word
2) If I disable MacType and enable it after I opened Chrome / Webstorm / Word it just doesn't do anything ... Fonts are the same as they were without MacType

P.S MacType applies only for File Explorer for me ... How to fix ?

**Comment by snowie2000** [comment]
In my system, webstorm and chrome works perfectly fine and nothing special needs to be done. 

What's the problem when you enable mactype? App crash or something?

Chrome is sandboxed, so you can't render it after its start.

**Comment by Rock-n-Roll-CRC** [comment]
> 

Nothing, MacType seems to be working, but he applies only for file explorer. Chrome doesn't have anychanges with MacType enabled, webstorm just doesn't open when I click on the shortcut. But everything works fine at once I disable MacType

**Comment by snowie2000** [comment]
Which version are you on? The rc or one of the test versions I posted in some threads?

**Comment by snowie2000** [comment]
I've drafted a new test build, would you mind giving it a try?

**Comment by s5bug** [comment]
Installing the test build (uninstalling MacType, extracting the 7z to where MacType once was) made MacType generally not work (even though the service claims to be activated).

Attempting to proceed past this screen:

![image](https://user-images.githubusercontent.com/7751296/179894147-215b1cc1-a9f3-48a3-910a-e3fbac7ce963.png)

Crashes.

I'm wondering if my system is in some sort of invalid state (perhaps an installer package could fix this?)

**Comment by snowie2000** [comment]
Oh sorry, please re-download the test version. Some files are not the right version.

**Comment by s5bug** [comment]
New test version works beautifully 👍

**Comment by iHeadway** [comment]
> New test version works beautifully 👍

Where I can find it?

**Comment by snowie2000** [comment]
It's a pre-release, so it's hidden in the release section.
