### ISSUE TITLE
最新测试版1.2022.720.2 test build的字体渲染淡了很多

### ISSUE THREAD

**Issue by digiant** [snowie2000/mactype#874]
同样的配置文件下，最新测试版的字体明显感觉偏细偏淡，不知道怎么调了。

**Comment by snowie2000** [comment]
确实淡了一些，因为换了freetype的渲染引擎。
大体上renderweight+0.1和原版比较接近，但是对于宋体等还是淡一些。

**Comment by ssssssbbb** [comment]
> 确实淡了一些，因为换了freetype的渲染引擎。
> 大体上renderweight+0.1和原版比较接近，但是对于宋体等还是淡一些。

新参数和原有lcdfilterweight有什么区别

**Comment by snowie2000** [comment]
lcdfilterweight是cleartype渲染模式下特有的一个参数，基本上就是对笔划的粗细等产生一个微调作用。

 PixelLayout是harmony lcd rendering模式下特有的参数，是对lcd面板中RGB子像素的位置定义的方法，不同的lcd面板有完全不同的三原色排列（如钻石排列，Pentile，标准RGB）而ClearType模式下只能支持RGB横向排列。同时在HarmonyLCD模式下LCDFilterWeight无效。

**Comment by ssssssbbb** [comment]
> lcdfilterweight是cleartype渲染模式下特有的一个参数，基本上就是对笔划的粗细等产生一个微调作用。
> 
> PixelLayout是harmony lcd rendering模式下特有的参数，是对lcd面板中RGB子像素的位置定义的方法，不同的lcd面板有完全不同的三原色排列（如钻石排列，Pentile，标准RGB）而ClearType模式下只能支持RGB横向排列。同时在HarmonyLCD模式下LCDFilterWeight无效。

明白，谢谢

**Comment by snowie2000** [comment]
上个版本存在一个bug导致字体显示不太正常，新版本已修复。

**Comment by ssssssbbb** [comment]
> lcdfilterweight是cleartype渲染模式下特有的一个参数，基本上就是对笔划的粗细等产生一个微调作用。
> 
> PixelLayout是harmony lcd rendering模式下特有的参数，是对lcd面板中RGB子像素的位置定义的方法，不同的lcd面板有完全不同的三原色排列（如钻石排列，Pentile，标准RGB）而ClearType模式下只能支持RGB横向排列。同时在HarmonyLCD模式下LCDFilterWeight无效。

出差才回来试了下。。。这个Harmony LCD模式是没有开关，也就是说LCDFilterWeight直接失效了？反复看了说明都没有提及

**Comment by snowie2000** [comment]
harmonylcd是一个freetype编译开关，并且和cleartype渲染模式互斥，意味着他们无法同时生效并且不能在运行时切换。

**Comment by ssssssbbb** [comment]
> harmonylcd是一个freetype编译开关，并且和cleartype渲染模式互斥，意味着他们无法同时生效并且不能在运行时切换。

所以你觉得从理论上或从视觉上，HarmonyLCD对普通横排RGB有比ClearType模式强的地方吗，我试下来好像除了按P排的参数调会使效果更糟糕，没办法获得增强效果，即使想测试极端情况，按过度收紧的像素坐标比如-5,0,0,0,5,0，也无法获得过度锐利的极端效果，理论上也应该受物理子像素距离的限制，所以我不太理解这个除了应对P排还有其他作用吗

**Comment by snowie2000** [comment]
在我的电脑上，两者显示效果相当，没有明显的区别，不过我并没有设置过自定义LCDFilterWeight。

P排参数当然只能在P排的显示器上使用，在普通RGB横排显示器上使用只会有反作用。

HarmonyLCD的设计是可以自由定义rgb子像素的排列位置，理论上可以适应几乎所有lcd面板，所以兼容性肯定要好于cleartype模式，官方宣称由于harmonyLCD的设计原理，它生成的图像可以避免lcdfilterweight设置不当导致的彩边问题

**Comment by ssssssbbb** [comment]
> 在我的电脑上，两者显示效果相当，没有明显的区别，不过我并没有设置过自定义LCDFilterWeight。
> 
> P排参数当然只能在P排的显示器上使用，在普通RGB横排显示器上使用只会有反作用。
> 
> HarmonyLCD的设计是可以自由定义rgb子像素的排列位置，理论上可以适应几乎所有lcd面板，所以兼容性肯定要好于cleartype模式，官方宣称由于harmonyLCD的设计原理，它生成的图像可以避免lcdfilterweight设置不当导致的彩边问题

默认的LCDFilterWeight确实没有看出区别，调过之后差别很大，PixelLayout完全赶不上，在用于黑而不粗这方面，这是个不可或缺的参数，网上的配置99.9%都滥用加粗，字都给弄变形了。

我认为两个参数方向不同，PixelLayout着重点是子像素位置，LCDFilterWeight着重点是子像素亮度。有没有可能，两者故意设计成冲突只是因为LCDFilterWeight的子像素逻辑只适用于横排RGB，是因为不适合P排等异形排列，而不是对于适合它的横排RGB也不如PixelLayout？

所以，未来能否提供LCDFilterWeight的版本？或者说，让LCDFilterWeight在PixelLayout横排RGB参数的情况下生效？

**Comment by snowie2000** [comment]
目前我还不清楚freetype内部的代码逻辑是不是能做到两者可以并存，如果不能的话将会比较麻烦，可能要在安装程序上选择了

**Comment by ssssssbbb** [comment]
> 目前我还不清楚freetype内部的代码逻辑是不是能做到两者可以并存，如果不能的话将会比较麻烦，可能要在安装程序上选择了

感谢，我对你的敬仰犹如滔滔江水连绵不绝,又如黄河泛滥一发不可收拾
