### ISSUE TITLE
Settings for directwrite mode.

### ISSUE THREAD

**Issue by Dim-Tim-1963** [snowie2000/mactype#885]
Dear **snowie2000**, can you tell which INI settings work now in **directwrite** mode?  Is it possible to make, say, fonts in modern Firefox/Waterfox darker and thicker?

**Comment by snowie2000** [comment]
Every possible setting specifically available for DirectWrite is listed at https://github.com/snowie2000/mactype/wiki/DirectWrite-section

For making fonts of DirectWrite applications darker or thicker, I would have to say, maybe...

**Comment by Dim-Tim-1963** [comment]
Thanks!
...but still GDI rendering looks much better.  So I will keep Waterfox Classic while possible. :)
