### ISSUE TITLE
ECharts斜体字间距异常

### ISSUE THREAD

**Issue by fonlan** [snowie2000/mactype#888]
比如以下ECharts示例中的斜体，浏览器用的最新的102内核的CentBrowser，禁用DirectWrite和启用DirectWrite的截图，但禁用DirectWrite时字符间距不正常，有明显的粘连，启用DirectWrite后则一切正常。
https://echarts.apache.org/examples/zh/editor.html?c=dataset-encode1
![mactype_echarts](https://user-images.githubusercontent.com/7898348/186094977-aae29a1a-3db7-4531-86d3-cd4332d2cb9c.png)

**Comment by snowie2000** [comment]
MacType并不支持倾斜字体，所以你看到的界面是由GDI直接绘制的。
当然GDI对倾斜的支持也很不好……

**Comment by fonlan** [comment]
好吧，那看来没办法了，对这种倾斜字体的话DW是唯一解了
