### ISSUE TITLE
MacType 2021.1-RC1 版 服务模式 无法选择配置 注册表模式又不能用????

### ISSUE THREAD

**Issue by Tmalll** [snowie2000/mactype#891]
![Snipaste_2022-09-09_09-02-40](https://user-images.githubusercontent.com/40192806/189250925-ffc1c61c-04ea-451d-815d-c8d4b9b91801.jpg)
![image](https://user-images.githubusercontent.com/40192806/189250966-71a1c3c0-996c-486a-a435-480d4a56de2b.png)
服务模式, 底下那里选了配置不能点下一步.

**Comment by snowie2000** [comment]
需要点完成

**Comment by Tmalll** [comment]
点完成,下面这个框框里也不显示配置
![image](https://user-images.githubusercontent.com/40192806/189253791-7ec6c9fd-12de-4988-aace-d70e225b4d18.png)

2019版的就没这问题
![image](https://user-images.githubusercontent.com/40192806/189253857-343df3ea-dd7d-4e68-a2c2-3bffd42c1c91.png)

**Comment by snowie2000** [comment]
你就一个配置文件，根本没有更改，自然不会显示

**Comment by Tmalll** [comment]
> 你就一个配置文件，根本没有更改，自然不会显示

额好吧~~ 我又闹了个配置, 两个来回切了一下正常了, 可能刚才从2019版的换2021版的配置文件名一样

**Comment by snowie2000** [comment]
下面是显示配置变更的，如果配置没有变更就不会执行对应的配置刷新流程。

另外服务模式在RC1中不稳定，建议使用pre-release版本，目前看来还比较稳定的。

**Comment by Tmalll** [comment]
我用着还行, 之前2019版的在win11 22H2下面 用注册表模式也没啥问题, 换2021版的升级下哈
![image](https://user-images.githubusercontent.com/40192806/189254997-d7b8ef44-0f54-416a-959c-585ca117b5ba.png)

![image](https://user-images.githubusercontent.com/40192806/189255095-5354511d-c9cc-4f47-a964-b3edccc3b50f.png)


![image](https://user-images.githubusercontent.com/40192806/189255160-ef76e73e-f9e5-4a5e-8c4f-affc048eef9f.png)

**Comment by snowie2000** [comment]
注册表模式是很奇怪的，有些人不管什么系统都不出问题，有些人就各种死机崩溃。

**Comment by Tmalll** [comment]
我感觉服务模式有点问题 这centbrowser又不渲染了,
![image](https://user-images.githubusercontent.com/40192806/189256242-248e4ae5-334b-4deb-b2df-59db0b32cbff.png)

但是另外的标签页又渲染了
![image](https://user-images.githubusercontent.com/40192806/189256400-995da77b-e72f-4972-a510-5136253c7401.png)

**Comment by Tmalll** [comment]
> 注册表模式是很奇怪的，有些人不管什么系统都不出问题，有些人就各种死机崩溃。

早起版本win10 我遇到过蓝屏 好像是1607 还是1709这种版本, 好像是复制注册dll的时候被自带wdf给拦截了, 进pe把那几个dll删掉就ok了, 后来就再没碰到过
