### ISSUE TITLE
我有个需求不知道怎么配置，希望有大神帮忙给个配置

### ISSUE THREAD

**Issue by bestv5** [snowie2000/mactype#892]
我希望所有进程都不渲染和加载dll，只有资源管理器渲染。这个配置该怎么配置。

**Comment by snowie2000** [comment]
使用包含模式。

https://github.com/snowie2000/mactype/wiki/UseInclude

此模式一定会出现延迟渲染，不可能解决。

**Comment by bestv5** [comment]
> 使用包含模式。
> 
> https://github.com/snowie2000/mactype/wiki/UseInclude
> 
> 此模式一定会出现延迟渲染，不可能解决。
如果我只是想渲染资源管理器(explorer.exe)，其他应用不渲染和dll处理，是按下面的配置进行配置吗？
1. 在Mactype.ini添加下面的内容
UseInclude=1
[IncludeModule]
explorer.exe
2. 然后删除[ExcludeModule] and [UnloadDll] 下面的内容。

我提出这种需求，是因为经常遇到某个应用出现没有权限、加载dll错误问题，为了不单独添加这些进程进行忽略，想出了只渲染资源管理器进程的需求。

**Comment by snowie2000** [comment]
dll加载错误的问题已经讨论了很久了，但是没有人有一个比较靠谱的答案，我自己从来没遇到过，所以无法解决。

没有权限的问题我也有遇到，但是似乎是随机发生的，概率也不高，很难稳定的重现，暂时没有办法找到真正的原因。

**Comment by bestv5** [comment]
> dll加载错误的问题已经讨论了很久了，但是没有人有一个比较靠谱的答案，我自己从来没遇到过，所以无法解决。
> 
> 没有权限的问题我也有遇到，但是似乎是随机发生的，概率也不高，很难稳定的重现，暂时没有办法找到真正的原因。

我发现把 dll加载错误和权限问题发生的进程配置在UnloadDll中，就不会发生，那么能不能通过配置达到程序只渲染但不会进行loaddll处理呢？

**Comment by snowie2000** [comment]
不loaddll怎么渲染………………

你把程序放在UnloadDll中不就是告诉MacType不要渲染这个程序吗？

**Comment by bestv5** [comment]
> 



> 不loaddll怎么渲染………………
> 
> 你把程序放在UnloadDll中不就是告诉MacType不要渲染这个程序吗？

原来是这样，那我只能用UseInclude模式了，谢谢

**Comment by bestv5** [comment]
UseInclude 模式能配置在Mactype.ini里面吗，我想对所有配置都生效，在切换配置的时候不用单独改配置文件了。需要怎么配置？

**Comment by snowie2000** [comment]
你可以试试看，UseInclude是一个历史遗留……基本上没有做过多少测试🤣
