### ISSUE TITLE
How can use a beta version of a mactype?

### ISSUE THREAD

**Issue by rebron1900** [snowie2000/mactype#895]
After uninstall RC1,  just download the beta version and run it?

**Comment by snowie2000** [comment]
Either uninstall your previous installed version and download the new one or just stop the previous version and overwrite all the files with the new one (w/o the included profiles) should do.

**Comment by rebron1900** [comment]
大佬，beta版本在Chrome的渲染效果现在如何了？能和百分浏览器关了DW比么？

**Comment by snowie2000** [comment]
> 大佬，beta版本在Chrome的渲染效果现在如何了？能和百分浏览器关了DW比么？

不能，DW的渲染就没有进步过，微软一直从win10某个版本开始就没有改过渲染效果了。

**Comment by rudolphos** [comment]
>stop the previous version and overwrite all the files with the new one

Can't. MacType service is stopped, but shows this:
![image](https://user-images.githubusercontent.com/4366810/191947144-80f9ed6d-905c-4660-9cc4-062cc5a4b20e.png)

**Comment by snowie2000** [comment]
Stop the mactype from the Wizard and restart your computer.
