### ISSUE TITLE
Some fonts on certain programs not rendered properly without turning on ClearType.

### ISSUE THREAD

**Issue by Extatement-Nongly** [snowie2000/mactype#897]
I am using MacType ver.2021.1-RC1 and some fonts won't render properly without ClearType. I am also using Registry Mode, but this problem also occurs in Service Mode as far as I can tell. I use a [custom profile](https://drive.google.com/file/d/1R21l8fQuLq5zWKeOPpUux_OKhQccs5v0/view?usp=sharing) that's based entirely on Grayscale anti-aliasing:

Using IBM SPSS Statistics as an example;
Without ClearType
![without ct ibm](https://user-images.githubusercontent.com/50505051/192819392-f404d8f3-6b2a-4f22-aa54-1dd86654627e.PNG)
With ClearType
![with ct ibm](https://user-images.githubusercontent.com/50505051/192819664-7dd64af6-3d11-497e-ac2d-b9c75541c098.PNG)
As you can see, MacType is only rendering the font according to my profile when ClearType is on, but I have another weird observation to show.

Using MacType Wizard as an example;
Without ClearType
![without ct mt](https://user-images.githubusercontent.com/50505051/192820414-c877e3ba-72b2-49f6-9d8e-e0af2efda106.PNG)
With ClearType
![with ct mt](https://user-images.githubusercontent.com/50505051/192820464-7166a8ec-8fc0-42d0-a583-faf5ac59f1b4.PNG)
This time, the program completely ignores MacType and opts to use ClearType instead.

**Comment by snowie2000** [comment]
First, as I stated before, turning on cleartype changes the way windows renders the fonts. So in some cases it has to be turned on to make mactype in effect. 

Second, all mactype components have built in mechanisms to prevent mactype from rendering them. In case you messed up your profile in accident, you always have a chance to disable mactype.
