### ISSUE TITLE
MacType makes fonts unable to delete in Windows 11

### ISSUE THREAD

**Issue by cssobral2013** [snowie2000/mactype#898]

**Comment by sammilucia** [comment]
hey! can you please be more specific? Windows 11 has a lot of restrictions for deleting fonts to start with.

1. which fonts are you trying to delete?
2. have you confirmed you can delete the fonts without the MacType Tray / MacType Service running?

**Comment by cssobral2013** [comment]
1. This issue is displayed with any font, but is displayed sometimes;
2. When I uninstall Mac Type, I can delete fonts normally.

Em qua., 5 de out. de 2022 12:42 AM, Samantha Glocker <
***@***.***> escreveu:

**Comment by snowie2000** [comment]
So it only happened when you delete fonts from windows settings or it happened anywhere like deleting a font from Desktop?

**Comment by cssobral2013** [comment]
Either way.

Em qua., 12 de out. de 2022 5:03 AM, snowie2000 ***@***.***>
escreveu:
