### ISSUE TITLE
not work for Directwrite when ID2D1DCRenderTarget binded to a layeredwindows memory dc

### ISSUE THREAD

**Issue by fxliang** [snowie2000/mactype#900]
when directly draw to memory dc in GDI way, for layeredwindow, it works fine
![image](https://user-images.githubusercontent.com/4023160/196631275-c97ffa2b-e2d2-4095-b194-5ad07da82aed.png)
if use directwrite ID2D1DCRenderTarget binded to the same memory dc, it not work
![image](https://user-images.githubusercontent.com/4023160/196631453-76b4fcfa-dcc3-4830-aa9f-7eb637a36c75.png)

don't know why.

**Comment by snowie2000** [comment]
It works. It just doesn't work as good as you want it to be.

**Comment by fxliang** [comment]
got it
