### ISSUE TITLE
我有个极棒的字体不知道怎么配置，希望得到大佬帮助

### ISSUE THREAD

**Issue by qq000945** [snowie2000/mactype#902]
https://tieba.baidu.com/p/8102564454

【冷门提问】如何设置这种‘轻松使用设置中心’加载的带阴影字体

![9224b00a19d8bc3e5d5d7c0bc78ba61eaad345c4](https://user-images.githubusercontent.com/67133551/197740309-a0a23ac8-050a-4811-8331-11507ca490df.jpg)
![7c2e961ea8d3fd1fb35cd8fb754e251f97ca5fc4](https://user-images.githubusercontent.com/67133551/197740321-1c1e515e-17c0-4d54-b686-4d21c5de40ef.gif)
![4f9003fa828ba61e58bbb2ee0434970a324e59c4](https://user-images.githubusercontent.com/67133551/197740347-53f5f62a-2ba7-4087-8e37-50c31015e752.jpg)
↑如图所示，在‘轻松使用’中心里，按一下随便里边的某些设置，字体就会被改成这种方便残障人士阅读的带阴影的效果？（真的很酷炫，但是重启桌面后效果就会消失，自己怎么改也改不出来）

如图，所有字体都能加上这种酷炫的阴影（我自己用的默认是方正尚酷简体，别的字体也行）。。。。大家应该按一下都能弄出来，但是无法保存啊
![85513ad162d9f2d332515e2eecec8a136127ccd1](https://user-images.githubusercontent.com/67133551/197740420-caed8e13-df6f-452a-a2ac-a9d9d9f29c46.gif)

求教，有大佬能解释一下这个改阴影的原理吗？为何字体会自动切换成这种。。有没有人能复刻出这种效果来

**Comment by snowie2000** [comment]
mactype有阴影功能，但效果和Windows桌面的不同，桌面的那种阴影需要计算模糊，这会消耗比较多的性能，并且和背景混合也较为复杂。

![shadow](https://user-images.githubusercontent.com/11767189/197957947-a3ef3f7f-92f4-4f4f-87b9-532254c723b0.png)

如你所见，mactype支持的阴影是没有模糊的，但支持双色阴影（浅色和深色文字自识别）

**Comment by qq000945** [comment]
@snowie2000 十分感谢作者大人的答复   MacType是老牌美化软件，咱从小就见电脑城里有人用过了，未来有办法实现轻松访问的这种字体效果吗

**Comment by snowie2000** [comment]
@qq000945 不能实现，轻松访问那个也不能做到全局生效。这种字体投影是比较复杂的，也比较消耗性能，所以不会在所有软件上都实现，Windows也是如此。

**Comment by qq000945** [comment]
![210720095248147](https://user-images.githubusercontent.com/67133551/206073793-eb89a20a-f8f0-4184-a35a-fd776f08c6a4.png)
![uTools_1670379825435](https://user-images.githubusercontent.com/67133551/206073806-17fe6427-b8c0-42b1-b27e-ecca09844594.png)
![uTools_1670380379451](https://user-images.githubusercontent.com/67133551/206073811-003893f1-9e94-411d-a7d1-585b4dd2072f.png)

@snowie2000 问题已解决，安装主题软件StardockCurtains。安装后无需设置直接卸载，卸载时勾选2项即可，字体阴影会长久保持，某些地方的字体也会变得更优美好看

**Comment by snowie2000** [comment]
stardock的东西真是灵丹妙药
