### ISSUE TITLE
Stopped working in Brave Browser two days ago

### ISSUE THREAD

**Issue by clockworkwhale** [snowie2000/mactype#905]
Still works fine on the rest of the system and in Firefox, so it seems that this is the result of a change on Brave's end. Brave version update that broke it was Version 1.45.123 Chromium: 107.0.5304.110 64-bit

Tested with Mactype v1.2022.801.0 preview and 2021.1-RC1, no difference, neither version works with Brave anymore.

**Comment by ikaio** [comment]
same problem

**Comment by snowie2000** [comment]
Just tested on brave [Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)] with 2022.801, works fine.

**Comment by clockworkwhale** [comment]
> Just tested on brave [Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)] with 2022.801, works fine.

Confirmed by visual inspection of rendered fonts or just using process manager? Because for me the process manager does report that it's running on Brave, it's only when you look at the fonts you can clearly see that it is not actually working. Been the case since build 1.45.123 (have now updated to 1.45.127 and problem remains).

**Comment by snowie2000** [comment]
It's pretty obvious if you visit any sites with CJK fonts. It's night and day difference.

**Comment by clockworkwhale** [comment]
Yeah, fair enough. In that case I have no theory for why it's stopped working for me and the other guy in new versions of Brave. Windows 10 or 11? I'm on 10 here.

**Comment by snowie2000** [comment]
Windows 10 here. Maybe you could post your profile and let's see if something could be the culprit?

**Comment by clockworkwhale** [comment]
Sure, thanks for looking into it. I'm on the default profile, here the full contents of my default.ini: https://rentry.org/26fke

I'm currently running it in Tray mode (admin) but have tried Service mode too which did not fix Brave (works fine for every other app).

**Comment by snowie2000** [comment]
In my early tests, `ArmBreaker` has to be 2 to make chromium-based browsers work.

**Comment by clockworkwhale** [comment]
Unfortunately Armbreaker 2 did not resolve it. But since it's working for you, it seems clear that this problem is just some new quirk of my own system rather than a problem with Mactype. Gonna go ahead and close this, many thanks for trying to help!

**Comment by snowie2000** [comment]
I tried your profile (with armbreaker=1), and surprisingly, it worked with both chrome and brave.

There must be something missing in my previous tests.
