### ISSUE TITLE
MacType github hosted Wiki is currently being targeted by spammers (n/t)

### ISSUE THREAD

**Issue by garoto** [snowie2000/mactype#908]

**Comment by snowie2000** [comment]
I didn't see any changes. Which page was targeted?

**Comment by garoto** [comment]
> I didn't see any changes.

Because I reverted all previous spam edits.

https://github.com/snowie2000/mactype/wiki/Home/_history

**Comment by snowie2000** [comment]
I see, thank you so much!

I've restricted wiki editing to collaborators only for now.
