### ISSUE TITLE
导致Onedrive、Snipaste崩溃

### ISSUE THREAD

**Issue by jiabaoyu** [snowie2000/mactype#909]
使用的版本：
> Windows 11  (build 22621.819)
屏幕分辨率:	5120 x 2160
MacType版本:	2022.1 
MacTray版本:	1.0.2021.1
MacTuner版本:	1.0.2.361

出现的问题：Onedrive打开托盘图标时会崩溃、Snipaste启动崩溃。

我的两台PC，其系统版本完全一致，此问题仅在我其中一台上出现。

Snipaste崩溃的问题，经联系其维护者后确认是Mactype造成，他提供了一个“Qt6Gui.dll”文件，在替换掉Snipaste的该dll之后，Snipaste可以正常使用了。

虽然我试过排除Onedrive相关的进程（OneDrive.exe, FileCoAuth.exe, dllhost.exe），取消了Mactype的开机启动并重启电脑，点击Onedrive的托盘图标打开其面板仍旧会使其崩溃。

附上crash日志
>C:\ProgramData\Microsoft\Windows\WER\ReportArchive
[ReportArchive.zip](https://github.com/snowie2000/mactype/files/10118993/ReportArchive.zip)
>
>%localappdata%\CrashDumps
[CrashDumps.zip](https://github.com/snowie2000/mactype/files/10118999/CrashDumps.zip)

**Comment by snowie2000** [comment]
> 虽然我试过排除Onedrive相关的进程（OneDrive.exe, FileCoAuth.exe, dllhost.exe），取消了Mactype的开机启动并重启电脑，点击Onedrive的托盘图标打开其面板仍旧会使其崩溃。

mactype在关闭开机启动后就不存在任何影响了，所以显然是onedrive自己存在问题。
另外onedrive是一个和系统集成极其紧密的软件，调试它是非常困难的，如果能重现snipaste的话会容易解决很多。

**Comment by jiabaoyu** [comment]
> mactype在关闭开机启动后就不存在任何影响了，所以显然是onedrive自己存在问题。 另外onedrive是一个和系统集成极其紧密的软件，调试它是非常困难的，如果能重现snipaste的话会容易解决很多。

我在 `C:\Program Files\Microsoft OneDrive\xxx版本号` 下发现它也用了很多Qt的dll，想必也与此有关。
比较诡异的是，我其中一台PC完全没出现这问题。这边提供一下Snipaste的相关链接以供研究。

这是Snipaste的下载链接
https://dl.snipaste.com/win-x64-beta

这是Snipaste维护者提供的替换dll
https://github.com/Snipaste/feedback/files/10108628/Qt6Gui.zip

**Comment by jiabaoyu** [comment]
对了， 在snipaste发issue后， @liulex 提示我是mactype引起的。由于我当时在使用的PC是不受影响的那台，当即使用todesk远程控制了有问题的PC，当时仅退出了mactype，snipaste和onedrive的面板都没问题了。但当我直接使用该PC时，确认了没打开mactype，崩溃的问题又出现了。之后又尝试过使用todesk远程连接该PC，可惜未能复现当时关闭mactype即修复崩溃的情况。

**Comment by snowie2000** [comment]
试了链接中的snipaste版本，但是并没有崩溃😫

**Comment by jiabaoyu** [comment]
这就尴尬了。我之前用的是mactype官网下载的安装版，后来由于OneDrive崩溃，卸载后OneDrive倒是没事了。但是其他的文字渲染太丑陋了。
于是从GitHub下载了最新的beta zip。发现OneDrive依旧崩溃。这回是不用mactype都崩溃了。还重装过系统，再重新启用mactype，过了1天又崩了😢

一开始以为是残留的啥配置文件导致的，看了一下所有文件都在软件所在的文件夹中。
![image](https://user-images.githubusercontent.com/12813865/204732552-62858dab-6ce1-4ec9-9ce2-3dfc8bdf0ce1.png)

**Comment by snowie2000** [comment]
github中的release页还有隐藏的rc2版本，但只是新增了功能，修复了服务模式的一些稳定，并没有涉及到渲染的兼容性修正。
只是没有开mactype也能崩溃…………我就无法解释了。

mactype基本上算半个绿色软件，因为要自启动不得不写注册表和服务，除此以外是不会放文件到别的文件夹去的

**Comment by jiabaoyu** [comment]
其实自启动可以把一个软件的快捷方式放到
%AppData%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
或
%ProgramData%\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by snowie2000** [comment]
> 其实自启动可以把一个软件的快捷方式放到
%AppData%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
或
%ProgramData%\Microsoft\Windows\Start Menu\Programs\Startup

你要知道在uac环境下，这样启动的程序是只有用户权限的。

**Comment by jiabaoyu** [comment]
我都是直接关闭UAC的，那用户手动启动是否会存在没有管理员权限的问题？

**Comment by snowie2000** [comment]
关闭uac后自然就不存在权限问题了，但是win8开始uac是无法直接关闭的，只有改注册表才行，在控制面板（设置）中关闭uac并不会真正关闭。

**Comment by jiabaoyu** [comment]
猜想是权限问题，刚刚试了手动以管理员身份运行依旧崩溃😢

**Comment by snowie2000** [comment]
snipaste你可以用旧版重现吗？如果可以的话，请发给我一个crashreport
onedrive就算了，基本上没法处理的

**Comment by jiabaoyu** [comment]
snipaste的crashreport就是上边提供的，替换了Qt6Gui.dll之后就不会崩溃了。
我主要是来问OneDrive的，毕竟让微软去支持mactype不知道要等到什么时候。
![image](https://user-images.githubusercontent.com/12813865/204736907-f8618348-1b45-45dd-9baf-f57273da4b54.png)
现象就是点击托盘图标后能弹出面板，但是面板会卡死在这个画面，然后应用崩溃重启

**Comment by snowie2000** [comment]
我看了下，你是不是在配置中使用了替换字体？

**Comment by jiabaoyu** [comment]
没有，我配置中并未设置替换字体。
```
[General]
Name=Default
Icon=..\mactray.exe.ico,0

;【自动挂钩子进程】
;[0:Disable]  1:Enable
HookChildProcesses=1

;【字体微调】
;0:Normal 1:NoHinting 2:AutoHinting 3:Light+AutoHinting
HintingMode=1

;【抗锯齿方式】
;-1:Disable 0:Normal 1:Light 2:LCD(RGB) 3:LCD(GBR) 4:Light-LCD(RGB) 5:Light-LCD(GBR)
AntiAliasMode=4

;【常规体调整】
;-32:+32
NormalWeight=16

;【粗体字的调整】
;-16:+16
BoldWeight=2

;【斜体字的倾斜角度微调】
;-16:+16
ItalicSlant=0

;【只有在FontLoader=0（在下面）时此项设置才有效。建议选0，选1会占用大量内存，也没看出有什么好处。】
;0:Disable 1:Enable
UseMapping=0

;【Gamma模式开关】
;-1：关闭；0：使用设置的Gamma值（GammaValue）；1：使用sRGB的Gamma值；2：不明
GammaMode=0

;【Gamma值】
;GammaMode=0的时候此项设置才有效
;sRGB ≒ 2.2 CT-Default = 1.4
;windows的cleartype的Gamma值是1.4
GammaValue=1.5

;【对比度】
;数字越大越锐利，数字越小越发虚
Contrast=1.7

;【字体轮廓】
;数字越大字体就越粗越黑
RenderWeight=1.4
; DirectWrite 支持；DirectWrite support
DirectWrite=1

;【文字边界设置】
;数字越大越强调背景（类似文字边界被侵蚀的感觉），强调背景会有中字体锐利的感觉。适当降低对比度，提高TextTuning，可以使文字周围的颜色看起来“淡一点”
;再加上RenderWeight，把这三个设置的微妙平衡调节好的话，能得到不输给Mac的效果
;0:12

;AntiAliasMode=1时，通过TextTuning分量来调节
TextTuning=0

;AntiAliasMode=2时，通过TextTuning的RGB分量来调节
TextTuningR=4
TextTuningG=4
TextTuningB=4

;【字体加粗模式】
;对NormalWeight和BoldWeight有效
;0：Weight值大时横向加粗，值小时双向加粗，主要是避免Weight值过大时，模式3中在小字号时加粗过度出现斩头的现象；
;1：总是横向加粗；
;2：总是双向加粗，也就是freetype本身的粗体渲染。
;注意：通过加大GammaValue、TextTuning的值，可以减少Weight值过大的造成的效果问题，即可以在BolderMode=2时也可以避免转接头
BolderMode=0

;【字体的载入方法】
;（注意是载入方法，不是渲染方法）
;0：用freetype载入字体
;1：用windows的绘图核心载入字体
;很多freetype的设置需要此项选0才能生效
FontLoader=0

;【字体链接】
;当FontLoader=0时
;0：什么都不做；
;1：使用注册表里的字体链接设置，通过FreeType的字符表进行查找
;2：使用注册表里的字体链接设置，使用Windows的转换函数直接查找
;当FontLoader=1时
;会保持启用的状态，但是所有字体链接的处理会交由WIN32API完成。
FontLink=2

;【字体替代】
;当FontLoader=0时
;0：什么都不做；
;1：安全替换方案（兼容性较好），根据以下FontSubstitutes的配置进行替换；
;2：完全替换方案（效果较全面，如替换后出现乱码，请尝试使用1），根据以下FontSubstitutes的配置进行替换；
;当FontLoader=1时
;会保持启用的状态，但是所有字体替代的处理会交由WIN32API完成
FontSubstitutes=0

;【让freetype处理的最大的字体尺寸，单位是像素，0的话就是全尺寸】
;交付 gdi++ 处理的最大尺寸（单位为像素）
;0-2147483647
MaxHeight=0

;【阴影设置】
;格式：水平偏移,垂直偏移,阴影深度（值越大，越浅）	
;Shadow=1,1,5

;【液晶显示器的优化配置】
;[0:None]  1:Default  2:Light  16:Legacy
LcdFilter=2

;【字体缓存、内存的设置】
LoadOnDemand=1
CacheMaxFaces=256
CacheMaxSizes=6140
CacheMaxBytes=20485760

;【强制使用某一个字体】
;无视所有其他字体，全系统的字体都会被这里设置的字体代替
;ForceChangeFont=华文中宋

[DirectWrite]
;渲染模式，0=默认，1=锯齿，2=经典，3=经典自然，4=自然，5=自然对称，6=字体原型
RenderingMode=6
;Gamma值，不写则根据上面的GammaValue自动计算
GammaValue=1.5
;对比度，默认为1
Contrast=1.0
;抗锯齿程度，默认1
ClearTypeLevel=1

[Individual]
;【单独设置的字体】
;格式＝Hinting, AAMode, NormalWeight, BoldWeight, ItalicSlant, Kerning
XSong=,,30,,,
XSong SimSun=,,30,,,
XSong Mono=,,30,,,
宋体=,,30,,,
新宋体=,,30,,,
华文宋体=,,30,,,
华文中宋=,,30,,,
Batang=,,30,,,
MingLiU=,,30,,,
PMingLiU=,,30,,,
PMingLiU_HKSCS=,,30,,,
MingLiU_ExtB=,,30,,,
PMingLiU_ExtB=,,30,,,
PMingLiU_HKSCS_ExtB=,,30,,,
MS Mincho=,,30,,,
MS PMincho=,,30,,,

[Exclude]
;【除外的字体】

[ExcludeModule]
;【不渲染的程序，但仍会加载DLL】



[FontSubstitutes]
;【字体替代】
;系统在调用“=”前面的字体时会忽视“=”前面的字体，而去直接调用“=”后面的字体
SimSun=XSong SimSun
@SimSun=XSong SimSun
NSimSun=XSong Mono
@NSimSun=@XSong Mono
PMingLiu=XSong SimSun
MingLiu=XSong SimSun
;微软雅黑=XSong SimSun



[Experimental]
;the aggressiveness to disarm the OS protection. 
;0=do nothing
;1=remove force MS signed binary
;2=degrade Dynamic code generation protection
ArmBreaker=1

[Experimental@Firefox.exe]
ClipBoxFix=1
[UnloadDll]
AdobeIPCBroker.exe
audiodg.exe
AutoDarkModeSvc.exe
avgnt.exe
AxureRP.exe
bleachbit.exe
CCXProcess.exe
ConEmuC.exe
ConEmuC64.exe
cyberpunk2077.exe
dllhost.exe
dwm.exe
Fetion.exe
FileCoAuth.exe
FontCreator.cn.exe
FontCreator.exe
fontforge.exe
Fontforge_EN.exe
Fontforge_SC.exe
Fontforge_TC.exe
fontview.exe
gnucash-bin.exe
igfxCUIService.exe
igfxEM.exe
igfxHK.exe
lass.exe
MsMpEng.exe
mspdbsrv.exe
node.exe
notecase.exe
notecaselauncher.exe
NVDisplay.Container.exe
OfficeClickToRun.exe
ollyice.exe
OneDrive.exe
pia-service.exe
PlantsVsZombies.exe
QHActiveDefense.exe
QHSafeTray.exe
QHWatchdog.exe
RuntimeBroker.exe
sc2.exe
SearchFilterHost.exe
SearchIndexer.exe
SearchProtocolHost.exe
services.exe
spoolsv.exe
stacsv64.exe
svchost.exe
SynTPEnh.exe
SynTPHelper.exe
taskhostw.exe
unsecapp.exe
VBoxSVC.exe
VirtualBox.exe
vmnat.exe
vmnetdhcp.exe
vmware-authd.exe
vmware-usbarbitrator64.exe
vmware-vmx.exe
war3.exe
xd.exe
xdict.exe
[ExcludeSub]
devenv.exe
dllhost.exe
FileCoAuth.exe
javaw.exe
OneDrive.exe
PPLive.exe
QQGame.exe
svchost.exe
```

**Comment by snowie2000** [comment]
我查看了异常，都是在创建字体时出错的，但是更多的代码信息由于各种原因完全看不到，我试试看改改

**Comment by snowie2000** [comment]
OK，我修改了下字体创建相关的hook，你试一下使用附件中的文件覆盖。

[MacType-hook-opt.zip](https://github.com/snowie2000/mactype/files/10121374/MacType-hook-opt.zip)

**Comment by jiabaoyu** [comment]
谢谢。试了替换+重启，依旧崩溃。
[OneDrive.exe.3280.zip](https://github.com/snowie2000/mactype/files/10121515/OneDrive.exe.3280.zip)
[AppCrash_OneDrive.exe_18b9156b4c2af726dabb6d9f1bb4b16feed6d6a2_c615d21a_5fe8d12c-caa2-4658-ba58-53676e885893.zip](https://github.com/snowie2000/mactype/files/10121520/AppCrash_OneDrive.exe_18b9156b4c2af726dabb6d9f1bb4b16feed6d6a2_c615d21a_5fe8d12c-caa2-4658-ba58-53676e885893.zip)

**Comment by snowie2000** [comment]
请测试一下snipaste，onedrive那个你连不开mactype都能崩溃，显然不是我可以解决的。

**Comment by snowie2000** [comment]
onedrive建议你删除后重新安装，也许是在安装的过程中受到mactype的影响导致有文件没有正常的复制进去

我查看了错误报告，onedrive没有加载任何和mactype相关的文件，所以问题肯定不可能出在我这边的代码上，毕竟……他连运行的机会都没有啊

**Comment by jiabaoyu** [comment]
嗯，我再研究研究吧。测试了在退出mactype的情况下重装、启动，依旧崩溃。
> 我查看了异常，都是在创建字体时出错的

话说有没有可能是我用Font Replace Utility替换了系统字体文件导致的？但是我另一台PC也进行了同样的操作，完全没事😂

**Comment by snowie2000** [comment]
系统字体不要替换他，高版本的Windows对系统字体相当敏感，xp之类的就无所谓，很难坏掉

**Comment by jiabaoyu** [comment]
我试着重装系统来恢复原始字体试试吧。
主要微软雅黑的hinting太恶心了，即使配合mactype，看起来也是一坨💩

**Comment by jiabaoyu** [comment]
绝了。重装完，没开mactype，依旧崩溃了
[AppCrash_OneDrive.exe_b6b32d3be86fa2ef49a8a4e7721ceaa7e14cf65_c615d21a_0feac0e0-0f43-40d4-ae41-ce99bd556d9c.zip](https://github.com/snowie2000/mactype/files/10121957/AppCrash_OneDrive.exe_b6b32d3be86fa2ef49a8a4e7721ceaa7e14cf65_c615d21a_0feac0e0-0f43-40d4-ae41-ce99bd556d9c.zip)

[OneDrive.exe.11268.zip](https://github.com/snowie2000/mactype/files/10121958/OneDrive.exe.11268.zip)

**Comment by jiabaoyu** [comment]
对了，今天发现一个小bug：点击按“进程ID”排序，必定出现mactype的崩溃。
![image](https://user-images.githubusercontent.com/12813865/204773768-d6b19cde-b269-4254-830a-b7535c983aaa.png)

**Comment by snowie2000** [comment]
里面可以保存错误日志，麻烦保存后上传一下，谢谢

**Comment by jiabaoyu** [comment]
![image](https://user-images.githubusercontent.com/12813865/204778202-bbfb15ab-33ef-41f5-bce8-a4b7828ac640.png)
点击send report，它一直要求通过outlook发送，而在outlook中登录邮箱转半天都登不上

**Comment by jiabaoyu** [comment]
[bugreport.txt](https://github.com/snowie2000/mactype/files/10122429/bugreport.txt)

**Comment by snowie2000** [comment]
好的，谢谢，我去检查一下。send report是不会成功的，因为我没有配置smtp和对应的目标邮箱。
