### ISSUE TITLE
无法替换使用管理员身份开启的应用中的部分字体

### ISSUE THREAD

**Issue by KinComet** [snowie2000/mactype#910]
# 简述
替换字体部分无效，渲染有效。发生在极大多数应用中。
例如 Mem Ruduct
管理员身份：
![image](https://user-images.githubusercontent.com/111748332/205230102-b5def6ee-25b8-4c4e-a1de-2896e0c47298.png)
非管理员：
![image](https://user-images.githubusercontent.com/111748332/205230133-7eaa74eb-3735-4bfa-acfd-21bfea59a0ae.png)

**Comment by snowie2000** [comment]
正常现象，因为从未提升的explorer启动一个提升的应用，中间要穿过一层UAC，mactype是不可能做到的，所以实际上是程序先启动，mactype再渲染上去，这时候有些程序的字体已经创建完成了，就无法再替换了。

除了以前的注册表模式外，没有任何办法可以解决。

**Comment by Rothes** [comment]
> 正常现象，因为从未提升的explorer启动一个提升的应用，中间要穿过一层UAC，mactype是不可能做到的，所以实际上是程序先启动，mactype再渲染上去，这时候有些程序的字体已经创建完成了，就无法再替换了。
> 
> 除了以前的注册表模式外，没有任何办法可以解决。

了解。使用注册表模式解决。

**Comment by KinComet** [comment]
已使用注册表模式解决
