### ISSUE TITLE
Why there're still a lot of applications using Microsoft YaHei UI font even if I set FontSubstitutes to 2 and turned on the DirectWrite mode？

### ISSUE THREAD

**Issue by ACCoder2009** [snowie2000/mactype#912]
I love the font and the font rendering of MacOS, so I wrote a .ini files based on the XMac.LCD.Default.ini in XMac folder. I installed the Pingfang font which is the default font of MacOS to my computer. As the picture shows, I have set FontSubstitutes to 2 and turned on the DirectWrite mode.I also set ForceChangeFont to PingFang Bold. Yet I have done those, the words is still displayed in Microsoft YaHei UI sometimes. The right-click menu is an example. I am using Windows 11 22H2 and MacType 2022.801.0 preview release. The whole ini file is posted at the ending.
![屏幕截图 2022-12-16 110331](https://user-images.githubusercontent.com/120697184/208012987-ffff9148-81af-4473-827a-721481d9ad78.jpg)
![屏幕截图 2022-12-16 110457](https://user-images.githubusercontent.com/120697184/208012703-3e5c2775-aab8-4a25-bcd2-d3dc8992c947.jpg)
![屏幕截图 2022-12-16 105704](https://user-images.githubusercontent.com/120697184/208011782-ca5dc2cd-4a00-44d3-a34a-2b2fee535a71.jpg)
![屏幕截图 2022-12-16 105805](https://user-images.githubusercontent.com/120697184/208011899-9b247d05-ef24-4788-9a90-48ceea0b2b00.jpg)
`; Only for MacType (NOT SUPPORT THE OLD VERSION OF GDI++/HE)
; maxchow@qq.com

[Preview]
Font=@苹方 粗体
Color=$990088
Text=TotalMac配置预览
Size=9
Align=Center
[General]
Name=TotalMac

;【自动挂钩子进程】
;[0:Disable]  1:Enable
HookChildProcesses=1

;【字体微调】
;0:Normal 1:NoHinting 2:AutoHinting 3:Light+AutoHinting
HintingMode=1

;【抗锯齿方式】
;-1:Disable 0:Normal 1:Light 2:LCD(RGB) 3:LCD(GBR) 4:Light-LCD(RGB) 5:Light-LCD(GBR)
AntiAliasMode=2

;【常规体调整】
;-32:+32
NormalWeight=14

;【粗体字的调整】
;-16:+16
BoldWeight=2

;【斜体字的倾斜角度微调】
;-16:+16
ItalicSlant=0

;【只有在FontLoader=0（在下面）时此项设置才有效。建议选0，选1会占用大量内存，也没看出有什么好处。】
;0:Disable 1:Enable
UseMapping=0

;【Gamma模式开关】
;-1：关闭；0：使用设置的Gamma值（GammaValue）；1：使用sRGB的Gamma值；2：不明
GammaMode=0

;【Gamma值】
;GammaMode=0的时候此项设置才有效
;sRGB ≒ 2.2 CT-Default = 1.4
;windows的cleartype的Gamma值是1.4
GammaValue=1.4

;【对比度】
;数字越大越锐利，数字越小越发虚
Contrast=1.0

;【字体轮廓】
;数字越大字体就越粗越黑
RenderWeight=1.0

;【文字边界设置】
;数字越大越强调背景（类似文字边界被侵蚀的感觉），强调背景会有中字体锐利的感觉。适当降低对比度，提高TextTuning，可以使文字周围的颜色看起来“淡一点”
;再加上RenderWeight，把这三个设置的微妙平衡调节好的话，能得到不输给Mac的效果
;0:12

;AntiAliasMode=1时，通过TextTuning分量来调节
TextTuning=0

;AntiAliasMode=2时，通过TextTuning的RGB分量来调节
TextTuningR=0
TextTuningG=0
TextTuningB=0

;【字体加粗模式】
;对NormalWeight和BoldWeight有效
;0：Weight值大时横向加粗，值小时双向加粗，主要是避免Weight值过大时，模式3中在小字号时加粗过度出现斩头的现象；
;1：总是横向加粗；
;2：总是双向加粗，也就是freetype本身的粗体渲染。
;注意：通过加大GammaValue、TextTuning的值，可以减少Weight值过大的造成的效果问题，即可以在BolderMode=2时也可以避免转接头
BolderMode=0

;【字体的载入方法】
;（注意是载入方法，不是渲染方法）
;0：用freetype载入字体
;1：用windows的绘图核心载入字体
;很多freetype的设置需要此项选0才能生效
FontLoader=0

;【字体链接】
;当FontLoader=0时
;0：什么都不做；
;1：使用注册表里的字体链接设置，通过FreeType的字符表进行查找
;2：使用注册表里的字体链接设置，使用Windows的转换函数直接查找
;当FontLoader=1时
;会保持启用的状态，但是所有字体链接的处理会交由WIN32API完成。
FontLink=2

;【字体替代】
;当FontLoader=0时
;0：什么都不做；
;1：安全替换方案（兼容性较好），根据以下FontSubstitutes的配置进行替换；
;2：完全替换方案（效果较全面，如替换后出现乱码，请尝试使用1），根据以下FontSubstitutes的配置进行替换；
;当FontLoader=1时
;会保持启用的状态，但是所有字体替代的处理会交由WIN32API完成
FontSubstitutes=2

;【让freetype处理的最大的字体尺寸，单位是像素，0的话就是全尺寸】
;交付 gdi++ 处理的最大尺寸（单位为像素）
;0-2147483647
MaxHeight=0

;【阴影设置】
;格式：水平偏移,垂直偏移,深色文字的阴影透明度(0-100),深色文字的阴影颜色，浅色文字的阴影透明度(0-100),浅色文字的阴影颜色
;颜色值格式：BBGGRR 
;Shadow=1,1,30,FFFFFF,20,000000

;【液晶显示器的优化配置】
;[0:None]  1:Default  2:Light  16:Legacy
LcdFilter=2

;【微调LcdFilter】
;LcdFilter>0，且AntiAliasMode>-1时，该微调才生效
;这5个值分别代表文字笔划中从左到右的笔划浓度，最小为0，最大为255
;注释掉这个参数则恢复使用
;LcdFilter=1，默认值为“16,64,112,64,16”
;LcdFilter=2，默认值为“0,85,86,85,0”
;LcdFilterWeight=20,80,120,80,20

;【字体缓存、内存的设置】
LoadOnDemand=1
CacheMaxFaces=256
CacheMaxSizes=33554432
CacheMaxBytes=67108864
EnableKerning=0

;【强制使用某一个字体】
;无视所有其他字体，全系统的字体都会被这里设置的字体代替
ForceChangeFont=@苹方 粗体

;【优先使用点阵】
;小于指定字号的文字将优先使用内嵌点阵
MaxBitmap=0

;【设置Direct-Write】
;启用Direct-Write
DirectWrite=1

[Individual]
;【单独设置的字体】
;格式＝Hinting, AAMode, NormalWeight, BoldWeight, ItalicSlant, Kerning
XSong=,,28,0,,
XSong SimSun=,,28,0,,
XSong NSimSun=,,28,0,,
XSong Sharp=,,28,0,,
XSong Sharp.SimSun=,,28,0,,
XSong Sharp.NSimSun=,,28,0,,
XSong Harmony=,,28,0,,
XSong Harmony.SimSun=,,28,0,,
XSong Harmony.NSimSun=,,28,0,,
XSong Classical=,,28,0,,
XSong Classical.SimSun=,,28,0,,
XSong Classical.NSimSun=,,28,0,,
XSong Tradition=,,28,0,,
XSong Tradition.SimSun=,,28,0,,
XSong Tradition.NSimSun=,,28,0,,

宋体=,,28,0,,
新宋体=,,28,0,,
SimSun-ExtB=,,28,0,,
仿宋_GB2312=,,28,0,,
仿宋=,,28,0,,
华文仿宋=,,28,0,,
华文宋体=,,28,0,,
华文中宋=,,28,0,,
Batang=,,28,0,,
MingLiU=,,28,0,,
MingLiU-ExtB=,,28,0,,
PMingLiU=,,28,0,,
PMingLiU-ExtB=,,28,0,,
PMingLiU_HKSCS=,,28,0,,
PMingLiU_HKSCS-ExtB=,,28,0,,
MS Mincho=,,28,0,,
MS PMincho=,,28,0,,`

**Comment by snowie2000** [comment]
ForceChangeFont was removed in a previous version which I can't recall off hand, but it is not effective anymore.

**Comment by snowie2000** [comment]
Ok, there it is: https://github.com/snowie2000/mactype/releases/tag/2021.1-rc1

> Breaking changes
Windows XP support was dropped. Please upgrade if you're still using this ancient system.
Option ForceChangeFont was removed. Please use regular fontsubsitution instead.
Registry mode was removed in the wizard. However, a detailed guide will be provided in the wiki to let you set it up manually if you still wish to use it.

**Comment by ACCoder2009** [comment]
> 

So I can use ForceChangeFont if I use an earlier version, right?

**Comment by ACCoder2009** [comment]
Well, then I'll try an earlier version. I hate YaHei!

**Comment by ACCoder2009** [comment]
> Ok, there it is: https://github.com/snowie2000/mactype/releases/tag/2021.1-rc1
> 
> > Breaking changes
> > Windows XP support was dropped. Please upgrade if you're still using this ancient system.
> > Option ForceChangeFont was removed. Please use regular fontsubsitution instead.
> > Registry mode was removed in the wizard. However, a detailed guide will be provided in the wiki to let you set it up manually if you still wish to use it.

So I can use ForceChangeFont if I use an earlier version, right?

**Comment by snowie2000** [comment]
Yes you can, however older versions aren't compatible with shadowstack, which means a whole lot of applications will crash when they run in newer cpus, which is unfortunately what windows 11 requires.

**Comment by ACCoder2009** [comment]
> Yes you can, however older versions aren't compatible with shadowstack, which means a whole lot of applications will crash when they run in newer cpus, which is unfortunately what windows 11 requires.

我才发现咱俩都是中国人，刚才麻烦您用英语回复了。我还有一个问题，还烦请您再回答一下。恕我一再打扰。
刚才试了一下不管是使用2019.1-beta6版本的ForceChangeFont还是2021.1-rc1版本的替换字体，在使用苹方Bold之后都会出现汉字逆时针旋转了90°的问题。
![屏幕截图 2022-12-16 115717](https://user-images.githubusercontent.com/120697184/208018848-8e2f532e-2257-40f6-9375-5c96d116e83b.jpg)
想请问一下是否有解决方法。

**Comment by ACCoder2009** [comment]
@snowie2000 I have found a way that can force to change the font of every application. I think it may be helpful for your developing work, so I'm telling it to you. We can change the data of fonts in the regedit so that the font we like will be used. I guess that this is also the principle of MacType ForceChangeFont, but when I do this manually, there won't be any gibberish, this is different from the MacType effect. If I am showing amateur skills in front of an expert, then just ignore this and despise me. Hope that MacType can be better!

**Comment by snowie2000** [comment]
That is actually how Windows handles font name alias for different locales.

For example, `Sans serif` is a font that is universally available in all languages but not physically exists. It's a virtual font that points to different physical fonts in different languages. And it has the ability to override existing registered physical fonts with virtual fonts, a.k.a. font subsitutite.

So, yes, you can do it, in system level. And it has a way better compatibility than mactype way, cuz the substitution happened at the moment the requested fonts were created.
