### ISSUE TITLE
可否介紹 Vistuner 及 [general] PixelLayout=a,b,c,d,e,f 的用法

### ISSUE THREAD

**Issue by wai148GitHub** [snowie2000/mactype#922]
因相关说明不多  谢谢

**Comment by snowie2000** [comment]
Vistuner的用法比较简单，只是缺少一个向导。

打开程序后看到如下界面
![ui](https://user-images.githubusercontent.com/11767189/222366088-b28cce6f-10de-422e-8d9e-c613124bb200.png)
1. 选第一个按钮，打开一个配置文件，配置文件可以在任何地方，并不限制在ini文件夹，选择配置文件后vistuner会自动用关联的编辑器打开这个配置（默认一般都是记事本）

2. 点击第二个按钮，选择一个应用程序（exe），tuner会启动这个应用程序，并将第一步中打开的配置文件应用到该程序上。

3. 在第一步打开的记事本（或别的对应程序）中修改配置文件，并保存。第二步中打开的应用将自动刷新界面展示修改后配置的效果。重复此步直到效果满意为止。

此时界面应该如下：
![full](https://user-images.githubusercontent.com/11767189/222366922-d5f5d491-de17-4c8f-96e9-f2636baa8d72.png)

4. 点击 change profile可以更换需要修改的配置。更换后新的配置也将被自动应用到下面的应用中

5. 点击Add more applications可以启动更多应用程序，这些应用程序可以同步刷新预览配置文件的效果

应用右侧的 || 和 □ 按钮分别可以 暂停 和 终止 预览过程。终止预览并不会杀掉应用程序。暂停预览可以用于对比配置修改前后的区别。

由于设计上和安全性上的原因，对于多进程应用是无法调试的（如Chrome等），另外由于DirectWrite的特殊性，实时预览对DW也没有效果。

**Comment by snowie2000** [comment]
PixelLayout中a-e分别代表了三个像素RGB在空间中对应的xy坐标。
更详细的信息请参考freetype官方说明：https://freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html#ft_library_setlcdgeometry
