### ISSUE TITLE
点击 '注册表加载' 的说明会切换到注册表加载模式

### ISSUE THREAD

**Issue by ddzzkunye** [snowie2000/mactype#924]
你好.
点击 '注册表加载' 的说明会切换到注册表加载模式, 这是在预料范围内或者受允许的吗?

**Comment by snowie2000** [comment]
这是一个bug，不过应该不会帮你切换到注册表模式的，其中的代码已经被移除了。

**Comment by ddzzkunye** [comment]
好的, 已了解了
close as not planned
