### ISSUE TITLE
配置文件文档页面丢失?  未在文档中发现但可使用的特性?

### ISSUE THREAD

**Issue by ddzzkunye** [snowie2000/mactype#925]
你好!
![image](https://user-images.githubusercontent.com/92249100/226327875-1eb245a5-4f5c-48e0-a7f1-0a084d866d3a.png)
上图Wiki中关于预览文字设置的部分, 红色的是代表了页面丢失, 
是因为现在这些特性不再建议使用了吗?

---------
我还在一些人的文件里发现了:
```ini
[Preview]
Align=Center
```
这完全未在文档中体现出来啊
~~一股CSS味~~

**Comment by snowie2000** [comment]
preview节中的内容对Mactype本身不生效，只是用来改变向导中预览画面的渲染参数的。红色部分表示wiki中缺少对应的说明
