### ISSUE TITLE
Rendering Firefox with MacType

### ISSUE THREAD

**Issue by TheGitMpeg** [snowie2000/mactype#935]
Hello! I have a bug: I have MacType with Tray mode (standalone) and I'm trying to make the system render Firefox with MacType following your steps, but I realize that MacType doesn't change the text rendering on Firefox beside it's enabled according to MacType's Process Manager.
Screenshot:
![image](https://github.com/snowie2000/mactype/assets/111948174/e75a435e-9e03-4c48-b9a4-b9b27cb979d0)
How can I solve it? I need an answer please.

**Comment by snowie2000** [comment]
From what I can infer from the screenshot, it already worked.

**Comment by h0munculus** [comment]
Cairo backend was removed in Firefox 68.x.x so that will not work. I like to set `gfx.font_rendering.cleartype_params.rendering_mode` to **5**

But other than that text rendering in Firefox is not what it used to be sadly.

**Comment by tordenflesk** [comment]
One of several reasons I'm "stuck" with Waterfox Classic.

Even if I exclude "pixel"-fonts properly with Mactype they're positioned "off-pixel" in Fx so they'e more often than not blurred in the UI (demonstrated here in Waterfox Current):
![image](https://i.imgur.com/H4Eke6C.png)

Ublock's Correct, other text "pops into place" if I'm lucky when resizing the window.

Waterfox Classic with Mactype:
![image](https://i.imgur.com/gcBiHnB.png)

**Comment by snowie2000** [comment]
I think this is because nowadays, firefox is rendered with DirectWrite which supports sub-pixel positioning, while in the old days, GDI doesn't so that all the pixel fonts are always displayed pixel-perfect.

**Comment by mashirochan** [comment]
I'm not sure if it's just the one specific site or specific font or what, but in Firefox this text is very clearly not applying anti-aliasing correctly:

![1729467720_firefox_19-42-00](https://github.com/user-attachments/assets/03e88d84-bca4-4fa9-93c9-36a4236fcab0)

I have `gfx.font_rendering.cleartype_params.rendering_mode` set to `5` and have tried with `DirectWrite` enabled and disabled.

The font displays perfectly fine in Edge:

![1729467803_msedge_19-43-23](https://github.com/user-attachments/assets/a41aba47-1d7c-44dd-a142-0d6cef1a5236)

Font: IBM Plex Sans 12pt
Site: https://developer.availity.com/partner/api_guide
Firefox: version 131.0.3
Windows: Windows 11 Education 23H2

This is the profile that I'm using: [SoftGrayNoHinting.txt](https://github.com/user-attachments/files/17452442/SoftGrayNoHinting.txt)

Any help would be greatly appreciated, thanks!

**Comment by snowie2000** [comment]
According to your profile, you didn't have [ArmBreaker](https://github.com/snowie2000/mactype/wiki/ArmBreaker) set locally or globally, so any DirectWrite settings will not be effective for your Chrome/Edge/Chromium because they are protected.

As for your firefox, once you have `DirectWrite=0` in your profile, nothing will be done to your firefox and it will render everything on its own.

**Comment by mashirochan** [comment]
I'm new to all this and slightly confused, apologies - it looks like I already have `DirectWrite=1` in my profile, which enables DirectWrite - don't I want that enabled to fix the issue in Firefox? Is `ArmBreaker` irrelevant for the Firefox issue, or do I need to enable that locally/globally as well (and if so, do I just add like `ArmBreaker=1` at the bottom of the profile under `[Experimental@Firefox.exe]`)? Sorry and thanks again!

**Comment by TheGitMpeg** [comment]
I think the process of adding Firefox into MacType's list technically disables hinting, and it still looks great at my eyes, regardless of hinting.

**Comment by snowie2000** [comment]
Once you have DirectWrite=1, mactype starts intercepting rendering of your firefox regardless of the ArmBreaker option.

ArmBreaker is not required for firefox and only required for chromium based browsers.

Armbreaker can't be enabled on a per-app basis, it can only be enabled globally.
