### ISSUE TITLE
Install MacType without installer (?)

### ISSUE THREAD

**Issue by LilywhiteLilith** [snowie2000/mactype#937]
Hello,
Since I offer the installation of MacType in my program, the following question arises.
Would it be sufficient to copy the MacType folder with all files and subdirectories on the target computer into a non-access protected folder (e.g. C:\MacType - in my experience MacType runs here without any noticeable problems) without using the installer? This would save the user from having to launch the setup program and also ensure that MacType does NOT end up in the Applications folder, since I have limited access there (e.g. subfolder "\languages").
With the startup method "manual" I did not find any entries in the registry after e regular Setup with Installer, apart from the uninstall information, so i think this method would be practicable?

**Comment by snowie2000** [comment]
Yes, a simple file copy is enough for mactype to work properly in manual mode.

**Comment by LilywhiteLilith** [comment]
I love this program more and more...
:-)
