### ISSUE TITLE
服务已停用

### ISSUE THREAD

**Issue by ottocsb** [snowie2000/mactype#939]
更新完您发布的```2023.5.31```后，出现了无法自动渲染的情况，使用的配置文件没有发生变化，
且我从注册表渲染改为服务渲染后可以正常渲染，使用注册表进程加载如下图情况：
![image](https://github.com/snowie2000/mactype/assets/83228451/d99c289c-f6e4-4033-aa50-4444440fb46c)
![image](https://github.com/snowie2000/mactype/assets/83228451/863bba51-dea9-42df-bb31-a2b61a7df9b9)

或我手动启用服务也可以恢复渲染，有点怪

**Comment by ottocsb** [comment]
我在想有可能是我升级的方式不正确，导致注册表失效，我没有卸载mactype后再进行安装

**Comment by snowie2000** [comment]
注册表需要重启才能生效。另外是否火绒拦截了呢？

新版本只是整合了一个补丁，没有对加载做任何修改。另外注册表加载不会用到exe，所以任何exe的修改都不会影响的。

**Comment by ottocsb** [comment]
火绒的拦截被我取消了，也重启了。
我刚刚完成了停用，退出，重启，删除，重新下载使用配置，注入注册表，重启的流程操作，重启后进程渲染依旧是停用。
暂时使用服务模式，等闲了我再试试。
