### ISSUE TITLE
LCDFilterWeight

### ISSUE THREAD

**Issue by ssssssbbb** [snowie2000/mactype#941]
虽然我感觉不会有其他人认为这是个问题了，但是从足够科学的应用方法来说，不恢复这玩意，违背了最初开发目的：解决Windows字重过低和字形变形。因为高点密度显示器可以靠点的聚拢来提供足够的色深，密度低的显示器只能靠提高单个点的色度，LCDFilterWeight就是干这个的，网上流行的使用RenderWeight增加笔画粗细的方法会使得字形改变，即使我再不能阻止大家使用，它也是不科学的，低密度显示器要增加单个字的像素量，使用增大逻辑DPI或直接用nomeiryoUI加字号才是对的。

现在的新参数PixelLayout是为高密度显示器的不同子像素布局准备的，但它和LCDFilterWeight冲突，意味着新显示器的功能排斥了低密度显示器，这违背了最开始的开发初衷。

除了我因为LCDFilterWeight感到渲染无效化，另外也有见到不使用该参数而使用其他自带配置的用户反映“不能渲染”，因此

望不忘初心。

**Comment by snowie2000** [comment]
这是由于这两个功能是由freetype的不同渲染器提供的，实际上freetype原版不允许你同时编译这两个功能，我通过修改freetype使他可以在Mactype同时存在了，但依然是无法同时生效的，只能选择一个。

**Comment by ssssssbbb** [comment]
感谢

**Comment by digiant** [comment]
> 

可以试一下用鸿蒙中黑体来代替微软雅黑，加粗下原始字体
