### ISSUE TITLE
微信3.9.0.28这个版本之后的就不能MACTYPE渲染了，有没有大佬教下怎样解决

### ISSUE THREAD

**Issue by weavers1f** [snowie2000/mactype#945]
1080P的屏，这个版本之后，微信就跟chrome那样渲染不了，字体看着虚，现在停留在了这个版本。
企业微信也是一个样，最后能MT渲染的版本是4.1.0.6007，那之后的就虚了。

**Comment by snowie2000** [comment]
应该是转向electron了。以后就是dw的渲染效果了。

**Comment by digiant** [comment]
看安装目录里用了skia，渲染效果贼垃圾。

**Comment by CHN-STUDENT** [comment]
话说大佬们有老版本么，不明白微信更新了啥，看他们更新日志天天跟刷API一样。。结果越来越狗屎

> UPDATE：感谢三大妈，https://soft.3dmgame.com/down/242613.html

顺便我扔到 github release 了：https://github.com/CHN-STUDENT/FuckTxWx/releases/tag/3.8.1.26
