### ISSUE TITLE
微信中渲染失败

### ISSUE THREAD

**Issue by wzxmer** [snowie2000/mactype#946]
在输入框中显示是正常的，能渲染，但是聊天记录框中，显示的是系统字体。不知道是不是微信的原因，更新后就这样了
![1686304922530](https://github.com/snowie2000/mactype/assets/46368648/76e060b2-7ae5-43c3-8047-deed0438a7f2)

**Comment by snowie2000** [comment]
微信修改了他们的渲染核心，成了skia，无解
