### ISSUE TITLE
Microsoft Edge issue when rendering text

### ISSUE THREAD

**Issue by TheGitMpeg** [snowie2000/mactype#947]
Hello, I have the following issue:
Microsoft Edge doesn't render pages with MacType.
Please look at the picture:
![image](https://github.com/snowie2000/mactype/assets/111948174/6189fa82-0cde-4b99-87c7-99fa8719a0d4)
I need a solution please. Thank you for the answer!

**Comment by huzhangyang** [comment]
Same As #943 . Unfortunately there is no known solution yet.

**Comment by Big-Cake-jpg** [comment]
Do you install MacType in a non-C drive?
If yes, try to move it to `C:/Program Files` directory and restart the computer.

**Comment by L33Z22L11** [comment]
> Do you install MacType in a non-C drive? If yes, try to move it to `C:/Program Files` directory and restart the computer.

Thanks, it works.
