### ISSUE TITLE
2021 RC1 only renders part of characters in recently updated Wechat

### ISSUE THREAD

**Issue by strontiumpku** [snowie2000/mactype#948]
Only part of characters are rendered. Restarting Mactype service does not help. Seems something changed in Wechat? This happens only in recently updated Wechat verison (3.9.5.81). Windows verison: Win 11 22H2 (22621.1702). Mactype version: 2021-RC1.

Thanks for looking into it :)

![image](https://github.com/snowie2000/mactype/assets/61595822/7e2c28c3-e813-430c-99ed-5d5df8f4d889)
![image](https://github.com/snowie2000/mactype/assets/61595822/f455bc85-7394-4f05-a6db-f587e83f8ccd)

**Comment by weavers1f** [comment]
你去已关闭的问题那里看看，最近有两个在说这个

**Comment by strontiumpku** [comment]
大家似乎都在讨论浏览器，我没找到感觉太相关的。我先试下更新到最新的test版本看看
在我这里问题也不是总能复现

**Comment by weavers1f** [comment]
已关闭的问题那里呀，最近两个就是在讨论微信的，大家的现在都渲染不了微信了，微信改渲染框架了

**Comment by ssssssbbb** [comment]
后知后觉了，这个起码2个月前就这样了，坚持旧版本就完事

顺便，后面的QQ electron多半也是这样，垃圾

**Comment by weavers1f** [comment]
> 

我也是一直坚持旧版本用了一两个月，只不过现在新版微信能公众号文章多开窗口浏览，忍着用了新版

**Comment by strontiumpku** [comment]
多谢楼上两位，在closed issues里看到了……
