### ISSUE TITLE
GDIObjectLeak On 22621.2134

### ISSUE THREAD

**Issue by InoriILU** [snowie2000/mactype#962]
![image](https://github.com/snowie2000/mactype/assets/89334352/0c5b2db9-9c81-46aa-864a-0a89b4a1fb31)
it made the explorer crash repeatedly.

**Comment by InoriILU** [comment]
![image](https://github.com/snowie2000/mactype/assets/89334352/b159f9d3-3bc4-48e4-97e7-f6a5d6f498a1)

**Comment by snowie2000** [comment]
抱歉暂不支持win11，win11由于bug实在太多，没有支持的计划。

As there are too many changes happening and too many bugs remaining in Windows 11, as long as you are using the latest version of Mactype (could be a preview version), that is what the best we could get so far.

May be until Windows 12 releases....

**Comment by InoriILU** [comment]
> 抱歉暂不支持win11，win11由于bug实在太多，没有支持的计划。
> 
> As there are too many changes happening and too many bugs remaining in Windows 11, as long as you are using the latest version of Mactype (could be a preview version), that is what the best we could get so far.
> 
> May be until Windows 12 releases....

彳亍，谢谢大哥qwq
Thanks.
