### ISSUE TITLE
Possible solution for service mode to work like registry

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [snowie2000/mactype#969]
#775

> For now, no known method has been found to force a window redraw or update from a service, so you have to hover to make the window repaint itself.

One of the main difference between registry mode and service mode is the registry mode have better responsive than service mode, applications will apply MacType on first draw immediately in registry mode, but in service mode, first draw is usually not effected by MacType in some software. There are several methods to solve this:

1. Mouse hover on each window element to trigger redraw
1. Minimized and restore

I have just discovered another method that is drag the Window to outside of screen visible area, then drag back, so redraw is triggered.

Maybe add some code to automatically these processes? Call some user32 API to move window once MacType is loaded to target process, from current position to somewhat X -10000, Y -10000, then move it back.

The solution may coded by using AutoHotkeys or a dedicated background process. However, I think only MacType itself know when it gets loaded. So integrate the action to MacType itself is prefered. The action may be disabled by default and use an INI config to enable.

**Comment by snowie2000** [comment]
> For now, no known method has been found to force a window redraw or update from a service, so you have to hover to make the window repaint itself.

This is not true anymore. In the recent releases, I've implemented a new simple way to walkaround this redraw problem:
since we can't ask windows to redraw themselves, we can make windows redraw themselves by themselves. After applying mactype to a process, the loaded mactype dll will send redraw command to repaint the window.

**Comment by mhtvsSFrpHdE** [comment]
I'm at [MacType 2021.1-RC1](https://github.com/snowie2000/mactype/releases/tag/2021.1-rc1), it seems this new method not included in this release yet. I'll wait for next release then.
