### ISSUE TITLE
Mactype在Win11的cmd与powershell中出现错误

### ISSUE THREAD

**Issue by SilentEntropy** [snowie2000/mactype#973]
![image](https://github.com/snowie2000/mactype/assets/114558723/b8465f41-e417-4241-93d4-66f4dcd186f6)
![image](https://github.com/snowie2000/mactype/assets/114558723/3783b2c6-ee91-41c6-b5c8-2f2bed35c59f)

**Comment by snowie2000** [comment]
关掉字体替换
cmd类程序是无法替换字体的

**Comment by SilentEntropy** [comment]
使用mactype的注册表模式，怎么关掉字体替换

**Comment by SilentEntropy** [comment]
mactype怎么关掉字体替换

**Comment by snowie2000** [comment]
打开配置文件，fontsubstitute = 0

**Comment by 0xFFFFFF65** [comment]
![image](https://github.com/snowie2000/mactype/assets/114558723/1fedb760-240c-458f-b010-ea8f928a5e4d)
在哪

**Comment by 0xFFFFFF65** [comment]
不行

**Comment by SilentEntropy** [comment]
改了ini文件夹里的def与mactype的ini
不行

**Comment by 0xFFFFFF65** [comment]
不行

**Comment by 0xFFFFFF65** [comment]
@snowie2000 @snowie2000 不行

**Comment by snowie2000** [comment]
把你的配置文件贴出来看一下，你这个肯定是开了字体替换的，而且很明显替换的有问题
