### ISSUE TITLE
Mactype不兼容cmd类的exe,那怎么排除这些项

### ISSUE THREAD

**Issue by SilentEntropy** [snowie2000/mactype#974]
**经过我的测试，cmd类的程序的字体显然会出现乱码问题，比如powershell,cmd
这样的话如何排除这些渲染不正常的程序**

**Comment by SilentEntropy** [comment]
@snowie2000

**Comment by snowie2000** [comment]
不存在兼容性问题，你提到的问题是错误替换字体导致的。替换字体本身就是兼容性不确定的操作。

**Comment by SilentEntropy** [comment]
并没有替换字体
