### ISSUE TITLE
安装之后，谷歌浏览器控制台字体颜色特别浅。

### ISSUE THREAD

**Issue by 222** [snowie2000/mactype#992]
![Snipaste_2024-05-22_11-13-57](https://github.com/snowie2000/mactype/assets/28282761/c9a0099b-6780-44c4-8f7c-55dc2fba2613)

**Comment by oimmc** [comment]
跟踪一下，有解决吗

**Comment by snowie2000** [comment]
宋体本来就是这样的，你到浏览器设置里面把默认字体换掉，别用宋体就好了。宋体一直就这个样子没得救。

之所以原来的宋体你不觉得浅是因为它用的是点阵，点阵是很浓的，换成矢量后，衬线字体在低dpi下普遍就会出现很浅的现象

**Comment by oimmc** [comment]
> 宋体本来就是这样的，你到浏览器设置里面把默认字体换掉，别用宋体就好了。宋体一直就这个样子没得救。
> 
> 之所以原来的宋体你不觉得浅是因为它用的是点阵，点阵是很浓的，换成矢量后，衬线字体在低dpi下普遍就会出现很浅的现象

我换成了微软雅黑，或者其他尝试了几个，依旧是很浅，是不是我替换的不对呢，如图：
![image](https://github.com/user-attachments/assets/ae8ce8c6-4c62-4e4a-9102-9e148505f408)

**Comment by snowie2000** [comment]
在console中生效的是等宽字体，别的不生效。
