### ISSUE TITLE
开启mactype会导致命令提示符闪退，无法打开。

### ISSUE THREAD

**Issue by billowssun** [snowie2000/mactype#995]
这个问题困扰我好久，之前一直是无数次重启，偶尔可以打开，但是最近忍无可忍，才想到了mactype，将终端应用排除在外才不会闪退。

**Comment by snowie2000** [comment]
这个是已知问题呀，mactype老版本对dw的hook是有问题的，更新到最新版就可以了

**Comment by billowssun** [comment]
请问下最新版是这个版本吗？MacTypeInstaller_2021.1-rc1

**Comment by snowie2000** [comment]
> 请问下最新版是这个版本吗？MacTypeInstaller_2021.1-rc1

不是的，你点release，可以看到有一些preview版

**Comment by billowssun** [comment]
新版本侏儒注册表还是原来的方法吗。

**Comment by snowie2000** [comment]
新版本的向导已不再支持启用注册表模式了，你需要手动启用：https://github.com/snowie2000/mactype/wiki/Enable-registry-mode-manually

**Comment by billowssun** [comment]
![image](https://github.com/snowie2000/mactype/assets/55521033/c10aced9-5882-4250-9f3a-1cc64da77f55)
这个似乎失效了，我尝试过。

**Comment by snowie2000** [comment]
必须关闭安全启动secure boot否则不生效

**Comment by billowssun** [comment]
手动开启注册表模式成功了，不过新版本很多进程不支持替换了，现在很尴尬，一些替换一些不替换，同一个界面不同进程看到的字体不一致。
![image](https://github.com/snowie2000/mactype/assets/55521033/aeee10c7-5bbe-4c40-ad13-00c62690107b)

**Comment by KeeLee2005** [comment]
> 这个问题困扰我好久，之前一直是无数次重启，偶尔可以打开，但是最近忍无可忍，才想到了mactype，将终端应用排除在外才不会闪退。

确实是MacType导致WindowsTerminal崩溃，但是终端管理员不受影响。
![QQ截图20240629142724](https://github.com/snowie2000/mactype/assets/92454987/9daa1009-3e45-4e0e-b404-3df17c1a28a7)

我暂时的解决办法是以管理员身份运行Windows终端，然后在MacType里排除有关进程。像终端这种UWP应用的字体渲染的观感已经比较不错了，所以这样做问题不大。

MacType版本: 2021.1 
MacTray版本: 1.0.2021.1
MacTuner版本: 1.0.2.361
Windows版本: Windows 11 23H2 Build 22635.3790

**Comment by snowie2000** [comment]
> > 这个问题困扰我好久，之前一直是无数次重启，偶尔可以打开，但是最近忍无可忍，才想到了mactype，将终端应用排除在外才不会闪退。
> 
> 
> 
> 确实是MacType导致WindowsTerminal崩溃，但是终端管理员不受影响。
> 
> ![QQ截图20240629142724](https://github.com/snowie2000/mactype/assets/92454987/9daa1009-3e45-4e0e-b404-3df17c1a28a7)
> 
> 
> 
> 我暂时的解决办法是以管理员身份运行Windows终端，然后在MacType里排除有关进程。像终端这种UWP应用的字体渲染的观感已经比较不错了，所以这样做问题不大。
> 
> 
> 
> MacType版本: 2021.1 
> 
> MacTray版本: 1.0.2021.1
> 
> MacTuner版本: 1.0.2.361
> 
> Windows版本: Windows 11 23H2 Build 22635.3790

和terminal中设置的渲染模式有关。新版已经不会崩溃了
