### ISSUE TITLE
开机explorer.exe是停用状态

### ISSUE THREAD

**Issue by TuringWang9527** [snowie2000/mactype#999]
每次开机需要自己进程序点一下启用才能用，怎么才能默认启用呢

**Comment by snowie2000** [comment]
旧版本bug，请升级

**Comment by TuringWang9527** [comment]
> 旧版本bug，请升级

哪个是最新的呀，我下载的2021推荐的那个

**Comment by snowie2000** [comment]
> > 旧版本bug，请升级
> 
> 
> 
> 哪个是最新的呀，我下载的2021推荐的那个

最新的2023

**Comment by jonm58** [comment]
https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31

**Comment by TuringWang9527** [comment]
> > > 旧版本bug，请升级
> > 
> > 
> > 哪个是最新的呀，我下载的2021推荐的那个
> 
> 最新的2023

大佬，我把原来的卸载了安装了2023的，但是2023版的是压缩包，不是安装版，开机不能自启动啊

**Comment by snowie2000** [comment]
新版本都是压缩包形式的，没有发布安装包。
设置开机自启动不是通过向导的吗？和安装包也没什么关系啊
